### ISSUE TITLE
Buttons take a long time to set enabled/disabled

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#100]
I was struggling with a 240ms pause when the skater attached to the track in ESPB in this issue:
https://github.com/phetsims/energy-skate-park-basics/issues/137

This is not a problem in dev.52 and a problem in dev.53. That is the revision where the new sun buttons were introduced.

The problem is isolated to where the RectangularPushButton (for the clear thermal button) is enabled/disabled.  When I tried commenting that part out in ESPB call sites, the problem went away.  This issue must be fixed (or worked around) before ESPB can go to release candidate phase.

**Comment by pixelzoom** [comment]
@samreid wrote:
> Let's leave this issue open until scenery 0.2 is verified to solve this issue. 

@jonathanolson Did scenery 0.2 solve this issue?

**Comment by jonathanolson** [comment]
Yes, using addCachedPaint/removeCachedPaint or setting node.cachedPaints=[...], with all of the gradients/patterns that would potentially be used.

**Comment by pixelzoom** [comment]
This should be addressed by https://github.com/phetsims/sun/issues/150.  @jonathanolson please work with @jbphet to implement cachedPaints for sun components.

**Comment by jonathanolson** [comment]
cachedPaints has been added to the relevant sun buttons, see https://github.com/phetsims/sun/issues/150.

I saw no pause on desktop, but don't have the iPad 3 available for testing at the moment.

**Comment by jonathanolson** [comment]
Tested on the iPad 3, however there's a pause regardless of the changes, or whether that button is enabled or not.

Seems to be more related to the lack of WebGL, but I'd love to have it profiled.

**Comment by jonathanolson** [comment]
Also noted in the spreadsheet for redeploy that ESPB's WebGL will need to be redone with WebGLNode, as it's too slow on the iPad right now.

As far as I'm concerned (and have tested), this particular issue shouldn't be causing performance problems now. Reassigning to @pixelzoom to see if there's anything else that needs to be done for the redeploy with this particular issue.

**Comment by pixelzoom** [comment]
I've never experienced this, so I can't verify/close. Assigning back to @samreid because he reported the initial problem.

**Comment by samreid** [comment]
This issue was prominent on my Lenovo + Win + Chrome setup, I will need to wait until I have access to that platform again (it is currently at my home office) to test this out.

**Comment by samreid** [comment]
I switched ClearThermalButton.js to use RectangularButtonView.threeDAppearanceStrategy instead of the flatAppearanceStrategy, and tested with master branches on my Lenovo running Win8+Chrome 43.0.2357.81 m (64-bit) and the problem is gone.  The buttons enable instantly and there is no pause in the motion of the skater.  This issue seems like it has been addressed by something, possibly (a) scenery updates (b) fixes within chrome or (c) something else.  I think it is time to close this issue.

One more thing, in my opinion, these 3d buttons look much nicer (more buttony and consistent with the rest of the sim), so I'm going to create an issue to use the 3d appearance strategy in ESPB now that performance seems good.

**Comment by pixelzoom** [comment]
@samreid wrote:
> so I'm going to create an issue to use the 3d appearance strategy in ESPB now that performance seems good.

Why would they be used in ESPB and not in other sims?

**Comment by pixelzoom** [comment]
... or perhaps this is specific to the thermal buttons, and there's some reason why they specifically look better as 3D-ish?

**Comment by samreid** [comment]
RectangularButtonView.threeDAppearanceStrategy is the default (see RectangularButtonView.js) but ESPB had to use the flat version as a workaround since dynamic motion was getting disturbed when the button became enabled.  All sims should probably be using the default unless there are extenuating circumstances.

**Comment by pixelzoom** [comment]
Got it, thanks for clarifying.
