### ISSUE TITLE
All interactive controls should highlight in some way when mouse is over

### ISSUE THREAD

**Issue by jbphet** [phetsims/sun#116]
In the 9/4/2014 developer meeting we discussed the behavior of UI components, and used Energy Skate Park as an example.  We noticed that the buttons and the slider knobs highlight when the user hovers over them, but other components, such as check boxes, radio buttons, and such do not.  We agreed that all UI controls should highlight in some way when the user hovers over them.

**Comment by pixelzoom** [comment]
Closing this because it's too vague to do anything about and it's been open for 6 months. If there are specific components that need to highlight, please create issues for those components.
