### ISSUE TITLE
Radio Button improvements

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#119]
@aaronsamuel137 & I discussed the radio button model and discussed the following potential improvements:

1. Create RadioButtonModel (similar to ButtonModel but with a selected property).  See ToggleButtonModel for an example of how to derive from ButtonModel.
2. Use the new RadioButtonModel (or a derivation thereof) in RadioButton Appearance classes
3. Remove the double button copies (one for selected and one for deselected) from RadioButtonGroup

May be good for @aaronsamuel137 to work on this with @samreid or @jbphet if their times match up.

**Comment by pixelzoom** [comment]
@aaronsamuel137 Anything else to do here, or can this be closed?

**Comment by pixelzoom** [comment]
@aaronsamuel137 Anything else to do here, or can this be closed?

**Comment by aaronsamuel137** [comment]
Nothing else to be done for this issue. Closing.
