### ISSUE TITLE
use meaningful names for options related to accessibility

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#12]
... for example, ToggleButton has a 'label' option.  

new ToggleButton( { label: 'Sound'} ) is misleading, leads me to believe that the button will be labeled, and tells me nothing about how the string will be used (it's spoken by the screen reader.)

I suggest using a prefix for all accessibility-related options.

**Comment by pixelzoom** [comment]
This use of the 'label' option appears to have been expunged from all code (unless I missed something). Assigning to @samreid to verify, in case he's aware of someplace where it's still lurking.  Feel free to close.

**Comment by samreid** [comment]
I looked for `:label '` and `'Sound'` and in SoundToggleButton and AriaSpeech and didn't see any evidence of leftover accessibility labels.  Closing.
