### ISSUE TITLE
HTMLPushButton does not fully disable

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#123]
The HTML on the HTMLPushButton does not disable the way that other nodes do. To demonstrate, run the sun button demo (sun_en.html) and press the "Disable Buttons" button in the lower right corner. You'll see the screenshot below.  The text on the button labeled "HTML button example" is not grayed out.  This is probably a scenery issue with HTMLText node.

![screenshot_378](https://cloud.githubusercontent.com/assets/3046552/4534102/263d5044-4da2-11e4-9af7-f4965b0db2a5.png)

**Comment by pixelzoom** [comment]
Problem appears to be fixed in master. Now sure how or why, maybe scenery 0.2 addressed this. Closing.

**Comment by jonathanolson** [comment]
Looks like opacity is working properly for the DOM renderer now, presumably fixed in 0.2.
