### ISSUE TITLE
RadioButtonGroup should support the Navigation Bar screen buttons

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#127]
With labels, the RadioButtonGroup can look something like this (example from molecule polarity):

![out3](https://cloud.githubusercontent.com/assets/679486/4537087/56302128-4dd4-11e4-8afa-e1e4046c16be.png)

The navbar buttons are very similar, and they look like this:

![image](https://cloud.githubusercontent.com/assets/679486/4537068/0e9ecea4-4dd4-11e4-9167-4b6a51524595.png)

Our RadioButtonGroup should be able to support different "looks" like this, and we should be able to use RadioButtonGroup to implement the navbar screen buttons.

**Comment by ariel-phet** [comment]
@samreid looks like this issue is quite stale...please comment, close, or lets revisit

**Comment by samreid** [comment]
My recommendation is to close this issue and reopen if/when any of the following occurs:

(a) we need the look and feel from joist in some other part of a simulation (so far has not been the case)
(b) the difference in implementation becomes problematic for phet-io, accessibility or some other concern (so far has not been the case)

**Comment by pixelzoom** [comment]
+1 to close.
