### ISSUE TITLE
Is contentAppearanceStrategy used?

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#131]
I can't see any usages of this line in RadioButtonGroup.js in the options declaration.

```
contentAppearanceStrategy: RadioButtonsAppearance.contentAppearanceStrategy
```

I also tried commenting it out and it did not change the behavior of the sun demo.  Can this be removed?

**Comment by pixelzoom** [comment]
@samreid Sounds like @aaronsamuel137 answered your question. Anything else to do here?

**Comment by samreid** [comment]
Sounds good, thanks for the explanation @aaronsamuel137.
