### ISSUE TITLE
InOutRadioButton should be implemented using the new RadioButtonGroup?

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#132]
We have radio push buttons with a pseudo-3d look in InOutRadioButton.  We may be phasing these out for the look of the new RadioButtonGroup, but it may still be necessary in some situations.  Would there be value in refactoring the RadioButtonGroup to support this as an alternative view for the radio buttons?  See also #127 regarding having the RadioButtonGroup support the navigation bar buttons too.  Here's an image of the InOutRadioButtons from under pressure:

![image](https://cloud.githubusercontent.com/assets/679486/4537364/8e86730a-4dda-11e4-814f-7787a8ded46c.png)

Or perhaps we should try to use the new RadioButtonGroup look where possible, and only create the InOutRadioButton look if necessary?  This latter option would have to be approved by the sim design team.

**Comment by pixelzoom** [comment]
InOutRadioButton no longer exists, see #184. Closing.
