### ISSUE TITLE
Buttons don't handle having no content very well

### ISSUE THREAD

**Issue by jbphet** [phetsims/sun#136]
"content" is currently an option when constructing buttons such as RectangularPushButton, but if no content is included and minWidth and minHeight aren't specified, odd failures occur that are related to trying to draw gradients with inappropriate color stops.  This should be handled differently.

**Comment by pixelzoom** [comment]
RectangularButtonView looks like it handles this properly.

RoundButtonView looks like it has multiple serious problems.

**Comment by jbphet** [comment]
I'm taking a look at this after it has sat for quite a while.  I added an empty RectangularPushButton and RoundPushButton to the Sun demo as an experiment (not checked in).  No errors were thrown nor asserts encountered.  However, the two buttons seemed to behave much differently in the absence of content.  This is what they looked like:

![sun-demo-empty-buttons](https://cloud.githubusercontent.com/assets/3082831/9181918/d2e488d0-3f64-11e5-8ad5-affe03eb3c31.png)

I'm not sure if this is really an issue since no actual failures are encountered.  I will label this for discussion during the next developer meeting.

For reference, here is the code that was added to ButtonDemoView.js:

```js
    //===================================================================================
    // Buttons with no content
    //===================================================================================

    var emptyButton1 = new RectangularPushButton( {
      listener: function() { message( 'Empty button 1 pressed' ); }
    } );
    this.addChild( emptyButton1 );

    var emptyButton2 = new RoundPushButton( {
      listener: function() { message( 'Empty button 2 pressed' ); },
      left: emptyButton1.right + 5,
      baseColor: 'pink'
    } );
    this.addChild( emptyButton2 );
```

**Comment by jbphet** [comment]
@pixelzoom suggested that the ```minWidth``` and ```minHeight``` options be tested with no content for RectangularPushButton before closing this issue.  I've done that testing, and these parameters work as expected with no problems.  For good measure, I also tested the ```radius``` option for RoundPushButton, and it works fine as well.  Everything looks good, closing.
