### ISSUE TITLE
sun buttons leak gradients

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#146]
This is a problem with RectangularButtonView and RoundButtonView.

Here's the problem code in RectangularButtonView.threeDAppearanceStrategy:

> 141 var overlayForHorizGradient = new Rectangle(...);
> 159 button.fillKept = true;
> 160 overlayForHorizGradient.fillKept = true;

One could turn off gradient caching for button by setting button.fillKept=false. But there's no way to get to overlayForHorizGradient.  So you're stuck with caching. So any sim that is dynamically creating buttons is leaking gradients through overlayForHorizGradient.

Note that this is independent of https://github.com/phetsims/scenery/issues/328 (gradient leak in scenery). Once that's fixed, sun would still be leaking here.

Assigning to @jbphet since he was the primary developer. This needs to be fixed to resolve https://github.com/phetsims/reactants-products-and-leftovers/issues/18, in order to publish RPAL.

**Comment by pixelzoom** [comment]
@jbphet Is this issue still relevant, now that fillKept has been removed in scenery 0.2?

**Comment by pixelzoom** [comment]
@jonathanolson feel free to chime in on whether this issue is still relevant.

**Comment by jonathanolson** [comment]
fillKept has been removed, please add to node.cachedPaints (addCachedPaint( gradient )) or set node.cachedPaints=[..gradients..]. No need to garbage collect these, when the node is not in the displayed tree at all (even if invisible), they'll be removed Scenery-side.

**Comment by pixelzoom** [comment]
So yes, this issue is relevant and still needs to be addressed (before Summer 2015 redeploy). 

Issue https://github.com/phetsims/sun/issues/150 may be a duplicate, or may address this.

**Comment by jonathanolson** [comment]
To me, https://github.com/phetsims/sun/issues/150 would be helpful for performance, but as noted two times above, Scenery 0.2 won't let gradients leak.

Can we leave https://github.com/phetsims/sun/issues/150 as the open issue to handle adding in cachedPaints?

**Comment by pixelzoom** [comment]
@jonathanolson feel free to close this issue as you see fit.  I'd prefer not to keep sticking my nose in it, and have you and @jbphet work it out.

**Comment by jonathanolson** [comment]
Sounds good to me. I'll take primary responsibility on moving older code over to use it.
