### ISSUE TITLE
implement momentary buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#149]
This is needed to address https://github.com/phetsims/scenery-phet/issues/80.

**Comment by pixelzoom** [comment]
I implemented RoundMomentaryButton and RectangularMomentaryButton using the sun button framework. Examples are shown in the sun demo program.  RoundMomentaryButton is used in scenery-phet.EyeDropperNode. 

Assigning to @jbphet to review.

**Comment by jbphet** [comment]
Momentary button code looks good.  I did a little cleanup of how the buttons were used in the demo to make their behavior more consistent with the other buttons.  @pixelzoom can check if desired, but changes are pretty minor.  Closing.
