### ISSUE TITLE
thumbNode option for HSlider

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/sun#151]
In phetsims/molecules-and-light#83 a request has been made for a thumb shape which cannot be drawn using current HSlider options.  A solution could be to to create an optional parameter in HSlider that allows passing in a node for the thumb so any unique shape can be used.

**Comment by jessegreenberg** [comment]
I have made a change to HSlider to allow passing in an optional thumbNode.  I do not have permission to push to sun, so I am sending the patch to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Got the patch for @jessegreenberg, on my todo list.  Assigning this issue to me.

**Comment by pixelzoom** [comment]
@jessegreenberg I added options.thumbNode.  The default thumb has been moved to ThumbNode inner type.

Note that the client is responsible for the managing the "look" of their custom thumb. This generally involves adding a ButtonListener, and responding to changes to options.enabledProperty. See ThumbNode for an example.  You'll probably need to add this to your custom thumb in Molecules & Light.

Please review my changes. Let me know if you have any questions. Feel free to close if it looks OK.

**Comment by samreid** [comment]
We will also need to make sure accessibility is supported for the thumbnode.  This means setting focusable:true on it, and adding the input listener to handle left/right/up/down.  The listener is already added to the thumbNode, but we should set focusable on it whether it was passed in or created in HSlider.

**Comment by pixelzoom** [comment]
@samreid wrote:
> We will also need to make sure accessibility is supported for the thumb node. [...]

focusable:true is set for the default thumb node, so I assume these are instructions for clients who are not using the default thumb.  @jessegreenberg please consider this in Molecules & Light.

**Comment by samreid** [comment]
I was thinking the clients wouldn't be responsible for setting focusable or adding input listeners--these would be done in the central location of the slider code.

**Comment by samreid** [comment]
I implemented the support I was describing above and tested in Capacitor Lab. Should be re-tested with a custom knob when ready.

**Comment by pixelzoom** [comment]
The slider has no way of knowing how the provide thumbNode should change its "look" in response to pointer events (over, down, up,...) or being disabled.  That behavior must be specified by the client, and requires an input listener for the pointer events, and an observer for the (optional) enabledProperty.

**Comment by pixelzoom** [comment]
Having HSlider responsible for setting focusable:true (as @samreid has done) is fine, since that is independent of the thumb's "look".

**Comment by jessegreenberg** [comment]
This looks great, thank you very much.  I have added a custom thumbNode in Molecules And Light in a similar way to the new default in HSlider.  As discussed above, setting focusable:true and adding the accessibility input listeners is left for HSlider code.

I do not observe the optional enabledProperty because the slider will always be enabled for Molecules and Light.  Would there be any reason to link buttonListeners to the enabledProperty on custom thumbNodes when the slider is always enabled?

**Comment by pixelzoom** [comment]
If your sim doesn't need to disable the slider, then you can safely ignore the optional enabledProperty.

**Comment by jessegreenberg** [comment]
Sounds good, thank you.  Since the accessibility discussion above has settled and everything looks OK I am closing this issue.
