### ISSUE TITLE
should disabling a UI component set focusable:false?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#154]
This is a general question, but I'll ask it in sun, since most of the 'focus' work seems to have been done there.  I see that sun UI components (e.g., RectangularPushButton) do this:

> focusable: true

Some of these UI components (e.g. RectangularPushButton) are capable of being disabled. 

When a UI component is disabled, should it still be able to receive focus? 
Should it be visited or skipped during tab traversal?
What happens if the UI component that has focus becomes disabled?

**Comment by samreid** [comment]
IDRC recommended making disabled (and even invisible!) components focusable, so that the user can get a sense of what buttons are in the sim, even if they cannot be used at the moment.  For invisible buttons, IDRC recommended fading them into view when focused.

The IDRC recommendation may be unconventional:  I tried

```html
<button type="button">Click Me!</button>
```
and
```html
<button type="button" disabled>Click Me!</button>
```

And only the former was focusable.

I'm not sure of the best way to proceed.

**Comment by samreid** [comment]
It would be good to discuss this issue with @emily-phet and @jessegreenberg. I'm not sure what should happen to focus for disabled components.  Keep in mind that some components will lose focus while the user is dragging them, such as the evaporation slider in Beer's Law Lab.  Reassigning to @emily-phet for now as this appears somewhat of an accessibility design question.

**Comment by jessegreenberg** [comment]
> IDRC recommended making disabled (and even invisible!) components focusable,  so that the user can get a sense of what buttons are in the sim, even if they cannot be used at the moment.

This is my recommendation as well.  The user needs to find the disabled element and learn that some kind of interaction is required with the sim to enable the button.  It is not obvious to me why *invisible* elements should receive focus. This could clash with the pedagogical reasons for making the element invisible.
> Keep in mind that some components will lose focus while the user is dragging them, such as the evaporation slider in Beer's Law Lab.

I am imagining that the beaker in Beer's Law Lab would be represented with an aria-live region so focus should never need to leave the slider.

**Comment by samreid** [comment]
> It is not obvious to me why invisible elements should receive focus. 

I believe this was discussed in the context of an earlier version of forces and motion: basics, where the "go" button is invisible until it was pressable (which seems like it is basically serving the same purpose as enabled/disabled).  We may need to have a more concrete context for discussing invisible components to see if the same rules apply.  If a new button (or other user interface element) gets created, how does the user discover it?  Is that a normal activity?  If so, then leaving invisible objects out of the accessibility tree may be best.

**Comment by jessegreenberg** [comment]
I see, that makes a lot of sense for buttons.  I agree that whether other invisible elements should be navigable will depend on context and sim design.

> If a new button (or other user interface element) gets created, how does the user discover it? Is that a normal activity? If so, then leaving invisible objects out of the accessibility tree may be best.

I am unsure at the moment how normal this behavior is.  There is an 'aria-relevant' property that can be used to notify the user that additions and removals have been made to the DOM.  If invisible objects are left out of the accessibility tree then this property could be an option.

**Comment by emily-phet** [comment]
This can probably be addressed with the appropriate ARIA role, aria-disabled was explored for this in the a11y-research repo. Looks like it was successful for all browsers we test for screen reader accessibility.
