### ISSUE TITLE
add options.minWidth to Panel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#158]
Seems to be a common need for this, for example when you want to have N panels all the same with, currently filled by clients adding an HStrut.  This option would specify the width of the HStrut, and it would be added internally by Panel.  Most recently needed by @phetsims/thejakey in rutherford-scattering.

**Comment by pixelzoom** [comment]
Proposed solution is to add options.minWidth:

> minWidth: 0, // minimum width of the panel

Add a strut to the content like this:

```js
if ( options.minWidth > 0 && content.width < options.minWidth ) {
  content.addChild( new HStrut( options.minWidth ) );
}
```

**Comment by pixelzoom** [comment]
Since the content itself might vary in size dynamically, we probably need to do this:

```js
if ( options.minWidth > 0 && ( content.width < options.minWidth || options.resize === true ) {
  content.addChild( new HStrut( options.minWidth ) );
} 
```

**Comment by pixelzoom** [comment]
`content.addChild` is a bad way to do this, because content may have overridden addChild. For example, if `content` is an HBox (or LayoutBox with orientation:'horizontal') then addChild will position the HStrut to the right of box's other children, effectively extending the width by options.minWidth.

**Comment by thejakey** [comment]
I agree that finding an alternative solution to having `options.minWidth` create a `HStrut` child behind the scenes is preferred

**Comment by thejakey** [comment]
Would something like changing `background.setRect( 0, 0, content.width...` to `background.setRect( 0, 0, Math.max( content.width, options.minWidth )...` work?

**Comment by pixelzoom** [comment]
@thejakey Good suggestion to adjust the width of the background rectangle, that's the approach I used. I also realized that an 'align' option is now needed, since the panel is now possibly wider than the content. options.align can have values 'left', 'right' or 'center' (default), patterned after scenery.LayoutBox.

Take it for a spin in rutherford-scattering and let me know how it works out.

**Comment by thejakey** [comment]
Looking good so far, thanks!
![image](https://cloud.githubusercontent.com/assets/2800720/6361068/4b9e54ba-bc3c-11e4-8f84-172b952b839d.png)
