### ISSUE TITLE
add titleAlignY to AccordionBox

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#159]
Requested to support a feature in https://github.com/phetsims/least-squares-regression/issues/30.

Add options.titleAlignY to sun.AccordionBox, which controls vertical alignment of title relative to expand/collapse button.

> titleAlignY: 'center' // vertical alignment of button and title, 'top'|'center'

Will also need to rename the existing `titleAlign` option to `titleAlignX`.

**Comment by pixelzoom** [comment]
Implementation completed. Assigning to @bereaphysics to review.

**Comment by bereaphysics** [comment]
Looks good, thanks @pixelzoom. Closing.

**Comment by jonathanolson** [comment]
@pixelzoom, can you verify that my change above is what was intended? The default 'center' was erroring on anything that didn't override titleAlignY.

**Comment by pixelzoom** [comment]
@jonathanolson yes, that was a copy-paste error, thanks for catching, sorry for forgetting to test with 'ea'.

**Comment by jonathanolson** [comment]
No worries, I'm just running automated tests more and it was pretty easy to spot.
