### ISSUE TITLE
Add arch support to HSlider

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#161]
HSlider will will need arch support for https://github.com/phetsims/concentration/issues/34

**Comment by samreid** [comment]
Fixed above, but should be reviewed by @pixelzoom since the start drag method was changed to avoid computing values when disabled.

**Comment by pixelzoom** [comment]
startDrag method looks fine.

**Comment by samreid** [comment]
Anything else to do for this issue before it can be closed @pixelzoom ?

**Comment by pixelzoom** [comment]
Nothing else to do for arch support.  Whether there's anything to do for together support will depend on whether we need to "play back" highlighting of the knob, etc.  I'll close this issue and assume that together will be addressed more generally.
