### ISSUE TITLE
OnOffSwitch should deliver values to the arch data stream

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#165]
OnOffSwitch should report values to the arch data stream.  Currently it just signifies whether it was pressed.

**Comment by samreid** [comment]
Fixed above, can I get a micro-review from @jbphet or @pixelzoom?

**Comment by samreid** [comment]
The main thing to review is that my refactoring didn't disrupt the logic of the method.

**Comment by pixelzoom** [comment]
I'll have a look.

**Comment by pixelzoom** [comment]
Looks good, closing.
