### ISSUE TITLE
branch: together

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#167]
I believe that everything in the together branch has been merged into master. If so, please delete the branch.

**Comment by pixelzoom** [comment]
Ditto for arch branch.

**Comment by samreid** [comment]
I deleted the arch branch.  The together branch still has one feature that should be reviewed for merging to master, related to ComboBox together instrumentation.

**Comment by pixelzoom** [comment]
> The together branch still has one feature that should be reviewed for merging to master, related to ComboBox together instrumentation.

Can you describe the feature, or point me to specific lines of code? So I don't have to spend time diff'ing branches and wondering whether I found everything that's relevant...

**Comment by pixelzoom** [comment]
@samreid wrote:
> The together branch still has one feature that should be reviewed for merging to master, related to ComboBox together instrumentation.

Can you describe the feature, or point me to specific lines of code? So I don't have to spend time diff'ing branches and wondering whether I found everything that's relevant...

**Comment by samreid** [comment]
There is only one unmerged commit in the branch, and all changes are in ComboBox.js.  I'm not sure whether it is good for master or not--but it would be good to discuss.

**Comment by pixelzoom** [comment]
Comparing 'master' to 'arch' for ComboBox, I cannot locate this "one feature that should be reviewed for merging to master".  It looks to me like everything in arch appears in master (albeit in a more current form.)

**Comment by samreid** [comment]
We are discussing the `together` branch, not the `arch` branch, see https://github.com/phetsims/sun/issues/167#issuecomment-87906916

**Comment by pixelzoom** [comment]
Ah sorry, I was indeed comparing with arch. (But wondering why I can still compare with the 'arch' branch when you deleted it?)

I see 2 potential "features" in the "together" branch that are not merged into master:

(1) componentType
Looks like there's a `this.componentType` that is passed to arch.start. Not sure how to evaluate this. 

(2) listNodeVisibleProperty
Looks like we're keeping track of whether the list is popped up or not. I don't think that handing the state of UI components should be a responsibility of together.  That would be quite the programming burden. I'd rather see it handled by record/playback of scenery events.

**Comment by samreid** [comment]
This branch is stale and I think we should postpone work on the together branch of ComboBox until (a) we hear whether it is a require feature for our imminent deadlines (b) whether we are going to record UI component state, and if so, whether that will be done with a different technology such as scenery input event recording.  Let's leave this branch alone until the above questions are answered.

**Comment by pixelzoom** [comment]
Assigning to @samreid to delete this branch when it's no longer needed.

**Comment by samreid** [comment]
I deleted the remote branch, please delete your working copy branches at your convenience.
