### ISSUE TITLE
branch: opacity-1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#168]
There's a commit on 2/27/15 by @samreid that says "Set opacity to 1 to force canvas into a single layer" so I'm guessing he created this branch.  No issue number associated with the commit. 

Please describe this branch and what is planned for it.

**Comment by samreid** [comment]
@jonathanolson is working on a way to get scenery to avoid creating lots of layers to handle opacity.  This branch will no longer be necessary once that's done.

**Comment by pixelzoom** [comment]
Assigning to @jonathanolson to delete this branch once the above-mentioned scenery work is completed.

**Comment by samreid** [comment]
I no longer need this branch.  @jonathanolson feel free to delete if you also don't need it.

**Comment by pixelzoom** [comment]
@jonathanolson status?

**Comment by jonathanolson** [comment]
Deleted, closing.
