### ISSUE TITLE
implement 'enabled' feature for CheckBox using opacity

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#171]
SUN.Buttons use opacity to make themselves look enabled/disabled. CheckBox does not, it relies on its label implementing setEnabled, and this is quite cumbersome for clients. Should we change CheckBox be similar to Buttons in how it implements enabled?

Feedback from @jbphet @jonathanolson @samreid please.

**Comment by pixelzoom** [comment]
Eg, this example from hookes-law.VisibilityControls:

> var valuesCheckBox = new CheckBox( new Text( valuesString, TEXT_OPTIONS ), valuesVisibleProperty, CHECK_BOX_OPTIONS );
> valuesCheckBox.disabled = true;

The box will appear disabled, but the text label will not.

**Comment by jonathanolson** [comment]
As far as Scenery performance goes, avoiding opacity will still help even with WebGL, but I'm not sure if the different appearance of button background and text being individually semi-transparent would be too jarring (changing fills to include alpha transparency is much better Scenery-side).

On the other end, if you want to change appearance of the button/checkbox content, enabled listeners are useful. I don't mind having opacity be the default and being able to override it.

**Comment by jbphet** [comment]
I'd vote for using opacity for the default disabled-look behavior in CheckBox and set it up so that the user can easily override it.  The SUN.Button API allows for easy overriding of this behavior through options.contentAppearanceStrategy, perhaps for consistency we could do the same thing for CheckBox.

**Comment by samreid** [comment]
Opacity seems the simplest and most consistent.  If we have to invoke a workaround (something other than opacity) to get good performance in scenery (webgl or not) we should apply that strategy throughout sun, not just in checkbox.

**Comment by pixelzoom** [comment]
OK, I'll take care of this. I'm going to use change CheckBox to use the options.contentAppearanceStrategy approach used in buttons, and default to changing opacity to indicate enabled state.

**Comment by pixelzoom** [comment]
Looks like molecules-shapes and charges-and-fields are the only clients using CheckBox option.checkBoxColorDisabled, which will be going away.

**Comment by pixelzoom** [comment]
Looks like molecules-shapes and charges-and-fields are the only clients using CheckBox option.checkBoxColorDisabled, which will be going away.  I think they will probably work fine with the default contentAppearanceStrategy (using opacity), but reminder to test.

**Comment by pixelzoom** [comment]
Really scary how difficult it has proven to address this issue.

**Comment by pixelzoom** [comment]
This is done. A few notes:

(1) I tried to follow the pattern used in (for example) sun.RectangularPushButton for checkBoxAppearanceStrategy and contentAppearanceStrategy. But CheckBox has no interactionStateProperty, and no button model, so I had to use a simplified variation of the pattern. To go the full distance, CheckBox needs to be reimplemented as a type of toggle button. And that is much more work than I have time for right now.

(2) Two colors where deleted from charges-and-fields.ChargesAndFieldsColors: checkBoxDisabled and controlPanelTextDisabled.  To my eye, the end result looks the same as the most recent dev version (1.0.0-dev.9).  And to my eye, the disabled "Direction only" check box looks much too dim on the black background.  But it's the same look, so I didn't mess with it. @bereaphysics I'll leave it up to you to decide whether you want to change anything. A different appearance would involve passing custom appearance strategies to your check box via options.checkBoxAppearanceStrategy and/or contentAppearanceStrategy.

(3) One color was deleted from molecules-shapes.MoleculeShapesColors: checkBoxDisabled. Comparing to 1.0.0, the behavior is now different.  Previously, the "Show Lone Pairs" text didn't fade out. This is contrary to 'disabled' behavior in other sims, so I didn't try to reproduce the 1.0.0 behavior. As with charges-and-fields the disabled check box looks too dim on the black background.  @jonathanolson I will leave it up to you to decide whether any additional changes are needed.  A different appearance would involve passing custom appearance strategies to your check box via options.checkBoxAppearanceStrategy and/or contentAppearanceStrategy.

**Comment by pixelzoom** [comment]
Assigning to @jbphet for review.

**Comment by bereaphysics** [comment]
I discussed with @arouinfar the checkboxes in charges-and-fields. The new look is dim but this is the point of the disabled look. We will stick with this default strategy. Thanks @pixelzoom

**Comment by jonathanolson** [comment]
Agreed that it looks darker than desired, but I'm fine with the entire contents changing color. I'll create an issue to correct the colors (a color change is still ideal in this case, no opacity needed).

Before that though, can we discuss a potentially better way? If the check box color is on the brighter side of gray, can the opacity be tweaked to look good in the dark-background sims? I'd imagine this would come up often, and we'll generally want less opacity against a dark background.

**Comment by pixelzoom** [comment]
> can the opacity be tweaked to look good in the dark-background sims?

You can tweak the opacity by providing your own options.checkBoxAppearanceStrategy.  Do you have another proposal?  We could add something like checkBoxDisabledOpacity, but that seems redundant, and would only be applicable to the default checkBoxAppearanceStrategy.

**Comment by pixelzoom** [comment]
Example of providing a checkBoxAppearanceStrategy that is more opaque in the disabled state. The default checkBoxAppearanceStrategy uses opacity 0.6 (which I personally think is a tad too transparent in general).

```js
var myCheckBox = new CheckBox( myProperty, content, {
  checkBoxAppearanceStrategy: function( checkBox, enabled ) {
      checkBox.opacity = enabled ? 1 : 0.75;
  } 
} );

**Comment by pixelzoom** [comment]
As I mentioned above:
> The default checkBoxAppearanceStrategy uses opacity 0.6 (which I personally think is a tad too transparent in general).

Rather than a different opacity for dark background, perhaps we can find a default opacity that works well on light and dark backgrounds?

**Comment by jonathanolson** [comment]
Yes, an opacity that works well in all situations would be best.

**Comment by pixelzoom** [comment]
@jbphet reminder that you're assigned to review this.

**Comment by jbphet** [comment]
Commits look good - seems like this eliminated a fair amount of code.  I tested the behavior on several sims that set checkboxes to be disabled, and it worked great in all cases.  I also tested setting various options, such as the background color, and made sure that they all worked well with setting of the enabled state.  All in all, this looks awesome.  Nice.  Closing.
