### ISSUE TITLE
Panel options are unconventional

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#172]
Panel options are unconventional.  Currently looks like:

```js
    options = _.extend( {}, defaultOptions, options );
```

Lodash says the 3-arg extend function expects a function for 3rd argument.  How is this working at all?

**Comment by samreid** [comment]
If I recall correctly, this is how we normally do it:

```js
    options = _.extend( {
      fill: 'white',
      stroke: 'black',
      lineWidth: 1, // width of the background border
      xMargin: 5,
      yMargin: 5,
      cornerRadius: 10, // radius of the rounded corners on the background
      resize: true, // dynamically resize when content bounds change
      backgroundPickable: false,
      align: 'right', // {string} horizontal of content in the pane, left|center|right
      minWidth: 0 // minimum width of the panel
    }, options );
```

**Comment by samreid** [comment]
It looks like Panel is exporting defaultOptions.  Is this used anywhere?

**Comment by samreid** [comment]
Oh, perhaps exporting defaultOptions is the entire reason for doing it this way?

**Comment by pixelzoom** [comment]
This was done by @jonathanolson for molecules-shapes, see https://github.com/phetsims/sun/commit/0cc96ae771152e54794b75fef8026407ce2d95f2

**Comment by jonathanolson** [comment]
Yes, it's a pattern that makes defaults available. Currently used in Molecule Shapes, so we can combine user options and default options and determine what options will be used.

**Comment by pixelzoom** [comment]
@samreid Did @jonathanolson address your concern? Can this be closed, or is there something to do here?

**Comment by samreid** [comment]
OK makes sense.  Thanks for explaining.  Closing.
