### ISSUE TITLE
add ES5 set/get enabled for HSlider

### ISSUE THREAD

**Issue by jbphet** [phetsims/sun#177]
HSlider has an enabled property that can be used to control its enabled state.  For consistency with other Sun components, such as check boxes and buttons, it should be possible to set this state via an ES5 setter, e.g. ```myHSlider.enabled = false```.

**Comment by pixelzoom** [comment]
For consistency with other sun components, I also recommend removing options.enabledProperty.  Other sun components do not have this property, HSlider is unique in this respect.

**Comment by pixelzoom** [comment]
I believe that @jbphet is referring to the enabled Property (uppercase 'P') versus a JavaScript property (lowercase 'p').

For consistency with other sun components, I also recommend removing options.enabledProperty.  Other sun components do not have this property, HSlider is unique in this respect.

**Comment by pixelzoom** [comment]
@jbphet I see that you've added this feature like this:

```js
    set enabled( value ) {
      this.enabledProperty.value = value;
    },

    get enabled() { return this.enabledProperty.value }
```

First, this doesn't pass lint, missing semicolon.

My understanding is that we've agreed to use the scenery pattern for setters/getters. That is, provide both a standard set/get, and an ES5 set/get.  So the above should be:

```js
    setEnabled: function( enabled ) { this.enabledProperty.value = enabled; },
    set enabled( value ) { this. setEnabled( value ); },
 
    getEnabled: function() { return this.enabledProperty.value; },
    get enabled() { return this. getEnabled(); }
```

**Comment by pixelzoom** [comment]
I'd also like to see the code use one consistent way of accessing the value of enabledProperty. The existing code used this.enabledProperty.get(), so I think that the added code should do the same.

**Comment by pixelzoom** [comment]
At 4/21/15 developer meeting we discussed whether to remove options.enabledProperty from HSlider (and RadioButtonGroup) or use this pattern when adding enabled set/get to other sun components. We decided to remove options.enabledProperty.

**Comment by pixelzoom** [comment]
I'm not so sure that we should remove options.enabledProperty.  I'm kind of liking this pattern.

**Comment by samreid** [comment]
> I'm not so sure that we should remove options.enabledProperty. I'm kind of liking this pattern.

I agreed it is nice where it is used, but I think the trouble was that we weren't consistently supporting this pattern.  Perhaps we could more broadly support this pattern?

**Comment by pixelzoom** [comment]
Moved the issue of whether to remove options.enabledProperty to https://github.com/phetsims/sun/issues/178.  

So the original work covered by this issue is completed, closing.
