### ISSUE TITLE
remove options.enabledProperty from sun components

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#178]
https://github.com/phetsims/sun/issues/177#issuecomment-94874207

> At 4/21/15 developer meeting we discussed whether to remove options.enabledProperty from HSlider (and RadioButtonGroup) or use this pattern when adding enabled set/get to other sun components. We decided to remove options.enabledProperty.

**Comment by pixelzoom** [comment]
This was also proposed for HSlider in https://github.com/phetsims/sun/issues/177.

No consensus yet on whetherr we should do this.

**Comment by aaronsamuel137** [comment]
I can work on this if that's what we decide, but it sounds like @samreid and @pixelzoom are liking this pattern, and so am I. Perhaps we should just leave things as they are?

**Comment by pixelzoom** [comment]
Since it's part of the options API, I'm OK with leaving it as is. If we encounter additional situations where we wish we had this option, then we can revisit adding it as a standard thing.  If we don't encounter such situations, it's not tragic if these are the only cases where it's useful.

**Comment by pixelzoom** [comment]
If @samreid feels the same way, then I'm OK with closing this issue.

**Comment by samreid** [comment]
Yes, I agree with @pixelzoom's statement here https://github.com/phetsims/sun/issues/178#issuecomment-104394687, closing.
