### ISSUE TITLE
Do we need a ComboBox.dispose() function if ComboBoxes are long-lived?

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#181]
Same question as https://github.com/phetsims/scenery-phet/issues/150 but for ComboBox.  Do we need a dispose() function if ComboBoxes are long-lived?

**Comment by pixelzoom** [comment]
Nothing that has the same lifetime as the sim needs a dispose function. But when writing reusable components, I think a dispose function should generally be part of the required implementation.  It's relatively easy to add when you're writing code.  It's relatively expensive if you wait to implement "when needed".  (And I'm speaking from repeated experience here.)

**Comment by pixelzoom** [comment]
Nothing that has the same lifetime as the sim needs a dispose function. But I don't think you can make that assumption when writing reusable UI components. So when writing reusable UI components, I think a dispose function should generally be part of the required implementation. It's relatively easy to add when you're writing code. It's relatively expensive if you wait to implement "when needed". (And I'm speaking from repeated experience here.)

**Comment by pixelzoom** [comment]
I completed the implementation of this.disposeComboBox. Assigning to @samreid for review.

**Comment by samreid** [comment]
I saw another listener in the constructor that is not getting removed:

```js
    buttonNode.addInputListener(
      {
        down: function() {
          if ( !listNode.visible ) {
            self.trigger0( 'startedCallbacksForComboBoxPopupShown' );

            moveList();
            listNode.visible = true;
            enableClickToDismissListener = false;
            sceneNode = self.getUniqueTrail().rootNode();
            sceneNode.addInputListener( clickToDismissListener );

            self.trigger0( 'endedCallbacksForComboBoxPopupShown' );
          }
        }
      } );
```

Does this need to be `removeEventListener`ed?

Also, do we need to remove the itemListener from the items?

```js
    for ( var j = 0; j < items.length; j++ ) {

      var itemNodeOptions = items[ j ].options;

      // Create the list item node itself
      var itemNode = new ItemNode( items[ j ], itemWidth, itemHeight, options.itemXMargin, itemNodeOptions );

      // add item to list
      listNode.addChild( itemNode );
      itemNode.left = options.buttonXMargin;
      itemNode.top = options.listYMargin + ( j * itemHeight );

      // item interactivity
      itemNode.cursor = 'pointer';
      itemNode.addInputListener( itemListener );
    }
```

**Comment by pixelzoom** [comment]
We do not need to remove the listener added to buttonNode. buttonNode and the listener have the same lifetime, and are both owned by the ComboBox.  Ditto for the itemNodes and itemListener.

**Comment by samreid** [comment]
I see, thanks for clarifying that (I think I have been fuzzy on that issue previously).  Everything else seems good.
