### ISSUE TITLE
Move HSlider to new dispose pattern

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#182]
HSlider stores many values as instance variables (as opposed to closure variables) and calls them in its dispose function.  @jbphet and @samreid have identified a superior pattern for handling this.  An example is forthcoming in MomentaryButtonModel.

**Comment by samreid** [comment]
See 4ef67ea907bfc72a2b2e06643589eb68c3543401 changes to MomentaryButtonModel.

**Comment by pixelzoom** [comment]
To make sure I understand... The "superior pattern" is to define this.disposeXXX (e.g., this.disposeComboBox) for each instance, and call that function from the prototype dispose function.  Is that correct?

**Comment by samreid** [comment]
Yes, that's it.  It allows us flexible naming through closure variables (and without having to keep creating publicly accessible instance variables) while still working properly with subclassing.

**Comment by pixelzoom** [comment]
Like.  Reducing to 1 instance variable greatly reduced the possibility of accidental shadowing by subtypes.  And I'd like to explicitly propose that the instance function should be named `this.disposeXXX`, where `XXX` is the name of the constructor.  For example `this.disposeComboBox` for type `ComboBox`. Following that convention will ensure that subtypes don't accidentally shadow the function.

**Comment by pixelzoom** [comment]
This is done, assigning to @jbphet to verify. The changes were very difficult to test, and touched tandem instrumentation. So take a peek and let me know if you see any problems.

**Comment by pixelzoom** [comment]
I also did some general cleanup, mentioned in the commits above. You can ignore the commits to hookes-law, they were included accidentally.

**Comment by pixelzoom** [comment]
Labeling this issue as high-priority for review, since it has the potential to mess up a lot of sims.

**Comment by jbphet** [comment]
Review completed.  I noticed one place where a link was being done that should probably be an unlink, see https://github.com/phetsims/sun/commit/7b9e8cb3f973a976dc32f3f2a8c61331becb4d25.

I also tested this by using the constraint capability to implement an integer slider in the beaker sim, and it worked well.  Closing.
