### ISSUE TITLE
add ability to constrain value to HSlider

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#183]
I need to constrain the value set by HSlider.  In Hooke's Law, the range of spring constant is 100-1000 N/m, but the requirement is to constrain the slider so that the value can only be set in increments of 10.  I'm proposing to add `options.constrainValue` to HSlider,  with default value `function(value) { return value; }`. This will be called immediate before any call to valueProperty.set.  Does anyone object to this?

Here's how you could use this to constrain dragging to (for example) increments of 10:

```js
var mySlider = new HSlider( valueProperty,... {
  constrainValue: function( value ) {
    return Math.round( value / 10 ) * 10;
  }
};
```

**Comment by pixelzoom** [comment]
Another way to handle this would be to specify something like options.sliderIncrement, then do:

`value = Math.round( value / options.sliderIncrement ) * options.sliderIncrement;`

But options.constrainValue seems more flexible.

**Comment by pixelzoom** [comment]
Feedback on Skype:

AD: fine with me
JB: Sounds good to me, and will be useful for something that we need to do shortly for beaker.  This also seems like a cool way to create things like integer-only sliders.  So yeah, good idea, I say go for it.
SR: I think options.constrainValue seems best
JB: I think I like the sound of the more general approach (options.constrainValue).

**Comment by pixelzoom** [comment]
This also assumes that the model plays nice, and uses the same increment. Ie, if the slider is told to set its value to 93, it should not try to adjust the value to some multiple of 10 (for example).

**Comment by pixelzoom** [comment]
Done as described above. @aaronsamuel137 could you please review?

**Comment by pixelzoom** [comment]
@aaronsamuel137 reminder that you're assigned to review this.

**Comment by aaronsamuel137** [comment]
Looks great. Closing
