### ISSUE TITLE
replace InOutRadioButton with RadioButtonGroup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#184]
Motivated by https://github.com/phetsims/sun/issues/50, https://github.com/phetsims/sun/issues/51 and https://github.com/phetsims/sun/issues/132.

InOutRadioButton has significant problems, and has a "shadow" look that we intentionally moved aware from for game buttons (e.g., vegas.LevelSelectionButton).  RadioButtonGroup is superior. 

InOutRadioButton is currently used in these sims (designer in parentheses):

- [x] acid-base-solutions (Kelly L)
- [x] balloons-and-static-electricity (Noah P & Sam R)
- [x] estimation (Bryce G)
- [x] fraction-comparison (Karina H)
- [x] under-pressure (Sam R)

I don't see any reason why we shouldn't replace them with RadioButtonGroup.

@samreid suggested in https://github.com/phetsims/sun/issues/51#issuecomment-58368549 that we should discuss with designers.

**Comment by pixelzoom** [comment]
@ycarpenterphet Do you see any reason why we can't replace InOutRadioButton with RadioButtonGroup in acid-base-solutions? 

Here's acid-base-solutions with InOutRadioButton:

![screenshot_15](https://cloud.githubusercontent.com/assets/3046552/7359410/53c2eecc-ecfb-11e4-872e-edaa8e21b960.png)

Here's acid-base-solutions with RadioButtonGroup:

![screenshot_16](https://cloud.githubusercontent.com/assets/3046552/7359416/6371ba7e-ecfb-11e4-9af6-14ba6487d607.png)

**Comment by pixelzoom** [comment]
@samreid You and Noah P. are listed as the designers for balloons-and-static-electricity. So I think it's your call about switching to RadioButtonGroup. What say ye?

**Comment by pixelzoom** [comment]
Looking at the list of sims above (https://github.com/phetsims/sun/issues/184#issue-71421084), with the exception of @samreid, all of the designers are no longer with the project.  So how are we going to resolve this?

**Comment by samreid** [comment]
I think balloons will work well with RadioButtonGroup.  I also think we should use RadioButtonGroup for the other cases as well (though I didn't review each one in context).  I think if we run across situations where RadioButtonGroup doesn't look perfect, we should adapt RadioButtonGroup to work instead of using InOutRadioButton instead.  But I think @ariel-phet needs to be in this discussion since he was around for the advent of InOutRadioButton in fractions sim.

**Comment by pixelzoom** [comment]
I agree that RadioButtonGroup will work well. To my eye, the indication of which item is selected is superior.

@ariel-phet The proposal is to replace all usages of InOutRadioButton with RadioButtonGroup, and delete InOutRadioButton.  Let us know what you think, then assign back to me.

**Comment by ariel-phet** [comment]
Agreed, that drop shadow look was sort of an older variant, and I agree that the RadioButtonGroup has a major advantage of clarity over which item is selected. We also have good evidence of this clarity from interviews since it is the same paradigm used in our "Scene" selection buttons, as well as a similar paradigm to what is done for the Screen selection icons on the navbar.

**Comment by pixelzoom** [comment]
OK. I'll do the conversions to RadioButtonGroup

**Comment by pixelzoom** [comment]
acid-base-solutions, balloons-and-static-electricity and under-pressure are published sims, so their look can be compared to the versions on the PhET website.

For the other 2 sims, I published dev versions before changing to RadioButtonGroup, to facility before/after comparisons.  Here are those dev versions:

http://www.colorado.edu/physics/phet/dev/html/estimation/1.0.0-dev.3/estimation_en.html
http://www.colorado.edu/physics/phet/dev/html/fraction-comparison/1.0.0-dev.11/fraction-comparison_en.html

**Comment by pixelzoom** [comment]
@ycarpenterphet You can ignore the request above. We decide to change all sims to RadioButtonGroup, so that they have a uniform look.

**Comment by pixelzoom** [comment]
Can InOutRadioButton and InOutRadioButtonView in js/experimental/buttons also be deleted?

**Comment by samreid** [comment]
Discussed over skype, the answer is yes.

**Comment by pixelzoom** [comment]
I have reviewed acid-base-solutions, since I was the developer liaison.

Could the responsible developers please review the other sims? That is:

@jbphet: estimation

@samreid: balloons-and-static-electricity, fraction-comparison, and under-pressure

**Comment by pixelzoom** [comment]
Btw.. estimation was the most time consuming. The icons originally contained the white background, and they had to be recreated from the .ai files with transparent backgrounds.

**Comment by samreid** [comment]
Sim + code looks good for balloons-and-static-electricity, fraction-comparison, and under-pressure, nice work.  @jbphet can look at estimation next.

**Comment by jbphet** [comment]
Looks good in estimation too, closing.
