### ISSUE TITLE
experimental/SliderKnob.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#185]
js/experimental/SliderKnob.js has no doc, and I don't see an issue related to it. What is this and what is the plan for it?  Can it be deleted?

**Comment by pixelzoom** [comment]
Assigning to @jbphet since commits show that he was the author and did most of the work on it.

**Comment by jbphet** [comment]
There was a request from @ariel-phet from quite a while ago to make a slider knob based on the newly created (at the time) button code.  This was prototyped, shown at a team meeting, and I believe the direction was to continue working on it.  However, other priorities took precedence.  We can leave this open as a reminder to get back to it at some point.

**Comment by pixelzoom** [comment]
@dubson reported (and I confirmed) that the sun demo app is now broken due to the experimental SliderKnob. I am commenting it out.

**Comment by jbphet** [comment]
In the interest of code cleanliness, I decided to delete the experimental SliderKnob and remove the commented-out code from the demo.  I think we would use a different approach now anyway, given that the buttons have evolved a lot.  Closing.
