### ISSUE TITLE
RadioButton lacks 'enabled' feature

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#186]
RadioButton and its subtypes (e.g. AquaRadioButton) currently lack the 'enabled' feature. This is needed for hookes-law-lab.  I'll add it as we have for other sun components - using opacity.

**Comment by pixelzoom** [comment]
It would be nice to someday make RadioButton and its subtypes more similar to the components in sun/buttons/. That is, have a RadioButtonModel and various radio button views.  But that's a huge chunk of work. So for now, I've implemented the 'enabled' feature in the context of how RadioButton is currently implemented.  

Assigning to @jbphet for review.

**Comment by jbphet** [comment]
I'm not seeing anything in the code that disables pickability, so I tried just setting enabled false on an AquaRadioButton in a sim (acid-base-solutions) and the button got transparent but still worked.  So I think pickability may need to be set.  Back to you, @pixelzoom.

**Comment by pixelzoom** [comment]
(Accidentally checked in BracketNode in the above commit, you can ignore that.)

`this.pickable = enabled`

Back to @jbphet.

**Comment by jbphet** [comment]
Looks good, closing.
