### ISSUE TITLE
issues with PressAndHoldListener

### ISSUE THREAD

**Issue by jbphet** [phetsims/sun#189]
While working on https://github.com/phetsims/scenery-phet/issues/71, I observed two issues with PressAndHoldListener:

1. the endCallback function is called even if the button is disabled
2. the first firing from press-and-hold doesn't occur until after the timerDelay plus one timerInterval.  It should probably fire the first time after one timerDelay

@pixelzoom and I discussed whether this listener type could be eliminated altogether since the functionality for buttons is being pulled into PushButtonModel, but this doesn't appear to be an option since this listener is used for things other than buttons, such as in NumberPicker.js.

**Comment by pixelzoom** [comment]
@jbphet Why is this assigned to me? Can't you make the same fixes that you did when you copied this code into sun buttons?

**Comment by jbphet** [comment]
Removed accidentally committed debug statements in 3b38f4eff215f7dbf2dd4f9b6e735fcf701c43b9.

**Comment by jbphet** [comment]
Changes made, back to you @pixelzoom.

**Comment by pixelzoom** [comment]
The amount of duplication with between PressAndHoldListener  and PushButtonModel still bothers me. I'm going to take a closer look, perhaps there's some general "handler" pattern than can be factored out and used in both places.

**Comment by pixelzoom** [comment]
Tested with ArrowButton and NumberPicker. Closing.
