### ISSUE TITLE
bad arg to supertype constructor in ButtonModel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#190]
Here's how ButtonModel calls its supertype constructor:

```js
    PropertySet.call( this, {

      // Property that tracks whether or not a pointer that could interact with the button is currently over the button.
      over: false,

      // Property that tracks whether a pointer is currently down on, a.k.a. pressing, the button.
      down: false,

      // Property that tracks whether or not the button is enabled.
      enabled: true
    }, 'buttonModel' );
```

The last arg to PropertySet is supposed to be {Object} options, so I don't know how passing {string} 'buttonModel' is working.

**Comment by pixelzoom** [comment]
Here's the fixed supertype constructor call. (I also took some of the obvious/verbose verbage out of the properties comments.)

```js
PropertySet.call( this, {
      over: false,  // Is pointer over the button?
      down: false, // Is pointer down?
      enabled: true  // Is the button enabled?
    }, options );
```

I'm guess that the 'buttonModel' arg was vestigial, leftover from one of the many together approaches that was tried.  Assigning to @jbphet to answer to verify that, and to verify the changes.

**Comment by jbphet** [comment]
Indeed, that was a bad argument.  The fixes look good and make sense.  I'll do some testing as well once the issues described in https://github.com/phetsims/scenery-phet/issues/71#issuecomment-117849861 is cleared up.

**Comment by jbphet** [comment]
Commit looks good.  Button behavior tested in Sun Demo, Faraday's Law, Example Sim, Hooke's Law, and Area Builder and the behavior seems correct in all cases.  Closing.
