### ISSUE TITLE
add visibility annotations

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#195]
Add a @public, @protected or @private annotation to anything that's publicly visible.
See https://github.com/phetsims/tasks/issues/307.

**Comment by jbphet** [comment]
Did this, closing.

**Comment by jbphet** [comment]
A few updated are needed based on things that were discussed in the 11/19/2015 status meeting, namely that annotations for tandem should be ```@public (tandem)``` and those for accessibility should be ```@public (accessibility)```.

**Comment by jbphet** [comment]
Additional annotations added, this should cover it, closing (again).
