### ISSUE TITLE
sun demo should use default ScreenView layoutBounds

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#196]
If we want this demo to be representative of what sun components typically look like, we should probably be using the default layoutBounds. It's currently using `new Bounds2( 0, 0, 768, 504 )`, the default is `new Bounds2( 0, 0, 1024, 618 )`.

**Comment by pixelzoom** [comment]
@jbphet I'll take care of this for scenery-phet (https://github.com/phetsims/scenery-phet/issues/182), how about you handling sun?

**Comment by jbphet** [comment]
this has been addressed, closing
