### ISSUE TITLE
design of arrow buttons in carousel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#197]
Related to #166 (create a Carousel), the desired look of the buttons is shown below. This button is not a rounded rectangle. Two corners are rounded to match the corners of the carousel, the other 2 corners are squared off.

The sun library currently supports rectangular and circular push buttons (RectangularPushButton and RoundPushButton, respectively).  We do not have support for the button shape requested here, which would require an arbitrary shape to implement. 

Options:
(1) Change the requirements and use RectangularPushButton (least amount of work, approach used in Area Builder)
(2) Create a one-off button for use in Carousel (not recommended)
(3) Add support to sun for buttons with arbitrary shapes (a ton of work)

Assigning to @ariel-phet to decide how to proceed. Also mentioning @amanda-phet, since I'm working from her requirements in the Function Builder design doc, which @ariel-phet has stated is the requirements specification for Carousels in general.

![screenshot_619](https://cloud.githubusercontent.com/assets/3046552/9864127/87cf3d6c-5b03-11e5-8cea-ad1f7f2674a0.png)

**Comment by pixelzoom** [comment]
For comparison, here's a carousel from Level 4 of the Area Builder "Game" screen:

![screenshot_621](https://cloud.githubusercontent.com/assets/3046552/9864274/1135d678-5b05-11e5-9384-978da7c3fce7.png)

And here's a prototype from Function Builder that uses RoundPushButton:

![screenshot_620](https://cloud.githubusercontent.com/assets/3046552/9864254/f253b702-5b04-11e5-9c99-1b268837b83b.png)

**Comment by ariel-phet** [comment]
@pixelzoom are you saying that something like this could work

![alternate](https://cloud.githubusercontent.com/assets/4051174/9864317/8d5fc858-5b05-11e5-986d-324cc35d19ea.png)

**Comment by ariel-phet** [comment]
@amanda-phet - a bit part of this will be your call...how important is the look of this button on the end to you...does it have to fill the entire height? Could it have rounded inside corners (obviously not as nice aesthetically)

**Comment by ariel-phet** [comment]
@pixelzoom - I understand option (2) is not ideal, but can you flesh out a bit more why not recommended?

**Comment by pixelzoom** [comment]
> https://github.com/phetsims/sun/issues/197#issuecomment-140232097

Sorry, but... ugly.

>  I understand option (2) is not ideal, but can you flesh out a bit more why not recommended?

Because we don't need more one-off code. We spent a great deal of time on sun buttons, and I don't relish the task of reproducing what they do.  Highly recommend to choose (1), with a longterm plan to do (3).

**Comment by pixelzoom** [comment]
Also wondering... If (1) is not acceptable, then why was it acceptable in Area Builder?

**Comment by ariel-phet** [comment]
(1) was acceptable for the same reasons, but not ideal. Were hoping to fix it in the more generalized version.

**Comment by amanda-phet** [comment]
When we had the carousel design meeting a while back, it was pretty clear that these buttons were problematic, but that it was probably important long-term to be able to draw a button with two rounded corners. 

One thing I don't like about the button in Area Builder is that it is layered on top of the panel itself, and with the transparency it makes the stroke around the panel gray-ish on the edges. 
<img width="57" alt="screen shot 2015-09-14 at 6 39 21 pm" src="https://cloud.githubusercontent.com/assets/7852916/9865179/f4e5324c-5b0f-11e5-988c-3e96dd385cac.png">

Is it possible to make the button a gray rounded rectangle (with no stroke), layered under the panel stroke so that it does not cover it? Like this: 
<img width="201" alt="screen shot 2015-09-14 at 6 37 29 pm" src="https://cloud.githubusercontent.com/assets/7852916/9865160/b4ade4f8-5b0f-11e5-9fb7-7c38b52dac8c.png">
 


>Also wondering... If (1) is not acceptable, then why was it acceptable in Area Builder? 

I believe Area Builder was developed before the carousel design meeting happened- and actually prompted the discussion.

**Comment by pixelzoom** [comment]
@amanda-phet wrote:
> One thing I don't like about the button in Area Builder is that it is layered on top of the panel itself, and with the transparency it makes the stroke around the panel gray-ish on the edges. 

I noticed this too, yuck. The buttons in the new Carousel (and in Function Builder) do not overlap the carousel outline. Whether or not to stroke the edge of the button is optional. See sample in https://github.com/phetsims/sun/issues/197#issuecomment-140231587, where the button is edge is lightly stroked.

**Comment by pixelzoom** [comment]
A couple of other options that occurred to me, neither of them easy, but worth discussing:

(4) Change the API of scenery.Rectangle so that the radius of each corner can be specified separately. 

(5) Change the API of sun.RectangularPushButton so that the radius of each corner can be specified separately.

**Comment by pixelzoom** [comment]
@ariel-phet and @amanda-phet I'm going to proceed with using buttons where all 4 corners are rounded (option 1) since this is the only option that is currently supported by PhET's button library.  

Since this issue has come up before (and is certain to come up again), we should add support for it to sun. I've labeled this issue for discussion at developer meeting, to decide how to proceed.

**Comment by pixelzoom** [comment]
The button was factored out into CarouselButton, and I've referenced this issue in a TODO item in the code.

**Comment by pixelzoom** [comment]
9/17/15 dev meeting notes:

• add support to kite to create this shape (2 rounded corners)
• 3D look of buttons makes it difficult to do for arbitrary shapes
• investigate how it looks with the shape shoehorned into RectangularButtonView

**Comment by pixelzoom** [comment]
Sub-issues have been broken out into separate issues (shown immediately above), so closing.
