### ISSUE TITLE
make PageControl interactive

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#199]
Email from @kathy-phet:

> I noted that you can click on the dots at colorado.edu ... not suggesting to change behavior in what you built, but just to give an example of the when that functionality does exist. http://www.colorado.edu/

**Comment by pixelzoom** [comment]
I added interactivity and stroke/lineWidth options for the dots. You can now emulated the dots at www.colorado.edu if that's what's desired.

**Comment by pixelzoom** [comment]
This will be reviewed as part of #166. Closing.

**Comment by pixelzoom** [comment]
Reopening. Pandora is out of the box. 

iOS page control (UIPageControl) does have a setting that enabled interactivity. You can see it in action on the home screen of iPad and iPhone. Problem is that it behaves differently than the page control on www.colorado.edu, which is what I implemented.  UIPageControl doesn't seem to let you jump to a specific page. Instead, clicking left/right of the current-page dot changes the selection to the previous/next page.  On www.colorado.edu, the control lets you jump immediately to any page. 

So... I'll need to investigate whether UIPageControl has some feature that I'm not aware of, or whether we need to decide which behavior(s) to implemented, what the default should be, etc.

**Comment by pixelzoom** [comment]
More in-depth information on UIPageControl is at https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/UIKitUICatalog/UIPageControl.html.

Class reference page is https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIPageControl_Class/index.html#//apple_ref/doc/uid/TP40006781, which says:

> The page control advances only one page in either direction.

So it looks like jumping immediately to a specific page is not supported.

@kathy-phet please advise on how you'd like this to behave.

**Comment by pixelzoom** [comment]
I think what I'll do here is support both types of interactivity.

**Comment by samreid** [comment]
@pixelzoom does this still need to be marked for developer-meeting?

**Comment by pixelzoom** [comment]
Yes.

**Comment by pixelzoom** [comment]
Comment from @kathy-phet via email:
> I did think that Amanda had a good point that on touch the dots are pretty un-useable in terms of available touch area interaction. However, that does also make me wonder if we are supporting swipe interaction to change pages. And just wondering -- not saying we should or should not include that.

Can't find my email reply, but the main points are:
• page control doesn't handle swipe
• support for "swipe" and other gestures is a larger issue, not specific to this control
• gestures differ by OS and device
• overriding the native swipe behavior of the browser seems rude
• defining consistent semantic for gestures is essential; e.g., does swipe mean "change screen", "change scene on the current screen", ... ?

**Comment by samreid** [comment]
Swipe is tricky from a pure UI standpoint (ignoring issues of implementation).  Because items in the carousel are often dragged out, the user would have to grab onto part of the carousel that doesn't have an item to drag the carousel.  Could be awkward for carousels that are "packed full" of items and don't have much blank space for dragging the carousel itself.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/sun/issues/166#issuecomment-142759431, @jbphet asked:
> Do we want to add some touch and mouse area expansions to the PageControl? I just tested on an iPad, and the page control does work for switching screens, and it might be tricky to touch these little circles if the touch area isn't expanded a bit.

Pointer areas will be addressed after we decide what type(s) of interactivity is desired.

**Comment by pixelzoom** [comment]
9/24/15 dev meeting

• individual dots are not particularly useful as an interactive control, even with mouse
• most likely to use these as just an indicator
• we'll revisit the interactivity issue when someone needs interactivity, and open a new issue

Closing.

**Comment by samreid** [comment]
There are still TODOs marked for this issue, discovered during https://github.com/phetsims/chipper/issues/946

**Comment by pixelzoom** [comment]
Found and closed 1 TODO, that should have been removed when we decided:
> * • we'll revisit the interactivity issue when someone needs interactivity, and open a new issue
