### ISSUE TITLE
Why isn't "step" button in play controls a "fire on hold" button?

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/sun#203]
@pixelzoom only assigning you since I figure you can answer this question, but also could be an appropriate developer meeting question.

It seems to me the default for our "step" button when it comes to play/pause/step controls should be that it is a "fire on hold" button like the tweaker. Would that be an easy change to make. I encountered this while using bending light and it seemed it would be natural to allow that functionality.

**Comment by samreid** [comment]
In discussion with @ariel-phet, he suggested firing a step event every 250ms or so.

**Comment by pixelzoom** [comment]
Do you mean scenery-phet.StepButton? (This issue is in sun.)  

Fire-on-hold seems like a fine option to add this button (on by default?)  It's implemented in sun.PushButtonModel (options below), so you should be able to add it easily to StepButton.  I would start with the default delay and interval and see how that feels. 


```js
      // fire-on-hold feature
      fireOnHold: false, // is the fire-on-hold feature enabled?
      fireOnHoldDelay: 400, // start to fire continuously after pressing for this long (milliseconds)
      fireOnHoldInterval: 100 // fire continuously at this interval (milliseconds)
```

**Comment by samreid** [comment]
I added fireOnHold to StepButton (on by default) in the above commit, this will affect all sims that use StepButton.  We should spot-test a few sims that use this feature.  It is working great in Bending Light.

**Comment by samreid** [comment]
I used the default options and they seemed good in Bending Light.

**Comment by ariel-phet** [comment]
BTW @pixelzoom I did not know where StepButton lived, so sun was my best guess...

**Comment by pixelzoom** [comment]
No problem. I've never used the step button, and didn't know if there was in fact one, so thought it best to clarify.  Also didn't notice when reading the GitHub notification on my phone that you had created the issue.

**Comment by jbphet** [comment]
Just tried this in Neuron, and it works great, but it was weird that the StepBackButton didn't work the same way, so I've added it there as well.

**Comment by jessegreenberg** [comment]
Just tried it in Molecules and Light, works well and the default options look good there too.

**Comment by pixelzoom** [comment]
No usages is my sims.

**Comment by jbphet** [comment]
All devs will test the sims for which they are responsible and will report any issues here.  If nothing found in a week, this can be closed.

**Comment by pixelzoom** [comment]
Sims to be tested:

- [ ] bending-light
- [ ] color-vision
- [ ] energy-forms-and-changes
- [ ] energy-skate-park-basics
- [ ] fluid-pressure-and-flow
- [ ] gravity-and-orbits
- [ ] molecules-and-light
- [ ] neuron
- [ ] pendulum-lab
- [ ] rutherford-scattering
- [ ] states-of-matter
- [ ] wave-on-a-string

**Comment by samreid** [comment]
I checked all of the sims for which I am primary developer, as well as pendulum lab and wave on a string.  Everything looks great, nice suggestion @ariel-phet. Closing.
