### ISSUE TITLE
ButtonModel: unnecessary override of dispose

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#206]
ButtonModel extends PropertySet, then overrides dispose:

```js
   dispose: function() {
      PropertySet.prototype.dispose.call( this );
    }
```

There is no new functionality added to dispose here, so it's unnecessary.

**Comment by jbphet** [comment]
Not sure why that was there - whether there were other things that were subsequently removed, if it was copied from something else, or what.  At any rate, it is gone now.  Closing.
