### ISSUE TITLE
sun: defaults for touchArea dilation should be zero

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#207]
Search for `touchArea =` to find cases where a default touchArea is being set.  For example, RoundButtonView and RectangularButtonView are both dilating the touchArea by default. 

Sun is a general-purpose library of UI components. It has no prior knowledge about how large a UI component will be. The client has control over the size of the UI component. So (imo) the client should also be responsible for deciding whether touchAreas (and pointerAreas) require dilation.

**Comment by samreid** [comment]
Not feeling too strongly on the issue, but wanted to make sure someone elucidated the counter-points: (a) having a default touch area for buttons makes them touch friendly when used at their normal size and not directly adjacent to each other
(b) if we set the touchArea dilation to 0 as a default, how many simulations will we have to iterate through and duplicate the code "touchAreaExpansionX:5, touchAreaExpansionY:5" or equivalent?

**Comment by pixelzoom** [comment]
> "when used at their normal size"

How does a button have any inherent "normal size"? The size of a button is fully dependent on its content and margin. And sun is a general-purpose API, not PhET specific.

**Comment by pixelzoom** [comment]
1/7/16 dev meeting: We decided to set defaults to 0, and add testing with `?showPointerAreas` to QA checklist.

**Comment by samreid** [comment]
1/7/16 dev meeting: perhaps composite components such as radio button groups should set the touch areas of its own components.

**Comment by samreid** [comment]
1/7/16 dev meeting: @jonathanolson suggests providing a bounding box for a component or group of components, so that the touch areas of elements expand to fill the bounding box.

**Comment by pixelzoom** [comment]
I set the touchArea-related options to zero for sun.buttons.  Have not addressed other type in sun.

**Comment by pixelzoom** [comment]
Only 2 components remaining that have non-zero pointer area options:

AccordionBox
VerticalAquaRadioButtonGroup

Looks like it would fairly straightforward to move the non-zero value to the client call sites, so that sim behavior is unchanged for these components.

**Comment by pixelzoom** [comment]
Here's what the default AccordionBox touchArea looks like, way too large and likely to bump into something in the general case.

![screenshot_103](https://cloud.githubusercontent.com/assets/3046552/12242079/22369fd2-b854-11e5-9026-a4beec7e05d4.png)

**Comment by pixelzoom** [comment]
Done. To summarize:

• For sun.buttons, set default values for pointer area options to zero, did not adjust call sites. We will identify any problems with standard `?showPointerAreas` test.

• For AccordionBox and VerticalAquaRadioButtonGroup, set default values for pointer area options to zero.  At all call sites, added options for the old default values. 

• No other sun components have options related to pointer areas.  Some set pointer areas for subcomponents (e.g. HSlider, OnOffSwitch), and should have options, but addressing that deficiency is not part of this issue.

Randomly assigning to @samreid to review, since he had the most comments above.

**Comment by samreid** [comment]
I created a new issue #223 for tracking subcomponents.  Skimming through the code and testing sun's example, I did not see any other issues, closing.
