### ISSUE TITLE
Carousel: add ability to scroll to a specified page or item

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#209]
Given an item, scroll the carousel to the page that shows that item. This is needed in function-builder, and seems generally useful.

Two changes are required:

(1) make `pageNumberProperty` public
(2) add `scrollToItem: function( item )`

**Comment by pixelzoom** [comment]
(1) is already done:

`this.pageNumberProperty = pageNumberProperty; // @public {Property<number>} page number that is currently visible`

**Comment by pixelzoom** [comment]
Feature added.  I've also added a button to sun_en.html to demonstrate the feature. @jbphet would you mind reviewing, since you reviewed Carousel?

**Comment by pixelzoom** [comment]
I added buttons in the sun demo, to test scrolling to page or item.  Here's what the Components screen looks like:

![screenshot_85](https://cloud.githubusercontent.com/assets/3046552/11512138/f62078c2-9829-11e5-9954-32463ec198a0.png)

**Comment by pixelzoom** [comment]
It would also be useful to have Carousel.scrollToItemIndex, so I'll add that.

**Comment by pixelzoom** [comment]
Done, back to @jbphet.   To summarize: `scrollToItemIndex` and `scrollToItem` were added, along with private fields to support them.

**Comment by pixelzoom** [comment]
I'm starting to use this feature in function-builder, so raising the priority of my review request.

**Comment by pixelzoom** [comment]
@jbphet ping

**Comment by pixelzoom** [comment]
@jbphet can you get to this, or should I assign to someone else to review?

**Comment by jbphet** [comment]
Looks good to me.  I also did some testing, doing things like setting out of range values and invoking ```scrollToItem``` with non-contained nodes as the parameter, and all cases were handled well (hit assertions).  Closing.
