### ISSUE TITLE
rename constructor parameters for toggle buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#211]
Here's the constructor for RoundToggleButton:

```js
  /**
   * @param {Object} valueA one possible value for the toggle
   * @param {Object} valueB the other value for the toggle
   * @param {Property} property axon property that can be either valueA or valueB.
   * @param {Object} [options]
   * @constructor
   */
  function RoundToggleButton( valueA, valueB, property, options )
```

Similar constructors and doc for RectangularToggleButton and ToggleButtonModel.  

The params `valueA` and `valueB` (and their doc) don't tell us how the values relate to the state of the button.  You must either experiment or read to the code to discover that `valueA` is when the button is toggled off, `valueB` is when the button is toggled on. 

Better names for these params would be `valueOff` and `valueOn` respectively.

**Comment by pixelzoom** [comment]
Done, see above commit. Assigned to @jbphet for review.

**Comment by pixelzoom** [comment]
@jbphet can you get to this, or should I assign to someone else to review?

**Comment by jbphet** [comment]
Changes look good, improves usability, and appears to work in the Sun demo.  Closing.
