### ISSUE TITLE
pointerAreas can't be set for Carousel buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#213]
`Carousel` needs a way to set the pointerAreas for its `CarouselButtons`.  

The buttons are currently dilated a little bit (but not enough) by supertype `RectangularPushButton`.
![screenshot_101](https://cloud.githubusercontent.com/assets/3046552/12123270/4b6a9f2c-b39d-11e5-9eb4-e68acf9d8a17.png)

And we shouldn't be relying on the pointerAreas set by `RectangularPushButton`, because it shouldn't be setting defaults like it currently is, see https://github.com/phetsims/sun/issues/207.

**Comment by pixelzoom** [comment]
Also note that the default touchArea starts to encroach on the contents of the Carousel.  This is probably not what we want. In the above examples, we want the touchAreas to extend out from the ends of the Carousel.

**Comment by pixelzoom** [comment]
Feature added.  Pointer areas are dilated such that they do not overlap the Carousel's content.  Here's an example of what this looks like, from the sun demo application:

![screenshot_102](https://cloud.githubusercontent.com/assets/3046552/12184798/b968b83e-b554-11e5-9f82-8f8aa6d137d8.png)

@jbphet would you mind reviewing, since you've reviewed other Carousel features?

**Comment by jbphet** [comment]
Changes look good, closing.
