### ISSUE TITLE
JSdoc of button options is out of sync with implementation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#215]
These options were added to PushButtonModel:

```js
// fire-on-hold feature
fireOnHold: false, // is the fire-on-hold feature enabled?
fireOnHoldDelay: 400, // start to fire continuously after pressing for this long (milliseconds)
fireOnHoldInterval: 100 // fire continuously at this interval (milliseconds)
```

... but were not added to the documentation in various button types that use PushButtonModel (eg, RectangularPushButton, RoundPushButton).  

This demonstrates a problem with trying to enumerate all options in the JSdoc of the top-level button types - they are prone to become out of sync with reality. 

A better approach to documentation might be something like (for example in RectangularPushButton):

```js
All of the options supported by PushButtonModel and RectangularButtonView, plus the following that are specific to this type:
<list of options specific to this type>
```

Labeling for discussion at developer meeting.

**Comment by samreid** [comment]
Yes, that sounds scaleable, more maintainable and easier to implement.

**Comment by jbphet** [comment]
I agree that it would be better have the usage of options documented where the options are declared, and have it be the developers responsibility to look at where the options are passed and figure out which ones are available to the client.  This is a bit of a pain, but far more maintainable.

I will assign this to myself to clean it up in the Sun buttons.

**Comment by pixelzoom** [comment]
I bumped up against this while working on https://github.com/phetsims/sun/issues/204, so decided to take care of its.  @jbphet please review.

**Comment by pixelzoom** [comment]
Note that I also fixed some bad doc, like: `{object} options`, `{options} options`, `{Object} options`.

**Comment by jbphet** [comment]
Looks good, closing.
