### ISSUE TITLE
disabled button continues to fire

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#216]
Originally reported in https://github.com/phetsims/reactants-products-and-leftovers/issues/42, but isolated to sun.

Under certain conditions, a button with `fireOnHold:true` will continue to fire after it has been disabled.  

To reproduce, add this bit of code to `sun.ButtonsView`:

```js
var MIN_VALUE = 0;
var value = 1;
var testButtonListener = function() {
  value--;
  assert && assert( value >= MIN_VALUE, 'value out of range: ' + value );
  console.log( value );
  testButton.enabled = ( value > MIN_VALUE );
};
var testButton = new RectangularPushButton( {
  fireOnHold: true,
  content: new Text( 'test #216' ),
  listener: testButtonListener,
  centerX: this.layoutBounds.centerX,
  bottom: this.layoutBounds.bottom - 20
} );
this.addChild( testButton );
```

Run the sun demo application, and you'll see this button at the bottom-center of the "Buttons" screen:

![screenshot_120](https://cloud.githubusercontent.com/assets/3046552/12212372/f0fd29a6-b626-11e5-848c-a08408dd03a1.png)

Press and hold the button. The button appears to be disabled when `value` <= 0, but `buttonListener` continues to fire, and the assertion fails.

Console output:

```js
0
-1
Assertion failed: value out of range: -1
-2
Assertion failed: value out of range: -2
-3
Assertion failed: value out of range: -3
...
```

Important to note is that the above only fails if we start with value = MIN_VALUE + 1. If value is (for example) MIN_VALUE + 2, there's no problem.

High priority because this affects all clients that use the "fire on hold" feature, and because it's blocking publication of Reactants, Products and Leftovers 1.1.0.

**Comment by pixelzoom** [comment]
As noted in https://github.com/phetsims/reactants-products-and-leftovers/issues/42#issuecomment-169841473:

> When a spinner button is disabled, that results in a call to `PushButtonModel.setEnabled`, which in turn calls `CallbackTimer.stop`, which stops the timer. In the situation that @phet-steele set up, the problem is that the timer hasn't started running yet, so `CallbackTimer.stop is a no-op`.

**Comment by pixelzoom** [comment]
When we start with value = MIN_VALUE + 1, the call to `sun.CallbackTimer.stop` is a no-op, because both delayID and intervalID are null. But (somehow) the timer continues to fire.

When we start with value = MIN_VALUE + 2, the call to `sun.CallbackTimer.stop` stops the timer, because `intervalID` is non-null.

**Comment by pixelzoom** [comment]
Hmmm.... `CallbackTimer.stop` see `intervalID === null`, but `CallbackTimer.fire` shows a valid `intervalID`.

**Comment by pixelzoom** [comment]
The bug is in `CallbackTimer.start`, which looks like this:

```js
54 start: function() {
55      var self = this;
56      if ( !self.isRunning() ) {
57         self.fired = false;
58         self.delayID = Timer.setTimeout( function() {
59         self.delayID = null;
60         self.fire();
61         self.intervalID = Timer.setInterval( function() {
62            self.fire();
63          }, self.interval );
64        }, self.delay );
65       }
66     },
```

On line 60, `fire` is called after `delayID` is cleared and before `intervalID` is set.  If this first `fire` call results in the button being disabled, then the call to `stop` will be a no-op, because `delayID` and `intervalID` are both null. 

The fix is to either (a) swap lines 59 & 60, or (b) move line 60 to after `intervalID` is set.

**Comment by pixelzoom** [comment]
I chose option (b), calling `fire` after `intervalID` is set.

I'll leave this open until it's verified in phetsims/reactants-products-and-leftovers#42.

CallbackTimer is used only in `FireOnHoldInputListener` and `PushButtonModel`, so assigning to @jbphet to review.  High priority since this is blocking publication of RPAL 1.1.0.

**Comment by jbphet** [comment]
Changes look good.  That was a subtle one, eh? Closing.
