### ISSUE TITLE
multiple problems in the button type hierarchy related to buttonModel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#217]
There seems to be some confusion/inconsistency in the sun button hierarchy about where the buttonModel is managed.  Here's an example for rectangular buttons:

RectangularPushButton constructor:

``` js
66 this.buttonModel = new PushButtonModel( options ); // @public, listen only
67 RectangularButtonView.call( this, this.buttonModel, ... );
```

RectangularButtonView constructor:

``` js
47 this.buttonModel = buttonModel; // @protected
```

Problems:

(1) Assigning to `this.buttonModel` twice (in the supertype and subtype).  The assignment in `RectangularPushButton` is unnecessary, `RectangularPushButton` requires no access to `this.buttonModel` (see 2 & 3) and the supertype constructor call should be:

``` js
67 RectangularButtonView.call( this, new PushButtonModel( options ), 
     new PushButtonInteractionStateProperty( this.buttonModel ), options );
```

(2) Prototype functions `addListener` and `removeListener` should be moved from `RectangularPushButton` to `RectangularButtonView`, so they can be used by other `RectangularButtonView` subtypes.  Currently the other subtypes lack these APIs.  See for example `RectangularToggleButton`, which extends `RectangularButtonView` but has no way to add/remove listeners.

(3) Disposal of `this.buttonModel` should be handled in `RectangularButtonView.dispose`, not `RectangularPushButton.dispose`, so that all subtypes of `RectangularButtonView` handle disposal of the buttonModel uniformly.

(4) Visibility of `this.buttonModel` is marked as `@protected` in `RectangularButtonView`, meaning that it should be accessible only to subtypes, but `RectangularPushButton` has no need to know about it. `RectangularPushButton` currently marks visibility as `@public`, for some reason expanding its visibility. What is the correct visibility? It should be annotated in `RectangularButtonView`.

(5) `RoundPushButton` and `RoundButtonView` suffer from these same problems.

(6) `RoundMomentaryButton` suffers from the same problem.

**Comment by pixelzoom** [comment]
@jbphet let's discuss how to straighten this out.

**Comment by pixelzoom** [comment]
Re (2)... Perhaps there was a decision made that only push buttons can have listeners?

**Comment by pixelzoom** [comment]
Labeling for developer meeting, we should try to clean up these problems in sun buttons.

**Comment by samreid** [comment]
@ariel-phet says @jbphet will have some time freed up soon after Gene Expression and Expression Exchange is published.  Perhaps @jbphet can work on this while working on sonification and common code things.  Perhaps in a month or so?

**Comment by jbphet** [comment]
@pixelzoom - This issue has been assigned to me for quite a while, but is unfortunately never getting any attention.  I know you spent a fair amount of time on sun buttons recently when you were adding support for `enabledProperty`.  What's your opinion on this now - is there still some work that needs to be done on the button type hierarchy?  If so, let's label this issue for developer meeting and assign it to @ariel-phet so that we can get it prioritized and taken care of, or decide not to.

**Comment by pixelzoom** [comment]
I review the problems reported in https://github.com/phetsims/sun/issues/217#issue-125714682.  All of them were addressed as the result of the recent work on sun buttons that factored out ButtonNode base class.

Closing.
