### ISSUE TITLE
dependency on joist in sun

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#219]
While working on https://github.com/phetsims/sun/issues/216, I noticed that the "fire on hold" feature that was added to sun buttons introduced a dependency on joist.  `sun.PushButtonModel` uses `sun.CallbackTimer`, which uses `joist.Timer`. The dependency was added in @3d9fe824652fffc958ad8993632c749b0b183582 for work on https://github.com/phetsims/scenery-phet/issues/71.  `sun` is supposed to be usable independent of PhET frameworks, so this dependency is undesirable and needs to be expunged.

@jbphet thoughts on how to proceed? Perhaps we could factor out this functionality as a listener that lives in `scenery-phet` and can be added to a `sun` button.

**Comment by samreid** [comment]
Brainstorming another option: we could move joist.Timer to sun or one of its true dependencies.

Also, I noticed sun/CallbackTimer.js also depends on joist.Timer.

**Comment by jbphet** [comment]
Good catch @pixelzoom.  IMO, timers are pretty basic functionality and we should definitely have one available for our UI components.  I like the idea of moving Timer from Joist to something more general.  Moving it to Sun doesn't seem quite right.  Phetcommon?

**Comment by pixelzoom** [comment]
> Also, I noticed sun/CallbackTimer.js also depends on joist.Timer.

Yes, that's what I noted in the first comment.

**Comment by pixelzoom** [comment]
@jbphet said:
>  I like the idea of moving Timer from Joist to something more general. Moving it to Sun doesn't seem quite right. Phetcommon?

If the longterm intention is to deprecate phetcommon (see https://github.com/phetsims/phetcommon/issues/24), then phet-core might be a better place for it.

**Comment by pixelzoom** [comment]
Probably also better to move to phet-core since there's precedent for having that repo as a dependency  in other repos that are useful outside of PhET (eg, in scenery, kit, dot).  That dependency is necessary to access PHET_CORE.inheit.

**Comment by jbphet** [comment]
Moving Timer.js to phet-core sounds good to me.  Shall I just do it, or do we want to run it by the other devs in the next dev meeting?

**Comment by samreid** [comment]
Phet core sounds good.

**Comment by pixelzoom** [comment]
Just do it.™

**Comment by jbphet** [comment]
My plan would be to still have the timer clocked in Joist as is currently done in Sim.js, but to have the timer itself reside in phet-core.

**Comment by pixelzoom** [comment]
That sounds good. We don't need any change in functionality, just a change in where joist.Timer lives.

**Comment by jbphet** [comment]
Did the change.  I'm leaving it labeled for dev meeting to let folks know about it and warn them to watch for any weirdness.

**Comment by jbphet** [comment]
Discussed in dev meeting to create awareness, closing.

**Comment by pixelzoom** [comment]
Reopening. Namespace wasn't adjusted when Timer was moved to phet-core.

**Comment by pixelzoom** [comment]
Namespace fixed. Assigned to @jbphet to review.

**Comment by jbphet** [comment]
Good catch, change looks good, closing.
