### ISSUE TITLE
Carousel: add ability to disable scrolling animation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#222]
In function-builder, I need to programmatically scroll the carousel in order to determine the location of each item in the carousel in the global coordinate frame.  Because of the animation that takes place when you call `Carousel.scrollToItem` or `scrollToItemIndex`, I was getting the incorrect result.  So this is one situation in which disabling animation is useful, and it seems like a generally useful feature.

**Comment by pixelzoom** [comment]
Feature implemented.  Assigning to @jonathanolson to review, since we discussed this briefly today. Rather than adding an `animationEnabled` flag to `scrollToItem` and `scrollToItem`, I added option `animationEnabled` and setter/getter for `animationEnabled` field.  This allows you to enable/disable animation not only for the scroll functions, but for the Carousel in general.

**Comment by jonathanolson** [comment]
Looks good, although one question (unlikely to come up in practice):

I saw ```scrollTween && scrollTween.stop()``` was only run if animation was enabled. If the client:
1. Sets animationEnabled to true
2. Calls scrollToItem to kick off animation (to item A)
and before the animation completes:
3. Sets animationEnabled to false
4. Calls scrollToItem to something on another page (item B)

Presumably the last scrollToItem wouldn't interrupt the tween, so would the tween cause the scroll to end up at item A while the index is at item B?

**Comment by pixelzoom** [comment]
Good point.  Should probably call `scrollTween && scrollTween.stop()` regardless of whether `animationEnabled`.

**Comment by pixelzoom** [comment]
Done. @jonathanolson anything else?

**Comment by jonathanolson** [comment]
Nope, thanks!

**Comment by pixelzoom** [comment]
Reopening. There's a bug in this feature, it only works for horizontal carousels.

**Comment by pixelzoom** [comment]
Fixed and closing.

**Comment by pixelzoom** [comment]
Reopening.  

To reset a carousel without scrolling, the client has to currently do something like this:

```js
var saveAnimationEnabled = myCarousel.animationEnabled;
myCarousel.animationEnabled = false;
myCarousel.reset();
myCarousel.animationEnabled = saveAnimationEnabled;
```

In Function Builder, I have 3 carousels to reset, so this gets quite ugly. What I'd really like to do is tell `reset` to disable animation, and let it handle saving and restoring the animation state, e.g.:

```js
myCarousel.reset( { animationEnabled: false } );
```

**Comment by pixelzoom** [comment]
Done, closing. If anyone wants to review, go for it.

**Comment by veillette** [comment]
I assigned this commit to the wrong ticket
