### ISSUE TITLE
New HSlider features: snap to value and disable range

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/sun#224]
From https://github.com/phetsims/forces-and-motion-basics/issues/104, it was decided that the FAMB slider should be updated to match the look and feel of sun's HSlider

@samreid said:
> @ariel-phet do you want to address this as part of the S2015R? The implementation will likely remain independent but we could spend 2-4 hours making this slider look a bit more like the standard sun one.

> Unifying the implementation would take even longer and would probably increase the complexity of the sun one. Not sure how important that is.

From July 30 developer meeting:

>AP: Simplifies tandem & accessibility to unify as much as possible.
SR: Sounds good, let’s go for it. We can also try to implement this in a way that doesn’t complicate HSlider too much.

@samreid said:
> Unassigning this for now. I'll reassign it when we start reworking forces and motion basics for the Summer 2015 Redeploy.

Now that FAMB is up for redeploy, it is time to work on this issue.  The features in the FAMB slider that are not in sun/Slider include:

- zero on release
- disable half of the slider to restrict values

**Comment by ariel-phet** [comment]
@jessegreenberg you might want to talk to @pixelzoom 

The slider for function builder is going to need to have the ability to disable portions of the slider to restrict values, so we should make this disabling a portion more general, not just disabling half the slider.

**Comment by pixelzoom** [comment]
Thoughts...

(1) I'm at least 1 week out from working on this for function-builder, and I won't have the luxury of implementing a general solution.  Generalization will need to occur much later.  So my advise to @jessegreenberg is to proceed with what you need for FAMB, after familiarizing yourself with the requirements for function-builder. 

(2) HSlider is already rather complicated. Rather than adding this feature directly to HSlider, it would be preferably to investigate a solution that involves extending or decorating HSlider. Or perhaps creating a more complicated "SliderTrack" abstraction.

**Comment by jessegreenberg** [comment]
Thanks for the recommendations @pixelzoom.  I like the idea of a 'SliderTrack' abstraction, I think I will try that solution first.

Sliders often do not include 0 in their range.  The desired features are more accurately described by 'snap to value on release' and 'disable range contained by slider'.  I will update issue name to reflect this.

**Comment by jessegreenberg** [comment]
I suppose it would be more helpful to **enable** a sub range of the slider.  This way, a sub range in the middle of the slider could be enabled, while the ends around the min and max of the slider range could be disabled.

**Comment by samreid** [comment]
> I suppose it would be more helpful to *enable* a sub range of the slider. 

Yes, this seems like the more natural way to frame it, good idea.

**Comment by jessegreenberg** [comment]
These features were added in the commits above.  Added check boxes to sun/demo/ComponentsView to test and play with these feature.  @samreid would you be able to review these changes?

**Comment by samreid** [comment]
Sure, I'll take a look.

**Comment by samreid** [comment]
It looks like these options are duplicated between HSlider and SliderTrack:

```js 
      enabledProperty: new Property( true ),
      snapValue: null,
      startDrag: function() {}, // called when a drag sequence starts
      endDrag: function() {}, // called when a drag sequence ends
      constrainValue: function( value ) { return value; }, // called before valueProperty is set
```

Should some of these be de-duplicated?

**Comment by samreid** [comment]
Also, snapToValue is duplicated in both HSlider and SliderTrack:

```js
    var snapToValue = function( value ) {
      if( value <= range.max && value >= range.min ) {
        valueProperty.set( value );
      }
      else {
        throw new Error( 'snapValue must be within slider range' );
      }
    }; 
```

Can it be declared once and referenced twice?

**Comment by samreid** [comment]
What do you think about renaming SliderTrack.js to HSliderTrack.js so it will be more clear that they belong together, and they alphabetically become colocated?

**Comment by samreid** [comment]
Can you document the new option `snapValue: null`?  It is not clear what it is for.  It seems from context that it is a number.  Ah, it is for sliders that jump back to a single value (not snapping to ticks).

**Comment by jessegreenberg** [comment]
Good points @samreid.  I wasn't sure if SliderTrack would be specific to HSlider, or available for use with other components. Options were duplicated to make sure that those options were defined if used outside of HSlider.  But now I cannot think of a case where SliderTrack would be useful outside of HSlider.

+1 for changing to HSliderTrack if this abstraction will only ever be used with HSlider.

**Comment by jessegreenberg** [comment]
Thanks for the review comments @samreid.  Commits above make the recommended changes.  Please let me know if there are other issues I should resolve here.

**Comment by jessegreenberg** [comment]
HSliderTrack was getting Slider's tandem with pass through options.  In the commit above, SliderTrack receives a cloned set of options so that its tandem can be unique.

**Comment by jessegreenberg** [comment]
Two more things after use in https://github.com/phetsims/forces-and-motion-basics/issues/166

1) It should be possible to set the snap value
2) After a refactor, the disabled track has a 'pointer' cursor

**Comment by jessegreenberg** [comment]
Done in commits above.

**Comment by samreid** [comment]
Currently the HSlider and HSliderTrack both have a _snapValue, and getters and setters for it, is this intentional?  Should the HSlider snapValue and HSliderTrack snapValue be able to vary independently?

Range parameter seems unused in HSliderTrack.

**Comment by jessegreenberg** [comment]
It was intentional, though the two values should not vary independently.  It was a solution to the problem that HSliderTrack needs to track a changing 'snapValue' for its unique drag handler.  But it seems that the getters and setters are not necessary.  Removing these showed that the enabledRangeObserver could be handled just in HSlider.  @samreid would you mind reviewing these changes?

**Comment by samreid** [comment]
Sure, I'll take a look.  Marking as high-priority so it will appear on my todo list for the near future.

**Comment by samreid** [comment]
https://github.com/phetsims/sun/commit/3c696e66010e9d43f127e57b0367e64d3cdf61c6 seems good to me.  Anything else to do here @jessegreenberg ?

**Comment by jessegreenberg** [comment]
Not that I am aware of, thanks for the review comments @samreid!  Closing.

**Comment by pixelzoom** [comment]
@jessegreenberg and @samreid...

I'm reopening this. Problems noted while working on https://github.com/phetsims/sun/issues/245.

(1) HSliderTrack has no default values for some of its options.  Specifically, these options are referenced in the constructor, but are missing from the options hash: `enabledProperty`, `startDrag`, `endDrag`, `snapValue`, `constrainValue`.  In general, any option that is references in the implementation should be present (and documented) in the options hash that appears in the `_.extend` call.  And this is something that reviewers should look for.

(2) Many of the options are named with a 'track' prefix: `trackSize`, `trackFillEnabled`, `trackFillDisabled`, `trackStroke`, `trackLineWidth`.  That prefix was important when the track was created inside of HSlider.  But the prefix is inappropriate now that HSliderTrack has been factored out, and is inconsistent with other options.  Since HSlider currently (and incorrectly) passed all of its options to HSliderTrack, this will be a bit difficult to address until https://github.com/phetsims/sun/issues/245 is resolved.

**Comment by pixelzoom** [comment]
I've addressed (1) in the above commit, by providing missing default values and documentation for options. @jessegreenberg please review.

(2) will need to be addressed after #245.

**Comment by pixelzoom** [comment]
Moved issue (2) to https://github.com/phetsims/sun/issues/247.  

@jessegreenberg feel free to close this after reviewing the changes noted in https://github.com/phetsims/sun/issues/224#issuecomment-241123431.

**Comment by jessegreenberg** [comment]
These options were discussed as part of the review.  The only options in HSliderTrack were those that were not otherwise needed by HSlider.  We agreed that having them in both files created a duplication of options and initial values.  The options missing from ```_.extend``` in HSliderTrack had initial values defined in HSlider.

**Comment by jessegreenberg** [comment]
After thinking about this a bit more, I agree that this is most important:
> In general, any option that is references in the implementation should be present (and documented) in the options hash that appears in the _.extend call.

```_.extend``` serves as important documentation.  Changes in https://github.com/phetsims/sun/commit/a862631e2a5c913b4fe6ba22e29beb396541b467 look good to me.  Closing.
