### ISSUE TITLE
Disabled components should not be pickable

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#227]
While investigating phetsims/phet-io#282 I saw the following components that had setEnabled or set enabled without obvious setting of pickable:false:

- [ ] RoundButtonView
- [ ] RectangularButtonView
- [ ] NodesPushButton
- [ ] HSlider, see #226 
- [ ] ABSwitch

**Comment by pixelzoom** [comment]
According to comment https://github.com/phetsims/phet-info/issues/24#issuecomment-231123503, this is not true, disabled components must be pickable to support a11y.

> ... for accessibility we will want enabled:false elements to still have pickable:true. If an element is disabled, we will still want it to receive input events so that it can be found with whatever navigation strategy is used.

**Comment by samreid** [comment]
Maybe we need to iterate through all components and make sure they remain pickable: true while enabled: false?

**Comment by samreid** [comment]
We reopened https://github.com/phetsims/phet-io/issues/282 and will send messages even from disabled objects.  Now we are discussing whether to close this issue and how to become consistent about enabled and its impact on pickability.

**Comment by jessegreenberg** [comment]
We decided that components that are disabled should be pickable for discoverability and accessibility.    We will create new issues in common repositories to make sure that disabled elements are pickable, as suggested by @samreid in https://github.com/phetsims/sun/issues/227#issuecomment-231160857.  Closing this issue, @jessegreenberg will create new issues.
