### ISSUE TITLE
ComboBox puts the list in the wrong z-order

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#229]
ComboBox adds the popup "list" eagerly (in its constructor), so if the ComboBox is constructed too soon, the list will be behind other objects.

Workaround 1: create ComboBox last
Workaround 2: give ComboBox a listParent that is guaranteed to be in front

But perhaps we should rewrite combo box to add the list to the list parent dynamically, when the list is shown?

**Comment by samreid** [comment]
I'm not too excited about spending a lot of time on this now, but I want to raise for discussion at developer meeting to make sure I understand the problem and its implications.

**Comment by pixelzoom** [comment]
I don't understand how Workaround 1 (create ComboBox last) has any bearing on this issue. The position of a ComboBox in the rendering order has no bearing on where it's popup list appears.

The current approach is Workaround 2 (give ComboBox a listParent that is guaranteed to be in front).   With this approach, adding on-demand vs eagerly would insure that multiple combo boxes could share the same listParent, and the correct (most recent) list would be on top. (Whether that's important for multi-touch is up for debate.)  It would also make it possible to decorate listParent after ComboBox instantiation - currently children added to listParent after  ComboBox instantiation will appear in front of the popup list.

If we decided to do something different, it should be applicable to other UI components that have popups (eg, menus).  Unless we add general support for something like Java's JRootPane, I don't see a way to guarantee that the current popup is in front.

**Comment by pixelzoom** [comment]
With Workaround 2 (give ComboBox a listParent that is guaranteed to be in front), adding on-demand vs eagerly would insure that multiple combo boxes could share the same listParent, and the correct (most recent) list would be on top. (Whether that's important for multi-touch is up for debate.)  It would also make it possible to decorate listParent after ComboBox instantiation - currently children added to listParent after  ComboBox instantiation will appear in front of the popup list.

If we decided to do something different, it should be applicable to other UI components that have popups (eg, menus).  Unless we add general support for something like Java's JRootPane, I don't see a way to guarantee that the current popup is in front.

**Comment by jonathanolson** [comment]
> Imo, adding to listParent on-demand instead of eagerly would be sufficient to address this issue.

Sounds fine to me.

**Comment by samreid** [comment]
Meeting consensus: we decided to try making addChild dynamic and see if the performance is good enough on iPad.

**Comment by samreid** [comment]
Calling `moveToFront` when the list is shown also seems like a nice solution.

**Comment by samreid** [comment]
Committed above and tested in Circuit Construction Kit: Basics.

Before:
![image](https://cloud.githubusercontent.com/assets/679486/14695749/75aeb442-0732-11e6-90a3-47d4198fe7dc.png)

After:
![image](https://cloud.githubusercontent.com/assets/679486/14695755/8232e8e6-0732-11e6-9403-9f02f5f76fef.png)

It would be great if @jonathanolson or @pixelzoom could sign off on this strategy.  I went with moveToFront because it was simpler than dynamically adding, and seemed to have the same effect.

**Comment by pixelzoom** [comment]
The `moveToFront` approach looks reasonable to me. But worth noting that it won't address occlusion issues caused by something in front of a ComboBox's `listParent`.

**Comment by samreid** [comment]
> The `moveToFront` approach looks reasonable to me. But worth noting that it won't address occlusion issues caused by something in front of a ComboBox's `listParent`.

Neither would adding it to `listParent` lazily, right?

Please close this issue if there is nothing else to do or discuss here.

**Comment by pixelzoom** [comment]
> Neither would adding it to listParent lazily, right?

Correct.  

But we had discussed general solutions, and this isn't general.  Having popups in front is a general need that's exclusive to combo box -- it's needed by other things, like menus and dialogs.  Imo we need an approach that is shared by all popups, including combo box.  

I don't think you need to address this here. But it is kicking the can down the road.

**Comment by samreid** [comment]
OK I created another sun issue for "Add support for popups to be "in front" #238", and will close this one.
