### ISSUE TITLE
enabled/disabled check box support for VerticalCheckBoxGroup

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/sun#231]
If a check box is in a group and needs to be disabled, a custom panel is required so that the check box can be referenced to set enabled/disabled.  It would be convenient if VerticalCheckBoxGroup could support enabling check boxes.

One option for the solution:
  1.  CheckBox has an optional ```checkBoxEnabledProperty```
  2.  checkBox.enabled is linked to optional ```checkBoxEnabledProperty```
  3. VerticalCheckBoxGroup ```items``` can have an optional ```checkBoxEnabledProperty``` which gets passed to the individual CheckBox.

This way, a property to enable the check box could be controlled outside of VerticalCheckBoxGroup.

**Comment by pixelzoom** [comment]
Not recommended to use VerticalCheckBoxGroup, I'd like to see them go away. See https://github.com/phetsims/sun/issues/30.

**Comment by pixelzoom** [comment]
Not recommended to use VerticalCheckBoxGroup, I'd like to see them go away. See #30.

In this type of situation, you're better off creating your own CheckBox instances, and handling layout with your own VBox.

**Comment by jessegreenberg** [comment]
I see, I didn't realize that.  Thanks for pointing out that issue.  I will proceed with custom layout for check box groups.  Closing, removing developer meeting label.
