### ISSUE TITLE
Add an option to set the maxTextWidth for TextPushButton

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#232]
Discovered in https://github.com/phetsims/fraction-matcher/issues/90#issuecomment-194828638, TextPushButton can have its maxWidth set, but not its maxTextWidth.  This means that the button "chrome" (shadows, highlights, bevel, etc) would be scaled instead of just the text content of the button, which could look odd or inconsistent, particularly if buttons are shown next to each other (with different scalings).

Checking to see if there is a precedent for this, I see GameFeedbackDialog in Balancing Chemical Equations uses maxWidth on the TextPushButton.  Similarly, this is done in Build an Atom and Neuron.  I'm also seeing many cases where TextPushButton is instantiated without a maxWidth.

**Comment by samreid** [comment]
Fixed above and tested with and without passing maxTextWidth (since I wasn't sure how maxWidth=null would be handled), it seemed correct in both cases.  @jonathanolson @pixelzoom @jbphet or @jessegreenberg can you please review this issue?  I'll mark for developer meeting to make sure someone volunteers :)  If you volunteer before then, please self-assign and remove the "developer meeting" label.

**Comment by pixelzoom** [comment]
I inspected the commit, looks correct to me.

**Comment by samreid** [comment]
Thanks @pixelzoom, closing.
