### ISSUE TITLE
AccordionBox: simplify title bar

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#233]
When the AccordionBox is expanded with option `showTitleWhenExpanded: true`, the top corners of the title bar must have corners that match the box, while the bottom corners of the title bar must be square.  

Here's an example in reactants-products-and-leftovers:

![screenshot_146](https://cloud.githubusercontent.com/assets/3046552/14027081/90e87ebe-f1bb-11e5-964b-9275b039b6d7.png)

Here's the related code in AccordionBox (line 125). Ugly special-case handling and complicated Shape computation.

```js
    if ( options.cornerRadius === 0 || !options.titleBarFill ) {
      // no rounded corners or no title bar visible, so use a Rectangle
      expandedTitleBar = new Rectangle( 0, 0, boxWidth, collapsedBoxHeight, expandedTitleBarOptions );
    }
    else {
      // rounded top corners, square bottom corners (start at bottom left and move clockwise)
      expandedTitleBar = new Path( new Shape()
          .moveTo( 0, collapsedBoxHeight )
          .lineTo( 0, options.cornerRadius )
          .arc( options.cornerRadius, options.cornerRadius, options.cornerRadius, Math.PI, 1.5 * Math.PI )
          .lineTo( boxWidth - options.cornerRadius, 0 )
          .arc( boxWidth - options.cornerRadius, options.cornerRadius, options.cornerRadius, 1.5 * Math.PI, 0 )
          .lineTo( boxWidth, collapsedBoxHeight )
          .close(),
        expandedTitleBarOptions );
    }
```

This could be simplified greatly by using (the relatively new) `Shape.roundedRectangleWithRadii`, which draws a rectangle with specific rounded corners. Something like (untested):

```js
var expandedTitleBarShape = Shape.roundedRectangleWithRadii( 0,  0, boxWidth, collapsedBoxHeight, {
  topLeft: options.cornerRadius,
  topRight: options.cornerRadius     
} );
expandedTitleBar = new Path( expandedTitleBarShape, expandedTitleBarOptions );
```

**Comment by pixelzoom** [comment]
Simplified as described above.

Tested in reactants-products-and-left-overs (`showTitleWhenExpanded: true`) and area-builder (`showTitleWhenExpanded: false`).  

Randomly assigning to @jbphet to review.

**Comment by jbphet** [comment]
Nice simplification!  Changes look good, and I did a quick test on three sims that I know of that use this component - Area Builder, Build and Atom, and Isotopes and Atomic Mass - and the accordion box appeared to work fine in all of them.  Closing.
