### ISSUE TITLE
specifying T type for a ComboBox is inappropriate

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#242]
Related to code review https://github.com/phetsims/beers-law-lab/issues/181.

In beers-law-lab.SoluteComboBox, I noticed this:

``` js
ComboBox.call( this, items, selectedSoluteProperty, soluteListParent, {
      labelNode: labelNode,
      listPosition: 'below',
      itemYMargin: 12,
      itemHighlightFill: 'rgb(218,255,255)',
      tandem: tandem,
      type: TSolute
    } );
```

In general, ComboBox's `items` parameter is an array of objects, and there's no requirement that the array (or the values assigned to it `property` parameter) must be homogenous.   So this bit in ComboBox is totally inappropriate:

``` js
65 type: null // the phet-io type function for the combo box element type, such as String
```

**Comment by samreid** [comment]
Putting to high priority so it's on my TODO list.  I can try taking out the type parameter from TComboBox and see what happens.

**Comment by samreid** [comment]
The `valueType` is used to convert the value to a state object which can appear in the data stream and is therefore is quite useful.

Even though our combo box supports heterogeneous types, we may want to constrain ourselves to use homogeneous types to reduce complexity and improve maintainability.  For instance, in Java, you can instantiate an ArrayList without type arguments (good for any type) or an ArrayList<SomeType>, which is more specific and often better.

**Comment by samreid** [comment]
Reassigned to @pixelzoom for discussion.

**Comment by pixelzoom** [comment]
I guess I'm OK with requiring combo box items to be homogeneous. But if that's going to be a requirement, then it should be documented/verified/enforced in ComboBox.

**Comment by samreid** [comment]
This seems like a good spot for me to collaborate with @andrewadare or @pixelzoom on.

**Comment by zepumph** [comment]
Discussed in 10/31 phet-io meeting with @andrewadare and @samreid. Happy Halloween!

In axon with property, we use the option phetioValueType to say what the property T type is.
We looked into the pattern used for RadioButtonGroup also, because they should use the same conventions.

@samreid's argument for homogenious types within these groups is less repeat code, and easier to maintain. Heterogenious groups might have more functionality, but will have much more complicated code, because a listener will have to check type before continuing.

**Comment by samreid** [comment]
As we saw in #773, the phetioValueType is redundant and we should adopt the phetioValueType of the ComboBox Property instance.

**Comment by andrewadare** [comment]
Let's assign to both @samreid  and myself, whoever gets to it first can take it.

**Comment by pixelzoom** [comment]
Let's also make sure that we document/verify/enforce that the type of items in a ComboBox is homogeneous.

**Comment by samreid** [comment]
I'm going to take a look at this now.

**Comment by samreid** [comment]
> Let's also make sure that we document/verify/enforce that the type of items in a ComboBox is homogeneous.

If the type is provided by AXON/Property but only for phet-io instrumented types, it will be difficult to consistently verify that values are of the right type.  For phet-io instrumented types, this type verification should be provide by Property (though I don't know how this would be implemented).  If we had something like that in Property, then we could validate all of the ComboBox values during startup.

**Comment by samreid** [comment]
I removed the ComboBox parameter above, and am using the phetioValueType from the Property.  @andrewadare can you please review?

**Comment by andrewadare** [comment]
Soon, it would be good to discuss the pattern where we assign `tandem: null` in the ComboBox.js options object, then make subsequent checks for null. But that's a separate (wider) issue.

For phet-io/#773, we added an [assertion](https://github.com/phetsims/sun/blob/fa1a19058d43cb0fc10ee525acfb7f3c4568e66a/js/buttons/RadioButtonGroup.js#L150-L151) that enforces homogeneity. I didn't see anything similar in ComboBox - should there be one?

**Comment by pixelzoom** [comment]
It seems like the homogeneity check should be independent of PhET-iO. Could we iterate over ComboBox's `items` arg and verify that the `value` property of each item has the same type?

**Comment by samreid** [comment]
> Could we iterate over ComboBox's `items` arg and verify that the `value` property of each item has the same type?

Not necessarily, some of the types may be subtypes:
```js
new ComboBox([cow,horse,dog,fish,antelope])
```

Would error out with `fish not instance of Mammal`.

**Comment by pixelzoom** [comment]
How about at least documenting that `items` should be homogenous?

**Comment by samreid** [comment]
Like this? https://github.com/phetsims/sun/commit/76bbb73265c19bba930a9ab2cf464ba566aec14e

**Comment by pixelzoom** [comment]
👍

**Comment by pixelzoom** [comment]
Seems like @andrewadare still had a question in https://github.com/phetsims/sun/issues/242#issuecomment-258874590.  Back to @andrewadare and @samreid to resolve.

**Comment by andrewadare** [comment]
I don't have any further comments (we have other issues to deal with the null Tandem patterns in our code, I was just reminded of that while reviewing this.)
