### ISSUE TITLE
NumberSpinner: backgroundMinWidth option is misleading

### ISSUE THREAD

**Issue by andrea-phet** [phetsims/sun#243]
Currently, the `backgroundMinWidth` option is misleading because it doesn't exactly set the width of the background node - it sets the width minus the margins:
```js
var backgroundWidth = Math.max( maxWidth, options.backgroundMinWidth ) + ( 2 * options.xMargin );
```
I think that line should be 
```js
var backgroundWidth = Math.max( maxWidth + 2 * options.xMargin, options.backgroundMinWidth );
```
so `backgroundMinWidth` actually sets the width of that white background rectangle.

Related to work @pixelzoom and I did for #85

**Comment by andrea-phet** [comment]
Assigning to @pixelzoom for review

**Comment by pixelzoom** [comment]
👍 Closing.
