### ISSUE TITLE
HSlider passes all of its options to sub-components

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#245]
HSlider line 111:

```js
    var thumbNode = options.thumbNode || new ThumbNode( this.enabledProperty, options );
    thumbNode.centerY = thisSlider.track.centerY;
```

This passes all of the HSlider options to ThumbNode, including layout (x,y,left,right,...) and transforms (scale,...)   This is currently working only because `centerY` is set on the next line, and centerX is set to match `valueProperty`.

**Comment by pixelzoom** [comment]
Similar problem for the slider track, line 118:

```js
    // make a copy of the options to pass to the slider track so that the track can have a unique tandem
    var trackOptions = _.clone( options );
    trackOptions.tandem = trackOptions.tandem ? trackOptions.tandem.createTandem( 'sliderTrack' ) : null;

    // @private track
    thisSlider.track = new HSliderTrack( valueProperty, thisSlider.valueToPosition, snapToValue, trackOptions );
    thisSlider.track.centerX = thisSlider.valueToPosition( ( range.max + range.min ) / 2 );
```

**Comment by pixelzoom** [comment]
In the above commit, I propagated only the options that are relevant to HSliderTrack and HSliderThumb.  This approach is admittedly "brute force", but we're currently lacking a general/elegant way of propagating options to subcomponents (see discussion in https://github.com/phetsims/scenery-phet/issues/255). 

@jessegreenberg please review. I tested in sun demo and several sims, but please check a few sims.

**Comment by jessegreenberg** [comment]
Thanks @pixelzoom, looks good to me.  I tested molecules-and-light, hookes-law, ohm's-law, and forces-and-motion-basics.
