### ISSUE TITLE
HSlider: touchArea dilation is ignored for custom thumbs

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#246]
Options `thumbTouchAreaXDilation` and `thumbTouchAreaYDilation` are currently being ignored if a custom thumb is provided.  The bug is in this block of code, HSlider line 132:

```js
    // thumb touch area
    if ( !options.thumbNode ) {
      if ( !options.thumbTouchAreaXDilation ) {
        options.thumbTouchAreaXDilation = 0.5 * thumbNode.width;
      }
      if ( !options.thumbTouchAreaYDilation ) {
        options.thumbTouchAreaYDilation = 0.25 * thumbNode.height;
      }
      // touch area dilated along X and Y directions
      thumbNode.touchArea = thumbNode.bounds.dilatedXY( options.thumbTouchAreaXDilation, options.thumbTouchAreaYDilation );
    }
```

Moving the touchArea assignment outside of the if statement fixes the problem. I.e.:

```js
    // thumb touch area
    if ( !options.thumbNode ) {
      if ( !options.thumbTouchAreaXDilation ) {
        options.thumbTouchAreaXDilation = 0.5 * thumbNode.width;
      }
      if ( !options.thumbTouchAreaYDilation ) {
        options.thumbTouchAreaYDilation = 0.25 * thumbNode.height;
      }
    }

    // touch area dilated along X and Y directions
    if ( options.thumbTouchAreaXDilation || options.thumbTouchAreaYDilation ) {
      thumbNode.touchArea = thumbNode.bounds.dilatedXY( options.thumbTouchAreaXDilation, options.thumbTouchAreaYDilation );
    }
```

Note that this change may affect sims that are depending on the buggy behavior.

**Comment by pixelzoom** [comment]
I searched for "thumbNode:" to locate sims that use a custom thumb:

forces-and-motion-basics  (does not set touchArea)
molecules-and-light (does set touchArea)

**Comment by pixelzoom** [comment]
On second thought... Let's make the client responsible for dilating the custom thumb.  I'll update the documentation of `thumbTouchAreaXDilation` and `thumbTouchAreaYDilation` to indicate that.

**Comment by pixelzoom** [comment]
There's another problem here as well. It's impossible to turn off touchArea dilation.  The default options are:

```js
      thumbTouchAreaXDilation: null, // {number|null} horizontal dilation of thumb touchArea
      thumbTouchAreaYDilation: null, // {number|null} vertical dilation of thumb touchArea
```

And the test is:

```
      if ( !options.thumbTouchAreaXDilation ) {
        options.thumbTouchAreaXDilation = 0.5 * thumbNode.width;
      }
      if ( !options.thumbTouchAreaYDilation ) {
        options.thumbTouchAreaYDilation = 0.25 * thumbNode.height;
      }
``` 

The above bit of code is probably there so that we don't change the behavior of sims that are rely on a default touchArea.  Sims that don't want touchArea expansion would hopefully be able to provide options like this:

```js
var mySlider = new HSlider(... {
  thumbTouchAreaXDilation: 0,
  thumbTouchAreaYDilation: 0
} );
```

But that's still going to result in the default touchArea being set.

**Comment by pixelzoom** [comment]
Two changes in the above commit:

(1) Documented the fact that the touchArea dilation options apply only to the default thumb.

(2) Explicitly test for `null` (e.g. `if ( options.thumbTouchAreaXDilation === null )` ) when deciding whether to compute default touchArea dilation. 

Randomly selected @jessegreenberg to review.

**Comment by jessegreenberg** [comment]
Looks good to me, thanks for fixing this.  I agree that the client should be responsible for setting the dilation on custom thumb touch areas.  Closing.
