### ISSUE TITLE
HSliderTrack and HSliderThumb use unnecessary prefix on option names

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#247]
This issue was factored out of https://github.com/phetsims/sun/issues/224#issuecomment-241122710.

In HSliderTrack, many of the options are named with a 'track' prefix: `trackSize`, `trackFillEnabled`, `trackFillDisabled`, `trackStroke`, `trackLineWidth`.  That prefix was important when the track was created inside of HSlider.  But the prefix is inappropriate now that HSliderTrack has been factored out, and is inconsistent with other options. 

HSliderThumb has the same problem.

Since HSlider currently (and incorrectly) passed all of its options to HSliderTrack and HSliderThumb, this will be a bit difficult to address until #245 is resolved.

**Comment by pixelzoom** [comment]
Resolved this issue and #245 in the above commits.  @jessegreenberg please review.

**Comment by jessegreenberg** [comment]
Commits look good to me, and everything works well with #245.  Thanks for adding the documentation in https://github.com/phetsims/sun/commit/462d396b84ffb0c9ba0c6af5468daa200f26f4fd.  Closing.
