### ISSUE TITLE
no tandem for HSlider thumb

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#248]
Noted while working on https://github.com/phetsims/sun/issues/245.

HSlider currently creates a tandem for its track (HSliderTrack) but not for its thumb (HSliderThumb). Why? 

HSliderTrack is created at HSlider line 126.

HSliderThumb is created at HSlider line 147.

**Comment by pixelzoom** [comment]
The tandem name for the track ('sliderTrack') also seems a little over qualified.  Wouldn't 'track' be sufficient?

**Comment by pixelzoom** [comment]
Mentioning @jessegreenberg because he added the tandem for HSliderTrack.

**Comment by samreid** [comment]
> HSlider currently creates a tandem for its track (HSliderTrack) but not for its thumb (HSliderThumb). Why?

I can see the asymmetry of this, thanks for pointing it out.  The reason it was developed this way is that the track emits input events when the user clicks on the track and the slider (not the knob) emits events when the knob is dragged.  Hence the track and slider needed to be instrumented to get the events into the data stream.  It seems like we should instrument the knob for completeness, so that phet-io clients could customize it.

> The tandem name for the track ('sliderTrack') also seems a little over qualified. Wouldn't 'track' be sufficient?

Yes, `track` seems better.

I'll leave this assigned to me to address these issues.

**Comment by pixelzoom** [comment]
> Hence the track and slider needed to be instrumented to get the events into the data stream.

I don't understand instrumenting the track and "slider".  The track is part of the slider. If you're instrumenting the track, then shouldn't you be instrumenting the track and thumb, and not the "slider"?

**Comment by pixelzoom** [comment]
>  It seems like we should instrument the knob for completeness, so that phet-io clients could customize it.

Let's be sure to refer to this as the "thumb", not the "knob".

**Comment by samreid** [comment]
> Let's be sure to refer to this as the "thumb", not the "knob".

Good call, will do.

> I don't understand instrumenting the track and "slider". The track is part of the slider. If you're instrumenting the track, then shouldn't you be instrumenting the track and thumb, and not the "slider"?

There are 3 classes at play: HSlider, ThumbNode and TrackNode.

HSlider defines an input listener on line 143 which is added to the thumbNode.  TrackNode defines an input listener that listens for events in the track.  ThumbNode does not handle drag events.  It was implemented this way to make the thumb customizable without having the client having to attach the listeners.  However, it means that the events are coming from HSlider and TrackNode.  Given the current slider implementation, implementing ThumbNode would give the ability to show/hide it or make it unpickable, etc, not to receive events from it.

**Comment by samreid** [comment]
I instrumented the HSliderThumb in the preceding commit.  @pixelzoom would you like to review?

**Comment by pixelzoom** [comment]
The track (`this.track`) and thumb (`var thumbNode`) tandems are named like this:

```js
141 tandem: options.tandem && options.tandem.createTandem( 'sliderTrack' )
147 tandem: options.tandem && options.tandem.createTandem( 'thumbNode' )
```

How about this?

```js
141 tandem: options.tandem && options.tandem.createTandem( 'slider' )
147 tandem: options.tandem && options.tandem.createTandem( 'thumb' )
```

And if there's some (inconsistently applied) convention to name the tandem the same as the `var`, then I'd be in favor of renaming `thumbNode` to `thumb`.

**Comment by pixelzoom** [comment]
The track (`this.track`) and thumb (`var thumbNode`) tandems are named like this:

```js
141 tandem: options.tandem && options.tandem.createTandem( 'sliderTrack' )
147 tandem: options.tandem && options.tandem.createTandem( 'thumbNode' )
```

This seems a little awkward/inconsistent. How about changing to this?

```js
141 tandem: options.tandem && options.tandem.createTandem( 'track' )
147 tandem: options.tandem && options.tandem.createTandem( 'thumb' )
```

And if there's some (inconsistently applied) convention to name the tandem the same as the `var`, then I'd be in favor of renaming `thumbNode` to `thumb`.

**Comment by samreid** [comment]
I think it has generally worked well to name node vars with a node suffix.  Please correct me if this is incorrect. But in this case it may be best to use `var trackNode` and `var thumbNode` and use `trackNode` and `thumbNode` for the tandems.  Whichever we choose, the tandem names and var names should be consistent.

**Comment by pixelzoom** [comment]
> Whichever we choose, the tandem names and var names should be consistent.

Agreed. This would be fine too:

```js
141 tandem: options.tandem && options.tandem.createTandem( 'trackNode' )
147 tandem: options.tandem && options.tandem.createTandem( 'thumbNode' )
```

**Comment by pixelzoom** [comment]
@samreid said:
> I think it has generally worked well to name node vars with a node suffix. 

I see exceptions to this in the first sim that I looked at. concentration.ConcentrationSlider, uses 'track' and 'thumb', as I proposed:

```js
63 this.track = new Track( TRACK_SIZE, solutionProperty, tandem.createTandem( 'track' ) );
66 this.thumb = new Thumb( THUMB_SIZE, TRACK_SIZE, solutionProperty, tandem.createTandem( 'thumb' ) );
```

**Comment by samreid** [comment]
What about this proposed convention:

For view components that have a corresponding model component, use the `Node` suffix.  For view components that do not have a corresponding model component, omit the `Node` suffix.

For instance:
```
var skaterNode = new SkaterNode(skater);
var clearButton = new ClearButton();
var rectangle = new Rectangle();
```

**Comment by pixelzoom** [comment]
That's the convention that I've been trying to use for naming variables and types.  Not sure how consistent I've been.  

I'm also not totally sold on the need to have the tandem and var names match.

**Comment by samreid** [comment]
> I'm also not totally sold on the need to have the tandem and var names match.

This has served as a good rule of thumb, mainly to (a) help us give good descriptive var names (b) make text searches yield both results (i.e. renaming `myVar` also renames the `myVar` tandem.)  Are there cases you can think of where they should intentionally not match?

**Comment by pixelzoom** [comment]
8/25/16 discussion with @samreid and @jbphet:

For HSlider, let's use 'track' and 'thumb' for both the tandem and var names. I'll do this.

**Comment by pixelzoom** [comment]
Nothing left to do here, closing.
