### ISSUE TITLE
HSlider saves all of its options

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#249]
Address this TODO in HSlider:

```js
95 this.options = options; // @private TODO save only the options that are needed by prototype functions
```

**Comment by pixelzoom** [comment]
Addressed in above commit. Assigning to @jessegreenberg since he's reviewing other HSlider issues.

**Comment by jessegreenberg** [comment]
Looks great to me.  I thought about picking out thumb and track options in the same way so that options are distributed in the same way, but it is more complicated since tandem needs to be added to the track options.  Closing.
