### ISSUE TITLE
HSlider doesn't verify that "enabledRange" is within the slider's range

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#250]
`enabledRangeProperty` was added in @2b83e994039b2d33845d5e51d7735d144c188d97 by @jessegreenberg.   When `enbledRangeProperty` changes, there is currently no verification that its value is within the range of the slider value.

**Comment by pixelzoom** [comment]
Fixed in above commit. Assigned to @jessegreenberg to review.

**Comment by jessegreenberg** [comment]
Thanks @pixelzoom this is an important think to check.  Commit looks good and it caught the error when I tried it out.  Closing.
