### ISSUE TITLE
OnOffSwitch: use pixels instead of percentages for touchArea default

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#255]
In light of https://github.com/phetsims/sun/issues/251#issuecomment-242508522, OnOffSwitch's defaults for touchArea should be changed to pixels instead of percentages. 

Relevant code in OnOffSwitch:

```js
81  thumbNode.touchArea = Shape.roundRect( -touchAreaDilation, -touchAreaDilation, (0.5 * options.size.width) + (2 * touchAreaDilation), options.size.height + (2 * touchAreaDilation), cornerRadius, cornerRadius );
```

**Comment by pixelzoom** [comment]
ABSwitch will be affected, since it has OnOffSwitch as a subcomponent. Will need to add options for pointer areas.

**Comment by pixelzoom** [comment]
ABSwitch is used by 9 sims, but currently has no way to change pointer areas of the OnOffSwitch.  So there should be no impact on existing clients.  But I will add options for future use.

**Comment by pixelzoom** [comment]
Work is completed.

Summary of what was done:

• added pointer areas options for OnOffSwitch thumb, with default values that correspond to previous behavior for default `size`
• adjusted touchArea options for clients of OnOffSwitch that use a custom `size` (color-vision only)
• added pointer area options for ABSwitch thumb, with default values that correspond to previous behavior for default `switchSize`
• adjusted touchArea options for clients of ABSwitch that were providing a custom `switchSize`

Randomly selected @andrewadare to review.

**Comment by andrewadare** [comment]
Code looks good to me, only question I have is whether it might be better to assign some kind of global constant for the frequently-used values (e.g. 5px dilations) instead of hard-coding them everywhere, so that if it's decided to change it later, one change would do it. Or, maybe that's not at all what you want; not sure.

**Comment by pixelzoom** [comment]
There are 14 occurrences of "var ABSwitch".  I inspected the uses of ABSwitch, and only those in area-builder, balancing-act and expression-exchange (all @jbphet sims) are using 5px dilations.  All others are using the defaults (8px), except pendulum lab (3.5px).  So no, I don't think we need global constants for the 5px dilation.  Closing.
