### ISSUE TITLE
ComboBox: add enabled/disabled feature

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#256]
Needed in https://github.com/phetsims/phet-io/issues/576.

Should follow the pattern agreed on in https://github.com/phetsims/sun/issues/241

**Comment by pixelzoom** [comment]
Feature added, demonstrated in sun demo.

@samreid please review, and verify that this feature is used in phetsims/phet-io#576.

**Comment by samreid** [comment]
In the preceding commit, I fixed a problem where tandem customization was being overwritten later in the constructor.  I fixed this by moving Tandem.addInstance to the bottom of the constructor.

**Comment by samreid** [comment]
Change set looks good, aside from the issue I addressed in my preceding commit.  Test in sun example looks good.  We may revisit this if "setEnabled" moves into Node.  Reassigned to @pixelzoom to discuss my change, if necessary.

**Comment by pixelzoom** [comment]
> I fixed a problem where tandem customization was being overwritten later in the constructor.

I don't see the problem you're describing.  Between where `addInstance` is now and where it was before, there is no code executed that uses the tandem:

``js
    // enable/disable the combo box
    var enabledObserver = function( enabled ) {
      self.pickable = enabled;
      self.opacity = enabled ? 1.0 : options.disabledOpacity;
    };
    this.enabledProperty.link( enabledObserver );
      
    // @private called by dispose
    this.disposeComboBox = function() {
      self.enabledProperty.unlink( enabledObserver );
      options.tandem && options.tandem.removeInstance( this );
      property.unlink( propertyObserver );
    };
```

Or are you saying that the convention to make `addInstance` the last line of the constructor?

**Comment by samreid** [comment]
Customization code can be called synchronously right after `addInstance`.  In this case, the customization was being overriden by the `link` which happened afterwards.

**Comment by pixelzoom** [comment]
By "customization code", do you mean PhET-iO customizations?  And by "can be" do you mean that this is where any customization code *will be* called, or might be called?

**Comment by samreid** [comment]
> By "customization code", do you mean PhET-iO customizations?

Yes.  PhET-iO supports synchronous customization which are applied immediately after objects are registered with `addInstance` as well as dynamic customization (calling methods on objects) after they are created (asychronously).

**Comment by pixelzoom** [comment]
Got it, thanks for explaining. 

Closing.
