### ISSUE TITLE
Should we refactor AquaRadioButton to consolidate the circles for PhET-iO?

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#258]
In https://github.com/phetsims/phet-io/issues/576#issuecomment-244436190

@pixelzoom said:

@samreid Your implementation requires setting the pieces of the button separately. I.e., in beers-law-lab-wrapper.js:

```js
         phetioID: 'beersLawLab.beersLawScreen.view.detectorNode.bodyNode.absorbanceRadioButton.innerCircle',
          method: 'setVisible',
          args: [ false ]
        }, {
          phetioID: 'beersLawLab.beersLawScreen.view.detectorNode.bodyNode.absorbanceRadioButton.outerCircleSelected',
          method: 'setVisible',
          args: [ false ]
```

A better solution would restructure AquaRadioButton so we are controlling visiblity of the button, not each of its parts separately. The API entry would then look like this:

```js
         phetioID: 'beersLawLab.beersLawScreen.view.detectorNode.bodyNode.absorbanceRadioButton.button',
          method: 'setVisible',
          args: [ false ]
        }, 
```

**Comment by pixelzoom** [comment]
Yes, we should.

**Comment by pixelzoom** [comment]
@samreid Do we need to discuss? Are you doing this or me?

**Comment by pixelzoom** [comment]
`AquaRadioButton` is (imo) the wrong place to add instrumentation. Move the instrumentation into the `RadioButton` subtype, where already have `selectedNode` and `deselectedNode`. And presumably we'll want similar instrumentation for other subtypes of `RadioButton`.

**Comment by pixelzoom** [comment]
Also wanted to point out that you need to hide both `selectedNode` and `deselected` node, for the case where the initial state of the button is unselected.   In beers-law-lab customization, you only hid `innerCircle` and `outerCircleSelected`, an approach that is highly dependent on the initial state of the button.

**Comment by samreid** [comment]
@pixelzoom and I addressed this in the above commit, closing.
