### ISSUE TITLE
RadioButtonGroup options.align is broken

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#268]
Noticed while attempting to left-align radio button content in models-of-the-hydrogen-atom.

`RadioButtonGroup` has option `align`, which one might expect to align the content on the buttons. In reality, it appears to do nothing. The problem appears to be that `RadioButtonGroup` is passing `align` to `RectangularButtonView`, and expecting it to handle alignment. But `RectangularButtonView` has no support for alignment, which (given that it has options `minWidth`, `minHeight`, `xMargin` and `yMargin`) would appear to be a deficiency.

`RectangularButtonView` should probably be given options for horizontal and vertical alignment (both default to 'center').  And `RadioButtonGroup` should undoubtedly have separate horizontal and vertical alignment too.

Also highly recommended to actually test this feature (e.g. in the sun demo application).

Until this is fixed, the workaround is to create your button content with identical dimensions, and handle the alignment yourself in the content. This negates half of the reason to use RadioButtonGroup.

Assigning to @ariel-phet to prioritize and assign, because I don't have time to fix this. (I'm planning to hack around it in models-of-the-hydrogen-atom.)

**Comment by ariel-phet** [comment]
Assigned to @jbphet to work on once SOM is out the door

**Comment by pixelzoom** [comment]
Suggested to fix this AlignBox and AlignGroug. See using https://github.com/phetsims/sun/issues/276 (

**Comment by ariel-phet** [comment]
@jbphet I thinik now that SOM is out, time to work on this issue.

**Comment by jbphet** [comment]
For reference, below is an example of what @pixelzoom was trying to accomplish when he ran into this issue.  Note that the content of the radio buttons are all left aligned.  This was taken from the current master version of Models of the Hydrogen Atom.

![motha-control-panel](https://cloud.githubusercontent.com/assets/3082831/22385015/26e2b1f8-e48e-11e6-9002-d774bafc7380.PNG)

**Comment by jbphet** [comment]
I've added alignment options to `RectangularButtonView` and added that capability to pass this option through the `RadioButtonGroup` constructor.  @pixelzoom suggested that there be different options for handling vertical and horizontal alignment for the `RadioButtonGroup` as a whole versus the content nodes for the buttons.  I don't quite understand this, because the group as a whole doesn't have any visible container, so I don't understand what the alignment would do.

Back to @pixelzoom to review the changes and to discuss alignment options for the group as a whole.

**Comment by jbphet** [comment]
I also backed out the workaround in Models of the Hydrogen atom, but left it commented out in case there are problems.  @pixelzoom - please review and removed the commented-out code if this looks okay.

**Comment by pixelzoom** [comment]
@jbphet said:
> @pixelzoom suggested that there be different options for handling vertical and horizontal alignment for the RadioButtonGroup as a whole versus the content nodes for the buttons.

I'm not suggesting "as a whole". The alignment determines how the content on the buttons is aligned.  Feel free to call it `buttonContentAlign` if you think that's clearer.  I would be happy with `align` that works properly and is documented.

**Comment by pixelzoom** [comment]
Issues:

(1) Why does RadioButtonGroup still have an `align` option? Is it used somewhere? 

(2) Dubious test harness in sun demo.

In https://github.com/phetsims/sun/issues/268#issue-178131092, I said: 
> Also highly recommended to actually test this feature (e.g. in the sun demo application).

There's 1 RadioButtonGroup in the sun demo:

```js
    var radioButtonGroup = new RadioButtonGroup( radioButtonProperty, radioButtonContent, {
      orientation: 'vertical',
      selectedLineWidth: 4,
      buttonContentXAlign: 'left'
    } );
```

Am I supposed to test RadioButtonGroup by manually changing the options?  To test `buttonContentYAlign`, I had to figure out that I also had to change the font size for at least 1 of the buttons.

(2) Insufficient documentation and no validation for  alignment options.

In RadioButtonGroup:

```js
111      buttonContentXAlign: 'center',
112      buttonContentYAlign: 'center',
```

In RectangularButtonView:

``js
68      xAlign: 'center',
69     yAlign: 'center',
```

No documentation or validation in either case.  If you provide an invalid value, it fails down in AlignBox.

**Comment by pixelzoom** [comment]
I removed the workaround in MOTHA.

I paired with @jbphet  to address the remaining issues mentioned in https://github.com/phetsims/sun/issues/268#issuecomment-276820873. See above commit.

Closing.
