### ISSUE TITLE
Make it possible to reuse FontAwesome shapes without introducing memory leaks

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#270]
From https://github.com/phetsims/joist/issues/329 we removed caching from FontAwesomeNode because it was causing a memory leak.  In https://github.com/phetsims/function-builder/issues/102 we identified that some sims, such as Function Builder spend a lot of time (like 1000ms) during startup parsing the same svg path over and over.

The memory leak was caused because Path assumes the Shape is dynamic, and adds listeners to it like so:

``` js
        // Add Shape invalidation listener if applicable
        if ( this._shape ) {
          this._shape.onStatic( 'invalidated', this._invalidShapeListener );
        }
```

@pixelzoom and I discussed it and would like to investigate adding a new Path option `{staticShape}` which indicates that no listeners would be attached to the Shape.  This would make it possible to reuse the shapes created by FontAwesomeNodes without inadvertently introducing memory leaks.

@pixelzoom also recommends making the shape creation function public so that clients can manage how the shape is created (if a different strategy is necessary).

It would be great to hear from @jonathanolson whether this proposed strategy would work well, or if there are better recommendations.

It would also be nice to factor out FontAwesomeShape, but it is unclear how to do this because the shapes must be transformed and it is unclear whether it is possible to transform a shape in-place.  Another alternative would be to preprocess all of the Shapes, transform them and use getSVGPath so they don't have to be re-transformed each time the sim launches.

**Comment by jonathanolson** [comment]
A staticShape option sounds fine, although it might be more convenient to have an 'immutable' flag on the Shape itself.

If we have the flag on the Shape, it can fail out when attempts are made to mutate it, and could be performed at the end of creating a shape, e.g. ```new Shape().drawStuff().close().done()```.

Thoughts @pixelzoom and @samreid?

**Comment by samreid** [comment]
@jonathanolson it sounds good to me.  Let's hear from @pixelzoom.

**Comment by pixelzoom** [comment]
+1 for marking the Shape as immutable.

**Comment by pixelzoom** [comment]
Here's what I had in mind:

```js
// FontAwesomeShape.js

var Shape = require( 'KITE/Shape' );

var ICONS = {... }; // fontawesome SVG data
var SHAPE_MATRIX = Matrix3.createFromPool( ... ); // to create a unity-scale icon

function FontAwesomeShape( iconName ) {
  //TODO How to apply SHAPE_MATRIX? No way to pass a transform to Shape constructor, or transform in place. 
  Shape.call( this, ... );
  this.mutable = false; //TODO or set this via options?
}
```

```js
// FontAwesomeNode.js

var SHAPE_CACHE = {};

function FontAwesomeNode( iconName ) {

  options = _.extend( {
    fill: 'black',
    pickable: false,
    enableCache: true
  }, options );

  var shape;
  if ( options.enableCache ) {
    // cache the shape
    if ( !SHAPE_CACHE[ iconName ] ) {
      SHAPE_CACHE[iconName] = new FontAwesomeShape( iconName );
    }

    // get the shape from the cache
    shape = SHAPE_CACHE[ iconName ];
  }
  else {

    // don't use the cache
    shape = new FontAwesomeShape( iconName );
  }

  Path.call( this, shape, options );
}
```

**Comment by samreid** [comment]
Regarding subclassing Shape for the icons, I augmented the code like so to generate the transformed SVG Strings:

```js
  window.out = {};
  var getShapeByName = function( iconName ) {
    assert && assert( ICONS[ iconName ], 'Icon not found: ' + iconName );

    // At one point, shapes were cached to reduce the overhead of having to reinterpret the SVG each time the shape was
    // loaded, but this led to memory leaks (see https://github.com/phetsims/joist/issues/329).  As a result, the icons
    // are loaded anew each time.
    var shape = new Shape( ICONS[ iconName ] ).transformed( SHAPE_MATRIX );
    window.out[ iconName ] = shape.getSVGPath();
    return shape;
  };

  _.keys( ICONS ).forEach( function( k ) {
    getShapeByName( k );
  } );
```

However, this takes the file size from 11kb to 83kb because the strings look like this:
```js
var ICONS2 = {
    ban_circle: 'M 32.00000000000000000000 -16.00000000000000000000 Q 32.00000000000000000000 -19.47500000000000142109 
/// etc
```

**Comment by pixelzoom** [comment]
Unless applying the transform is a performance issue, I'd prefer not to add additional preprocessing steps to integration fontawesome SVG data.  I think it's advantageous for the data to appear as it does in the fontawesome source.

**Comment by pixelzoom** [comment]
Before we get too much further into this, we should verify that there's going to be a performance payoff.  In https://github.com/phetsims/function-builder/issues/102, @samreid did some benchmarking that identified creation of FontAwesomeNode as a performance issue.  Caching assumes that most of the cost is in parsing the SVG and creating the Shape.  Is that true?  If a significant portion of the cost is in creating the associated Path, then the payoff may be smaller.

**Comment by pixelzoom** [comment]
9/22/16 dev meeting: @pixelzoom @samreid and @jonathanolson will work on this, no need to involve other developers.

**Comment by jonathanolson** [comment]
> Caching assumes that most of the cost is in parsing the SVG and creating the Shape. Is that true?

Pretty sure that was true the last time. Path generally just asks the Shape for its bounds, svg string, etc., all of which should be faster with one Shape.

@samreid, any preferences on how to make a Shape immutable? I have a slight preference for a method so it can be chained at the end (like is common for constructing Shapes), like .done() or .makeImmutable(). @pixelzoom suggested "this.mutable = false".

**Comment by pixelzoom** [comment]
Currently in FontAwesomeNode we have:

```js
return new Shape( ICONS[ iconName ] ).transformed( SHAPE_MATRIX );
```

So add `.done()` to the end, like this?

```
return new Shape( ICONS[ iconName ] ).transformed( SHAPE_MATRIX ).done();
```

**Comment by pixelzoom** [comment]
@jonathanolson Any thoughts on this TODO in https://github.com/phetsims/sun/issues/270#issuecomment-248962756? 

```js
  //TODO How to apply SHAPE_MATRIX? No way to pass a transform to Shape constructor, or transform in place. 
```

**Comment by jonathanolson** [comment]
> So add .done() to the end, like this?

That would be the plan.

> @jonathanolson Any thoughts on this TODO in #270 (comment)?

I don't like the overhead of creating two Shapes (with two copies of each segment in the Shape), but I believe it's currently the best way (given that each segment only has a transformed() immutable-style method).

Presumably if we add mutable transforms to Shape and segments in the future, we'll find this location in searches, so we can remove the TODO when doing the refactoring.

**Comment by pixelzoom** [comment]
> I don't like the overhead of creating two Shapes (with two copies of each segment in the Shape), but I believe it's currently the best way (given that each segment only has a transformed() immutable-style method).

Please take a close look at the `FontAwesomeShape` example.  How can `FontAwesomeShape` extend `Shape` if we need to create 2 Shapes?

**Comment by jonathanolson** [comment]
I saw the example, but I wasn't sure why we were creating FontAwesomeShape. I didn't see any methods added.

A global FontAwesomeNode.getShape( name ) sounds preferable?

**Comment by pixelzoom** [comment]
Why is that preferable? That would be like `ArrowButton.createShape()` instead of `new ArrowShape()`.  Clients should be able to create and manage FontAwesomeShapes independently of FontAwesomeNode.

**Comment by samreid** [comment]
> @samreid, any preferences on how to make a Shape immutable? I have a slight preference for a method so it can be chained at the end (like is common for constructing Shapes), like .done() or .makeImmutable(). @pixelzoom suggested "this.mutable = false".

.makeImmutable() seems clearest and most consistent with existing shape API.

**Comment by jonathanolson** [comment]
> Why is that preferable? That would be like ArrowButton.createShape() instead of new ArrowShape(). Clients should be able to create and manage FontAwesomeShapes independently of FontAwesomeNode.

First, I'm not sure why we'd want clients to create the shapes. Every 'check_empty' shape would be identical except for duplicated instance objects (since it will be immutable), so we really only want a shared shape for each type (one shared shape instance for 'check_empty', ideally allocated when it is initially requested).

Additionally, I don't feel like managing FontAwesomeShapes without a require to FontAwesomeNode is needed, but I'd still be happy if we had a FontAwesomeShape object whose sole interface was ```FontAwesomeShape.getShape( name )``` instead of ```FontAwesomeNode.getShape( name )```. In neither case is the client required to ever touch a Node if they want a Shape instead.

So in general, it would be preferable because we won't be creating duplicate shapes (performance win), we won't need inheritance to accomplish it (simplicity), and we are less likely to cause JIT issues because our shapes will have the same hidden class as most other shapes (performance win).

The potential upside to inheritance seems to only come into play if we need to store additional mutable state on the shapes (or immutable state that new methods would access that aren't part of Shape). @pixelzoom, are there additional advantages to the inheritance pattern?

**Comment by pixelzoom** [comment]
@jonathanolson said:
> First, I'm not sure why we'd want clients to create the shapes. 

To be able to create and manage a Shape that is based on fontawesome data with having to use the caching feature.  With caching, once a Shape is in the cache, it's in the cache for the lifetime of the sim.  Unless you want to complicate matters and add a "flush cache" feature.

@jonathanolson said
> we won't need inheritance to accomplish it (simplicity)

I don't agree at all in this case that forgoing inheritance is simpler.  FontAwesomeShape is responsible for the SVG shape descriptions, FontAwesomeNode is responsible for the cache. But if you want to spread responsibilities around where they don't belong, go for it. 

Btw... Shapes itself is a nice example of where inheritance would have been appropriate (SVGShape ), but instead we have constructor parameters that are overloaded and poorly documented.

**Comment by pixelzoom** [comment]
I also suspect that the objection to FontAwesomeShape has more to do with https://github.com/phetsims/sun/issues/270#issuecomment-249293716 than with the use of inheritance. Each segment is immutable, so the only way to transform a Shape is to create another Shape. And that makes implementing FontAwesomeShape (as I've proposed it) currently impossible.

**Comment by pixelzoom** [comment]
Adding @samreid to assignees since this is now block https://github.com/phetsims/phet-io/issues/642, which he needs to complete by Thursday, 9/29.

How should we proceed?

**Comment by jonathanolson** [comment]
> How should we proceed?

I can give Shape .makeImmutable(), I'll be fine with however you decide FontAwesome*.js should look.

**Comment by pixelzoom** [comment]
OK, I'll proceed with `sun` work. 

Is this necessary in FontAwesomeNode?

```js
      // Font awesome nodes are expensive to pick (and have a lot of holes in them which you may wish to pick anyways,
      // such as the door of the 'home' icon, so don't pick by default.
      pickable: false,
```

**Comment by pixelzoom** [comment]
Shape caching added in above commit.  This will leak memory until Shape.makeImmutable call is added on this line of FontAwesomeNode:

```js
101 return new Shape( ICONS[ iconName ] ).transformed( SHAPE_MATRIX ); //TODO call makeImmutable, see sun#270
```

@jonathanolson Feel free to test `makeImmutable` in this context, and address the above TODO.

**Comment by samreid** [comment]
> Is this necessary in FontAwesomeNode?

> ```js
      // Font awesome nodes are expensive to pick (and have a lot of holes in them which you may wish to pick anyways,
      // such as the door of the 'home' icon, so don't pick by default.
      pickable: false,
```

I suspect pickable:null (the default) would handle this, if it is rare for clients to add listeners to font awesome shaped Paths.

**Comment by samreid** [comment]
I'm not sure if you need other feedback from me, let me know is so.

**Comment by jonathanolson** [comment]
I'm working on Shape immutability now.

> Is this necessary in FontAwesomeNode?

> I suspect pickable:null (the default) would handle this, if it is rare for clients to add listeners to font awesome shaped Paths.

Seems fairly common, as all checkboxes and reset-all/volume/home buttons probably have listeners or are descendants of something with listeners, and many of the font-awesome icons seem well suited to being on buttons.

pickable:false seems like an appropriate default to me, as long as it can be overridden.

**Comment by jonathanolson** [comment]
Commits above to add immutability. @pixelzoom or @samreid, do we have a sim for testing that would exhibit a major memory leak if this caused them again?

**Comment by pixelzoom** [comment]
Caching was originally removed because of this issue:  https://github.com/phetsims/joist/issues/329

**Comment by pixelzoom** [comment]
The only sim that I'm aware of that would demonstrate a leak is model-of-the-hydrogen-atom (in development).  Pressing the camera button on the spectrometer creates snapshots.  Pressing the "View snapshots" button opens a dialog, with `FontAwesomeNode( 'trash' )` icons on buttons.

**Comment by pixelzoom** [comment]
I reviewed the changes to Shape, looks straightforward.

@samreid Would you please review the changes to FontAwesomeNode?

**Comment by samreid** [comment]
I thought one of the problems with Shape (see discussion in https://github.com/phetsims/sun/issues/270#issue-178406865) was the back-reference in lines like:

```js
subpath.onStatic( 'invalidated', this._invalidateListener );
```

Setting an immutable flag after the listeners have already been added doesn't seem to mitigate this problem at all.  @jonathanolson and @pixelzoom can you comment?

**Comment by samreid** [comment]
Though I have a faint memory that the memory leak is through a Path parent reference, not through shape listeners....

**Comment by samreid** [comment]
The code changes in FontAwesomeNode look correct.  I can take it for more of a test drive once the discussion above concludes.

**Comment by jonathanolson** [comment]
> Though I have a faint memory that the memory leak is through a Path parent reference, not through shape listeners....

Yup, https://github.com/phetsims/scenery/commit/ff21c54932df41202549b24b040fb1f6505e174c should fix that. I left the listeners from segment=>subpath and subpath=>shape so that if someone mutates a segment of an immutable shape then it will fail an assertion.

Unless people are holding references to very specific things inside of Shapes, then a Shape, its subpaths and segments should all be collected at the same time.

**Comment by samreid** [comment]
I tested out the FontAwesomeNode runtime and it seems good.  With memory leak:

![image](https://cloud.githubusercontent.com/assets/679486/18889809/d1250a36-84bb-11e6-9338-bcf9543a4521.png)

Without memory leak:
![image](https://cloud.githubusercontent.com/assets/679486/18889828/e3d3e9a4-84bb-11e6-9fd7-ee76a5b8c511.png)

```js
    var a = [];
    setInterval( function() {
      for ( var i = 0; i < 100; i++ ) {
        var h = new FontAwesomeNode( 'home' );
        // a.push( h ); // memory leak
      }
    }, 0 );
```

**Comment by jonathanolson** [comment]
> In this case, Path should remove its Shape listener.

It seems like a fairly rare case (usually you would construct the Shape and then mark it as immutable before it ever gets to Path).

I decided when implementing that this wasn't worth (to me) Path having to add yet another listener to Shape, just to listen for when it was made immutable (addShapeBecameImmutableListener?).

Path's setShape could use a note about this interaction.

Let me know if that sounds acceptable?

**Comment by pixelzoom** [comment]
My feeling that if it's something that's possible to do, then it should be handled.   And seems relatively easy to handle this case:

In Shape, call `invalidate` in `makeImmutable`:
```js
    makeImmutable: function() {
      this._immutable = true;
      this.invalidate();
      return this; // for chaining
    },
```

In Path, remove the listener when a Shape becomes immutable:

```js
   invalidateShape: function() {
      this.invalidatePath();

      var stateLen = this._drawables.length;
      for ( var i = 0; i < stateLen; i++ ) {
        this._drawables[ i ].markDirtyShape(); // subtypes of Path may not have this, but it's called during construction
      }

       // if the shape has become immutable, remove the 'invalidated' listener
       if ( this._shape.isImmutable() ) {
        this._shape.offStatic( 'invalidated', this._invalidShapeListener );
      }
    },
```

**Comment by jonathanolson** [comment]
Changes as described pushed.

**Comment by pixelzoom** [comment]
@samreid Do you want to take another look at this before it goes live in https://github.com/phetsims/phet-io/issues/642?

**Comment by samreid** [comment]
The change set looks correct, it seems OK to close.

**Comment by pixelzoom** [comment]
Reopening.  This behavior (console) doesn't look correct:

```
> var shape = new phet.kite.Shape().lineTo( 100, 100 );
> var path = new phet.scenery.Path( shape );
> shape.makeImmutable()
assert.js:22 Assertion failed: Concurrent modifications from static listeners are forbidden
```

According to the commit message for @https://github.com/phetsims/scenery/commit/e9485095e09c23162bde7b32ec81c481647df362, the Path should remove the listener from the shape, and there should be no error here.

**Comment by jonathanolson** [comment]
Sorry about that, it may be that we're not using that ordering pattern in any sims.

Since those are static listeners, we can't modify the listener list while it is iterating. Making it non-static would cause extra allocations in places we don't want, so presumably we'll want another event for this purpose?

Alternatively, we could have making a Shape immutable an assertion failure if it has any invalidation listeners.

@pixelzoom and @samreid, thoughts?

**Comment by samreid** [comment]
Since I am aware of the issue I am fine with the current behavior (as long as you document that makeImmutable must be called before new Path() is called).  But it may be opaque to others and the assertion @jonathanolson mentioned may be best, if that's straightforward.

**Comment by pixelzoom** [comment]
> Alternatively, we could have making a Shape immutable an assertion failure if it has any invalidation listeners.

Sounds good.

**Comment by jonathanolson** [comment]
@samreid, what is the correct way to check an Events object for the existence of a listener for a certain name? Might need a new method for that.

**Comment by samreid** [comment]
Events is deprecated and we should port to using Emitter instead.  Will that work for this case or do we need something for Events?

**Comment by jonathanolson** [comment]
Added issue for handling Events => Emitter for Kite, as that's a prerequisite.

**Comment by pixelzoom** [comment]
I believe that all work is done here, or moved to new issues. 

Closing.
