### ISSUE TITLE
why do we have 2 SVG files for fontawesome icons?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#271]
From https://github.com/phetsims/unit-rates/issues/123#issuecomment-252303331:

FontAwesomeNode documentation says:

```
To add a new icon:
// (1) Look up the unicode for the icon you want. For instance: http://fortawesome.github.io/Font-Awesome/icon/camera/ says Unicode: f030
// (2) Navigate to sherpa/lib/fontawesome-webfont-3.0.2.svg and copy the text from the d="" declaration from the corresponding element.
```

We have 2 svg files in sherpa:

```
sherpa/lib/fontawesome-webfont-3.0.2.svg
sherpa/lib/font-awesome-4.5.0/fonts/fontawesome-webfont.svg
```

@samreid  Why do we need fontawesome-webfont-3.0.2.svg? Can we just use font-awesome-4.5.0/fonts/fontawesome-webfont.svg?

**Comment by mattpen** [comment]
@pixelzoom - fontawesome-webfont-3.0.2.svg is used by FontAwesomeNode, and font-awesome-4.5.0/fonts/fontawesome-webfont.svg is used by the phet-io website and phet-io wrappers.  

Do we need to consolidate?  It appears that v4 is not backwards compatible with v3 and upgrading may be an intensive process.

**Comment by pixelzoom** [comment]
@mattpen I don't understand how the version dependency or compatibility issues. We add an icon to FontAwesomeNode by copy-pasting SVG data from fontawesome-webfont.svg.  Are you saying that the SVG format is different for 3.0.2 vs 4.5.0?  I recently added `level_down` to  FontAwesomeNode by copying it from the 4.5.0 version of fontawesome-webfont.svg, and I saw no problems.

**Comment by mattpen** [comment]
@pixelzoom - I'm not familiar with FontAwesomeNode enough to say whether we can upgrade easily or not.  I'm not aware of what changes there have been to the svg format, if any.  [According to their github page](https://github.com/FortAwesome/Font-Awesome/wiki/Upgrading-from-3.2.1-to-4), it mostly looks like the css classes changed names.  If we are copy/pasting code from the svg file, then its probably safe to remove the old file, all the old icons have been retained.

I would prefer to keep the later version if possible for the phet-io website and wrappers, whether or not we discard the old one.

**Comment by pixelzoom** [comment]
I proposed to that we delete sherpa/lib/fontawesome-webfont-3.0.2.svg, and change the documentation in FontAwesomeNode as shown below (agnostic of version number):

```js
To add a new icon:
// (1) Look up the unicode for the icon you want. For instance: http://fortawesome.github.io/Font-Awesome/icon/camera/ says Unicode: f030
// (2) Navigate to sherpa/lib/font-awesome-*/fonts/fontawesome-webfont.svg and copy the text from the d="" declaration from the corresponding element.
```

Labeled for developer meeting.

**Comment by pixelzoom** [comment]
10/27/16 dev meeting, we decided to do what I proposed in https://github.com/phetsims/sun/issues/271#issuecomment-256091764.  I'll do it.

**Comment by pixelzoom** [comment]
I deleted sherpa/lib/fontawesome-webfont-3.0.2.svg and adjusted all license-related files to point to sherpa/lib/font-awesome-4.5.0/fonts/fontawesome-webfont.svg.  The SVG font information (which is the sole portion used in PhET sims) remains licensed under SIL OPEN FONT LICENSE Version 1.1, so I simply renamed the license text file to sherpa/licenses/font-awesome-4.5.0.txt.

@mattpen Please verify that this doesn't mess up usage in the website (it should be totally unrelated).

**Comment by pixelzoom** [comment]
Note that I also tested a sim build, confirmed that the correct license info is in the sim's HTML file, and regenerated third-party-licenses.md.

**Comment by mattpen** [comment]
The website and the io wrappers are still working in terms of font-awesome, thanks @pixelzoom.
