### ISSUE TITLE
problems with Boolean*ToggleButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#272]
Problems with BooleanRoundToggleButton and BooleanRectangularToggleButton, noted while working on https://github.com/phetsims/unit-rates/issues/125.

(1) Allows the client to specify options.content.  That option should be blacklisted, since the constructor args are used to create the button's content.

(2) Uses a ToggleNode to switch between different Nodes for true and false state. But ToggleNode does no positioning of the Nodes.  So if the images are of different sizes, one or both of them will not be properly centered on the button.

Both of these are relatively easy to fix, but may affect sims that depend on the buggy behavior.

Labeling for developer meeting, to decide how to proceed.

**Comment by pixelzoom** [comment]
Issue (1) addressed in above commit. If any sim is trying to set options.content for a BooleanRoundToggleButton, it will now fail an assertion.  Such sims should be using RoundToggleButton.

**Comment by pixelzoom** [comment]
ToggleNode is currently used in balloons-and-static-electricity (ControlPanel), forces-and-motion-basics( GoPauseButton), and sun (BooleanRoundToggleButton, BooleanRectangularToggleButton).  Shall we make ToggleNode align the centers of its child Nodes, and test the above usages? Or is there some more general use case for ToggleNode that will be affected?

**Comment by pixelzoom** [comment]
Or we could just add this to BooleanRoundToggleButton and BooleanRectangularToggleButton:

```js
trueNode.center = falseNode.center;
```

**Comment by pixelzoom** [comment]
Or require the client to handle it the centering. E.g.:

```js
var trueNode = new Image( ... );
var falseNode = new Image(...);
trueNode.center = falseNode.center;
var myButton = new BooleanRoundToggleButton( trueNode, falseNode, ... );
```

**Comment by pixelzoom** [comment]
I don't like the approach described in https://github.com/phetsims/sun/issues/272#issuecomment-254701469, because it relies on internal knowledge of BooleanRoundToggleButton --- specifically, that BooleanRoundToggleButton and ToggleNode don't set the position of trueNode and falseNode.

**Comment by pixelzoom** [comment]
10/27/16 dev meeting: Change ToggleNode to center by default.  We can add `xAlign` and `yAlign` options in the future if necessary. Enumerate sims that need to be tested. I'll do this.

**Comment by pixelzoom** [comment]
Done. Tested in (all?) sims that use ToggleNode, or one of the buttons that uses ToggleNode.

@samreid please take a peek.

**Comment by samreid** [comment]
The changes look good, closing.
