### ISSUE TITLE
remove ToggleNode wrapChildren option?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#273]
ToggleNode currently has this option:

``` js
//Wrap the nodes so that visibility flags won't be toggled on the passed-in nodes directly (in case they appear elsewhere in the DAG)
//Or opt-out if you know the nodes don't appear elsewhere and want to opt out of the increased tree depth and associated performance costs
wrapChildren: true
```

Which is handled in ToggleNode constructor:

``` js
    var targetTrueNode = options.wrapChildren ? new Node( { children: [ trueNode ] } ) : trueNode;
    var targetFalseNode = options.wrapChildren ? new Node( { children: [ falseNode ] } ) : falseNode;

    this.addChild( targetFalseNode );
    this.addChild( targetTrueNode );
```

Problems with this feature:

(1) This is something that could be a feature for _any_ composite Node, and I don't believe it belongs in ToggleNode.  Wrapping nodes for the purposes of using scenery's DAG feature should be the responsibility of clients. 

(2) Having the client wrap the nodes would make it much more obvious what is going on and why. Having it buried in ToggleNode is misplaced responsibility.

(3) BooleanRoundToggleButton and BooleanRectangularButton use ToggleNode, and `wrapChildren` option is not exposed.  So every such button is currently getting 2 additional nodes, whether it needs them or not.  Again, better to make the client responsible for wrapping the nodes.

The `wrapChildren` option was added by @samreid in @95cd625f13e1759b56d0de4cc4169f52ced8793d, probably to address some sim-specific case(s) where he was using scenery's DAG feature.  I recommend removing this feature from ToggleNode, and addressing it in the client(s) that have the need to wrap the Nodes.

**Comment by pixelzoom** [comment]
The decision to add this option is documented in https://github.com/phetsims/sun/issues/36#issuecomment-28173209.

**Comment by pixelzoom** [comment]
ToggleNode is used directly by balloons-and-static-electricity, forces-and-motion-basics, neither of which appears to have a need to use scenery's DAG feature. 

BooleanRoundToggleButton is by scenery-phet PlayPauseButton and RecordStopButton, neither of which appears to have a need to use scenery's DAG feature. 

BooleanRectangularToggleButton is used by pendulum-lab and and scenery-phet (SoundToggleButton, TimerToggleButton).  None of these uses appear to have a need to use scenery's DAG feature. 

So I can't find any cases where the `wrapChildren` option is needed. @samreid Do you recall why you added this?

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/sun/issues/36#issue-22427104, @samreid said:
> In https://github.com/phetsims/joist/issues/88#issuecomment-28170299 we suspected ToggleNode's inferior performance could be causing the slow tab changes.  It should be rewritten to use setVisible not setChildren.

There are currently no uses of ToggleNode in joist, so perhaps this is something that is no longer needed?

**Comment by samreid** [comment]
I haven't had an opportunity to investigate this yet.

**Comment by jonathanolson** [comment]
> Wrapping nodes for the purposes of using scenery's DAG feature should be the responsibility of clients.

Agreed, it works that way for most other buttons or components.

**Comment by pixelzoom** [comment]
10/27/16 dev meeting: Delete this feature, I'll do it.

**Comment by pixelzoom** [comment]
Done, testing with various sims that use ToggleNode directly, and with toggle buttons. @samreid please review.

**Comment by samreid** [comment]
The code change looks good and I tested it in Tug Of War, all seems well, closing.
