### ISSUE TITLE
TextPushButton default font

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/sun#275]
```new Font( 20 )``` actually has size 10, since Font isn't PhetFont.

I didn't want to bump the default size up by 2x (since this code is used everywhere), but should that be done?

**Comment by pixelzoom** [comment]
Options:

1. Change `new Font(20)` to `new PhetFont(20)`. Visit 69 (?) call sites of `new TextPushButton` and add `font: new PhetFont( 10 )` option to all TextPushButtons that don't specify a font.

2. Overload `Font` constructor to support a `{number} size` arg, ala PhetFont.

Given the effort involved in (1), I'd probably go for (2). @jonathanolson your opinion?

**Comment by jonathanolson** [comment]
Sun can't rely on PhetFont though, correct?

**Comment by pixelzoom** [comment]
Ah right... sun can't rely on scenery-phet.

**Comment by pixelzoom** [comment]
So @jonathanolson... It looks like the work here is done, and it's ready for review?

**Comment by jonathanolson** [comment]
> I didn't want to bump the default size up by 2x (since this code is used everywhere), but should that be done?

If the answer is "no, do not bump up the font size", then it is done and can be closed.

**Comment by pixelzoom** [comment]
If `Font(20)` is actually size 10, can't you just change TextPushButton line 26 from:

```font: new Font( 20 ),```

to:

```font: new Font( { size: 10 } ),```

?

**Comment by jonathanolson** [comment]
> Seems like the behavior will then be identical, no?

Yes, the behavior would be identical. But the default font is already size 10, so should that be added in?

> TextPushButton line 26

Just as a clarification, I've already simplified the code by removing the font declaration completely (https://github.com/phetsims/sun/commit/a822decd3410f5d6066ee657fc3b92358fb46ae9), so is it desired to:

1. Change the default font to something not-10? I'd prefer to keep it the way it is, but I asked in case it actually would be helpful to be 20.
2. Add back in a redundant font declaration (e.g. ```new Font( { size: 10 } )```. I'd prefer to omit this, but don't care very much.

**Comment by pixelzoom** [comment]
> I've already simplified the code by removing the font declaration completely 

Sorry, my working copy was behind 1 commit (was looking at this issue on a different machine).  I think what you've done is fine, and should have no affect on existing clients.  

I'm going to close this, since I see no need for @jbphet to (re)review.
