### ISSUE TITLE
RadioButton should use Property's phetioValueType

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#277]
As we did for RadioButtonGroup and ComboBox, RadioButton should use the phetioValueType from the Property.

**Comment by samreid** [comment]
Fixed above and tested by linting and running BLL, which is instrumented and uses the RadioButton type.  Aqua shows green so far, but I'll report back if I see trouble:

![image](https://cloud.githubusercontent.com/assets/679486/20875115/5b5929a0-ba75-11e6-8b0e-51c4d622d9d5.png)

**Comment by samreid** [comment]
@zepumph or @andrewadare can you please review?

**Comment by zepumph** [comment]
@samreid I would love to review, let's collaborate on it sometime so that we can make sure that I'm reviewing the right stuff.

**Comment by zepumph** [comment]
All looked good when reviewing with @samreid. We even used the phet-io brand aqua tests to convince ourselves.
