### ISSUE TITLE
AccordionBox layout bug

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#280]
Noticed while working on unit-rates.

If the contentNode for an AccordionBox has its origin (x=0,y=0) at somewhere other than the upper-left corner of its bounding box, then the layout will be messed up.

For example, this bit of code in a ScreenView constructor:

```js
    var AccordionBox = require( 'SUN/AccordionBox' );
    var Circle = require( 'SCENERY/nodes/Circle' );
    var contentNode = new Circle( 100, { fill: 'red' } );
    this.addChild( new AccordionBox( contentNode, {
      center: this.layoutBounds.center
    } ) );
```

... looks like this:

![screenshot_117](https://cloud.githubusercontent.com/assets/3046552/21958128/41c8819e-da63-11e6-9728-77258a3fe336.png)

Explicitly fixing the origin for the contentNode, like this:

```js
    var contentNode = new Circle( 100, { fill: 'red', left: 0, top: 0 } );
```

provides the correct layout:

![screenshot_116](https://cloud.githubusercontent.com/assets/3046552/21958131/6b336530-da63-11e6-8a47-b9ee2933aaea.png)

I'll use this workaround for now in unit-rates.

**Comment by pixelzoom** [comment]
It's not obvious to me how to fix this.  The bug is probably in the chuck of code labeled "content layout", but I'm not grok'ing this.  Looks like this bit of code was significantly revised by @jbphet in @de72ee4f07ba180393d395e67bcf1105518d9875 and @21b619ac56f3d3b3698583494ab6587e1e2037fe.  @jbphet would you mind looking into this?

**Comment by pixelzoom** [comment]
Here's the problem....

On line 110, we have:

```js
110 expandedBox.addChild( contentNode ); 
```

Then the computations for layout appear later:

```js
164    // content layout
165    contentNode.bottom = expandedBox.bottom - options.contentYMargin;
166    var contentSpanLeft = expandedBox.left + options.contentXMargin;
 167   var contentSpanRight = expandedBox.right - options.contentXMargin;
```

Since `contentNode` is already a child of `expandedBox`, the computation that use `expandedBox` are incorrect.  So I believe that we should be doing `expandedBox.addChild( contentNode );` _after_ the layout computations.

@jbphet Does that make sound right?

**Comment by pixelzoom** [comment]
I went ahead and made the change, after testing in a bunch of sims that use AccordionBox (area-builder, build-an-atom, RPAL, MOTHA, unit-rates,...)

@jbphet please verify.  High priority, since this has the potential to mess up sims.

**Comment by jbphet** [comment]
The reasoning makes sense and the change looks reasonable.  I also tested on several simulations, specifically Build an Atom, States of Matter, and Expression Exchange and saw no problems.  Closing.
