### ISSUE TITLE
Working around immutable components

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/sun#281]
Many components are written so that colors or other initial options can't be changed. Some would be somewhat time-consuming to refactor/rewrite. I've run into this a lot with various buttons, NumberPicker (https://github.com/phetsims/scenery-phet/issues/287), ShadedSphereNode, etc.

I have a prototype solution that I'd like to propose, as I don't have the time currently to independently modify each component.

**Comment by jonathanolson** [comment]
Docs from the prototype constructor:

Given a type that has an option that can only be provided on construction (e.g. 'color' option for NumberPicker),
MutableOptionsNode can act like a mutable form of that Node. For example, if you have a color property:

```js
var colorProperty = new Property( 'red' );
```

You can create a NumberPicker equivalent:
```js
var pickerContainer = new MutableOptionsNode( NumberPicker, [ arg1, arg2 ], {
  font: new PhetFont( 30 ) // normal properties that are passed in directly
}, {
  color: colorProperty // values wrapped with Property. When these change, a new NumberPicker is created and swapped.
}, {
  // Options passed to the wrapper node.
} );
```

Now pickerContainer will have a child that is a NumberPicker, and pickerContainer.nodeProperty will point to the
current NumberPicker instance. The NumberPicker above will be created with like:

```js
new NumberPicker( arg1, arg2, {
  font: new PhetFont( 30 ),
  color: colorProperty.value
} )
```

Parameter documentation:
```
   * @param {Function} nodeSubtype - The type of the node that we'll be constructing copies of.
   * @param {Array.<*>} parameters - Arbitrary initial parameters that will be passed to the type's constructor
   * @param {Object} staticOptions - Options passed in that won't change (will not unwrap properties)
   * @param {Object} dynamicOptions - Options passed in that will change. Should be a map from key names to
   *                                  Property.<*> values.
   * @param {Object} [wrapperOptions] - Node options passed to MutableOptionsNode itself (the wrapper).
```

Thoughts?

**Comment by jonathanolson** [comment]
Of note, the prototype has helped in proportion-playground with:

- ShadedSphereNode (main/highlight/shadow colors are not mutable)
- NumberPicker (color is not mutable)
- RadioButtonGroup (selectedStroke/baseColor are not mutable)
- ResetButton (baseColor actually looks mutable in retrospect, but a colorProperty isn't accepted)

**Comment by samreid** [comment]
This seems like a nice pattern to use.  I'm wondering if you picture it as a long-term solution or just a holdover until each of those elements is mutable.  Also, where else do you think it will be used outside of color customization?

**Comment by jonathanolson** [comment]
> This seems like a nice pattern to use. I'm wondering if you picture it as a long-term solution or just a holdover until each of those elements is mutable.

It can work as a long-term solution for things that we want to keep as immutable. For some components, I view it as a workaround due to the cost of making them mutable given the prevalent "options construction" pattern.

> Also, where else do you think it will be used outside of color customization?

Depends, could be stroke sizes, changing listeners for components, changing icons, etc.
