### ISSUE TITLE
HSlider layout changes based on position of thumb

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#282]
In issues like:
https://github.com/phetsims/circuit-construction-kit-common/issues/253
https://github.com/phetsims/rutherford-scattering/issues/97

And in many places in our codebase.  For instance, in MediumControlPanel.js

```js
    var mediumPanel = new Panel( mediumPanelNode, {
      fill: '#EEEEEE',
      stroke: '#696969',
      xMargin: 13.5, // Adjusted manually so that the panels will align in English and the slider knob won't go outside
                     // the panel
      yMargin: options.yMargin,
      cornerRadius: 5,
      lineWidth: options.lineWidth,
      resize: false // Don't resize when the slider knob encroaches on the right border
    } );
```

There are workarounds for the fact that HSlider bounds change based on the position of the thumb/knob (when it goes over the edge).

To address this problem, we could add struts, manually set bounds or an invisible spacing panel.  Here is the latter:

```js
    var buffer = new Rectangle( 0, 0, this.track.width + thumb.width, thumb.height, {
      fill: 'yellow',
      pickable: false
    } );
    buffer.center = this.track.center;
```

It looks like this:
![image](https://cloud.githubusercontent.com/assets/679486/22839150/893da400-ef85-11e6-95b4-4972e9862bef.png)

And it prevents incorrect layouts from occurring due to the position of the thumb.  @pixelzoom or @jonathanolson  or @jbphet or @jessegreenberg do you know a better way to implement this (say using bounds overrides?) . Or is this the best approach (after turning the fill off, of course).

Here's a complete snippet you could paste into HSlider that (along with requiring Rectangle) will produce this behavior:

```js
    // @private track
    this.track = new HSliderTrack( valueProperty, this.valueToPosition, snapToValue, {

      // propagate options that are specific to HSliderTrack
      size: options.trackSize,
      fillEnabled: options.trackFillEnabled,
      fillDisabled: options.trackFillDisabled,
      stroke: options.trackStroke,
      lineWidth: options.trackLineWidth,
      enabledProperty: options.enabledProperty,
      startDrag: options.startDrag,
      endDrag: options.endDrag,
      snapValue: options.snapValue,
      constrainValue: options.constrainValue,

      // phet-io
      tandem: options.tandem.createTandem( 'track' )
    } );
    this.track.centerX = this.valueToPosition( ( range.max + range.min ) / 2 );

    // thumb
    var thumb = options.thumbNode || new HSliderThumb( this.enabledProperty, {

        // propagate options that are specific to HSliderThumb
        size: options.thumbSize,
        fillEnabled: options.thumbFillEnabled,
        fillHighlighted: options.thumbFillHighlighted,
        fillDisabled: options.thumbFillDisabled,
        stroke: options.thumbStroke,
        lineWidth: options.thumbLineWidth,
        centerLineStroke: options.thumbCenterLineStroke,
        tandem: options.tandem.createTandem( 'thumb' )
      } );

    // do this outside of options hash, so that it applied to both default and custom thumbs
    thumb.centerY = this.track.centerY;

    var buffer = new Rectangle( 0, 0, this.track.width + thumb.width, thumb.height, {
      fill: 'yellow',
      pickable: false
    } );
    buffer.center = this.track.center;

    // Rendering order
    this.addChild( buffer );
    this.addChild( this.track );
    this.addChild( thumb );
```

Follow-up question: will this break anything?  Are there any clients relying on this bug that will have to be fixed?  Should I commit this to master?

**Comment by pixelzoom** [comment]
Could AlignBox/AlignGroup be applied to this problem?

**Comment by jonathanolson** [comment]
Overriding localBounds OR using a Spacer would both be preferable to using a Rectangle that is transparent.

AlignBox/AlignGroup can't help predict the maximum bounds over all possible configurations of component-specific movement (e.g. knowing the min and max slider positions). It's not an alignment / sizing issue that would be recommended for AlignBox/AlignGroup.

**Comment by samreid** [comment]
OK I'll look into localBounds or spacer, thanks @jonathanolson!

**Comment by samreid** [comment]
In the above commit, I'm dilating the track localBounds.  Here's what I checked to make sure it seems OK:

1. It corrects https://github.com/phetsims/circuit-construction-kit-common/issues/253
2. It has no lint errors
3. The "Evaporation" slider in concentration looks identical after this change and still works properly.
4. The gravity and orbits sliders appear identical after this change, and appear to work properly.

@jonathanolson or @pixelzoom will you please review the change?  If all seems well, we can create a new issue regarding cleaning up workarounds (like setting VBox/HBox resize=false) that should no longer be necessary.

**Comment by pixelzoom** [comment]
No documentation in the code about why `track.localBounds` is being dilated? No reference to this issue?

**Comment by samreid** [comment]
Many thanks @pixelzoom, I added documentation in the preceding commit.

**Comment by pixelzoom** [comment]
I tested sliders in all of my sims, and removed `resize: false` workarounds as noted in above commits.

Hooke's Law sliders are currently broken (see https://github.com/phetsims/hookes-law/issues/45) but I suspect that's related to PropertySet conversion.

**Comment by samreid** [comment]
Thanks, I'll close the issue.
