### ISSUE TITLE
AccordionBox: option to turn off expand/collapse feature of title bar

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#283]
Clicking in the title bar of an AccordionBox is currently equivalent to clicking its expand/collapse button.  In unit-rates, there are some buttons that are a bit close to the title bar, for example:

![screenshot_137](https://cloud.githubusercontent.com/assets/3046552/22950220/1f863e92-f2c2-11e6-8626-84ac70379664.png)

It's a little too easy to accidentally collapse the AccordionBox by hitting the yellow edit button - I do it all the time.  So I'd like to turn this feature off for Unit Rates, via a new option.

**Comment by pixelzoom** [comment]
Here's the new option:

```js
titleBarExpandCollapse: true, // {boolean} clicking on the title bar expands/collapses the accordion box
```

Other options related to title bar have "titleBar" prefix, so this seemed like a reasonable name.

I'm using `titleBarExpandCollapse: false` in unit-rates.

**Comment by pixelzoom** [comment]
@jonathanolson randomly chosen to review:

```
> phet.joist.random.shuffle( ['JB','JO','MP','JG','DB','MK'] )[0]
"JO"
```

**Comment by jonathanolson** [comment]
Haven't worked with AccordionBox before, but the commit looks correct and fairly simple. It seems there's always an expand/collapse button, so turning off both expanding and collapsing for the title should be fine.

Closing.
