### ISSUE TITLE
overriding addListener in a button subclass doesn't apply to listeners added through options

### ISSUE THREAD

**Issue by jbphet** [phetsims/sun#284]
In https://github.com/phetsims/scenery-phet/issues/291, @jessegreenberg needs to wrap listeners for Reset All buttons inside another function to prevent a flood of voice notifications upon reset when a screen reader is being used.  Wrapping the listener has turned out to be a bit tricky because listeners that are passed in through the options are added directly to the list of listeners in `ButtonModel` whereas listeners added through the `addListener` method are forwarded to the model through `addListener` calls in the button inheritance hierarchy.  Since `ResetAllButton` is not a direct descendant of `ButtonModel`, this override can't be called by `ButtonModel` when it processes its options.

It would be possible to add code to the button hierarchy to solve this issue and make it so that listeners in the options hash are added through the `addListener` method in the button hierarchy, and the listener is then removed from the options has before it is passed to the button model's constructor.  This is a bit ugly, and would complicate the button code a bit, so I'd like to get input from the other developers as to whether this would be worthwhile, or whether this seems like it is such an unusual situation that handling the problem in the descendant class (as @jessegreenberg has done for `ResetAllButton`) is the way to go.

**Comment by jonathanolson** [comment]
This is probably like the 4th time I've thought about generalizing Node's pattern for more general use.

Node does this by forwarding any (legitimate) option to an ES5 getter (and typically to a function), so equivalently transforming:

- `var node = new Node( { opacity: 5 } )`
- to `var node = new Node(); node.opacity = 5;`
- to `var node = new Node(); node.setOpacity( 5 );` where overloading is supported.

Would that type of pattern be of use here?

**Comment by jessegreenberg** [comment]
I don't think that would solve this problem, the issue is that ```PushButtonModel``` adds ```options.listener``` without going through ```RoundPushButton.addListener()``` since all options in ```RoundPushButton``` are passed directly to ```PushButtonModel```.

**Comment by jessegreenberg** [comment]
Could this option be removed from PushButtonModel:
```js
listener: null, // {function} convenience for adding 1 listener, no args
```
so that clients must use addListener() in the button views to add a listener?  Button views could still support ```options.listener```.

**Comment by jbphet** [comment]
Discussed at dev meeting, decided that it would be better if the hierarchy handled the issue, and overriding `addListener` just worked. I'll implement this.

**Comment by pixelzoom** [comment]
@jbphet Why not just add all listeners via the same code path. I.e., add `options.listener` by calling `this.addListener`?

**Comment by jbphet** [comment]
Yes, that's the plan. Thanks for the ping, I'll do it on Friday.

**Comment by jbphet** [comment]
I committed a fix for this, but I had to duplicate the code in two places.  There is already an issue about how the button hierarchy leads to code duplication, see #133.  I'm going to look at refactoring the hierarchy in order to eliminate this duplication before saying that this has been fully addressed.

**Comment by jbphet** [comment]
It's been over three years and I haven't gotten to this.  It seems a bit pointless to leave it open longer when it hasn't really been a problem.  My hope is that when and if #133 gets addressed, this will too, but if it never does, we can probably live with that.  Closing.
