### ISSUE TITLE
HSlider clickXOffset is wrong if using thumbNode

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#288]
Currently most of the HSliders use the default thumb. But if you specify the thumbNode from options, there is a bug in the start function of the TandemSimpleDragHandler, see https://github.com/phetsims/resistance-in-a-wire/issues/85#issuecomment-299003588 for gifs of the problem, both in vertical and horizontal applications. Basically the first drag jumps up the slider about half the width of the thumbNode.x

Not sure who to assign this to. @samreid has some recent commits in HSlider.js, maybe we can work on it together sometime. Please reassign if there is a better person for the job.

**Comment by veillette** [comment]
Molecules-And-Light makes its own thumbNode but the slider behavior is fine. FYI, the thumb in Molecule and light is a scenery Path whereas the resistance-in-wire it's an Image. I don't know yet if this is relevant.

**Comment by zepumph** [comment]
@samreid and I worked through this problem, and found that  we need to use 'centerX' instead of 'x', because some thumb nodes don't have the same values for these, but the default one (used in most sims) does have the same value.

**Comment by zepumph** [comment]
@veillette, I actually found the same skipping problem in Molecules-and-light if I revert the line change I made for the bug fix.  Here is the thumbShape that is in MAL:
```js
    // draw the partial octagon shape of the slider.
    var thumbShape = new Shape();
    thumbShape.moveTo( 0, 0 ); // Top left corner of the thumb.
    thumbShape.horizontalLineTo( THUMB_SIZE.width * 0.75 );
    thumbShape.lineTo( THUMB_SIZE.width, THUMB_SIZE.height * 0.33 );
    thumbShape.verticalLineTo( THUMB_SIZE.height * 0.66 );
    thumbShape.lineTo( THUMB_SIZE.width * 0.75, THUMB_SIZE.height );
    thumbShape.horizontalLineTo( 0 );
    thumbShape.close();
```
The 'center' (0,0) is in the top left corner, this is why I was not surprised to see a jump in this as well. It is probably also worth noting that the amount of jump correlates to the width of the slider, so this jump is only a few pixels wide. This is bug that I even see on the production site, https://phet.colorado.edu/sims/html/molecules-and-light/latest/molecules-and-light_en.html, so I'm glad we are fixing it now.

**Comment by zepumph** [comment]
I tested all of the fuzzing for all sims (phet and phet-io brand), as well as looking at specific sims, both that implement their own thumbNode (MAL, RIAW, OM), and that use the default (ESPB, CV). All seems good. I also updated the documentation so that it is know that the thumbNode no longer has to have a center of 0,0. We also simplified HSliderThumb so that it doesn't need to center around 0,0. 

@samreid, since we already worked on this together, would you mind taking a look before we call this good.

**Comment by samreid** [comment]
The code changes look great.  In the above commit, I revised the documentation a bit.  I also tested Hooke's Law before/after and it looks pixel-perfect.  I noticed @pixelzoom is an author for HSlider, do you want to take a quick look before we close?
