### ISSUE TITLE
Centralize slider thumb design for PhET Look and Feel?

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#289]
From https://github.com/phetsims/sun/issues/288, it would make sense to change old sliders to what we now use in all sims. The default can be seen in color vision and energy skate park basics. Here are some pictures of old and random sliders (not sure the exact age of many of these, but @samreid said they were old). 

The general default, here seen in ESPB:
![image](https://cloud.githubusercontent.com/assets/6856943/25682264/c9a53b00-3014-11e7-9e85-eaa0c2a1c4cf.png)

FAMB:
![image](https://cloud.githubusercontent.com/assets/6856943/25682172/6de8c4f8-3014-11e7-8e48-5f0cfa019f0a.png)

MAL- although it is different, it seems to be specific to the design of the emissions emitter, so it should probably stay

OL:
![image](https://cloud.githubusercontent.com/assets/6856943/25682225/9d8e60a0-3014-11e7-8102-131f9a58e57f.png)

RIAW:
![image](https://cloud.githubusercontent.com/assets/6856943/25682285/dd704c9c-3014-11e7-9e42-4c0726c8bbd6.png)

There are probably more that I have not yet found. @ariel-phet what do you think about updating these old and disorganized slider designs with the current norm? @samreid changed it in RIAW as an example, and it looked like this (oooooo so modern):

![New RIAW](https://cloud.githubusercontent.com/assets/679486/25673986/8bdce692-2ff6-11e7-93fb-c77dfbbaec52.png)

**Comment by samreid** [comment]
I think it would be great to have a consistent look and feel for sliders across our simulations.  Other benefits of a shared implementation: less code to maintain, less places bugs can sneak in and (marginally) smaller downloads.

**Comment by ariel-phet** [comment]
@zepumph @samreid the sliders in Ohm's Law and RIAW can certainly be made to be consistent with other sims (however please give them a more "silver"/light gray appearance) to match better with the original look.

The slider thumb in MAL is quite specific, and so that should stay, although perhaps there is a way to use the general slider implementation but specify a different thumb?

The slider in FAMB has some specialized behavior (half of it disables when max speed is reached, and some customized snapping behavior and such), however the slider thumb can certainly be made consistent with all other sims (again would be good to retain the light blue color currently used)

**Comment by zepumph** [comment]
@ariel-phet please change priority if you feel differently.

**Comment by pixelzoom** [comment]
HSlider allows you to customize the thumb, see options.thumbNode.  I'm skeptical that we'll come to an agreement on 1 thumb to be used in all sims, or be able to convince designers to use a single thumb.

**Comment by pixelzoom** [comment]
FYI, the default HSlider thumb looks like this:

![screenshot_269](https://user-images.githubusercontent.com/3046552/26854989-f77ff566-4ad5-11e7-8528-0dd2e183fd28.png)

**Comment by zepumph** [comment]
> HSlider allows you to customize the thumb, see options.thumbNode. I'm skeptical that we'll come to an agreement on 1 thumb to be used in all sims, or be able to convince designers to use a single thumb.

I agree, I will just change the ones in RIAW and OL to spruce them up a bit. OL was done in https://github.com/phetsims/ohms-law/issues/53, and RIAW in phetsims/resistance-in-a-wire#88

Closing

**Comment by zepumph** [comment]
I removed the default thumbs RIAW now too.
