### ISSUE TITLE
Should UI components always declare their own Properties?

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#291]
From https://github.com/phetsims/sun/issues/274#issuecomment-307175326

We would like to investigate UI components creating their own Property instance so it can always be disposed when the UI component is disposed.  When a Property is passed in through an option, it will be *linked to* the UI Property rather than replacing it.

Assigning @jbphet since he was assigned in #274

**Comment by samreid** [comment]
@ariel-phet recommended @jbphet look into this when he look into sun in the next month or so.  But we should also consider other libs that may need this attention as well.

**Comment by jbphet** [comment]
@samreid - I think we decided that we need to support cases where UI components take in Properties created by the client as well as creating their own, and that correct disposal for both situations is being pursed under https://github.com/phetsims/sun/issues/121.  Does this issue need to remain open?

**Comment by samreid** [comment]
We are choosing between:

```js
// Option A: use the passed in option
function Checkbox( content, property, options ) {

  options = _.extend( {
    enabledProperty: null, // {BooleanProperty} initialized below if not provided
  }, options );

  // @public
  this.enabledProperty = options.enabledProperty || new BooleanProperty( true, {
    tandem: options.tandem.createTandem( 'enabledProperty' )
  } );

  this.disposeCheckBox = function() {
    if ( !options.enabledProperty ) {
      this.enabledProperty.dispose(); // Only dispose if we own it
    }
  };
}

// Option B: create an owned Property and wire it up
function Checkbox( content, property, options ) {

  options = _.extend( {
    enabledProperty: null, // {Property.<Boolean>} [enabledProperty] - optional
  }, options );

  // @public
  this.enabledProperty = new BooleanProperty( true, {
    tandem: options.tandem.createTandem( 'enabledProperty' )
  } );
  if ( options.enabledProperty ) {
    wirePropertiesTogether( this.options.enabledProperty, this.enabledProperty )
  }

  this.disposeCheckBox = function() {
    this.enabledProperty.dispose(); // We own this one, so we can always dispose it
  };
}
```

As far as I am aware, we haven't investigated Option B at all, but it simplifies disposal and may simplify PhET-iO APIs (since CheckBoxes would always have an enabledProperty with the same naming).  As far as I know, we haven't ruled out Option B and it would still be good to try it out.

@pixelzoom and @zepumph have been working on similar things lately, so I thought I'd cross assign them for comment.  If you have nothing to add or ask, you can unassign yourself.

**Comment by pixelzoom** [comment]
In option B, the owned Property should be public (and a tandem created?) only if options.enabledProperty was not provided. Otherwise you'll have 2 public Properties (and 2 tandems) that are controlling the enabled state.   

I'm also concerned about the complexity/confusion of option B.  It's fairly easy to determine whether `enabledProperty` was provided by the client, and dispose only if Checkbox owns it.  See https://github.com/phetsims/sun/commit/1c5ce3fa82fcef09c83586ceb4bc3f10a7f5624f.

**Comment by zepumph** [comment]
I agree that option A seems like a nice pattern. NOTE: That there needs to be an extra boolean in Option A to know if this type owns the Property, such that it knows whether or not to dispose it:

```js
    // @private {boolean} does this instance own enabledProperty?
    this.ownsEnabledProperty = !options.enabledProperty;
```

then in dispose:

```js
      if ( self.ownsEnabledProperty ) {

        // Checkbox owns enabledProperty, so dispose to release tandem and remove all listeners.
        self.enabledProperty.dispose();
      }
```

**Comment by jbphet** [comment]
In the version of `Checkbox.js` that is current as of this writing, option A is essentially used, and a local variable is set that tracks ownership with the following line of code:
```
    const ownsEnabledProperty = !options.enabledProperty;
```

There is other code that has been added to handle phet-io differences between passed-in versus self-created properties, but I think that is outside the scope of this discussion.

I think we have pretty much settled on option A.  @samreid - can we close this?  Do you think we should include a description of it in the "options" section of our pattern document?

**Comment by samreid** [comment]
Good idea @jbphet, @Denz1994 can you please review the usage of `options.enabledProperty` and `ownsEnabledProperty` in Checkbox.js and add corresponding documentation to phet-info/doc/phet-software-design-patterns.md in the options section?  After that, I believe this issue can be closed.

**Comment by samreid** [comment]
I added documentation in the design patterns doc, and I should also note that usage of `enabledProperty` significantly changed since we factored it out to scenery.  Closing.
