### ISSUE TITLE
Make sure Properties are disposed

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#292]
From
https://github.com/phetsims/sun/issues/274#issuecomment-307139130

> The only remaining work item on this is from comment #274 (comment) where it says, "[S]can through Property creation in common libs and make sure that Properties are disposed". I can do that tomorrow, Friday June 8 2017, since that is my common code day.

Perhaps we should complete #291 first because it may inform this issue.

**Comment by samreid** [comment]
@ariel-phet recommended @jbphet look into this when he look into sun in the next month or so.  But we should also consider other libs that may need this attention as well.

**Comment by jbphet** [comment]
This has been assigned to be for years, and has sat on the back burner for all of that time.  I'm going to make it my own "chip away", and will go through the following process, which isn't perfect, but better than nothing:

1. Search for all usages of `.link` and verify that there is either a corresponding `.unlink` or a `dispose` that would release any references (including dispose of a subclass of `Node`).
2. Repeat for `.lazyLink`.
3. Repeat for `.multilink`.

Note that I searched sun for `.linkAttribute` and didn't see any usages, so I don't need to look for any of those.

I'll track my progress in the details section below.

<details>

- 11/21/2022 - Worked up through `ComboBoxButton` for step 1 above.

</details>

**Comment by jbphet** [comment]
@samreid - Could you please do a quick review of https://github.com/phetsims/sun/commit/08202d21fe1aa7d32fb750673a73d8b19b408cce?  It's a change to add an unlink that I think was missing, and since it's in a heavily used piece of common code, I thought another dev should have a look.  Just leave the issue assigned to me when you're done and I'll continue chipping away at it.

**Comment by samreid** [comment]
That seems correct to me, thanks!

**Comment by jbphet** [comment]
The file `demoAlignGroup.ts` might leak memory, and I started looking at it, but I feel like it isn't worth the time since this isn't used in sims.

**Comment by jbphet** [comment]
Review and updates complete, closing.  See the timeline in the details section in [this comment above](https://github.com/phetsims/sun/issues/292#issuecomment-1322759744) for more information if needed.
