### ISSUE TITLE
tandem IDs for button fired emitters look a little odd

### ISSUE THREAD

**Issue by jbphet** [phetsims/sun#294]
Emitters were recently added to allow phet-io clients to see when the listeners for a button are about to be fired and then are done being fired.  I'm starting to use this functionality, and I noticed that the emitters are called `startedFiredEmitted` and `endedFiredEmitted`.  Since they represent emitters, I was a bit surprised that names weren't `startedFiredEmitter` and `endedFiredEmitter` or `startedFireEmitter` and `endedFireEmitter`.  Was this intentional, or was there a typo of some kind here?  If it *was* intentional, what was the rationale?

See commit 1f5c0553666ff43d22a9cf7ef29dcea614108400.

**Comment by zepumph** [comment]
Definitely a typo. Can I just fix this in master, or would you like this in maintenance releases for the recently published phet-io sims that are being used in sonification?

**Comment by zepumph** [comment]
assigning to @jbphet too, let me know if we need to do a maintenance release, or if it's good to close now.

**Comment by jbphet** [comment]
I think a maintenance release would be good.  I know it's a small thing, but I'm now using these IDs in the sonification wrapper, and they will break on the next release from master and we will have to remember why if we don't fix it now.  Better to get it taken care of.

**Comment by jbphet** [comment]
Back to @zepumph to do a maintenance release.

**Comment by zepumph** [comment]
@jbphet can you think of any other commits that should be added to these, while I'm doing it anyways?

**Comment by jbphet** [comment]
Yes, actually, there was a maintenance release for BASE where an issue about the positions of the charges on the wall was fixed.  Please work with him to get this fix in.  I'll add him to the list of assignees.

**Comment by zepumph** [comment]
I will watch https://github.com/phetsims/balloons-and-static-electricity/issues/273 for when the spot check QA task looks good.

**Comment by zepumph** [comment]
Maintenance releases are live:
* https://phet-io.colorado.edu/sims/john-travoltage/1.4.1-phetio/wrappers/index/
* https://phet-io.colorado.edu/sims/build-an-atom/1.5.3-phetio/wrappers/index/
* https://phet-io.colorado.edu/sims/balloons-and-static-electricity/1.3.1-phetio/wrappers/index/

After talking to @jessegreenberg I added commits from https://github.com/phetsims/balloons-and-static-electricity/issues/273 in the BASE Maintenance release as well. Closing

**Comment by jbphet** [comment]
Thanks @zepumph!
