### ISSUE TITLE
delete unused icons in FontAwesomeNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#295]
While adding the 'reply' icon for equality-explorer, I noticed that several of the icons in FontAwesomeNode appear to be unused.  Since these are included in every sim that uses FontAwesomeNode, we decided awhile back (see #15) that it's important to include only icons that are actually used. 

The unused icons and who added them:

ban_circle @samreid  
fullscreen @samreid 
keyboard @jessegreenberg 
reorder @samreid 

@jessegreenberg @samreid Can the above icons be deleted from FontAwesomeNode?

**Comment by jessegreenberg** [comment]
```keyboard``` is no longer being used and I removed it from FontAwesomeNode in the above commit.

**Comment by samreid** [comment]
I confirmed the icons are no longer used by manual search and aqua load only test, then I removed them in the above commit.  @pixelzoom anything else to do here?

**Comment by pixelzoom** [comment]
Done, closing.
