### ISSUE TITLE
Suspicious ComboBox spacing

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/sun#298]
pendulum-lab:
![pendulum-popup](https://user-images.githubusercontent.com/480878/27877796-43e38c06-6179-11e7-9ce0-7069b03b8a6d.PNG)

masses-and-springs:
![ms-popup](https://user-images.githubusercontent.com/480878/27877816-59d169e8-6179-11e7-89e5-0781cb90fe87.png)

Probably related to listYMargin, investigating.

**Comment by pixelzoom** [comment]
@samreid commented out buttonYMargin and listYMargin options in the client, and the problem went away.  I verified that commenting out both of these was required.

**Comment by jonathanolson** [comment]
Looks like the direct positioning of item nodes in the ComboBoxItemNode is likely to blame, as the ComboBoxItemNode for the ButtonNode wants to position it differently than the ComboBoxItemNodes for the listNode.

**Comment by jonathanolson** [comment]
Or possibly not, spoke too soon.

**Comment by jonathanolson** [comment]
Changes:

- Now always using different ComboBoxItemNodes for the ButtonNode, instead of using the first of listNodes (that was the main layout bug, where it repositioned the first item node).
- Fixed up disposal for handling the ComboBoxItemNodes for the ButtonNode (see https://github.com/phetsims/sun/issues/299).
- Did assorted other cleanup that was somewhat related.

Passed spot checks (pendulum lab, molarity), Aqua automated testing, phet-io spot checks (molarity with instance proxies, state mirroring, etc.).

@pixelzoom, would you like to review the changes?

**Comment by pixelzoom** [comment]
I skimmed the changes, didn't see anything amiss, looks good.   I also ran a few sims from master, compared to their published versions, and I didn't see any problems, they spacing in the combo boxes was unchanged.

Closing.
