### ISSUE TITLE
replace VerticalAquaRadioButtonGroup and VerticalCheckBoxGroup with layout managers

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#30]
Add layout managers, either in scenery, sun or scenery-phet, to make these groups go away.

Or clean up these groups, and generalize to one 'vertical group' that is independent of component type. There is duplicate code here.

**Comment by pixelzoom** [comment]
I have to say... This got even worse after it was instrumented for PhET-iO.  

For example, in VerticalCheckBoxGroup, the tandem for each check box is set like this:

```js
65  tandem: options.tandem.createTandem( items[ i ].tandemName || 'checkBox' )
```

If I had used this in BLL, the `tandemName` for each item is the same as the solution name.  So there would be no "CheckBox" in any of the tandem id for the check boxes. Whereas if I had created individual CheckBox instances, I would have given them tandem ids that have a "CheckBox" suffix (e.g. "showLinesCheckBox").

There's a similar problem in tandem ids for the AquaRadioButtons created by VerticalAquaRadioButtonGroup.

@samreid Do you agree that this is a little messed up?

**Comment by samreid** [comment]
I agree this is problematic.  I think we struggled with the same problem in ComboBox and settled on a similar strategy:

```js
itemNodeTandem = options.tandem.createTandem( itemNodeOptions.tandemName || 'comboBoxItemNode' );
```

Forces and Motion: Basics uses VerticalCheckBoxGroup like so:

```js
    this.verticalCheckBoxGroup = new VerticalCheckBoxGroup( [
      {
        content: new Text( sumOfForcesString, _.extend( { tandem: tandem.createTandem( 'showSumOfForcesTextNode' ) }, fontOptions ) ),
        property: model.showSumOfForcesProperty,
        tandemName: 'showSumOfForcesCheckBox'
      },
      {
        content: new Text( valuesString, _.extend( { tandem: tandem.createTandem( 'showValuesTextNode' ) }, fontOptions ) ),
        property: model.showValuesProperty,
        tandemName: 'showValuesCheckBox'
      },
      {
        content: showSpeedContent,
        property: model.showSpeedProperty,
        tandemName: 'showSpeedCheckBox'
      }
    ], {
      tandem: tandem.createTandem( 'verticalCheckBoxGroup' )
    } );
```

> If I had used this in BLL, the `tandemName` for each item is the same as the solution name. 

Perhaps we should document (and possibly have assertions?) that the item tandems should end in "CheckBox" for VCBG and "RadioButton" for VARBG?

**Comment by pixelzoom** [comment]
In ComboBox, it's the item tandem ids that are automatically created.  So we end up with ids like `solutionCheckBox.drinkMix`, which seems perfectly reasonable.

**Comment by samreid** [comment]
Why would it be reasonable to have `solutionComboBox.drinkMix` but not `solutionRadioButtonPanel.drinkMix`?

**Comment by pixelzoom** [comment]
It should be `solutionRadioButtonPanel.drinkMixRadioButton`.

**Comment by samreid** [comment]
I'm confused, we should chat!

**Comment by pixelzoom** [comment]
If you create you own CheckBox inside of a Panel, the id for the Panel would presumably be something like 'forcesControlPanel', and the CheckBox would be 'forcesControlPanel.showAppliedForceCheckBox, not `'forcesControlPanel.showAppliedForce`.

**Comment by samreid** [comment]
As pointed out in https://github.com/phetsims/sun/issues/30#issuecomment-297723334 the tandems end in `showSpeedCheckBox` not `showSpeed`.  That is as-desired, right?  So what is the problem?

**Comment by pixelzoom** [comment]
OK, I see... The client is responsible for the "*CheckBox" name.
