### ISSUE TITLE
HSlider: add option to vertically offset thumb

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#301]
HSlider vertically centers its thumb in the track, for example in sun demo:

![screenshot_311](https://user-images.githubusercontent.com/3046552/28079874-334d0fcc-6627-11e7-932e-7f422a6f5d23.png)

If you need to provide a custom thumb, this can be problematic.  For example, in Molecule Polarity we are discussing using this custom thumb (see https://github.com/phetsims/molecule-polarity/issues/39), which gets vertically centered in the track:

![screenshot_310](https://user-images.githubusercontent.com/3046552/28079895-44f30920-6627-11e7-8186-7c2e9bbb9e73.png)

What we'd like there is something like this, where the thumb is shifted down a bit:

![screenshot_312](https://user-images.githubusercontent.com/3046552/28079932-653a0c1a-6627-11e7-83b3-b1431624e6be.png)

I'm going to add option `thumbYOffset:0` to support this.  The center of the thumb will be offset by this amount from the center of the track.

**Comment by pixelzoom** [comment]
> _.shuffle( [ 'JB', 'JG', 'JO', 'SR' ] )[0]
"JO"

@jonathanolson please review.

**Comment by jonathanolson** [comment]
Looks good to me.
