### ISSUE TITLE
HSliderTrack: add cornerRadius option

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#302]
Add option `cornerRadius:0` to HSliderTrack.
Propagate through HSlider via option `trackCornerRadius:0`.  

This is needed to reproduce this look in Molarity, see https://github.com/phetsims/molarity/issues/40:

![screenshot_316](https://user-images.githubusercontent.com/3046552/28226575-e3fff50a-6893-11e7-9645-15ae1dc7ecf5.png)

**Comment by pixelzoom** [comment]
```
> _.shuffle( [ 'JB', 'JG', 'JO', 'SR' ] )[0]
"JO"
```

@jonathanolson please review.

**Comment by jonathanolson** [comment]
Your change looks good. Diff highlighted the line that got a comma added:
```js
  ineWidth: options.lineWidth,
```
Since this has been broken before your changes, I'm not sure if "correcting" it to `lineWidth` would break usages?

**Comment by jonathanolson** [comment]
(Probably fine to close this issue and create an issue for the `ineWidth`?)

**Comment by pixelzoom** [comment]
I'll create a new issue for `ineWidth`.
