### ISSUE TITLE
[branch] accordion-resize

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/sun#305]
For https://github.com/phetsims/sun/issues/304, changes may be significant.

**Comment by jonathanolson** [comment]
Branch removed, merged to master.

**Comment by jbphet** [comment]
Reopening.  This branch was restored during an effort to recover some branches that were accidentally deleted.  This one had been _intentionally_ deleted, and now needs to be re-deleted.  See https://github.com/phetsims/special-ops/issues/198.

**Comment by jbphet** [comment]
Re-deletion complete.  Closing.
