### ISSUE TITLE
Improve documentation in HSliderTrack

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/sun#308]
In slack, there were some questions about why HSliderTrack ```enabledTrack``` and ```disabledTrack``` are layered, and why both are visible when enabled.  There is some documentation at the top of the file, but it could be improved.

**Comment by jessegreenberg** [comment]
Tried to clarify some things, @jonathanolson since you noticed that it wasn't clear can you please review?

**Comment by jonathanolson** [comment]
Looks great, thanks!
