### ISSUE TITLE
branch: key-events-in-phet-io

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#309]
To support https://github.com/phetsims/phet-io/issues/1198

**Comment by jbphet** [comment]
I looked at this branch while working on https://github.com/phetsims/special-ops/issues/198.  It has two commits that aren't on master, and those commits are coming up on 4 years old.  @samreid - can we delete the branch and close this issue?

**Comment by zepumph** [comment]
Yes thanks

**Comment by samreid** [comment]
I noticed this issue was closed but the branch hasn't been deleted.  I'll delete the branch.
