### ISSUE TITLE
branch: ama/dispose

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#311]
Looks like this undocumented branch was created by @andrewadare on 7/7/2016, with one commit related to https://github.com/phetsims/sun/issues/212.  

https://github.com/phetsims/sun/issues/212#issuecomment-258960706 seems relevant:
> @pixelzoom I pushed revisions to Panel.js on the ama/dispose branch in 05d99f6. Both Rutherford and MOTHA work for me without problems in local testing.
> 
> In 7754d0a, my introduction of `this.disposePanel()` as a delegate for dispose() causes problems, even if the body of the function is completely empty. So I followed the pattern in CheckBox, which amounts to attaching all needed items to `this`. I don't like that very much, because it makes them public.

Based on the comments that appear after the above comment, it seems like the work in this branch is a bit of a dead end, and should likely be deleted. 

@samreid any recollections?

**Comment by samreid** [comment]
I reviewed the branch and it seems it can be deleted now, I'll do so.

**Comment by samreid** [comment]
Branch is gone, closing.

**Comment by jbphet** [comment]
Reopening.  This branch was restored during an effort to recover some branches that were accidentally deleted.  This one had been _intentionally_ deleted, and now needs to be re-deleted.  See https://github.com/phetsims/special-ops/issues/198.

**Comment by jbphet** [comment]
Re-deletion complete.  Closing.
