### ISSUE TITLE
Panel(resize:false) alignment incorrect when content size changes

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#313]
For Circuit Construction Kit: DC we would like the panel width to be a fixed size (for the max value of 10.0 ohms), but we would like all text to be right-aligned.  Putting resize:false prevents the background from resizing but it also prevents the text from remaining aligned.  Reference issue is https://github.com/phetsims/circuit-construction-kit-common/issues/396

How should we address this?

**Comment by jonathanolson** [comment]
The more I think about it, `align` isn't a supported feature when `resize:false` (if you want it to maintain alignment when the content changes bounds). It's more of an "align on startup".

**Comment by samreid** [comment]
We decided to use Rectangle instead of Panel for cases like this, see the CCK issue mentioned above, closing.
