### ISSUE TITLE
Why do TPanel and TVerticalCheckBoxGroup exist?

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#315]
I see that these two TTypes don't add anything to the type. Nothing is added to the event stream, and no methods are exposed to the api. @samreid do you think we should delete these and just use TNode?

**Comment by samreid** [comment]
I think they should be deleted and use TNode instead.

**Comment by samreid** [comment]
Reopened after accidental close, @zepumph can you please remove those types and replace usages with TNode?

**Comment by zepumph** [comment]
These have been deleted and TNode is being used by default.

Fuzz Tests are passing. Closing
