### ISSUE TITLE
add option for aligning icons in ToggleNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#319]
ToggleNode currently assumes that you want the icons center aligned:

```js
33 // align centers of the nodes, see https://github.com/phetsims/sun/issues/272
34 falseNode.center = trueNode.center;
```

In equality-explorer, I have 2 icons that most definitely cannot be center aligned.  They are:

![lock-artwork](https://user-images.githubusercontent.com/3046552/30987426-34a2999e-a454-11e7-83f3-16f403a0c8cc.png)

So that I can use ToggleNode for this application, I'm going to add an option to specify the strategy for aligning icons.  That strategy will default to the current behavior (centered).

**Comment by pixelzoom** [comment]
Done. Tested in BASE. Could not test in FAMB because it currently fails at startup in requirejs mode ("this.phetioArgumentTypes[0].toStateObject is not a function").  

Assigning to @zepumph to address FAMB, or assign to someone who should fix it.  Then feel free to close.

**Comment by zepumph** [comment]
https://github.com/phetsims/phet-io/issues/1223 addressed the concern yesterday. I only see SoundToggleButton being used in FAMB, and it runs without error and looks well aligned. Closing
