### ISSUE TITLE
NumberControl and HSlider vs enabledProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#322]
Discovered in https://github.com/phetsims/axon/issues/140

NumberControl passes `enabledProperty` to its `HSlider`. During `dispose`, the `HSlider` disposes the `enabledProperty` and hence when we try to remove a listener in `NumberControl`, there is an axon assertion failure since `enabledProperty` has no listeners.

Is the correct solution to this to: 

(a) have HSlider keep track of whether it created its own enabledProperty or had one passed in, and only dispose it if it is using the one it created itself?
(b) remove `self.enabledProperty.unlink( enabledObserver );` from NumberControl's dispose implementation?
(c) all of the above
(d) none of the above

**Comment by jonathanolson** [comment]
Presumably just (a). Disposing a Property that you don't own (was passed in) should be a general no-no.

**Comment by samreid** [comment]
Thanks @jonathanolson, I'll investigate that.

**Comment by samreid** [comment]
I tracked 2 optional properties in HSlider and only dispose them if they are "owned". Fuzz test is passing now with the axon branch, closing.
