### ISSUE TITLE
HSlider correctRounding

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#327]
Function `correctRounding` is defined inside the `HSlider` constructor, so every instance has a copy of this function.  If you add one more parameter (the value of valueProperty.value), then this function could be moved outside the constructor (private to the file, not in the `inherit` call), and 1 copy of the function will be shared by all instances.

Recommended signature:

`function correctRounding( newValue, currentValue, stepSize )`

Example usage on line 375:

`newValue = correctRounding( newValue, valueProperty.get(), stepSize )`

**Comment by pixelzoom** [comment]
Btw... Private functions are typically located after the `sun.register` call and before the `inherit` call.

**Comment by jessegreenberg** [comment]
Thanks @pixelzoom, I changed the signature to what you recommended in the ticket. I also moved the function out of constructor so it is shared, and moved it after sun.register call. But for #326 it is no longer in HSlider and in a trait called AccessibleSlider. AccessibleSlider is going to be reviewed in that issue. Closing this one.
