### ISSUE TITLE
Should be able to pass boxScale option through VerticalCheckBoxGroup to CheckBox

### ISSUE THREAD

**Issue by jbphet** [phetsims/sun#33]
CheckBox has an option 'boxScale' that allows tweaking of the size of the check box with relation to the textual label.  That option isn't passed through VerticalCheckBoxGroup, and a request has been logged on the BAA sim that could be easily fixed if this option were available.  See https://github.com/phetsims/build-an-atom/issues/70.

**Comment by SaurabhTotey** [comment]
I am closing this issue because, looking at VerticalCheckBoxGroup, it seems like there is an option called `checkboxOptions` which, as its name would suggest, gets passed down to its children CheckBoxes. As such, any option for CheckBox can be passed in from VerticalCheckBoxGroup.
