### ISSUE TITLE
Options are doubly applied to HSlider

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#330]
Discovered while @pixelzoom and I were working on https://github.com/phetsims/tandem/issues/44

I also tried this harness to check if scales get applied twice:

```js
    var x = new Rectangle(0,0,100,100,{fill:'red'});
    this.addChild(x);

    var x = new Rectangle(0,0,100,100,{top: 150,fill:'red',scale:2});
    this.addChild(x);

    x = new HSlider(new Property(0),{min:0,max:100},{top:50});
    this.addChild(x);

    x = new HSlider(new Property(0),{min:0,max:100},{top: 200,scale:2});
    this.addChild(x);
```

It showed the rectangle getting scaled correctly, and the slider getting scaled by an extra factor:

![image](https://user-images.githubusercontent.com/679486/33970587-1045daf2-e031-11e7-84fb-1c54713b9fba.png)

@jessegreenberg can you please take a look?

**Comment by samreid** [comment]
Proposed fix is above, it shows like this in my harness:

![image](https://user-images.githubusercontent.com/679486/33970757-10bc9100-e032-11e7-986a-e4aa23ee058b.png)

And it fixes the IOObject problem too.  Ready for @jessegreenberg review.

**Comment by jessegreenberg** [comment]
Sorry about that @samreid, this change looks great and fixes the problem. Thanks!
