### ISSUE TITLE
VerticalCheckBoxGroup uses an odd loop

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#332]
VerticalCheckBox has a for loop combined with an IIFE which should be simplified.  Discovered in https://github.com/phetsims/phet-io/issues/1298

**Comment by samreid** [comment]
Fixed above and tested by launching Gravity Force Lab: Basics.  @jessegreenberg can you please review this before GFLB goes to production?

**Comment by jessegreenberg** [comment]
Nice improvement @samreid, thanks. Looks good to me and I spot checked a number of sims that use VerticalCheckBoxGroup.
