### ISSUE TITLE
branch: molarity-a11yComboBox

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/sun#334]
For #333, a11y will be added to Combobox.js in a branch because there are still a number of questions about the a11y design for this UI component. one-off version will be out of molarity.

**Comment by jessegreenberg** [comment]
@zepumph with work on this continuing in #314 is it OK if this branch is deleted now?

**Comment by zepumph** [comment]
That sounds great thanks!

**Comment by zepumph** [comment]
Adding this to my list to, whoever gets to it first.

**Comment by zepumph** [comment]
(actually I'll just do it)

**Comment by jbphet** [comment]
Reopening.  This branch was restored during an effort to recover some branches that were accidentally deleted.  This one had been _intentionally_ deleted, and now needs to be re-deleted.  See https://github.com/phetsims/special-ops/issues/198.

**Comment by jbphet** [comment]
Re-deletion complete.  Closing.
