### ISSUE TITLE
We should use FireListener instead of SUN/buttons/ButtonListener

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#336]
SUN/buttons/ButtonListener is used in only 5 spots.  May be a good candidate to try SCENERY/FireListener instead.

Over to @ariel-phet for triage/priority/delegation.

**Comment by jonathanolson** [comment]
Handled this as part of the sun "new scenery listener" integration. @samreid can you review the changes to the phet-io event stream for the buttons?

**Comment by samreid** [comment]
I'm seeing new aqua fuzz issues (phet-io) related to `pressListener`.  Perhaps we need to dispose?  I'm looking into it:

```
build-an-atom
Uncaught Error: Assertion failed: Cannot register two different instances to the same id: buildAnAtom.gameScreen.view.challenges_0View.schematicToElementChallengeView.checkAnswerButton.pressListener
Error: Assertion failed: Cannot register two different instances to the same id: buildAnAtom.gameScreen.view.challenges_0View.schematicToElementChallengeView.checkAnswerButton.pressListener
    at window.assertions.assertFunction (http://localhost/assert/js/assert.js:22:13)
    at Phetio.addInstance (http://localhost/phet-io/js/phetio.js?bust=1520274077411:530:19)
    at Object.addInstance (http://localhost/phet-io/js/phetio.js?bust=1520274077411:655:14)
    at Tandem.addInstance (http://localhost/tandem/js/Tandem.js?bust=1520274077411:134:36)
    at PressListener.initializePhetioObject (http://localhost/tandem/js/PhetioObject.js?bust=1520274077411:143:19)
    at PressListener.PhetioObject [as constructor] (http://localhost/tandem/js/PhetioObject.js?bust=1520274077411:75:12)
    at new PressListener (http://localhost/scenery/js/listeners/PressListener.js?bust=1520274077411:112:18)
    at TextPushButton.RectangularButtonView [as constructor] (http://localhost/sun/js/buttons/RectangularButtonView.js?bust=1520274077411:99:28)
    at TextPushButton.RectangularPushButton [as constructor] (http://localhost/sun/js/buttons/RectangularPushButton.js?bust=1520274077411:51:27)
    at new TextPushButton (http://localhost/sun/js/buttons/TextPushButton.js?bust=1520274077411:41:27)
energy-skate-park-basics
Uncaught Error: Assertion failed: Cannot register two different instances to the same id: energySkateParkBasics.playgroundScreen.view.trackNode_13.controlPointNode_2.controlPointUI.deleteButton.pressListener
Error: Assertion failed: Cannot register two different instances to the same id: energySkateParkBasics.playgroundScreen.view.trackNode_13.controlPointNode_2.controlPointUI.deleteButton.pressListener
    at window.assertions.assertFunction (http://localhost/assert/js/assert.js:22:13)
    at Phetio.addInstance (http://localhost/phet-io/js/phetio.js?bust=1520274143058:530:19)
    at Object.addInstance (http://localhost/phet-io/js/phetio.js?bust=1520274143058:655:14)
    at Tandem.addInstance (http://localhost/tandem/js/Tandem.js?bust=1520274143058:134:36)
    at PressListener.initializePhetioObject (http://localhost/tandem/js/PhetioObject.js?bust=1520274143058:143:19)
    at PressListener.PhetioObject [as constructor] (http://localhost/tandem/js/PhetioObject.js?bust=1520274143058:75:12)
    at new PressListener (http://localhost/scenery/js/listeners/PressListener.js?bust=1520274143058:112:18)
    at RoundPushButton.RoundButtonView [as constructor] (http://localhost/sun/js/buttons/RoundButtonView.js?bust=1520274143058:91:28)
    at new RoundPushButton (http://localhost/sun/js/buttons/RoundPushButton.js?bust=1520274143058:50:21)
    at new ControlPointUI (http://localhost/energy-skate-park-basics/js/energy-skate-park-basics/view/ControlPointUI.js?bust=1520274143058:90:24)
```

**Comment by samreid** [comment]
See also related issue https://github.com/phetsims/scenery/issues/744

**Comment by samreid** [comment]
Faraday's Law now has 5 instrumented `pressListener` instances and the data stream reads like:

```
2 faradaysLaw.faradaysLawScreen.view.resetAllButton.pressListener press {"x":1289.633056640625,"y":782.843994140625}
3 faradaysLaw.faradaysLawScreen.view.resetAllButton.pressListener release
  4 faradaysLaw.faradaysLawScreen.view.resetAllButton.isFiringProperty changed {"oldValue":false,"newValue":true}
    5 faradaysLaw.faradaysLawScreen.view.resetAllButton fired
      6 faradaysLaw.faradaysLawScreen.view.resetAllButton.isFiringProperty changed {"oldValue":true,"newValue":false}
```

It seems like this is exposing an implementation detail to the PhET-iO API.  Perhaps we should use the `phetioEventSource` paradigm to collapse the press listener into the button that uses it?  Or is the PressListener a good level of granularity for the PhET-iO API, and we should make sure it is well documented and keep it?  @zepumph what do you think?

**Comment by zepumph** [comment]
I agree that the pressListener subComponent adds nothing substantial to the API, and I think clients would be happier to see that the parent button is triggering the event.

**Comment by samreid** [comment]
I'm running into a problem: when a Node gets a PressListener inputListener, how can we indicate that it is OK for that Node to trigger the PressListener events (without having to make a custom SubNodeIO type each time)?

I considered eliminating events declarations from IO types, but that seems an important part of the API.

I considered making all Nodes able to emit `press`, `release`, `drag` but that would be confusing for nodes that never emit those events.

We could add a PressListenerNodeIO class which extends NodeIO but adds press/drag/release?  Then those node types would specify `phetioType: PressListenerNodeIO`?

@zepumph does that latter option sound reasonable?

**Comment by samreid** [comment]
@zepumph and I agreed to investigate the latter strategy--it adds even more complexity to the instrumentation process and sim side, but helps us get to our API-side goal.

**Comment by jonathanolson** [comment]
> @zepumph and I agreed to investigate the latter strategy--it adds even more complexity to the instrumentation process and sim side, but helps us get to our API-side goal.

Would you also have DragListenerNodeIO and FireListenerNodeIO, since DragListener and FireListener extend PressListener?

How do you handle nodes that have a DragListener and a FireListener both added to it? (Thus the advantage of having tandems for individual listeners). I've had similar things done in the past where two listeners were the best implementation choice.

How would using something like PressListenerNodeIO work when you need to add a PressListener or listener subtype to something that already has a custom NodeIO phetioType subtype? (e.g. FaucetNode has FaucetNodeIO, Text has TextIO). Presumably we would not want PressListenerTextIO?

**Comment by samreid** [comment]
Great points @jonathanolson--I'm thinking we should look at standardizing the `pressListener` as part of the PhET-iO API, making sure we are confident about the name/events and trying to keep it stable as a public feature (rather than treating like an implementation detail).

From MVC pattern, it makes sense that Controller events come from something other than the View, and that seems fair enough to capture in the public PhET-iO API.

@zepumph thoughts?

**Comment by zepumph** [comment]
I'm convinced that we should create and keep PressListenerIOs in the phet-io api. I would just want to do two things before proceeding:

1. Bring this up in a design meeting (or something like that) to double check with @kathy-phet and @ariel-phet that this aligns with the features that make sense for a stable faradays-law (since that what we are working on now) api. It may also be good to show them what something like FAMB looks like with all of these PressListenerIOs in the studio.
2. Check with @jonathanolson that these controllers are here to stay and the naming/etc is stable.

**Comment by samreid** [comment]
Another issue for discussion: PressListener also signifies drag events.  So now it is possible (for example), to see in the data stream if the user tried to drag a button:

![image](https://user-images.githubusercontent.com/679486/37297728-fa4a4186-25e3-11e8-90d5-8dc359a0474a.png)

This seems OK to me but I wanted to raise it as a difference from the previous version.

**Comment by samreid** [comment]
Forces and Motion: Basics now has 1155 instrumented instances, 33 of which are PressListeners (presumably corresponding to the 33 instrumented buttons).

**Comment by samreid** [comment]
> Check with @jonathanolson that these controllers are here to stay and the naming/etc is stable.

Neither of us are confident that the names are stable.

**Comment by samreid** [comment]
I slacked @ariel-phet:

> can we schedule time for a Faraday’s Law PhET-iO Design meeting?  We can disuss issues like https://github.com/phetsims/scenery/issues/711, https://github.com/phetsims/sun/issues/336 and look through and make sure it is ready for stable PhET-iO republication.

**Comment by zepumph** [comment]
This issue is old, but looks like it is important to FL stable release. Marking as such.

**Comment by zepumph** [comment]
For all of summer @samreid and I have been working on phetsims/faradays-law#107 under the understanding that instrumenting pieces of new scenery input listeners is a good thing. We now use an emitter pattern, such that the PressListener isn't instrumented as type PressListenerIO, but instead the tandem is still `Tandem.required`, and it is passed to instrumented emitters that emit the appropriate events to the data stream, i.e. `pressedEmitter` instance emits the `emitted` event.

@samreid I'm not sure what is left in this issue, as ButtonModel runs on PressListener. Furthermore, it looks like sun's ButtonListener is no longer around (there is a ButtonListener in scenery though).

Is there anything else to do?

**Comment by samreid** [comment]
Thanks, we have made good progress with DragListener and PressListener, and can add other features to FireListener if/when necessary.  Closing.
