### ISSUE TITLE
snapValue should be moved out of HSlider

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#337]
HSlider supports a feature called `snapValue` which is only leveraged by Forces and Motion: Basics and HeaterCoolerNode.  This is something that should be handled in the simulation, not in the common code.  Can it be easily moved?

@samreid and @pixelzoom are still discussing this.

**Comment by samreid** [comment]
Maybe snapValue should just be renamed “clearValueOnRelease” and kept in HSlider? (edited)

**Comment by samreid** [comment]
Chris Malley [9:56 PM]
I don’t see the point in having `snapValue` (whatever the name) in HSlider.  Trivial to handle in `options.endDrag`.

**Comment by samreid** [comment]
@ariel-phet is this something @jessegreenberg can look into?  He is familiar with Forces and Motion: Basics and HSlider.

**Comment by ariel-phet** [comment]
@samreid yes, that seems appropriate

**Comment by ariel-phet** [comment]
@jessegreenberg mind taking a look at this. Feel free to mark for dev meeting or discuss wtih @jbphet since he worked on the heat bucket.

**Comment by jessegreenberg** [comment]
I actually also worked on HeaterCoolerNode so it makes sense for me to work on this.

**Comment by jessegreenberg** [comment]
This was done in the above commits, HeaterCoolerNode and forces-and-motion-basics use endDrag now instead. Was a straight forward change but Ill let @samreid review if he wishes since this is a common code component.

**Comment by samreid** [comment]
The change set in HSlider looks great.  Runtime behavior in Forces and Motion: Basics looks great.  Code change in Forces and Motion: Basics looks great.  I didn't look at HeaterCoolerNode.  Nice work @jessegreenberg, closing.
