### ISSUE TITLE
Are keydown/keyup callbacks on input listeners still used?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/sun#338]
I saw some in ButtonListener (in sun), but I believe the a11y system now uses different things. I couldn't find a case where these would be called from in Input, and I believe we removed the scenery "key" events fully.

Can these be removed?

**Comment by jessegreenberg** [comment]
@jonathanolson yes, can definitely be removed. It looks like sun/ButtonListener was already deleted so closing this issue.
