### ISSUE TITLE
create a version of RectanglePushButton that can has pseudo-3D look

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#34]
... to support vegas.LevelStartButton.  Run BAA game to see how this looks.

**Comment by pixelzoom** [comment]
LevelStartButton was replaced by LevelSelectionButton, which you can see in the Game screen of RPAL (screenshot below). The buttons have a pseudo-3D look.  So I'm going to close this. @samreid if this is not what you had in mind, please reopen and elaborate.

![screenshot_13](https://cloud.githubusercontent.com/assets/3046552/7359079/c18435d2-ecf7-11e4-9e49-c838ab5e527b.png)

**Comment by samreid** [comment]
Seems good, thanks.
