### ISSUE TITLE
PushButtonModel should use Emitter

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#340]
While @jonathanolson and I were looking at https://github.com/phetsims/sun/issues/336 and the API for pressListener/dragListener, we noticed that PushButtonModel has its own Emitter-like implementation.  Perhaps we could use Emitter there?  It would also be possible to put the Emitter on the PhET-iO API, so it would be easy to listen for when the button is pressed (instead of a proliferation of `addListener` methods in IO types).

**Comment by samreid** [comment]
I've converted PushButtonModel to use Emitter, and there were two logic changes:

1. PushButtonModel previously silently ignored requests to add the same listener twice, Emitter will throw that as an error
2. PushButtonModel previously silently ignored requests to remove a non-existent listener, Emitter will throw that as an error.

I'm partway through aqua tests and haven't seen any problem come up from Emitter in practice.

**Comment by samreid** [comment]
@zepumph can you please review the change above and discuss using the Emitter as the PhET-iO API (instead of PushButtonIO.addListener)?

**Comment by zepumph** [comment]
The change looks nice, good simplification.

For PhET-iO, I want to make sure that I understand fully. Currently the data stream looks like a "fired" event from the button, but you are proposing changing that to an "emited" event from the button's `firedEmitter`. Haven't we been down this road before? Am I not understanding this correctly?

**Comment by samreid** [comment]
We flip-flopped with respect to `pressListener`, I was wondering if the reasons we went with `pressListener` apply in this case too.

**Comment by zepumph** [comment]
I don't feel strongly enough to warrant the cost of making the change. Is the main/only thought that each TypeIO that uses this model type will need to have an 'addListener' method?

**Comment by samreid** [comment]
The main reasoning is that now we have two ways of doing the same thing.  If the button is powered by an Emitter and Emitters are normally how events are emitted from a PhET-iO simulation, it seems reasonable that the PushButtonModel emitter would take care of it.  So the proposal is that we would get rid of this code marked with TODOs:

```js
      this.phetioEventSource && this.phetioEventSource.startEvent( 'user', 'fired' );  // TODO: move this into the emitter?
      this.emitter.emit();
      this.isFiringProperty.value = false;
      this.phetioEventSource && this.phetioEventSource.endEvent(); // TODO: move this to the emitter
```

and instead instrument the emitter.

> I don't feel strongly enough to warrant the cost of making the change. 

Do you mean that this will be a breaking API change and we will need to update wrappers, or more of the cost of the internal change?

**Comment by zepumph** [comment]
@samreid does this issue seem like it is blocking stable phet-io of FL?

**Comment by samreid** [comment]
> I thought we have already been down this road, and we decided that it was weird if the component wasn't the thing sending out the "fire" event, and instead it was coming from the component's "fireEmitter"

I don't recall what issue it was, but I think we ultimately concluded that it was acceptable to have a nested emitter for events (even though it is clunky in the API, it makes life very easy on the implementation/maintenance side).

I think as long as we use Emitter consistently (using it for many emitter-type events instead of inlining some), it will be OK.  

This issue pertains to stability for Faraday's Law since it affects the tandems.  I'll work on it now and send it back to you for review.

**Comment by samreid** [comment]
After the change, the data stream looks like this:

![image](https://user-images.githubusercontent.com/679486/40811280-d5265856-64ed-11e8-998e-3bd29c62f208.png)

Furthermore, this will help us to move away from the `phetioEventSource` anti-pattern.

**Comment by samreid** [comment]
@zepumph can you please review the proposed change set (pushed above)?  If it seems OK, reassign to me and I'll apply this pattern to the other places we are using `phetioEventSource`.

**Comment by zepumph** [comment]
>Furthermore, this will help us to move away from the phetioEventSource anti-pattern.

That sounds really nice.

I'm convinced, and the implementation looks really nice. Thanks! What are the next steps? I see 43 usages of `phetioEventsSource` in 11 common code files. Should we do this for all? New issue?

**Comment by samreid** [comment]
I created issue #365, one for each day of the year.  Closing and will continue there.

**Comment by samreid** [comment]
Sorry, false alarm.  Due to implementation constraints in the Round/Rectangular buttons of several types, we should use the `phetioEventSource` pattern.  I've re-applied the pattern and cleaned it up.  Committing shortly.

**Comment by samreid** [comment]
> (instead of a proliferation of addListener methods in IO types).

Typically the listener can be added on the underlying property.

**Comment by pixelzoom** [comment]
I reported on Slack:
In EqEx fuzz testing, I’m seeing an occasional assertion failure in PushButtonModel, line 143, “Cannot fire when already firing”.  PushButtonModel was last changed by @samreid for https://github.com/phetsims/sun/issues/340.  EqEx is not instrumented for PhET-iO.

**Comment by pixelzoom** [comment]
Re https://github.com/phetsims/sun/issues/340#issuecomment-394494633... I haven’t seen this in CT, and it didn’t occur again in 3+ continuous hours of EqEx fuzz testing that I did last night.  So it’s probably something that is highly improbable.  So if you're confident that changes for this issue are unrelated, then feel free to close.

**Comment by pixelzoom** [comment]
@samreid This assertion failure appears in CT yesterday (6/18/2018, 10:24:42 PM) for equality-explorer-two-variables.  First time I've seen it in CT.   So there is a problem somewhere, but (so far) rarely encountered in CT.

equality-explorer-two-variables : fuzz : require.js : run
Uncaught Error: Assertion failed: Cannot fire when already firing
Error: Assertion failed: Cannot fire when already firing
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1529382282567/assert/js/assert.js:22:13)
    at PushButtonModel.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1529382282567/sun/js/buttons/PushButtonModel.js?bust=1529403717555:143:17)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1529382282567/sun/js/buttons/PushButtonModel.js?bust=1529403717555:83:16)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1529382282567/axon/js/Emitter.js?bust=1529403717555:180:49)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1529382282567/axon/js/Property.js?bust=1529403717555:282:29)
    at Property._setAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1529382282567/axon/js/Property.js?bust=1529403717555:269:14)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1529382282567/axon/js/Property.js?bust=1529403717555:216:16)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1529382282567/axon/js/Property.js?bust=1529403717555:311:36)
    at PressListener.release (https://bayes.colorado.edu/continuous-testing/snapshot-1529382282567/scenery/js/listeners/PressListener.js?bust=1529403717555:460:36)
    at Object.up (https://bayes.colorado.edu/continuous-testing/snapshot-1529382282567/scenery/js/listeners/PressListener.js?bust=1529403717555:195:14)
Approximately 6/18/2018, 10:24:42 PM

**Comment by zepumph** [comment]
@samreid what is the status of this issue. I don't see any commits fixing this error, but I don't see this error in CT anymore.

**Comment by zepumph** [comment]
Oops, assigned the wrong person.

**Comment by samreid** [comment]
I'm very confused.  It seems like https://github.com/phetsims/sun/issues/340#issuecomment-393756250 contradicts https://github.com/phetsims/axon/issues/180

Assigning for discussion tomorrow.

**Comment by samreid** [comment]
@zepumph and I focused on this, and got the button model types to use Emitter.  This means the following:

* They have uniform API for phet-io
* You can subscribe to events from them in phet-io
* They appear in the data stream
* You can trigger the buttons to fire by firing the emitter

Outstanding issues are mentioned above, closing this one.
