### ISSUE TITLE
Reduce the radius of AquaRadioButton

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#341]
From slack:

Ariel Paul [10:14 AM]
Hey Sam, why are radio buttons so big by default?
We have a general "rule of thumb" these days to make the radio button about the same radius as the first uppercase letter of its label
It seems we are always tweaking this size, maybe we should improve the default?

Sam Reid [10:16 AM]
Are you talking about the “Aqua” style radio buttons with circles and dots?

Ariel Paul [10:16 AM]
Yes

Sam Reid [10:16 AM]
Let me take a look

Ariel Paul [10:16 AM]
Same for slider thumbs in H-slider. I assume you are just using the defaults on the first 3 screens of wave interference
The ones on the diffraction screen seem much more reasonable and closer to our "norm" these days

Sam Reid [10:18 AM]
Wave Interference “side” and “top” radio buttons use a custom spacing of 8 (default is 3) and custom text, the rest are defaults. (edited)
Wave Interference customized the size of thumbs in HSlider.  The default ones were humongous!

Ariel Paul [10:19 AM]
But the radio button radius is just humongous by default

Sam Reid [10:19 AM]
That’s true.  I have no idea how many sims are using the defaults for that.  I could write a script that checks?  It would take 15 minutes to write the script then about 15 minutes to run the script (if my idea pans out).

Ariel Paul [10:20 AM]
Well, I am not worried necessarily about that, but more changing the default moving forward
It just seems when making prototypes like this, it would immediately make them cleaner

Sam Reid [10:21 AM]
If we change the default now, it would immediately impact all sims using the default (in master).
I like the idea of cleaner prototypes though.
I’m checking through all our sims to see what sims (if any) are using defaults for that.  I’m almost through the sims that start with the letter “a” and haven’t seen any yet.

Ariel Paul [10:23 AM]
seems worth investigating. I do not think any sim is using the default radio button size
Since I have asked it to be changed pretty much every time
I think balancing act might be a hold out

Sam Reid [10:24 AM]
balancing act is not using the defaults
It has “radius: 6”, the default is 16

Ariel Paul [10:27 AM]
I would say you are very safe to change it if the default is 16

Sam Reid [10:27 AM]
Here’s a radius of 7, does that seem good to you?

Sam Reid [10:27 AM]
uploaded this image: image.png 

Sam Reid [10:28 AM]
(as a new default?)

Ariel Paul [10:28 AM]
Yes, much better

**Comment by samreid** [comment]
I'm testing aqua with code that detects non-default values for the AquaRadioButton radius.  So far I'm up to the letter "f" with no hits.

**Comment by samreid** [comment]
Got my first occurrence of default AquaRadioButton radius used in a sim:

```
default radio button radius Error
    at new AquaRadioButton (http://localhost/sun/js/AquaRadioButton.js?bust=1521650008003:43:49)
    at new RealMoleculesScreenView (http://localhost/molecule-shapes/js/real/RealMoleculesScreenView.js?bust=1521650008003:102:30)
    at RealMoleculesScreen.createView (http://localhost/molecule-shapes/js/real/RealMoleculesScreen.js?bust=1521650008003:37:34)
    at RealMoleculesScreen.initializeView (http://localhost/joist/js/Screen.js?bust=1521650008003:243:25)
    at Array.<anonymous> (http://localhost/joist/js/Sim.js?bust=1521650008003:676:18)
    at http://localhost/joist/js/Sim.js?bust=1521650008003:684:27
```

**Comment by samreid** [comment]
No other hits in a full aqua fuzz.

In my opinion, the size in Molecule Shapes is great:

![image](https://user-images.githubusercontent.com/679486/37723529-2f1e8d06-2cf4-11e8-8e44-fa1b0ea1f94a.png)

I'll change the default down to 7 (6 seemed too small and 8 seemed too big) and make sure Molecule Shapes keeps the prior default of 16.

**Comment by samreid** [comment]
Update: VerticalAquaRadioButtonGroup had an independent default of 12--I was not checking for this.

**Comment by samreid** [comment]
Wave Interference and Wave on a String were the only places using the default of 12 for VerticalAquaRadioButonGroup.
Here's the default of 12 in Wave on a String:

![image](https://user-images.githubusercontent.com/679486/37725056-b38b2420-2cf7-11e8-8e55-a26821c1584e.png)

**Comment by samreid** [comment]
Fixed above, @ariel-phet can you please assign a reviewer?  @jonathanolson may be a good candidate if he has time, since he is responsible for the two sims that were using defaults.

**Comment by ariel-phet** [comment]
Sounds good @samreid, I assume this should be quick. Assigning @jonathanolson

**Comment by pixelzoom** [comment]
Unreviewed changes here to radio buttons.  Labeling as "block-publication".

**Comment by jonathanolson** [comment]
The current status of master here (with the changed and refactored out default) looks good to me. Closing.
