### ISSUE TITLE
changes to VerticalAquaRadioButtonGroup and VerticalCheckboxGroup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#344]
In addition to https://github.com/phetsims/sun/issues/262 ...

At the top of `VerticalAquaRadioButtonGroup`:

```js
//Render a simple vertical checkbox group, where the buttons all have the same sizes
//TODO: not ready for use in simulations, it will need further development & discussion first.
//TODO: Abstract out common functionality between this and VerticalCheckboxGroup
define( function( require ) {
```

(1) Contrary to the first comment, there are no checkboxes involved here.

(2) Contrary to the first TODO, this module occurs 15 times, in 12 sims, including many that are published.

(3) The second TODO is essentially issue https://github.com/phetsims/sun/issues/30, created 10/28/13.

Labeling for discussion at developer meeting.

**Comment by zepumph** [comment]
It is probably worth reminding people (since I forgot this in the past week) that TODOs in common code should have issues with them.

**Comment by jonathanolson** [comment]
What priority is handling the TODOs?

**Comment by samreid** [comment]
@samreid will take a look.  It could be that "factor out related parts between vertical checkboxes" is stale, may precede VBox.

I'll also add a comment like `// The vertical dilation is set automatically so the buttons are flush`

**Comment by pixelzoom** [comment]
Re this TODO:

```js
      //TODO #344 this is the total of left and right margins, replace with xMargin?
      padding: 8,
```

VerticalAquaRadioButtonGroup `padding` is used in pendulum-lab.
VerticalCheckBoxGroup `padding` is not used.
So I suggest that we change it to `xMargin`.

**Comment by pixelzoom** [comment]
Re this TODO in VerticalCheckBoxGroup:

```js
      //TODO #344 these are passed to CheckBox, replace with checkboxOptions: {...}
      boxWidth: 21,
      checkboxColor: 'black',
```

I suggest that we track down usages of these and change to:

```js
checkboxOptions: {
  boxWidth: 21,
  checkBoxColor:  'black'
}
```

**Comment by pixelzoom** [comment]
Re this TODO in VerticalCheckBoxGroup:

```js
        //TODO #344 VerticalAquaRadioButtonGroup has accessibleLabel, why not here?
        //TODO #344 VerticalAquaRadioButtonGroup has a11yNameAttribute, why not here?
```

@jessegreenberg I suspect that these fields are missing from VerticalCheckBoxGroup because it hasn't been instrumented for a11y yet.  Is that correct?

**Comment by pixelzoom** [comment]
Re this TODO in 

`//TODO #344 there's a bug here, indent for each item is not considered`

Highly recommended to fix the bug.   When `indent` is used, members of the group currently do _not_ have uniform width.    And it's possible (though unlikely) for `maxWidth + options.padding - indent` to result in a negative HStrut width.

**Comment by pixelzoom** [comment]
@samreid please review my proposals above for addressing TODO items.  Comment here, or ping me on Slack.

**Comment by jessegreenberg** [comment]
> @jessegreenberg I suspect that these fields are missing from VerticalCheckBoxGroup because it hasn't been instrumented for a11y yet.

Correct, VerticalCheckBoxGroup has not yet been instrumented.

**Comment by pixelzoom** [comment]
a11y-related TODO items removed, a11y instrumentation moved to #349.

**Comment by pixelzoom** [comment]
To summarize... Here are the proposed changes:

- [ ] change option `padding` to `xMargin`, with code changes to use `2 * xMargin` wherever `padding` appears
- [ ] add option `checkboxOptions: {...}` to VerticalCheckBoxGroup and move related options into it
- [ ] change `items[ {constant:...},...]` to `items[ {node: ...},...]` for VerticalCheckBoxGroup
- [ ] add `indent` feature to VerticalAquaRadioButtonGroup
- [ ] fix the bug in VerticalCheckboxGroup at `//TODO #344 there's a bug here...`

**Comment by pixelzoom** [comment]
Unassigning myself. @samreid please reassign to me when you have feedback.

**Comment by samreid** [comment]
> change items[ {constant:...},...] to items[ {node: ...},...] for VerticalCheckboxGroup

The change will be from `content` to `node`.

All proposed changes sound great.  I recommend either (a) renaming this issue to be clear that it covers VerticalCheckboxGroup as well as VerticalRadioButtonGroup or creating a new related issue to cover VerticalCheckboxGroup.

Additionally, do you think it would be possible to factor out a parent class that takes care of responsibilities common to both types?

**Comment by pixelzoom** [comment]
@samreid asked:
>Additionally, do you think it would be possible to factor out a parent class that takes care of responsibilities common to both types?

Most of the implementation of these types is concerned with creating checkboxes or radio buttons, and the layout is handled by VBox.  So VBox is essentially the "parent class".   There's a small amount of other stuff (pointer area dilation) that they share, but it doesn't seem significant enough to factor out.

**Comment by pixelzoom** [comment]
I completed several of the checklist items in https://github.com/phetsims/sun/issues/344#issuecomment-378813752.  But when I got to the one involving `padding`, it occurred to me that this responsibility don't belong here. It should be up to whatever is using these groups to add margins.   So my feeling is that the padding options should be removed.   Labeling for developer meeting to discuss.

**Comment by pixelzoom** [comment]
The only place the I see `padding:` for one of these groups is in `PLINKO_PROBABILITY/HopperModeControl`, see screenshot below.  The padding is really doing nothing here, since there's no container.   So I'm going to go ahead and remove the `padding` option.

![screenshot_714](https://user-images.githubusercontent.com/3046552/44169058-88767700-a090-11e8-94db-cb113536606d.png)

**Comment by pixelzoom** [comment]
The `indent` option was used in 1 place (WAVE_ON_A_STRING/BottomControlPanel), where it was set to zero.    So I see no reason to add it to VerticalAquaRadioButtonGroup, or fix the related bug in VerticalCheckboxGroup.  Instead, I'm going to remove the `indent` option.

**Comment by pixelzoom** [comment]
All work is completed. Here's a summary of what I did related to https://github.com/phetsims/sun/issues/344#issuecomment-378813752:

- VerticalAquaRadioButtonGroup: renamed `item.content` to `item.node`
- VerticalAquaRadioButtonGroup: moved option `radius` into `radioButtonOptions`
- VerticalCheckboxGroup: added option `checkboxOptions`
- VerticalCheckboxGroup and VerticalAquaRadioButtonGroup: deleted unused `padding` option
- VerticalCheckboxGroup: deleted unused `item.indent` feature

@samreid please review.

**Comment by samreid** [comment]
The proposed changes look great.  I read the combined change sets, the new code, tested Forces and Motion: Basics and Balloons and Static Electricity.  I discovered a few tangential issues which I'll reference below, but this issue is ready to close.
