### ISSUE TITLE
TODO in AccordionBox with no associated issue

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#345]
AccordionBox line 218, added by @zepumph in https://github.com/phetsims/sun/commit/cac6e3841deb3cdb1a700b398e0bac81b80cdd93:

`    // TODO: a11y`

All TODO items in common code are supposed to have an associated GitHub issue. Please identify (or create) an issue, and note it in the comment.

**Comment by zepumph** [comment]
This was added back when BAA was top priority for the a11y team, it no longer is in active conversion, and no other sims are using it so I removed the TODO. I will make sure that TODOs get issue numbers from now on.
