### ISSUE TITLE
add way to map valueProperty to another output value for AT

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/sun#355]
Required for https://github.com/phetsims/area-model-introduction/issues/2, it would be nice to be able to map the value of `valueProperty` of AccessibleSlider to another value that is read by AT when the `valueProperty` changes.

Will need to work well  with the other options that specify precision, and the string pattern that wraps the value with more content.

**Comment by jessegreenberg** [comment]
This was pretty straight forward, I tested it out in molecules-and-light. @jonathanolson can you please review and test in area-model sims where you need it?

**Comment by jonathanolson** [comment]
Working great, used in area-model (in the above commit).

Only note is about the JSDoc. At a brief glance, it looks like a partial doc for a function. Usually we'd just note `{function} - accessibleMapValue( { number } ): {number}` or something like that to note the input and return values.

Also if it's helpful, we could use _.identity as the value (lodash provides a shortcut for identity functions).

**Comment by zepumph** [comment]
This is an old review issue. We now have AccessibleValueHandler in typescript, so the documentation note is moot. Closing
