### ISSUE TITLE
AccessibleSlider options

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/sun#358]
Can initializeAccessibleSlider's options be changed somehow so we can specify a label and description?

Right now, I need to call initializeAccessibleSlider, and then manually mutate the labelTagName/labelContent/descriptionContent afterwards (in ProportionalPartitionLineNode).

For abstraction, should we have a field for the label and description (so if the implementation changes, we don't have to change client call-sites)?

**Comment by zepumph** [comment]
I'm tempted to hold off on this until we settle out and implement https://github.com/phetsims/scenery/issues/795.

**Comment by jessegreenberg** [comment]
We should go ahead and add these options in the meantime while we continue to work on https://github.com/phetsims/scenery/issues/795. @jessegreenberg will work on this.

**Comment by marlitas** [comment]
Meeting 11/5

- @jessegreenberg is going to determine wether this is stale or not and close if it is.
