### ISSUE TITLE
RadioButtonGroup description

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/sun#361]
When working on implementing Area Model's a11y, @zepumph pointed out we may want the description for the RadioButtonGroup to go below its fieldset.

Is this desired? (Could probably easily implement using `appendDescription:true`)

**Comment by jonathanolson** [comment]
Here's currently how the RadioButtonGroup for scene selection looks in area-model (using RadioButtonGroup, and with tabindices removed for readability):

```html
<div id="container-7-207-549-175-184">
  <p id="description-7-207-549-175-184">Switch between a 10x10 and 12x12 board.</p>
  <fieldset id="7-207-549-175-184">
    <div id="container-7-207-549-175-184-176">
      <input id="7-207-549-175-184-176" checked="checked" name="radioButtonGroup1Member" type="radio" style="width: 1px; height: 1px;" class="">
      <label id="label-7-207-549-175-184-176" for="7-207-549-175-184-176">10 by 10 board</label>
    </div>
    <div id="container-7-207-549-175-184-180">
      <input id="7-207-549-175-184-180" name="radioButtonGroup1Member" type="radio" style="width: 1px; height: 1px;">
      <label id="label-7-207-549-175-184-180" for="7-207-549-175-184-180">12 by 12 board</label>
    </div>
  </fieldset>
</div>
```

It looks like the "recommended" way of handling this would be to change `fieldset` => `ul` and the `div`s inside => `li`? Can this be done for every similar structure (i.e. every time we use the RadioButtonGroup component)? (@jessegreenberg or @zepumph does that look good ok?)

**Comment by terracoda** [comment]
@jonathanolson, no need for `div`'s inside the `li`'s. The list item itself wraps the radio button and its label. No need to have 2 wrappers.

**Comment by terracoda** [comment]
@jessegreenberg, @zepumph, I will re-listen to sample radio button groups that I mocked up a while ago asap and then create an MD file that includes a couple of valid options.

I'm not convinced we need to use `fieldset`, but I'll look into this.

**Comment by jonathanolson** [comment]
> no need for div's inside the li's. The list item itself wraps the radio button and its label. No need to have 2 wrappers.

Yup understood, was just trying to indicate I meant the `div`s inside the fieldset would change to `li`s (not the `div` that is the parent of the fieldset).

**Comment by terracoda** [comment]
@jonathanolson, one other thing. 

The code you pasted had `checked="checked"`, that's xhtml code, not HTML5 code. The HTML5 state attribute is just `checked`, all by itself. If that is not recognized, I would say we should use the aria attribute, aria-checked="true/false".

Was `checked="checked"` generated from our API? If so, I should create an issue to fix that. HTML5 not strict in this sense, but I think the proper HTML5 attribute is cleaner.

**Comment by amanda-phet** [comment]
Much of this conversation seems to be based on dated static description work. What we ended up putting in the design doc is as follows: 

Radio Button Group
Accessible Name: Area Grid Size
10 by 10 
12 by 12

So, the description text needs to be changed to "Area Grid Size", and the help text can be removed.

**Comment by terracoda** [comment]
@jessegreenberg, didn't mean to suggest making the ul focusable. I need to do to that in my simple mock-ups, so I can Tab onto groups to see what it sounds like. I am not able to focus on groups otherwise. 

Regarding the checked syntax, I guess it's fine if

**Comment by jessegreenberg** [comment]
I understand now, thanks @terracoda. In the above commit, the `aria-labelledby` attribute was added, pointing to a default `h3` tag. The `role=radiogroup` was also added.

@jonathanolson back to you, if you added a labelTagName of `p` in aria-model-introduction, that probably needs to be removed now.

**Comment by terracoda** [comment]
I'll leave myself assigned until I have the markdown file done.

**Comment by terracoda** [comment]
I've started a markdown file. It is called RadioGroup.md for now.

**Comment by terracoda** [comment]
@zepumph, I agree this is a problem. 

I think that we could handle this in a couple of different ways:
- using a general name on the md file and then listing out (or linking to) the js files inside the md file
- using the most common js file name, and then doing the same association to other js file (list or link)
- make one md file and name it in a comment in the top of the js file?

I think for the a11y stuff the goal is document the general pattern. Since the pattern has no look associated it, there will potentially be many visual versions of the same pattern.

**Comment by zepumph** [comment]
Consensus on how to proceed with style guide documentation will be decided in phetsims/binder#11. @terracoda what is left for this issue for @jonathanolson to implement in area model?

**Comment by terracoda** [comment]
@zepumph, I haven't quite finished the radio group md file, but I should tomorrow. I'm not sure if there is anything holding up further implementation in Area Model?

**Comment by terracoda** [comment]
@jonathanolson, are you ready to close this issue?

**Comment by jonathanolson** [comment]
A default H3 seems weird to me, usually a sim would specify where the headers go?

For example, the radio button group mentioned in this issue is explicitly NOT supposed to be an h3.

That said, I don't see anything else that needs to be done here in common code. I'll need to go through and update things with new labels/help text.

**Comment by terracoda** [comment]
@jonathanolson, the `h3`does not replace the `radiogroup,` it names the `radiogroup`. In our experience thus far,  the Play Area is an `h2`, so generally objects and groups directly under the Play Area would be named with an `h3` if an name is needed.

Is that more clear?

**Comment by terracoda** [comment]
And for more clarification, headings usually go with other elements containing content. Each heading starts a new section or subsection. Often in our case they are used to name a group of things or an object made up of multiple elements. So a group of radio buttons is usually named by a `h3` heading. A custom object like the balloon in Balloons and Static Electricity is a group of elements, so the group too, is named by an `h3` heading. In the PDOM these groups and objects are like subsections of content within the Play Area section. The heading is a way to give the object or group a name. The hierarchical heading structure is very useful for scaffolding non-visual users.

**Comment by terracoda** [comment]
@jessegreenberg, @jonathanolson, @mbarlow12, @zepumph the following HTML provides the best described experience (in my opinion in VoiceOver). I moved the `radiogroup` role to the parent wrapping element. 

I'll use this as our design pattern, and then we can test with NVDA and JAWS.

``` html
<div aria-labelledby="rg11-heading" role="radiogroup">
  <h3 id="rg11-heading">Charge Settings</h3>
   <ul class="rgroup" aria-labelledby="rg11-heading">
     <li><input id="r11-1" type="radio" checked tabindex="0">
            <label for="r11-1">Show all charges</label>
      </li>
      <li><input id="r11-2" type="radio">
            <label for="r11-2">Show no charges</label>
      </li>
      <li><input id="r11-3" type="radio">
             <label for="r11-3">Show charge differences</label>
      </li>
    </ul>
</div>
```

Upon focus of the selected radiobutton, I hear the follow:
"Show all charges, selected radio button list Charge Settings 3 items."

We do not hear "radiogroup", but I think "radio button list" is equivalent. We do not get any name repetition and we get the count of the items which I think users find very helpful.

I would guess that in other screen readers we might hear "radiogroup" instead of "radio button list" and still get item count.

**Comment by terracoda** [comment]
Actually, `aria-labelledby` is on both the parent wrapper `div `and the` ul`. This sounds best in VoiceOver in Safari and Chrome and ChromVox. I can only test on those 2 systems.

It would be nice to verify if there is repetition of the group name in either NVDA and JAWS.

**Comment by jessegreenberg** [comment]
Discussed during 5/25/18 meeting.

@terracoda is going to keep testing. We were curious about whether `aria-labelledby` is required on both the parent element and the `ul`. @terracoda will test it out on VO and then paste some examples here to be tested by someone with access to NVDA and JAWS.

**Comment by terracoda** [comment]
@jessegreenberg, I committed 3 more examples to the radiogroup-examples.html file in a11y-research. There are some differences which I will have to summarize in a post later tonight, sorry for the delay.

**Comment by terracoda** [comment]
@jessegreenberg, using `aria-controls` on the parent div also ensures the group's name is included. I am going to run through again using `aria-controls` to see the differences.

**Comment by terracoda** [comment]
@jessegreenberg, I take https://github.com/phetsims/sun/issues/361#issuecomment-392256873 back. It does not seem to be consistent.

**Comment by terracoda** [comment]
After repeat testing in VoiceOver & Safari and Chrome & ChromeVox, the best option is actually, html sketch **Example 4** that I made using a `fieldset`, a `legend` and an `ul` containing the radio buttons.

For the record, this structure sounds the same as **Example 11** see https://github.com/phetsims/sun/issues/361#issuecomment-392075670 with the 2 instances of `aria-labelledby` (one on the list and one on the parent group container). 

The reason is that when not using a `fieldset` as the group's parent, (i.e., a `div` as the parent wrapper) the differences that were very confusing in earlier testing was that VoiceOver likes `aria-labelledby` on the `ul` and ChromeVox likes `aria-labelledby` on the parent. 

And for these two screen readers, the same goes for `aria-label`. If one does not use a heading as the name for the group and uses `aria-label` instead, VoiceOver likes `aria-label `on the `ul` containing the radio buttons, and ChromeVox likes `aria-label` on the parent `div` with the `role="radiogroup"`.

**New Recommendations for testing in NVDA and JAWS**
```html
<fieldset role="radiogroup">
  <legend>Charge Settings</legend>
  <p>Choose how you see or hear charge information.</p>
  <ul>
    <li><input id="r4-1" type="radio" checked tabindex="0">
           <label for="r4-1">Show all charges</label></li>
    <li><input id="r4-2" type="radio">
          <label for="r4-2">Show no charges</label></li>
     <li><input id="r4-3" type="radio">
   	    <label for="r4-3">Show charge differences</label></li>
   </ul>
</fieldset>
```

If one replaces the `legend` with a heading for design reasons, `aria-labelledby` must be used to create the same experience in VoiceOver and ChromeVox:
``` html
<fieldset role="radiogroup" aria-labelledby="rg16-heading">
      <h3 id="rg16-heading">Charge Settings</h3>
      <p>Choose how you see or hear charge information.</p>
      <ul>
		<li><input id="r16-1" type="radio" tabindex="0" checked>
			<label for="r16-1">Show all charges</label>
		</li>
		<li><input id="r16-2" type="radio">
			<label for="r16-2">Show no charges</label>
		</li>
		<li><input id="r16-3" type="radio">
			<label for="r16-3">Show charge differences</label>
		</li>
	</ul>
   </fieldset>
```

To quote @zepumph, this one was a honker!

**Comment by terracoda** [comment]
The coded examples for the ARIA Practices 1.1 sound similar, but still different than the raw html, I've posted above.

@jessegreenberg, @zepumph and @mbarlow12 could one of explain to me how they are getting the count semantics even when they do not use a list structure.

[Example 2](https://www.w3.org/TR/wai-aria-practices/examples/radio/radio-2/radio-2.html) and [example 1](https://www.w3.org/TR/wai-aria-practices/examples/radio/radio-1/radio-1.html), seems to sound exactly the same, but only example 2 uses a list structure.

**Comment by terracoda** [comment]
The html code in the renamed sun/doc/RadioButtonGroup.md was discussed at the A11y Dev meeting, and it is fine to implement it now. There are two examples in the mark down file.

Please note that I am not sure which method is currently being used to select a radio button, ARIA or HTML. The sample code uses html5's attribute `checked`. It is well supported, but if we have any issues with the HTML5 `checked` attribute we should switch to the ARIA equivalent, aria-checked="true/false".

I am un-assigning myself, please re-assign if there are any questions. I will start a new issue for other parts of the mark down file.

**Comment by terracoda** [comment]
@jessegreenberg could you assign to the appropriate person if it is not you :-)

**Comment by jessegreenberg** [comment]
Ill work on this, removing the meeting label.

**Comment by marlitas** [comment]
Meeting 11/5/24
- This has been resolved in another issue. Closing as stale!
