### ISSUE TITLE
Convert from phetioEventSource to nested Emitter

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#365]
As we did for https://github.com/phetsims/sun/issues/340

**Comment by samreid** [comment]
I'm looking at RadioButtonGroupMemberModel:

```js
// @public (read only) - fire on up if the button is enabled, public for use in the accessibility tree
this.fire = function() {
  if ( self.enabledProperty.get() ) {
    phetioEventSource.startEvent( 'user', 'fired', {
      value: selectorProperty.phetioType && selectorProperty.phetioType.elementType && selectorProperty.phetioType.elementType.toStateObject && selectorProperty.phetioType.elementType.toStateObject( selectedValue )
    } );
    selectorProperty.set( selectedValue );
    phetioEventSource.endEvent();
  }
};
```

The Property is passed in by a client and may not be instrumented.  Also, the Property would be a model event, not a user event.  I recall we previously experimented with a synthetic Emitter (that cascades to the Property), but we removed it for some reason.  Not sure how to proceed for this case.

**Comment by samreid** [comment]
We are forced into using *ButtonModel because of the Rectangular/Round button types as a way of factoring out logic across the types.  It is important to have a user event like "button pressed" instead of a model event "button.emitter emitted", so I've kept this pattern and simplified it a bit.  Local tests are green and Bayes is OK with it (... so far).

**Comment by jonathanolson** [comment]
Bayes is unhappy, and after pulling I'm running into errors with button interaction in area-model.

**Comment by samreid** [comment]
Thanks, I see the problem on bayes.  Here's what aqua looks like locally, so I'm not yet sure what's happening.  I'll keep looking:

![image](https://user-images.githubusercontent.com/679486/40840755-3822fb40-6565-11e8-938d-9f9f33fe404f.png)

**Comment by samreid** [comment]
I should mark this as "blocks publication" but we don't have that label yet.  I'll notify slack.

**Comment by samreid** [comment]
It looks like https://github.com/phetsims/joist/commit/348266688b483e0bfc868b33dd3a453d1f97818c was committed but not pushed.  I pushed it now and will keep an eye on Bayes.

**Comment by samreid** [comment]
CT is happier after the push:

![image](https://user-images.githubusercontent.com/679486/40841937-6a6c564c-6569-11e8-9397-3e8f0783e6e9.png)

So I'm cautiously optimistic.

**Comment by samreid** [comment]
Closing again for now.
