### ISSUE TITLE
branch: yamldocs

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/sun#367]
Documentation only. This branch is for testing the utility of YAML front matter in our markdown documents. See https://github.com/phetsims/binder/issues/15 for more details.

**Comment by mbarlow12** [comment]
Branch merged into master and deleted.

**Comment by jbphet** [comment]
Reopening.  This branch was restored during an effort to recover some branches that were accidentally deleted.  This one had been _intentionally_ deleted, and now needs to be re-deleted.  See https://github.com/phetsims/special-ops/issues/198.

**Comment by jbphet** [comment]
Re-deletion complete.  Closing.
