### ISSUE TITLE
PushButton cannot use same instance for its args

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#37]
PushButton will break (not show the correct node visibilities) if some nodes are passed as multiple arguments.  For instance, in HomeButton, I put:

PushButton.call(this,icon,icon,icon,icon)

and it never showed up since it is setting icon.visible=false last (perhaps for the down or disabled part).  We had the same problem in https://github.com/phetsims/sun/issues/36 and decided to wrap the nodes by default and provide an option to not wrap them (in case the client is sure they don't appear elsewhere).

**Comment by pixelzoom** [comment]
@samreid PushButton is history, no longer exists. Anything we need to do related to HomeButton that you mentioned above, or can this issue be closed?

**Comment by samreid** [comment]
I think we are done here.  Closing.
