### ISSUE TITLE
RadioButtonGroupMember should use Emitter

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#373]
RadioButtonGroupMember needs the same Emitter implementation that @zepumph @chrisklus and @samreid introduced in https://github.com/phetsims/axon/issues/180 and https://github.com/phetsims/sun/issues/340.  I saw this code:

```js
    /**
     * @public (read-only) - fire on up if the button is enabled, public for use in the accessibility tree
     */
    fire: function() {
      if ( this.buttonModel.enabledProperty.get() ) {
        this.phetioStartEvent( 'user', 'fired', {
          value: this.property.phetioType &&
                 this.property.phetioType.elementType &&
                 this.property.phetioType.elementType.toStateObject &&
                 this.property.phetioType.elementType.toStateObject( this.value )
        } );
        this.property.set( this.value );
        this.phetioEndEvent();
      }
    },
```

@zepumph can you investigate?

**Comment by samreid** [comment]
Also, what is the logical conclusion of this approach?  Are most/all of the `phetioStartEvent` going to convert to `Emitter`?  What would the pros and cons of that be?

**Comment by zepumph** [comment]
I'll take a look

**Comment by zepumph** [comment]
We converted this event to `firedEmitter`. This involved us deleting RadioButtonGroupMemberIO because it was no longer doing anything. Next steps are to test disposal in https://github.com/phetsims/sun/issues/379, closing
