### ISSUE TITLE
Impossible set state from enabledProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#374]
Uncaught Error: Impossible set state:
friction.navigationBar.a11yButtonsHBox.keyboardHelpButton.keyboardHelpDialog.closeButton.enabledProperty

Discovered during https://github.com/phetsims/tandem/issues/61

**Comment by samreid** [comment]
Automated tests may miss this if it doesn't fuzz the about dialog.

**Comment by samreid** [comment]
Going on hold until https://github.com/phetsims/molarity/issues/48 is addressed.

**Comment by samreid** [comment]
I tested opening and closing the keyboard help dialog in friction and did not get an error.  @zepumph is this fixed?

**Comment by zepumph** [comment]
Yes it has been fixed for some time, we left this issue open until Molarity maintenance release was published (see https://phet-dev.colorado.edu/html/molarity/1.4.1/phet-io/wrappers/state/state.html)
Closing
