### ISSUE TITLE
use a consistent default for cornerRadius

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#376]
AccordionBox and Panel have different values for their `cornerRadius` options.  In the past few sims that I've worked on, we used both AccordionBox and Panel, and this difference forced me to set a consistent `cornerRadius`.   Rather than continue to do this, let's choose a consistent default.

**Comment by zepumph** [comment]
Sounds like a good idea. I don't have any preference on what that value it.

**Comment by jonathanolson** [comment]
Changing the current defaults would change sims - would we plan to keep all "current" behavior (adding corner radii overloads in many places)?

**Comment by pixelzoom** [comment]
Currently: Panel is 10, AccordionBox is 3.

**Comment by pixelzoom** [comment]
8/23/18 dev meeting consensus:   I will change AccordionBox default to `cornerRadius: 10`, and make all existing call sites set `cornerRadius: 3`, so that behavior of sims is unchanged.

**Comment by pixelzoom** [comment]
I changed AccordionBox's default to `cornerRadius: 10`. 

I only had to explicitly set `cornerRadius: 3` in 5 sims, FYI developers mentioned here:

area-builder @jbphet 
build-an-atom @jbphet 
isotopes-and-atomic-mass @jbphet 
least-squares-regression @jonathanolson 
sugar-and-salt-solutions (unpublished) @samreid 

Closing.
