### ISSUE TITLE
HSlider doesn't play well with panels that expand for i18n

### ISSUE THREAD

**Issue by arouinfar** [phetsims/sun#378]
A common strategy for i18n is to allow panels to expand by some amount before scaling down the contents/strings within. 

Masses and Springs contains a panel with some pretty long strings, so I requested this behavior, which ended up leading to a bit of refactoring, and ultimately required that the default panel width itself be wider, as @Denz1994 explained in https://github.com/phetsims/masses-and-springs/issues/308#issuecomment-410350708:

> After further investigation, there are a few things to consider. The contents of the panel is already being scaled because the panel is too small for the default sizes of the contents (hSlider in particular). If we change the maxWidth of the panel it will change the scale of its contents automatically because the contents will have more space to expand to its default size.

Other relevant MAS i18n issues include: 
https://github.com/phetsims/masses-and-springs/issues/293
https://github.com/phetsims/masses-and-springs/issues/313

I found this pretty surprising, given that there are many other expanding panels containing HSlider or numberControl (examples below), and that the panel widths in MAS rc.2 weren't particularly small. In the case of MAS, I was okay with making the default widths a bit wider, but there are likely other sims where I wouldn't want to make the default widths larger because it would be too visually heavy or crowded.

I was hoping that the devs could look into this and see if there is a more general solution than giving panels with HSlider a larger default width, so @ariel-phet recommended I open this issue.

Bending Light
<img width="374" alt="screen shot 2018-08-15 at 11 54 56 am" src="https://user-images.githubusercontent.com/8419308/44164501-72ae8500-a083-11e8-8a51-55decc161195.png">
<img width="426" alt="screen shot 2018-08-15 at 11 55 04 am" src="https://user-images.githubusercontent.com/8419308/44164500-72ae8500-a083-11e8-8bee-b82b545ecca7.png">

Rutherford Scattering
<img width="287" alt="screen shot 2018-08-15 at 11 54 28 am" src="https://user-images.githubusercontent.com/8419308/44164559-9d98d900-a083-11e8-8040-8275a273e7c2.png">
<img width="314" alt="screen shot 2018-08-15 at 11 54 35 am" src="https://user-images.githubusercontent.com/8419308/44164560-9d98d900-a083-11e8-8c6e-24d6e309f1b8.png">

CCK:DC
<img width="279" alt="screen shot 2018-08-15 at 11 55 24 am" src="https://user-images.githubusercontent.com/8419308/44164612-c15c1f00-a083-11e8-8751-2e80a2000c71.png">
<img width="295" alt="screen shot 2018-08-15 at 11 55 32 am" src="https://user-images.githubusercontent.com/8419308/44164611-c15c1f00-a083-11e8-8ce0-5f2a63100e48.png">

Here's a comparison of MAS rc.2 (original panel widths) and rc.3 (larger default panel widths):
<img width="1098" alt="screen shot 2018-08-15 at 12 10 43 pm" src="https://user-images.githubusercontent.com/8419308/44165224-5f9cb480-a085-11e8-938b-38185f529318.png">
<img width="1097" alt="screen shot 2018-08-15 at 12 10 54 pm" src="https://user-images.githubusercontent.com/8419308/44165222-5f9cb480-a085-11e8-8e93-f810fdfcaba0.png">

@ariel-phet I know you had talked about this with @Denz1994, so can you add a bit onto this issue? I'm not sure if I've adequately described things for the devs. Also not sure if the title is appropriate or not.

**Comment by Denz1994** [comment]
A generalization of this behavior extends to Panels whose content has default sizes that are larger than the Panel. This behavior was also present in the VerticalCheckboxGroup above the gravity slider.

The current solution involves making the Panel larger so the content fits its default size. There is room for discussion on a general solution.

**Comment by pixelzoom** [comment]
I don't understand what the problem is here.  Developers can set (and should be setting) independent `maxWidth` values for all of the text elements in HSlider and NumberControl.   That includes titles, tick labels, etc.   Additionally, they may set `maxWidth` on the entire UIComponent.   So unless you decide the you need more width to accommodate English strings (or translated strings), there's no need to make a Panel wider.

**Comment by Denz1994** [comment]
Considering the above comments from @pixelzoom and further discussion with @jonathanolson, I should not be using maxWidths to size texts or nodes. Instead, they should be sized using font, scale, etc. and then a maxWidth should be applied. 

There isn't anything that needs to be added to common code but instead, this revised approach should be taken in the future to negate the need to refactor sim code.
