### ISSUE TITLE
Carousel: replace TWEEN with TWIXT/Animation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#381]
The animation in `Carousel` currently relies on TWEEN, which we've deprecated.  It should be covered to use the latest TWIXT animation types (`Animation`, `Easing`, etc.) 

Assigning to @ariel-phet to prioritize and assing.  I'll be happy to handle this, if you'd like, since I just did a similar conversion for Hooke's Law in TRANSLATION_DURATION.

**Comment by pixelzoom** [comment]
> This appears to be the only use of TWEEN in common code, btw.

Correction... SCENERY_PHET/Drawer uses TWIXT/MoveTo, which is currently implemented using TWEEN.  It might be easier to reimplement MoveTo and OpacityTo, so that we don't need to change common or sim code that uses these.

**Comment by pixelzoom** [comment]
After Slack discussion (see https://github.com/phetsims/twixt/issues/19#issue-353869087) about what default to use for the Animation `stepper` options, I decided:

> ... In the meantime, I'll default to `stepper:'manual'`, change existing call sites to use `stepper:'timer'`, and let responsible devs decide whether to change. I don't have time to implement and test `step` in sims.

**Comment by pixelzoom** [comment]
Carousel animation has been reimplemented using TWIXT/Animation, with default `stepper: 'manual'`.  At existing call sites, `stepper: 'timer'` has been added, and an issue has been created for each affected sim to evaluate the `stepper` option.

**Comment by pixelzoom** [comment]
@jonathanolson randomly selected to review.

**Comment by chrisklus** [comment]
@pixelzoom as part of this issue, can clients get some sort of public info about the carousel's animation? 

This is my very bad solution for what I'm trying to do, and a simple `animation.endedEmitter` would do the trick instead (the important line is `this.numberPanel.updateModelLocations`):

```js
const animationDuration = 0.4; // in seconds

// @private {Node}
this.numberPanel = new LabNumberCarousel( model.numberStacks, animationDuration, ( event, stack ) => {
  const modelPoint = this.modelViewTransform.viewToModelPosition( this.globalToLocalPoint( event.pointer.point ) );
  const numberPiece = new NumberPiece( stack.number );
  numberPiece.positionProperty.value = modelPoint;
  model.dragNumberPieceFromStack( numberPiece );
  const numberPieceNode = this.getNumberPieceNode( numberPiece );
  numberPieceNode.dragListener.press( event, numberPieceNode );
} );
this.numberPanel.centerX = this.layoutBounds.centerX;
this.numberPanel.top = playAreaViewBounds.top;

this.numberPanel.pageNumberProperty.link( () => {

  // TODO: The following code needs to run when the Carousel is actually at the page that this Property says it's
  // at, but this is not an acceptable solution.
  setTimeout( () => {
    this.numberPanel.updateModelLocations( this.modelViewTransform );
  }, animationDuration * 1000 );
} );
```

The doc for `pageNumberProperty` is `// @public {Property<number>} page number that is currently visible`, but is not accurate if animations are enabled, so I think exposing parts of the animation is an appropriate alternative for clients.

**Comment by pixelzoom** [comment]
@chrisklus and I are going to discuss this via Slack, since I don't understand the use case.

Additionally... This has been assigned to @jonathanolson to review for 18 months. So I think we should reassign.  @chrisklus would you have time to do the review as part of this work?

**Comment by chrisklus** [comment]
@pixelzoom and I discussed this today and decided that the number cards can animate back to their original spots, and those spots don't need to be updated. This removes my animation desires described in https://github.com/phetsims/sun/issues/381#issuecomment-557202392.

**Comment by pixelzoom** [comment]
> ... decided that the number cards can animate back to their original spots ...

To elaborate... We spent a lot of time discussing this exact problem in Function Builder, and our conclusion was to animate back to the location where the item was removed from the carousel.

**Comment by samreid** [comment]
Carousel was thoroughly reviewed in #814, it is using TWIXT.  @pixelzoom said the Function Builder strategy is acceptable and working well.  Regarding @chrisklus recommendation to expose the animation sequence, I recommend we implement that once we have a use case that would leverage it.  So I think this issue can be closed.
