### ISSUE TITLE
Cannot dispose interactionStateProperty before disposing parent in RadioButtonGroupMember

### ISSUE THREAD

**Issue by chrisklus** [phetsims/sun#383]
@zepumph and I were looking for a leak in `RadioButtonGroupMember` and decided that `interactionStateProperty` should be disposed, but found that it couldn't be disposed before disposing the parent type because the parent type was trying to unlink the listeners to this property. One potential option:
```
this.disposeRadioButtonGroupMember();
RectangularButtonView.prototype.dispose && RectangularButtonView.prototype.dispose.call( this );
this.interactionStateProperty.dispose();
this.buttonModel.dispose();
```

**Comment by zepumph** [comment]
We found that the interactionStateProperty had to be disposed before the `buttonModel`,because it is a derived Property that depends on many ButtonModel Properties, and tries to unlink them on dispose.

Thus the above code snippet is a bit of a hack/workaround to get around the faulty hierarchy weirdness of sun button disposal. @samreid didn't we run into something like this with PhET-iO emitters recently? Do you have any ideas on how to proceed here? We could commit the above, but thought we would ask first before such a change.

**Comment by samreid** [comment]
I added this code to MemoryTestsScreenView.js

```js
    new ComponentHolder( function() {
      return new RadioButtonGroup( new Property('a'),[
        { value: 'a', node: new Text('a') },
        { value: 'b', node: new Text('b') }
        ], );
    } )
```

I commented out the other ComponentHolders and ran the memory test.  It suggested there was no memory leak, at least the way it is being used in this context:

![image](https://user-images.githubusercontent.com/679486/44624361-8048e380-a8a9-11e8-9df4-31065760112b.png)

Can you please be more specific about the test harness you are using, or what the symptoms were of the faulty hierarchy weirdness of sun button disposal?

**Comment by pixelzoom** [comment]
To avoid this type of ordering dependency, I recommend checking `hasListener` before attempting to `unlink` or `removeListener`.   This is especially true for any Property that have been passed in to a type; you have no control over when or whether the client may have disposed of that Property.

E.g. in FaucetNode:

```js
    this.disposeFaucetNode = function() {

      // Properties
      if ( options.interactiveProperty.hasListener( interactiveObserver ) ) {
        options.interactiveProperty.unlink( interactiveObserver );
      }
      if ( flowRateProperty.hasListener( flowRateObserver ) ) {
        flowRateProperty.unlink( flowRateObserver );
      }
      if ( enabledProperty.hasListener( enabledObserver ) ) {
        enabledProperty.unlink( enabledObserver );
      }

      // Subcomponents
      if ( shooterNode.hasInputListener( inputListener ) ) {
        shooterNode.removeInputListener( inputListener );
      }
      shooterNode.dispose();

      self.disposeAccessibleSlider();
    };
```

**Comment by chrisklus** [comment]
@zepumph thanks! Based on the order of the list, @SaurabhTotey and I will hit this next week during our Tuesday meeting, and we now know how to handle this correctly since learning from your previous suggestion and @pixelzoom's https://github.com/phetsims/sun/issues/383#issuecomment-418807962.

And thanks for mentioning something here, I probably would not have remembered to close this issue once we make the change.

**Comment by chrisklus** [comment]
@SaurabhTotey and I fixed this today. Closing.
