### ISSUE TITLE
Investigate dependency injection for VerticalCheckBoxGroup or VerticalAquaRadioButtonGroup

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#384]
Discovered in https://github.com/phetsims/sun/issues/344, it may be possible to use a dependency injection strategy as described in https://github.com/phetsims/wave-interference/issues/79#issuecomment-416045828.  This could simplify the call sites and the constructor implementations, and may allow us to unify the implementations.  This will be an investigation because it is unclear whether the `HStrut` behavior can be done after Checkbox/AquaRadioButton construction.

**Comment by pixelzoom** [comment]
There are many forms of dependency injection.   And if these types don't create their components, you've whittled them down to VBox.  Could you clarify what you had in mind, perhaps with an example?

**Comment by samreid** [comment]
I experimented  with the example in NetForceControlPanel.js.  The current implementation looks like this:

```js
    var verticalCheckboxGroupTandem = tandem.createTandem( 'verticalCheckboxGroup' );
    this.verticalCheckboxGroup = new VerticalCheckboxGroup( [ {
      node: new Text( sumOfForcesString, _.extend( { tandem: tandem.createTandem( 'showSumOfForcesTextNode' ) }, fontOptions ) ),
      property: model.showSumOfForcesProperty,
      tandem: verticalCheckboxGroupTandem.createTandem( 'showSumOfForcesCheckbox' )
    }, {
      node: new Text( valuesString, _.extend( { tandem: tandem.createTandem( 'showValuesTextNode' ) }, fontOptions ) ),
      property: model.showValuesProperty,
      tandem: verticalCheckboxGroupTandem.createTandem( 'showValuesCheckbox' )
    }, {
      node: showSpeedContent,
      property: model.showSpeedProperty,
      tandem: verticalCheckboxGroupTandem.createTandem( 'showSpeedCheckbox' )
    } ], {
      tandem: verticalCheckboxGroupTandem
    } );
```

I experimented with a pattern where the `Checkbox`es are created by the client code:
```js
    var verticalCheckboxGroupTandem = tandem.createTandem( 'verticalCheckboxGroup' );
    this.verticalCheckboxGroup = new VBox( {
      children: unify( [
        new Checkbox( new Text( sumOfForcesString, _.extend( { tandem: tandem.createTandem( 'showSumOfForcesTextNode' ) }, fontOptions ) ),
          model.showSumOfForcesProperty, {
          tandem: verticalCheckboxGroupTandem.createTandem( 'showSumOfForcesCheckbox' ) } ),
        new Checkbox( new Text( valuesString, _.extend( { tandem: tandem.createTandem( 'showValuesTextNode' ) }, fontOptions ) ),
          model.showValuesProperty, {
          tandem: verticalCheckboxGroupTandem.createTandem( 'showValuesCheckbox' ) } ),
        new Checkbox( showSpeedContent,
          model.showSpeedProperty, { 
          tandem: verticalCheckboxGroupTandem.createTandem( 'showSpeedCheckbox' ) } )
      ], 5, 5 ),
      align: 'left',
      spacing: 10,
      tandem: verticalCheckboxGroupTandem
    } );
```

The former uses VerticalCheckboxGroup.js which is 84 lines of code.  The latter uses a new utility function `unify` which is declared like so:
```js
    /**
     * Standardizes bounds, mouse areas, and touch areas for an array of Nodes.
     * @param {Node[]} nodes
     * @param {number} dilationX
     * @param {number} dilationY
     * @returns {Node[]} - the adjusted nodes, for chaining.
     */
    const unify = function( nodes, dilationX, dilationY ) {
      var right = _.maxBy( nodes, n => n.right ).right;
      nodes.forEach( n => {
        n.setLocalBounds( n.localBounds.withX( right ) );
        n.mouseArea = n.localBounds.dilatedXY( dilationX, dilationY );
        n.pointerArea = n.localBounds.dilatedXY( dilationX, dilationY );
      } );
      return nodes;
    };
```

The new pattern supports uniform bounds and mouse/touch areas like this:
![image](https://user-images.githubusercontent.com/679486/48454549-d9236c00-e774-11e8-94a1-dae9fd7bebc7.png)

Advantages of VerticalCheckBoxGroup:
* It is easy to find usages of VerticalCheckBoxGroup
* Options like dilatation, alignment, etc are factored out.

disadvantages of VerticalCheckBoxGroup:
* Requires an intermediate data structure for elements: 
```
   * @param {Object[]} items - Each item describes a checkbox, and is an object with these properties:
   *    node: {Node}, // label for the button
   *    property: {Property.<boolean>}, // Property associated with the button
   *    [tandem]: {Tandem} // optional tandem for PhET-iO
```

Advantages of creating `Checkbox` instances in the client code:
* No need to pass through an intermediate data structure
* Full control over creating the individual Checkboxes
* Ability to mix different component types, such as Checkboxes/Aqua Radio Buttons, etc.

Disadvantages of creating `Checkbox` instances in the client code:
* Duplicated calls to `new Checkbox` and passing options to each checkbox.  Could be overcome with a local `createCheckbox` closure.

*Summary*
Creating the `Checkbox` instances in the client code and using a general pattern like `unify` gives much more control and flexibility to the client without introducing significant overhead or disadvantages.  According to https://github.com/phetsims/tasks/issues/952#issuecomment-420007730 we decided to discuss with the team before moving further toward this pattern--so this seems a good point to check in.

**Comment by jonathanolson** [comment]
The one with creating Checkboxes in the code seems nice.

**Comment by jessegreenberg** [comment]
Another advantage of using Vertical{{ComponentType}}Group is that it includes instrumentation for a11y (and maybe phetio?)

**Comment by samreid** [comment]
@jessegreenberg reported we can set the focus highlight without using the local bounds.  And that, say VerticalAquaRadioButtonGroup can create custom a11y components (that are hard-coded to work great for HTML radio button group).

It could be possible to move options like this:

```js
      // supertype a11y options
      tagName: 'ul',
      groupFocusHighlight: true
```
to the instance site, or factor that out.

**Comment by samreid** [comment]
We discussed this, and developers can use this pattern as desirable.
