### ISSUE TITLE
identify sims that have a vertical slider

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#385]
Related to https://github.com/phetsims/sun/issues/380.   Before I do a lot of work on this, we should verify the requirements. 

First, we should identify HTML5 sims that have a vertical slider so that:

(1) we are certain that our requirements for vertical slider are complete
(2) we can identify where vertical slider should be used

@ariel-phet could you please assign this to someone to compile a list? 

---
EDIT: The "complete" list of sims with vertical sliders is:

- [x] capacitor-lab-basics
- [x] color-vision
- [x] curve-fitting
- [x] energy-forms-and-changes
- [x] graphing-quadratics
- [x] gravity-and-orbits
- [x] least-squares-regression
- [x] molarity
- [x] neuron
- [x] ohms-law
- [x] resistance-in-a-wire
- [x] states-of-matter
- [x] states-of-matter-basics

**Comment by ariel-phet** [comment]
@KatieWoe this would be a good task for you to familiarize yourself with any #HTML5 sim you have not opened yet :).

**Comment by KatieWoe** [comment]
Sure thing.  @pixelzoom Does this include only published sims, or also any sims still in development?

**Comment by KatieWoe** [comment]
Published sims:
Capacitor Lab: Basics
Color Vision
Gravity And Orbits
Least Squares Regression
Molarity
Neuron
Ohm's Law
Resistance In a Wire
States of Matter
States of Matter: Basics
(Unsure of pH Scale)

@pixelzoom Do you have any ideas of how to check any unpublished sims?  I thought of going through phettest, but if there are any that are in early stages of development I might miss them.

**Comment by KatieWoe** [comment]
Question for pH Scales for anyone who may know.
Would these movable boxes be sliders?  I don't think so, but I'm less confident.
![slider2](https://user-images.githubusercontent.com/41024075/44808813-6bf73600-ab8a-11e8-8326-21dcaf220748.PNG)
Per @jonathanolson 
"That’s interesting. In the code, it is almost assuredly NOT treated as a slider, although for its a11y code it will probably want to ACT like a slider."

**Comment by phet-steele** [comment]
> going through phettest, but if there are any that are in early stages of development I might miss them.

@KatieWoe phettest would include sims in the earliest of stages,

**Comment by KatieWoe** [comment]
Other Sims from Phettest:
(Possibly Blackbody Spectrum.  Same question as https://github.com/phetsims/sun/issues/385#issuecomment-417065378)
Curve Fitting
Energy Forms and Changes
Graphing Quadratics

**Comment by KatieWoe** [comment]
These are all the ones I was able to find.

**Comment by pixelzoom** [comment]
Thanks @KatieWoe.  Both published and unpublished (what you did) is great. 

FYI, pH Scale example will most definitely not be implemented using a VSlider.   It's a very special "one off" design.  It's a11y behavior will probably be similar to a VSlider, but I would expect it to be somewhat different (again) because of it's unique design.

Back to me.

**Comment by pixelzoom** [comment]
We'll ignore blackbody-spectrum for the same reason as pH Scale.  It's slider is a special "one off" design.

**Comment by pixelzoom** [comment]
Visual guide to vertical sliders in PhET sims

capacitor-lab-basics
![screenshot_723](https://user-images.githubusercontent.com/3046552/44926055-742bae80-ad0d-11e8-9ff4-77ec282c4951.png)

color-vision
![screenshot_724](https://user-images.githubusercontent.com/3046552/44926087-8f96b980-ad0d-11e8-80e6-9dd707fc93ca.png)

curve-fitting
![screenshot_725](https://user-images.githubusercontent.com/3046552/44926128-b05f0f00-ad0d-11e8-9c03-62d4246879b6.png)

energy-forms-and-changes
![screenshot_726](https://user-images.githubusercontent.com/3046552/44926186-dbe1f980-ad0d-11e8-8766-192c31b46735.png)
![screenshot_727](https://user-images.githubusercontent.com/3046552/44926188-df758080-ad0d-11e8-9b8f-973a7ec3db4e.png)

graphing-quadratics
![screenshot_728](https://user-images.githubusercontent.com/3046552/44926212-f1efba00-ad0d-11e8-9f4a-bb27257dadb5.png)

gravity-and-orbits
![screenshot_730](https://user-images.githubusercontent.com/3046552/44926253-121f7900-ad0e-11e8-92e1-311b58d655e6.png)

least-squares-regression
![screenshot_731](https://user-images.githubusercontent.com/3046552/44926294-3418fb80-ad0e-11e8-8a9d-9811e3985a5d.png)

molarity
![screenshot_732](https://user-images.githubusercontent.com/3046552/44926322-46933500-ad0e-11e8-99dd-809d270d4182.png)

neuron
![screenshot_733](https://user-images.githubusercontent.com/3046552/44926357-5dd22280-ad0e-11e8-9905-a94a57e33cd3.png)

ohms-law
![screenshot_734](https://user-images.githubusercontent.com/3046552/44926403-89550d00-ad0e-11e8-9fed-d1abfaab9483.png)

resistance-in-a-wire
![screenshot_735](https://user-images.githubusercontent.com/3046552/44926424-9c67dd00-ad0e-11e8-9698-2644d67e27f6.png)

states-of-matter, states-of-matter-basics
![screenshot_736](https://user-images.githubusercontent.com/3046552/44926471-c1f4e680-ad0e-11e8-9799-b9f7d6f5f760.png)

**Comment by pixelzoom** [comment]
After completing the initial work (see https://github.com/phetsims/sun/issues/380#issuecomment-417798090), I also noticed that all sims with vertical sliders have their labels on the left, and that is consistent with the current implementation.   So I'm going to propose that we don't make any additional enhancements related to tick marks until they are actually needed.  @ariel-phet does that sound reasonable?

**Comment by pixelzoom** [comment]
Moving the requirements issue to https://github.com/phetsims/sun/issues/385.

**Comment by pixelzoom** [comment]
All sims that were identified have been converted to VSlider.   On Slack I announced:

> Chris Malley [4:45 PM]
All sims with vertical sliders have been converted to use VSlider.  If you’re responsible for one of the sims listed in https://github.com/phetsims/sun/issues/385, you may wish to review.

Closing.
