### ISSUE TITLE
Checkbox.js doesn't have a public enabled Property

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#387]
found while working on https://github.com/phetsims/forces-and-motion-basics/issues/258.

in FAMB's MotionControlPanel, there was code creating what we not refer to as a "subProperty" to publically expose the checkbox's enabled value over the phet-io interface. As part of that issue I removed support for that, because I think it should be managed generally from this issue instead. @samreid we just deleted CheckboxIO, so perhaps we should just convert the property to a Property in `Checkbox.js`?

**Comment by zepumph** [comment]
NOTE: (I found this because I was using the new API diff tool!! http://localhost/phet-io-wrappers/api-diff/index.html?sim=forces-and-motion-basics&ea&otherClientURL=http://localhost/forces-and-motion-basics/build/phet-io/lib/phet-io.js)

**Comment by samreid** [comment]
Yes, Checkbox.js should have an instrumented `enabledProperty`.  Unassigning self, but reassign me if I should work on this.

**Comment by zepumph** [comment]
Faradays Law has checkbox, but I don't think this needs to be done for FL stable. Keeping at no priority.

**Comment by pixelzoom** [comment]
See ComboBox or NumberSpinner for the pattern used to add enabledProperty.

**Comment by pixelzoom** [comment]
If no one objects, I'll handle this, since I've been in Checkbox a bit today.

**Comment by zepumph** [comment]
>Note that if the client decides to provide options.enabledProperty, then it's the client's responsibility to instrument that BooleanProperty.

We ran into something like that for the Property the checkbox was toggling, as I added an assertion for it here too.


Beyond than I just added instance documentation and made sure `phetioReadOnly` was passed as a child as expected. I think we are good to close. Thanks for taking the lead on it @pixelzoom. It looks great.
