### ISSUE TITLE
Checkbox dispose cleanup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#393]
Introduced in https://github.com/phetsims/sun/commit/80548d6c4b0eccbdd8ede835cceee5f754aae9a2 by @zepumph.  

```js
    this.disposeCheckbox = function() {
      this.removeInputListener( checkboxButtonListener );
      this.removeAccessibleInputListener( changeListener );
      property.unlink( checkboxCheckedListener );
      toggledEmitter.dispose();
    };
```

Inside the function, `this` should be `self`.   I guess no one is disposing any Checkboxes, because this would have failed hard. 

I'll fix this.

**Comment by pixelzoom** [comment]
Fixed, closing.

**Comment by zepumph** [comment]
@pixelzoom thanks for handling this. I'm curious about https://github.com/phetsims/sun/commit/a171d3ee332d4a5bd262d6a53af15c539631d970, 

Why do we not need to remove listeners internal to the file, and why do we not need to dispose things like the toggledEmitter? 

For phet-io I think that the tandem will not be unregistered unless dispose is called. What are your thoughts?

**Comment by pixelzoom** [comment]
> Why do we not need to remove listeners internal to the file, and why do we not need to dispose things like the toggledEmitter?

You don't need to dispose of something that the Checkbox owns and that's not publicly accessible.  Those things will not result in references to a Checkbox instance, which is what constitutes a memory leak.  For example, `toggledEmitter` is entire private to the internal of CheckBox, so there's no way that it can result in a memory leak.   Ditto for `checkboxButtonListener` and `changeListener`.

> For phet-io I think that the tandem will not be unregistered unless dispose is called. What are your thoughts?

Good point. We'll need to determine whether the client provided `enabledProperty` or whether we're using the default.  If using the default, Checkbox will need to call `enabledProperty.dispose`.

**Comment by zepumph** [comment]
>You don't need to dispose of something that the Checkbox owns and that's not publicly accessible. Those things will not result in "held" references to a Checkbox instance, which is what constitutes a memory leak. For example, toggledEmitter is entirely private to the internals of CheckBox, so there's no way that it can result in a memory leak. Ditto for checkboxButtonListener and changeListener.

There is a tandem in the toggledEmitter as well, so a dispose call will be needed there too I think.

**Comment by pixelzoom** [comment]
The commit above handles disposal of enabledProperty (if the Checkbox owns it) and toggleEmitter.

**Comment by zepumph** [comment]
That looks great, and contains proper and thorough documentation. Thanks!
