### ISSUE TITLE
Avoid assertions when removing a listener from a disposed object

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#394]
In https://github.com/phetsims/sun/issues/121, we've been adding `dispose` to sun and scenery-phet components.   The way that `dispose` has been implemented has introduced an ordering dependency, and I'm proposing that we should be calling `hasListener` before doing `unlink`, `removeListener`, etc. 

Here's an example of the pattern that's been followed so far:

```js
/**
 * @param {Property} someProperty
 * @constructor
 */
function SomeType( someProperty ) {

  ...

  var someListener = function() {...};
  someProperty.link( someListener );

  // @private called by dispose
  this.disposeSomeType( function() {
    someProperty.unlink( someListener );
  } );
}

return inherit( ..., SomeType, {

  // @public
  dispose: function() { this.disposeSomeType(); }
} );
```

The above implementation introduces an ordering dependency.  If the client's order of operations is like this (dispose in opposite order of construction), then everything is OK:

```js
var someProperty = new Property(...);
var someType = new SomeType( someProperty );
...
someType.dispose();
someProperty.dispose();
```

But if the client's order of operations is like this, then there will be an assertion failure with message 'tried to removeListener on something that wasn\'t a listener'.
 
```js
var someProperty = new Property(...);
var someType = new SomeType( someProperty );
...
someProperty.dispose();
someType.dispose();
```

So before calling `unlink`, `removeListener`, etc., I think it's important to check `hasListener`. For the example above should be:

```js
   this.disposeSomeType( function() {
    if ( someProperty.hasListener( someListener ) ) {
      someProperty.unlink( someListener );
    }
   } );
```

Another example is in scenery-phet.FaucetNode:

```js
    // @private called by dispose
    this.disposeFaucetNode = function() {

      // Properties
      if ( options.interactiveProperty.hasListener( interactiveObserver ) ) {
        options.interactiveProperty.unlink( interactiveObserver );
      }
      if ( flowRateProperty.hasListener( flowRateObserver ) ) {
        flowRateProperty.unlink( flowRateObserver );
      }
      if ( enabledProperty.hasListener( enabledObserver ) ) {
        enabledProperty.unlink( enabledObserver );
      }

      // Subcomponents
      if ( shooterNode.hasInputListener( inputListener ) ) {
        shooterNode.removeInputListener( inputListener );
      }
      shooterNode.dispose();

      self.disposeAccessibleSlider();
    };
```

**Comment by samreid** [comment]
All the extra `hasListener` listener calls seem like a drag ,but it seems like we must choose between that and requiring clients to dispose in the reverse order of creation.  Can we live with this ordering dependency, or are there cases we can't accommodate it?

**Comment by pixelzoom** [comment]
Memory management is always a drag, as are the extra steps to write robust code.

-1 for relying on client to reverse the order.  That's not at all robust. It won't work in at least one case, DerivedProperty.   And some PhET repos (e.g. `sun`, were this issue is prevalent) are supposed to be usable outside of PhET.  

If we're not going to perform the `hasListener` checks, then perhaps `unlink`, `removeListener`, etc. should perform the `hasListener` check and do nothing if `false`.

**Comment by samreid** [comment]
> If we're not going to perform the `hasListener` checks, then perhaps `unlink`, `removeListener`, etc. should perform the `hasListener` check and do nothing if `false`.

That sounds more palatable than proliferating `hasListener` checks everywhere, but we would lose error checking in places where listeners might be removed at the wrong times. I checked `unlink` and it says:

```js
      /**
       * Removes a listener. If listener is not registered, this is a no-op.
       *
       * @param {function} listener
       * @public
       */
      unlink: function( listener ) {
        this.changedEmitter.removeListener( listener );
      },
```

So we were at least thinking of that behavior at one time.  Emitter.removeListener currently reads:

```js
    /**
     * Removes a listener
     * @param {function} listener
     * @public
     */
    removeListener: function( listener ) {

      var index = this.listeners.indexOf( listener );
      assert && assert( index >= 0, 'tried to removeListener on something that wasn\'t a listener' );

      // If callbacks are in progress, make a copy of the current list of listeners--the removed listener
      // will remain in the list and receive a callback for this emit call, see #72
      this.defendCallbacks();

      this.listeners.splice( index, 1 );
    },
```

**Comment by jonathanolson** [comment]
> and I'm proposing that we should be calling hasListener before doing unlink, removeListener, etc.

If we're following that pattern everywhere, can't we just revert to a no-op when trying to remove a listener that doesn't exist, so we don't have to add boilerplate around everything? What is our past "require hasListener checks()" decision giving us?

**Comment by pixelzoom** [comment]
As I said in https://github.com/phetsims/sun/issues/394#issuecomment-418908819:
> If we're not going to perform the hasListener checks, then perhaps unlink, removeListener, etc. should perform the hasListener check and do nothing if false.

**Comment by jonathanolson** [comment]
Understood. Original discussion is in https://github.com/phetsims/axon/issues/129 if we want to consider reverting.

**Comment by jbphet** [comment]
Discussed in today's "extra" dev meeting, we decided to try skipping the assert on an unlink of a function that is not a listener if the property was already disposed.  I'll implement.

**Comment by jbphet** [comment]
This should be implemented in all things that have a means of unregistering listeners, such as Emitter, DerivedProperty, Node.

**Comment by jonathanolson** [comment]
Handled for Node, unassigning.

**Comment by jessegreenberg** [comment]
@zepumph and I did this for dependencies of DerivedProperty in its dispose in the above commit because we were running into this issue while working on https://github.com/phetsims/scenery/issues/831. @jbphet can you please take a look at this commit as you work on this?

**Comment by zepumph** [comment]
After a decently large conversation on slack with @jonathanolson, @chrisklus, and @samreid, it was potentially recommended that we should handle this on a lower level, either in Property.unlink, or Emitter.removeListener. @jbphet I'll be curious where you end up putting this check.

**Comment by jessegreenberg** [comment]
I encountered this again while trying to dispose a Multilink, I believe the above commit is in line with https://github.com/phetsims/sun/issues/394#issuecomment-419998978. @jbphet can you please take a look?

**Comment by chrisklus** [comment]
@jessegreenberg I've been using this pattern regarding your commit above, since the dependency can not be disposed but can already be unlinked:

```js
if ( dependency.hasListener( this.dependencyListeners[ i ] ) ) {
  dependency.unlink( this.dependencyListeners[ i ] );
}
```

**Comment by samreid** [comment]
In the preceding commit, it is now no longer an assertion error to remove an unregistered listener from a disposed Emitter.  That code was leveraged by Property, so there was no extra case to handle for Property.  However, I did realized that Property.dispose was not calling `changedEmitter.dispose`, and that has also been added in the preceding commit.  We have never disposed the `changedEmitter` before and I was worried it could cause systemic problems (because there may have been buggy code relying on it), but local aqua testing has made it through >30 fuzz tests without any noted problems, so I decided to commit.  This will require a review, @ariel-phet can you please recommend a reviewer?

**Comment by ariel-phet** [comment]
@chrisklus since you have some dispose experience now, asking you to review. Let me know if that doesn't work for you.

**Comment by chrisklus** [comment]
Looks good @samreid. The change makes sense to me and I'm also not having any issues with local testing. Back to you.

**Comment by samreid** [comment]
Since we added this feature for Node and Emitter, and Property picked up this feature due to its usage of Emitter, this issue is complete, closing.
