### ISSUE TITLE
Convert TypeIOs that have the fire event to use the Emitter pattern

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#396]
From https://github.com/phetsims/axon/issues/180, we want to keep cranking away at TypeIOs that only exist to allow the type to have events on the data stream. Here is the current list of files that contain: `events: [ 'fired' ]`:

- [x] MenuItemIO
- [x] ComboBoxItemNodeIO
- [x] AquaRadioButtonIO
- [x] ScreenButtonIO
- [x] NavigationBarScreenButtonIO
- [x] JoistButtonIO
- [x] PeriodicTableCellIO
- [x] BarrierRectangleIO
- [x] TwoSceneSelectionNodeIO
- [x] MomentaryButtonModel's press/release events are redundant to the PressListener's.

Some of these may depend on buttonModels that already use the sun button hierarchy and PressListener, which means that they probably don't need much work to be deleted (i.e. JoistButtonIO is not needed at all right now, and I'm going to delete it right now). Others will need a manual conversion and a dedicated emitter. I'm going to add the chip-away, as well as tag @samreid for comment, and @pixelzoom so he is aware because he shared concern about this pattern in https://github.com/phetsims/sun/issues/395.

**Comment by samreid** [comment]
The Joist things will need to be addressed before Faraday's Law is ready to go.

**Comment by samreid** [comment]
@zepumph I was looking into TwoSceneSelectionNodeIO and it was unclear whether we should add an Emitter or just instrument `DownUpListener`, can you please review and make a recommendation?

**Comment by zepumph** [comment]
I think we need to have a conversation soon about whether or not it is enough to just have the scenery listeners instrumented (FireListener, PressListener, DragListener). For something like the TwoSceneSelectionNode, it emits the "fire" event, so likely we should have the `FireListener` emit that event (as well as the events from the parent `PressListener`. This doesn't answer the question for policy on types with events that don't belong in these types, like a checkbox's "toggled" event. In general I think that the more we can move into scenery in a maintainable and clear way (like we clearly can for buttons), the better.

**Comment by samreid** [comment]
Perhaps TwoSceneSelectionNode and types like it can leverage FireListener.  In that case, they would not need to add their own `firedEmitter`, since there would already be a `fire` event from the `FireListener`.  In other news, we should add a `firedEmitter` to `FireListener`.

Should ButtonModel subtypes return a different PressListener subtype?

Likewise AquaRadioButton is using scenery/input/ButtonListener, but it should probably switch to use FireListener.

Here are some notes about the input listener types:

```
New ones.  They don't extend PhetioObject because they have nested Emitters instead.
PressListener
 FireListener
 DragListener

Old ones:
PhetioObject
 DownUpListener
  ButtonListener
  FireOnHoldInputListener
PhetiObject
 SimpleDragHandler
```

Will it be tricky to revisit old simulations and update them to use `Emitter` and `Property`, which are now our foundational PhET-iO types?

Recently we converted a bunch of types to extend PhetioObject, but now we are finding that mainly we need 2 types: Emitter, Property.   We are wondering where to draw the line between creating an IO type vs creating nested Emitters and Properties.  Also, is Property just made of Emitters anyways (many behaviors can be obtained from its changedEmitter).

**Comment by samreid** [comment]
I have a proposed change in the aforementioned issue.  I'm inclined to hold off on other changes until that review is complete, in case it changes how we proceed.

**Comment by samreid** [comment]
Hold removed since https://github.com/phetsims/sun/issues/401 is complete.

**Comment by zepumph** [comment]
We only want to publish new simulations with a consistent data stream, so a specific sim should be considered blocked if it uses a file above that hasn't been converted yet.

**Comment by samreid** [comment]
I converted TwoSceneSelectionNode to use Emitter.  It used other features of DownUpListener, so I decided against going to FireListener for that case for now.

**Comment by samreid** [comment]
NavigationBarScreenButton was already using `firedEmitter`, I removed the IO type.

**Comment by samreid** [comment]
I finished the work prescribed in the initial comment, and added notes to https://github.com/phetsims/sun/issues/405 about potential improvements.  @zepumph can you please review the changes?  If all is well, please close.

**Comment by zepumph** [comment]
I'm worried about https://github.com/phetsims/shred/commit/c30d8954b98b7eef217eebb17627bf36890a3614#diff-cb5347fd7b352b8575364a3e2beec3faR73. 

I went down that road once with `pressListener` (which ftr is the parent to `FireListener`). and we ran into naming conflicts. It was decided that it is best to separate these tandems out. It makes the most sense to instrument it with a tandem like `fireListener`, because otherwise we don't really know how to distinguish the difference between that and a 'pressListener' in studio.

**Comment by samreid** [comment]
To clarify, you are recommending to use `createTandem` rather than passing the tandem through directly?

**Comment by zepumph** [comment]
That's right. Although we have done some hackary with that before between view and model types. This is a sub component, a listener, that is added to the Node. We decided it should be its own phetioID. If we want to reopen that discussion. I recommend a new issue for it.

**Comment by samreid** [comment]
I specified `createTandem` in the preceding commits, can you please verify?

**Comment by samreid** [comment]
@zepumph and I discussed when it is appropriate to use `createTandem` and created https://github.com/phetsims/phet-io/issues/1392 to discuss further.

**Comment by zepumph** [comment]
@samreid, since https://github.com/phetsims/sun/issues/396#issuecomment-429187432 I think this issue is ready to close. What do you think?

**Comment by samreid** [comment]
Agreed, thanks, closing.
