### ISSUE TITLE
Radio Buttons (design and implement)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#4]

**Comment by samreid** [comment]
No plans to work on this at the moment, others feel free.

**Comment by samreid** [comment]
> RadioButtonGroup is one type of radio button. So no, finishing #119 does not resolve this issue. I will review RadioButtonGroup, but there is much to be done on "radio buttons".

@pixelzoom please open a new issue describing any outstanding work to be done for radio buttons (if any).

**Comment by pixelzoom** [comment]
Outstanding work:

• Are there other types of radio buttons that would be useful for PhET sims? That was the "design" part of this issue before it became the "implement RadioButtonGroup" issue.  I see no evidence the general design discussion was completed.

• Do we need 3D vs flat look for radio buttons, as we have for other buttons?

• Why don't radio buttons use the sun "button" framework?  That was recommended by @samreid in https://github.com/phetsims/sun/issues/4#issuecomment-54641929 and didn't happen - why? 

• We have RadioButtonGroup and VerticalAquaRadioButtonGroup. Do we really need different "Group" containers for different types of buttons?  (See also https://github.com/phetsims/sun/issues/30).

• Why are some radio button is sun/buttons/ while others are in sun/?

• We currently have supertype `RadioButton` described as "Base type for radio buttons".  It is not used by RadioButtonGroup - by mistake or on purpose?  Is this still a legitimate base type? 

... And I could probably come up with more.  Yes, radio buttons are usable.  No, their implementation is not in a good final state.

**Comment by samreid** [comment]
I'm inclined to turn each of the bullets from https://github.com/phetsims/sun/issues/4#issuecomment-245349626 into separate issues and close this one.  All opposed?  All in favor?

**Comment by samreid** [comment]
Meeting consensus: let's make each a separate issue

**Comment by samreid** [comment]
New issues noted above, closing.
