### ISSUE TITLE
layout problem with AccordionBox title

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#400]
While working on Graphing Quadratics, I encountered a layout problem with the title in AccordionBox.  Here's a minimal example:

```js
new AccordionBox( new Rectangle( 0, 0, 100, 100, { fill: 'red' } ), {
    titleNode: new Text( 'Quadratic Terms', { font: new PhetFont( 22 ) } ),
    titleYMargin: 10,
    buttonLength: 25,
    buttonXMargin: 10,
    contentXMargin: 20,
    contentYMargin: 10
} );
```

which results in:

![screenshot_756](https://user-images.githubusercontent.com/3046552/45646847-b7ae4880-ba81-11e8-850d-f3b4947537bb.png)

**Comment by pixelzoom** [comment]
If I change default `titleAlignX: 'center'` to `titleAlignX: 'left'`, then the problem goes away.  That is, there is no overlap of the button and title.  So the layout code for center alignment is undoubtedly buggy, probably not checking `titleXSpacing` etc.

I'm not going to investigate this further because (a) `titleAlignX: 'left'` meets the needs of Graphing Quadratics, and (b) I don't have the time for this diversion.   Since the bug is in an important common-code component, highly recommended to address sooner rather than later.  Assigning to @ariel-phet to prioritize and assign.

**Comment by ariel-phet** [comment]
@Denz1994 giving this one to you. Probably good to investigate on your own and then work with @jonathanolson when you have a proposed solution.

**Comment by zepumph** [comment]
@pixelzoom should this be marked as block-publication for GQ, or did your work bypass this entirely for GQ?

**Comment by pixelzoom** [comment]
I bypassed this in GQ by using `titleAlignX: 'left'` as described in https://github.com/phetsims/sun/issues/400#issuecomment-422152834.

**Comment by Denz1994** [comment]
After review with @jonathanolson, we were able to add some logic that compares the necessary space for the title section of the accordion box to the content section. The width of the box is dependent on the larger of the two sections. With the addition of this logic the below image was produced using the code described in https://github.com/phetsims/sun/issues/400#issue-361020376

![image](https://user-images.githubusercontent.com/13894380/47453606-2d04eb80-d79b-11e8-87ce-4a65741f8b78.png)

Reassigning to @pixelzoom for testing in Graphing Quadratics or further input.

**Comment by pixelzoom** [comment]
I'll try to get this reviewed sometime the week of 10/29/18.

**Comment by pixelzoom** [comment]
This fix looks good, and I tested it in both sun demo and Graphing Quadratics. I decided to continue to use `titleAlignX: 'left'` in GRAPHING_QUADRATICS/QuadraticTermsAccordionBox, since it makes more sense for that case.
