### ISSUE TITLE
AquaRadioButton should use FireListener

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#401]
From https://github.com/phetsims/sun/issues/396, AquaRadioButton should no longer emit its own `phetioStartEvent('fired')` event, but should use the `FireListener`.  This means `FireListener` will need a `firedEmitter` which sends `'user'` messages and that `FireListener.release` will need to use the same callback pattern we exercised in `FireListener.press`.  These are nontrivial changes to `AquaRadioButton` which is widely used and `FireListener` which will be widely used, so will need a code review. I'll make the changes in master because they will touch several repos.

**Comment by samreid** [comment]
I've converted AquaRadioButton to use FireListener in my working copy.  I also removed AquaRadioButtonIO and its usages.

Lint is passing and the button behavior and phet-io data stream looks correct for Beer's Law Lab's AquaRadioButtons.  I also fuzz tested a few sims with AquaRadioButtons and they seemed OK.  I tested that the previous AquaRadioButton behavior of fire on release is preserved.

I decided to commit to master since the changes span several repos.  

I'd like to mark this issue as blocking until review is complete.  We shouldn't publish any sims with AquaRadioButton or FiredEmitter until this is reviewed and approved.  @zepumph are you available for review?

**Comment by samreid** [comment]
Also, here's the data stream from Beer's Law Lab: colorized when clicking on the solution radio button:

![image](https://user-images.githubusercontent.com/679486/45728916-638d8c00-bb87-11e8-9c3e-eead8fcfe154.png)

**Comment by zepumph** [comment]
Thoughts:

* As it pertains to the instrumentation of FireListener, at first I was wondering about only adding a listener sometimes, but always instrumenting the Emitter. Would it ever be strange to get a fire event without there being a fire callback to create downstream errors? 
* In Emitter is it weird to emit an event publicly to the data stream if there aren't any listeners attached that Emitter?
* It is worth noting, though maybe not worth investigating/fixing, that we lost support for phet-io when a11y causes the fire. FireListener has a build in a11y listener for click ( that it gets from PressListener), but it is different from what we need here (change event)


In general this is a good strategy. I don't know much about older listeners like those in `scenery/js/input` but I think that, when possible, we should convert them to use those in `scenery/js/listeners` so long as @jonathanolson thinks that's a good idea.

**Comment by samreid** [comment]
> at first I was wondering about only adding a listener sometimes, but always instrumenting the Emitter.

It seems FireListener should always have a firedEmitter as part of its schema.  By that token, maybe FireListener should require that `fire` is passed in?

> Would it ever be strange to get a fire event without there being a fire callback to create downstream errors?

Did you mean downstream events?  I think most or all FireListeners will have a `fire`, and maybe it should even be required.  

> In Emitter is it weird to emit an event publicly to the data stream if there aren't any listeners attached that Emitter?

In Arithmetic, it was valuable for us to have an emitter that signifies guesses, even if it doesn't trigger downstream events.

> we lost support for phet-io when a11y causes the fire.

Can you please create a new issue for that?  I'd like to understand it better and we may need to address it.

**Comment by zepumph** [comment]
@samreid anything else for this issue?

**Comment by samreid** [comment]
Thanks @zepumph, I created a new issue mentioned above, and closing this one.
