### ISSUE TITLE
support decoration of VSlider

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#406]
In the current implementation, Slider is drawn in the horizontal orientation, and rotates -Math.PI / 2 if the orientation is vertical (for VSlider).  This presents problems if you want to decorate a vertical slider; the child nodes are rotated and not located where you'd expect them to be.

For example, here's what happened in Graphing Quadratics when I attempted to add a child label to 3 VSliders:

![screenshot_789](https://user-images.githubusercontent.com/3046552/46923360-c716a800-cfd3-11e8-8e58-47b48ca31419.png)

The solution here is to wrap the rotated bits in a Node, and apply the rotation to the Node rather than the Slider directly.

**Comment by pixelzoom** [comment]
> The solution here is to wrap the rotated bits in a Node, and apply the rotation to the Node rather than the Slider directly.

Unfortunately it's not that easy.  The listener for the thumb ends up working incorrectly.

**Comment by pixelzoom** [comment]
I have this pretty much working for Slider.  I've added an intermediate Node whose children are the components of the Slider (thumb, track, ticks,...).  For a vertical slider, I'm rotating that intermediate Node instead of the Slider.

But I'm running into a problem with a11y.  For a Slider with `orientation: 'vertical'`, it seems to still think that the Slider is horizontal.  Screenshot below is with from the sun demo with `?accessibility`.  The focus outline is for a horizontal thumb. And as I press the arrow keys, the focus outline moves left/right instead of up/down.

@jessegreenberg - help.

**Comment by pixelzoom** [comment]
Attached is a zipped patch file for Slider.js, corresponding to where I'm at as of https://github.com/phetsims/sun/issues/406#issuecomment-429686924.

[Slider-55.patch.zip](https://github.com/phetsims/sun/files/2477181/Slider-55.patch.zip)

**Comment by jessegreenberg** [comment]
This was a general problem with FocusHighlightFromNode, thanks for pointing out. After https://github.com/phetsims/scenery/issues/880 and removing this line in HSlider valueObserver
```js
self.focusHighlight.centerX = thumb.centerX;
```
the highlight looks good in the patch in https://github.com/phetsims/sun/issues/406#issuecomment-429687539. @pixelzoom can you pull scenery and confirm?

**Comment by pixelzoom** [comment]
Thanks for the quick fix @jessegreenberg.  Would you mind reviewing the above commit?  I tested with sun demo (HSlider and VSlider) and a random set of sims that use HSlider and VSlider.

**Comment by jessegreenberg** [comment]
This looks very nice, I reviewed the commit and spot tested a few sims. I also tested decorating a VSlider with nodes relative the slider bounds, all looked as expected.

Closing this issue.
