### ISSUE TITLE
Listbox focus lost when using Firefox 

### ISSUE THREAD

**Issue by terracoda** [phetsims/sun#409]
As reported in https://github.com/phetsims/sun/issues/314#event-1930530650, keyboard focus works great in Safari alone and in Safari with VoiceOver. However, I noticed that the keyboard interaction is not working in Firefox Quantum 62.0.3 on MacOS High Sierra 10.13.6

When I try to use the arrow keys on the popped up list of options the focus highlight gets lost. This was using Firefox without a screen reader.

**Comment by zepumph** [comment]
@terracoda this is pretty old, is this still an issue for ComboBox? Perhaps in Molarity?

**Comment by terracoda** [comment]
@zepumph, yes this was an issue related to molarity's combobox, and it has been fixed. Closing.
