### ISSUE TITLE
Keyboard nav continuous slider motion stops with new keypress

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/sun#414]
Found during https://github.com/phetsims/QA/issues/219
If you are manipulating a slider with shift + arrow and let go of shift, the slide continues with arrow sized steps.  However, if you start with arrow, and push shift down as it is moving, the slider stops entirely.  This also occurs if you push a letter key, such as a.

**Comment by KatieWoe** [comment]
Note: does not seem to occur on all platforms.  Seen on Win 10 chrome and chrome os, but not seen on Mac 10.14 chrome

**Comment by jessegreenberg** [comment]
Thanks for making an issue @KatieWoe. It surprised me, but this is actually how HTML sliders work, which is why PhET sliders work this way with a keyboard. For example this vanilla HTML slider: https://jsfiddle.net/8gh9mysx/

Going to close this issue.
