### ISSUE TITLE
misc Slider improvements

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#418]
From https://github.com/phetsims/graphing-quadratics/issues/112#issuecomment-439653505:

- [x] Slider's default for `options.enabledProperty` should be changed from `Property` to `BooleanProperty`.
- [x] We should add checks that `enabledPropertyOptions` and `enabledProperty` options are mutually exclusive. 

Also:

- [x] inadequate doc for options `enabledProperty`, `enabledPropertyOptions`, `enableRangeProperty`
- [x] no verification that default `enableRangeProperty` is valid for Slider `range`

**Comment by samreid** [comment]
I reviewed all changes in the commit, and it looks good, thanks, closing.
