### ISSUE TITLE
ComboBox: add align option

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#419]
ComboBox items are left aligned, with no option to do otherwise. 

When the items are numbers, it would better to right align them.   For example, here's how the Collision Counter currently looks in Gas Properties:

![screenshot_892](https://user-images.githubusercontent.com/3046552/49117951-bbb7cd00-f25f-11e8-9a80-dac27de52171.png)

Add `align` option, with values 'left' (default), 'right', 'center'.  

`align` should apply to both the popup list and the current value displayed on the button.

**Comment by pixelzoom** [comment]
This will also fix the alignment of temperature choices in Gas Properties. This combo box is currently composed of NumberDisplay items.   The NumberDisplay items have `align: 'left'`, but they have different widths.

![screenshot_893](https://user-images.githubusercontent.com/3046552/49117977-d427e780-f25f-11e8-9b6d-38bf17766ea3.png)

**Comment by pixelzoom** [comment]
The `align` option was added in the above commits, and `align: 'right'` is used in Gas Properties.  What I thought was going to be trivial was downright scary — ComboBox has gotten complicated. 

I tested with `?a11y` and the focus highlight still looks correct:

![screenshot_895](https://user-images.githubusercontent.com/3046552/49119706-9d090480-f266-11e8-9e79-951fc4f94981.png)

Randomly assigned to @jessegreenberg to review, which works out nicely since my primary concern is breaking a11y.

**Comment by jessegreenberg** [comment]
Changes look good @pixelzoom. I tested a few other comboboxes, the option worked as expected, focus highlights were correct and screen reader output was not changed.

![image](https://user-images.githubusercontent.com/6396244/49305044-1e95a800-f49c-11e8-94ae-61513992b281.png)

Closing.

**Comment by pixelzoom** [comment]
Reopening. This feature was broken during #430.

**Comment by pixelzoom** [comment]
Alignment was fixed in https://github.com/phetsims/sun/commit/b47526a0d1fff3b08778959b4161b29130fd22ec.  Closing.
