### ISSUE TITLE
Subtypes of ButtonModel need to update downProperty if the button valueProperty can be set externally

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/sun#421]
Related to https://github.com/phetsims/wave-interference/issues/228 and https://github.com/phetsims/ph-scale/issues/71. For subtypes of ButtonModel where the Property associated with the button can be set externally by the simulation, we need to make sure that buttonModel.downProperty updates correctly. Otherwise, the button may always look down if valueProperty is set outside of user interaction. See the gif in the wave-inteference issue above.

This is done correctly for MomentaryButtonModel, but now we need to do it for StickyToggleButtonModel and probably others.

**Comment by jessegreenberg** [comment]
I reviewed all the button models I could find
PushButtonModel
MomentaryButtonModel
StickyToggleButtonModel
ToggleButtonModel

and it looks like ToggleButtonModel is the last one that is missing this or needs it.

**Comment by jonathanolson** [comment]
Looks good to me!
