### ISSUE TITLE
ComboBox propagates all options to ButtonNode subcomponent

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#422]
ComboBox is currently propagating all of its options to ButtonNode subcomponent.  That's creating problems particularly with phetio options over in https://github.com/phetsims/sun/issues/405#issuecomment-447501021.  

Options should be either cherry-picked or nested, and only the relevant options should be passed to ButtonNode.

**Comment by pixelzoom** [comment]
This in ButtonNode constructor:

```js
// The ButtonNode is not instrumented
options.tandem = Tandem.optional;
```

... is a good example of the "write buggy code to fix some other bug" anti pattern.  This line was presumably added because ComboBox's `tandem` was being propagated to ButtonNode.  But when an attempt was made to pass a legitimate tandem in https://github.com/phetsims/sun/commit/c7d4466a45eb50bf3fb9c845fa09e9c8844f4664, that tandem would have been silently overwritten. 

In general, assignment to an option without a preceding assertion is a bad idea.  E.g.:

```js
// bad
options.children = [ ... ];

// good
assert && assert( !options.children, 'SomeType sets children' );
options.children = [ ... ];
```

**Comment by pixelzoom** [comment]
Presumably priority=high, since this is required for #405 which is also high.

**Comment by samreid** [comment]
@pixelzoom bravely volunteered to investigate.  Thanks!

**Comment by pixelzoom** [comment]
Removing the dev:phetio label, since this isn't specific to PhET-iO.  Options shouldn't be propagated this way in general.

**Comment by pixelzoom** [comment]
I briefly investigated nested options, but that would change the API, and I concluded that there were too many existing usages to change.  So I went with cherry picking options.  See the above commit. 

Tested with many sims that have a ComboBox.  Tested in Studio with Beer's Law Lab. 

@zepumph Would you mind reviewing, since this is a prerequisite to #405?

**Comment by zepumph** [comment]
sure thing

**Comment by pixelzoom** [comment]
While working on #430, I've come to the conclusion that cherry picking is not the way to go.  So I'm going to bite the bullet and nest options for ButtonNode and other subcomponents.  So assigning back to me.

**Comment by samreid** [comment]
> I've come to the conclusion that cherry picking is not the way to go.

Can you please document this in phet-info/doc/phet-software-design-patterns.md?

**Comment by pixelzoom** [comment]
@samreid Clarification: "cherry picking is not the way to go _in this case_".   I don't see any point in noting this case specifically in phet-software-design-patterns.md.   And I don't have any general conclusions to offer on when nesting is the way to go.  It may be better when the number of options for a subcomponent reaches some N, but I don't know what N is.

**Comment by pixelzoom** [comment]
In #430, the number of button options was reduced/reorganized to a manageable size.   The button-specific options to ComboBox are:

```js
      // button
      buttonFill: 'white',
      buttonStroke: 'black',
      buttonLineWidth: 1,
      arrowHeight: null, // {number|null} defaults to max item height
```

So I no longer feel that we need to nest these.  If/when the  number of options grows in the future, we can revisit with a new issue.  On that note, closing this issue.
