### ISSUE TITLE
Should Dialog have a "tapToClose" option?

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#427]
During https://github.com/phetsims/molecules-and-light/issues/185 @zepumph and I noticed that Molecules and Light has a feature where tapping the dialog dismisses it:

```js
// close it on a click
var self = this;
var buttonListener = new ButtonListener( {
  fire: self.hide.bind( self )
} );
this.addInputListener( buttonListener );
```

Should this feature be in SUN/Dialog?  Alternatively, should we remove this feature from Molecules and Light?

**Comment by pixelzoom** [comment]
No, I don't think this should be support by Dialog. Standard behavior should be:
(1) click the close button to close the dialog
(2) clicking anywhere outside the dialog is the same as clicking the close button

Yes, I would remove this feature from MAL.

**Comment by ariel-phet** [comment]
@jessegreenberg I am OK with removing from all those dialogs

**Comment by jessegreenberg** [comment]
OK, this has been removed from the Dialogs mentioned in https://github.com/phetsims/sun/issues/427#issuecomment-451026345. @samreid is there anything more to do for this issue?

**Comment by samreid** [comment]
@jessegreenberg what's this occurrence in KeyboardHelpDialog?  I'm not familiar with "click":

```js
    // @private (a11y) - input listener for the close button, must be disposed
    var clickListener = {
      click: function() {
        self.hide();
        self.focusActiveElement();
      }
    };
    this.addInputListener( clickListener );
```

**Comment by samreid** [comment]
@pixelzoom I found 2 more occurrences like this in Equality Explorer, OopsDialog and InfoDialog:

```js
    // Click anywhere on the dialog to hide it.
    this.addInputListener( new ButtonListener( {
      fire: function() { self.hide(); }
    } ) );
```

Would you like me to remove them?

**Comment by pixelzoom** [comment]
Remove from Equality Explorer in the above commit.

**Comment by jessegreenberg** [comment]
Thanks @samreid, removed https://github.com/phetsims/sun/issues/427#issuecomment-453371912. `click` is the event when a button is clicked. This was added when KeyboardHelpDialog had a custom close button, but now it uses the one in Dialog.

**Comment by samreid** [comment]
Looks great, thanks!  I can't find any other occurrences of this pattern, closing.
