### ISSUE TITLE
issues with CombBoxItemNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#429]
In https://github.com/phetsims/sun/commit/4f2abd3732be01eae231a7fc1739c1d0e406bc94, @zepumph renamed an inner class of ComboBox.  `ItemNode` was renamed to `ComboBoxItemNode`.

(1) What was the motivation for the name change?  Since this is an inner class, the "ComboBox" prefix is redundant, and `ItemNode` should be sufficient.  You didn't rename `ButtonNode` to `ComboBoxButtonNode` because that would be redundant.  Surely that applies to `ItemNode` too.

(2) If there is some value to the name change... The first argument to the namespace registration was not updated, it's still `sun.register( 'ComboBox.ItemNode', ComboBoxItemNode )`.  I'm surprised that this isn't causing an Error.

**Comment by zepumph** [comment]
>(1) What was the motivation for the name change? Since this is an inner class, the "ComboBox" prefix is redundant, and ItemNode should be sufficient. You didn't rename ButtonNode to ComboBoxButtonNode because that would be redundant. Surely that applies to ItemNode too.

As this commit was from back in 2016, likely it was before I comprehended the inner class quite as well. I agree it sounds redundant to me now.


>(2) If there is some value to the name change... The first argument to the namespace registration was not updated, it's still sun.register( 'ComboBox.ItemNode', ComboBoxItemNode ). I'm surprised that this isn't causing an Error.

Yeah I wonder if namespace could do a requirejs only check that the last element of the first arg split by period is the same name as the constructor name?

We should be able to get access to this as long as things aren't minified:
```js
class e {
}
-->undefined
e.name
-->"e"
var x = function(){
}
-->undefined
x.name
-->"x"
```

**Comment by pixelzoom** [comment]
Done, closing.
