### ISSUE TITLE
maxWidth for Dialog

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/sun#435]
In https://github.com/phetsims/joist/issues/546, we used maxWidth on KeyboardHelpDialog. The change used Dialog's optional layoutStrategy:
```js
      layoutStrategy: function( dialog, simBounds, screenBounds, scale ) {

        // empirically determined to have some margin relative to max width
        dialog.maxWidth = ( simBounds.width / scale ) * 0.90;

        // this is the default centering strategy in Dialog
        dialog.center = simBounds.center.times( 1.0 / scale );
      }
```

But `simBounds` is the global bounds of the simulation so the dialog can extend outside of dev bounds if there is space in wider screens. In https://github.com/phetsims/friction/issues/158 it was mentioned that this was odd because most dialogs are constrained to the dev bounds. Questions for developer meeting:

1) Is it OK for the KeyboardHelpDialog to extend outside of dev bounds when there is space on wider screens?
2) If not, is there a good general way we can restrict the dialog to dev bounds?
3) Is this something that all Dialogs should do? Most PhET dialogs are within dev bounds because content or Text in the Dialog have maxWidth set individually.

**Comment by jessegreenberg** [comment]
@zepumph and I hacked way to see what it would look like to constrain maxWidth to the dev bounds:
```js
      // the width of the KeyboardHelpDialog is constrained to the simulation bounds
      layoutStrategy: function( dialog, simBounds, screenBounds, scale ) {
        var layoutBounds = phet.joist.sim.screens[ 0 ].view.layoutBounds;

        // empirically determined to have some margin relative to max width
        dialog.maxWidth = layoutBounds.width * 0.90;

        // this is the default layout strategy in Dialog
        dialog.center = simBounds.center.times( 1.0 / scale );
      }
```

And ?with stringTest=xss the result looks like this:
![capture2](https://user-images.githubusercontent.com/6396244/50861367-6bf01980-1366-11e9-8f68-d84045929c75.PNG)

Allowing it to grow to simBounds looks like
![capture1](https://user-images.githubusercontent.com/6396244/50861384-80341680-1366-11e9-8ef4-4d5662137363.PNG)

I think using simBounds is better since it allows the Dialog content to be larger where possible.

**Comment by pixelzoom** [comment]
If a dialog is too big to fit in the layoutBounds, then a dialog is probably the wrong way to present the information. If dialogs are movable, I think it's acceptable for them to be partially outside of the layoutBounds.   If dialogs are not movable, then they should be fully within the layoutBounds.  That said...

> 1. Is it OK for the KeyboardHelpDialog to extend outside of dev bounds when there is space on wider screens?

OK for dialogs that can be moved. Not OK for dialogs that can't be moved, since the user might resize the browser window after the dialog has been displayed.

> 2. If not, is there a good general way we can restrict the dialog to dev bounds?

Yes - the same way that we restrict the drag bounds of things to be inside layoutBounds.

> 3. Is this something that all Dialogs should do? Most PhET dialogs are within dev bounds because content or Text in the Dialog have maxWidth set individually.

layoutBounds is configurable, and we don't want Dialogs to know specifics of ScreenView or layoutBounds.  So a Dialog's maxWidth should be set per Dialog.  And layoutBounds can be communicated via dragBounds, like we do for DragListener.

**Comment by zepumph** [comment]
>layoutBounds is configurable, and we don't want Dialogs to know specifics of ScreenView or layoutBounds. So a Dialog's maxWidth should be set per Dialog. And layoutBounds can be communicated via dragBounds, like we do for DragListener.

For non-moveable Dialogs wouldn't it be nice if there was a default so that we didn't always have to manage the max width by setting it based on the layoutBounds of the context for that Dialog?

**Comment by pixelzoom** [comment]
Default for max size of Dialogs would be nice. What I don't want to see is `new Dialog( {ScreenView},...)`.

**Comment by jessegreenberg** [comment]
> Not OK for dialogs that can't be moved, since the user might resize the browser window after the dialog has been displayed.

Dialog's layoutStrategy is called when the sim is resized, so this case should be covered.

**Comment by samreid** [comment]
@jonathanolson said its odd to set maxWidth on the dialog, because that will also scale the border stroke.  @jonathanolson said instead it is better to scale the contents.

@zepumph pointed out that is difficult because we need to know the margins in that case.

**Comment by zepumph** [comment]
@jessegreenberg I'm not sure what's next here, what do you think?

**Comment by jessegreenberg** [comment]
Sorry, I was supposed to write up consensus notes.

Dialogs should remain within dev bounds rather than sim bounds. It is generally problematic to set `maxWidth` on dialogs (or panels or layout boxes or anything other than Text) for i18n because this causes shrinking of *all* content, including icons. For example, see https://user-images.githubusercontent.com/6396244/50861367-6bf01980-1366-11e9-8f68-d84045929c75.PNG for an example of the icons that have become more difficult to see after reducing their size.

For i18n we should generally only use `maxWidth` on Text. Unfortunately, this means we will need to do custom `maxWidth` setting for most labels from scenery-phet/HelpContent since they will have different contents and layouts.

It was discussed that we can have something like the proposal in https://github.com/phetsims/sun/issues/435#issue-397102821 as a safety net. But if we don't want the Dialog to be scaled down this way, I don't see much benefit in doing that. So I think we should remove the layoutStrategy in KeyboardHelpDialog.

**Comment by jessegreenberg** [comment]
It has been removed. We can continue in https://github.com/phetsims/friction/issues/158 and https://github.com/phetsims/resistance-in-a-wire/issues/203 which started this issue to set the maxWidth of the dialog content correctly. Closing.
