### ISSUE TITLE
Move Dialog to ES6

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#437]
As a prelude to further work in https://github.com/phetsims/sun/issues/369, I'd like to see Dialog in ES6.  I'll do that as a preliminary step.

UPDATE: There are 15 occurrences of `Dialog.call( this, ... )`, so we won't be able to use `class` until those cases are changed as well.  According to the conversation in https://github.com/phetsims/phet-info/issues/89 it is acceptable to port everything to ES6 except for the `inherit` part.

**Comment by zepumph** [comment]
* One potential improvement would be to make the internal type a class, but that may be confusing. 

* I also prefer curly braces for scope if the arrow function is more than a one-liner. What do you think about the above commit?

* I removed function keyword from inherit call methods, how does that seem to you?

**Comment by samreid** [comment]
> One potential improvement would be to make the internal type a class, but that may be confusing.

I think `function CloseButton( options ) {` should be deleted and replaced with usage of `scenery-phet/js/buttons/CloseButton.js`.  If you agree, let's open a new issue for that.

> I also prefer curly braces for scope if the arrow function is more than a one-liner. What do you think about the above commit?

No strong preference.

> I removed function keyword from inherit call methods, how does that seem to you?

Looks great!

**Comment by zepumph** [comment]
I created #486. Closing
