### ISSUE TITLE
Dialog.setAccessibleViewsVisible should be moved back to Joist

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#442]
Discovered in https://github.com/phetsims/sun/issues/369.  Dialog currently has:

```js

    /**
     * Hide or show all accessible content related to the sim ScreenViews, navigation bar, and alert content. Instead
     * of using setVisible, we have to remove the subtree of accessible content from each view element in order to
     * prevent an IE11 bug where content remains invisible in the accessibility tree, see
     * https://github.com/phetsims/john-travoltage/issues/247
     *
     * @param {boolean} visible
     * @private
     */
    setAccessibleViewsVisible( visible ) {
      for ( let i = 0; i < this.sim.screens.length; i++ ) {
        this.sim.screens[ i ].view.accessibleVisible = visible;
      }
      this.sim.navigationBar.accessibleVisible = visible;
      this.sim.homeScreen && this.sim.homeScreen.view.setAccessibleVisible( visible );

      // workaround for a strange Edge bug where this child of the navigation bar remains visible,
      // see https://github.com/phetsims/a11y-research/issues/30
      if ( this.sim.navigationBar.keyboardHelpButton ) {
        this.sim.navigationBar.keyboardHelpButton.accessibleVisible = visible;
      }
    },
```

This leverages too much detail work in joist and should be encapsulated somewhere in Joist.  Perhaps move `setAccessibleViewsVisible` to `Sim.js`?  @jessegreenberg can you please take a look?

**Comment by jessegreenberg** [comment]
Agreed. Furthermore, the workaround in this function is likely not required anymore after https://github.com/phetsims/a11y-research/issues/30

**Comment by jessegreenberg** [comment]
> we have to remove the subtree of accessible content from each view element in order to prevent an IE11 bug where content remains invisible in the accessibility tree,

Same for this line, we aren't doing this anymore.

**Comment by jessegreenberg** [comment]
And this should only be happening for modal Dialogs, it was a coincidence that Dialog only supports modal dialogs at the moment.

**Comment by jessegreenberg** [comment]
I verified that the workaround is not necessary in Edge anymore.

**Comment by jessegreenberg** [comment]
I thought about setAccessibleViewsVisible for non-modal dialogs briefly but decided not to go further until we support non-modal dialogs at all.

@samreid would you mind reviewing these changes?

**Comment by samreid** [comment]
Looks good to me, though I'm not sure how to test it.  But I presume you have covered that part.   Closing.
