### ISSUE TITLE
Dialog.showCallback/hideCallback should be converted to Node.on('visibility');

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#443]
Discovered during https://github.com/phetsims/sun/issues/369, Dialog has a set of options `Dialog.showCallback/hideCallback` which are only used in one place, which is equality-explorer/js/solveit/view/SolveItSceneNode.js.  Pinging @pixelzoom since he is the lead developer for that simulation.  In https://github.com/phetsims/sun/issues/369#issuecomment-452744448 we discussed converting show/hide to setVisible(true/false).  This would allow us to eliminate showCallback/hideCallback and use Node.on('visibility') instead.

**Comment by pixelzoom** [comment]
Self-assigning so I remember to look at this.

**Comment by pixelzoom** [comment]
SolveItSceneNode.js uses VEGAS/RewardDialog.

Options:

(1) Create my own subclass of `RewardDialog` that overrides `setVisible`, and handle callbacks there.

(2) Move `showCallback` and `hideCallback` options into RewardDialog and have it override `setVisible`.  This is the preferred option if what I've done in EqEx is generally useful.

@samreid thoughts?

**Comment by samreid** [comment]
Why not simply use `on('visibility',...)` ?

**Comment by pixelzoom** [comment]
In the previous commit, I replaced `showCallback` and `hideCallback` with `on( 'visibility', ... )`.  One thing that I found odd is that I had to explicitly set RewardDialog's initial state to `visible: false` (line 304), or else I wasn't getting a notification when the dialog was first made visible.   Hopefully that isn't indicative of some problem with using `setVisible` for Dialog. 

Back to @samreid.

**Comment by samreid** [comment]
After discussion in https://github.com/phetsims/sun/issues/455 and #369, I don't think Dialog is using `'visibility'` at all, so SolveItSceneNode.js may not be working as expected.  Perhaps `Dialog.isShowingProperty` should be made public, or perhaps `showCallback` and `hideCallback` could be turned into TinyEmitters.

My apologies for the runaround, @pixelzoom can you please take a look?

**Comment by pixelzoom** [comment]
You're correct SolveItSceneNode.js appears to be broken. Running with `?rewardScore=1`, it's not showing the reward or the dialog. I've reverted the breaking change in that was made in https://github.com/phetsims/equality-explorer/commit/ad7d0190c0b9f276923c97df62548cbee66d42fc, see above commit.  SolveItSceneNode.js now uses `showCallback` and `hideCallback` again.

I don't see any obvious advantage in replacing `showCallback` and `hideCallback` with more heavyweight Emitters.  Making `Dialog.isShowingProperty` public seems reasonable, but you'll have to decide whether it's value is read-only or can be set (and therefore making it call `show` and `hide`, or replacing `show` and `hide`).

**Comment by samreid** [comment]
The existing implementation is clear and not causing any problems.  I think this issue should be closed.
