### ISSUE TITLE
what to do about ComboBox.createItem?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#450]
In #430, ComboBoxItem was created and ComboBox.createItem was documented as:

```js
  /**
   * Creates a combo box item. Provided for backward compatibility. Using new ComboBoxItem is preferred.
   * @param {Node} node
   * @param {*} value
   * @param {Object} [options] see ComboBoxItem
   * @returns {ComboBoxItem}
   * @public
   */
  ComboBox.createItem = ( node, value, options ) => {
    return new ComboBoxItem( node, value, options );
  };
```

Should we replace the 56 uses of `ComboBox.createItem(` with `new ComboBoxItem(`? It looks like we could do this with one string replacement operation.

Or should we just mark ComboBox.createItem as `@deprecrated`? 

Or do people still want to use `ComboBox.createItem`?

**Comment by jonathanolson** [comment]
Replacement with `new ComboBoxItem(` (and the additional import) sounds fine to me.

**Comment by pixelzoom** [comment]
1/17/19 dev meeting consensus:  OK to replace `ComboBox.createItem` with `new ComboBoxItem`.

**Comment by pixelzoom** [comment]
ComboBox.createItem is gone.  Closing.
