### ISSUE TITLE
optimize margin around ComboBoxButton's arrow button

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#453]
Discussed with @ariel-phet.

ComboBoxButton's `xMargin` and `yMargin` are currently applied to both the item and the arrow parts of the button.   But as `xMargin` increases, the margin around the arrow becomes unnecessarily large.  In general, we want to keep the arrow part of the button looking roughly square.   So...

I'll investigate computing the margin around the arrow so it looks square.  If that's not possible, I'll add an `arrowXMargin`.   I'd most definitely prefer the former.

**Comment by pixelzoom** [comment]
ComboBoxButton is now divided into 2 "areas" with a vertical separator between them.  

The "item area" is to the left of the separator and displays the selected item.  It's margin is determined by options `xMargin` and `yMargin`.

The "arrow area" is to the right of the separator and displays an up or down arrow, depending on the value of `options.arrowDirection`.  This area is a square whose side length is `maxItemLength + 2 * options.yMarin`.  The arrow is 0.35 * the side length (value was chosen by consulting with @ariel-phet).

This provides a uniform "look" for the button's arrow without requiring additional options.  With the change and the changes in #430, many margin-related options have been reduced to `xMargin` and `yMargin` for ComboBox and its subcomponents.

Example in BLL:

<img width="345" alt="screenshot_972" src="https://user-images.githubusercontent.com/3046552/51358400-3f33b480-1a80-11e9-9517-fd366356d8bb.png">

Examples in Gas Properties:

<img width="261" alt="screenshot_974" src="https://user-images.githubusercontent.com/3046552/51358410-52df1b00-1a80-11e9-9a72-375283637489.png">

Examples in scenery-phet demo:

<img width="552" alt="screenshot_973" src="https://user-images.githubusercontent.com/3046552/51358422-5d99b000-1a80-11e9-83ef-f9f2e6a9fe4f.png">

**Comment by pixelzoom** [comment]
@ariel-phet please assign someone to review.

**Comment by pixelzoom** [comment]
@ariel-phet ping. I'd like to get the ComboBox work wrapped up.

**Comment by Denz1994** [comment]
@pixelzoom These options look great. Just one note and close if this is a non-issue.

Setting `xMargin:0` and `yMargin:0` causes the edges ComboBoxListItemNode.highlightRectangle to extend beyond the edges of the `ComboListBox` if the `ComboListBox` has a `cornerRadius > 0`.

Perhaps this is a good time to pass `ComboBox.cornerRadius` to `ComboBoxListItemNode.highlightRectangle` via `const listItemNode = new ComboListItemNode(...)` in `ComboBoxListBox.js`

Here is an example in Gas-Properties:
![image](https://user-images.githubusercontent.com/13894380/51687776-3f243f00-1fc1-11e9-88ed-818501930c7d.png)

**Comment by Denz1994** [comment]
Accidently closed.

**Comment by pixelzoom** [comment]
Thanks @Denz1994, good suggestion about corner radius.

Changes in the above commit:

* I added `highlightCornerRadius` for ComboBoxListItemNode, and the same value is used for the button, listbox and items in the list.  I cleared this design change with @ariel-phet, he gave it a thumbs up.

* This made me realize that `xMargin` and `yMargin` must be > 0, so I added assertions.  Otherwise the highlights will overlap the edges of the listbox regardless of the cornerRadius.  And since the highlight overlap is 1/2 the value of xMargin and yMargin, having zero margins makes no sense. 

* This also made me realize that ComboBoxListItemNode should have responsibility for its own highlighting.  So I moved the relevant input listener into ComboBoxListItemNode.  This cleaned up the API quite a bit. 

That said... There are undoubtedly ways to make ComboBox look bad.   For example `xMargin: 1, yMargin: 1, listLineWidth: 10` will look pretty awful.   But rather than try to detect every case that might look bad, the designer and programmer need to take a certain amount of responsibility for looking at what they specified and evaluating whether it looks "good".

Back to you for review.

**Comment by Denz1994** [comment]
This is a definite improvement and I agree with the below comment: 

> the designer and programmer need to take a certain amount of responsibility for looking at what they specified and evaluating whether it looks "good".

Closing this one.
