### ISSUE TITLE
ComboBox button and listbox may be scaled differently

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#457]
Because ComboBox's button and listbox have different parents, they may be scaled differently.  

If the scaling happens to be the same, then items are the same size on the button and in the listbox, and the listbox is the same width as the button's item area. For example in BLL:

<img width="365" alt="screenshot_1000" src="https://user-images.githubusercontent.com/3046552/51435231-439ecf80-1c30-11e9-9f98-f5807d0cf17e.png">

But if the scaling is different, then items will be different sizes on the button vs in the list.  And the list width will not match the width of the button's item area. For example, in unit rates `ShoppingSceneComboBox` has a `maxWidth`. That maxWidth applies to the combo box button, but not to the list box, so the items are larger in the list than on the button:

<img width="224" alt="screenshot_1001" src="https://user-images.githubusercontent.com/3046552/51435246-82348a00-1c30-11e9-9542-f12c4215a39c.png">

This is not a new problem with the revised ComboBox implementation #430.  It's been a problem since ComboBox was born, but no one apparently noticed.  For example you can see it in Unit Rates 1.0.9 on the PhET website.

**Comment by pixelzoom** [comment]
In Unit Rates, it would be better to scale the text in the combo box, and not the entire combo box. So I'll do that there.  But it would still be good to have a general solution.

**Comment by pixelzoom** [comment]
General solution push in the above commit.  To test/verify:

1.  In SUN/ComboBox, comment out `this.scaleListBox();`  in `showListBox`:

```js
    showListBox() {
      if ( !this.listBox.visible ) {
        this.phetioStartEvent( 'listBoxShown' );

        // show the list box
        //this.scaleListBox();
```
  
2. In SUN/Components/ScreenView, add `maxWidth: 50` to the ComboBox created in `demoComboBox`:

```js
    var comboBox = new ComboBox( items, selectedItemProperty, listParent, {
      highlightFill: 'yellow',
      listPosition: 'above',
      maxWidth: 50
    } );
```

3. Run sun demo, go to the Components screen, choose "ComboBox" demo, and verify that you can see this problem, where the list box is larger than the button:

<img width="199" alt="screenshot_1005" src="https://user-images.githubusercontent.com/3046552/51576934-41798280-1e75-11e9-8675-6594c3a34365.png">

4. In SUN/ComboBox, restore `this.scaleListBox();`  in `showListBox`:

```js
    showListBox() {
      if ( !this.listBox.visible ) {
        this.phetioStartEvent( 'listBoxShown' );

        // show the list box
        this.scaleListBox();
```
 
5. Again run sun demo, and verify that the problem is fixed. The list box is now scaled to match the button:

<img width="166" alt="screenshot_1006" src="https://user-images.githubusercontent.com/3046552/51576994-7ab1f280-1e75-11e9-8e17-3df932bffd41.png">

6. Experiment with other `maxWidth` values in `demoComboBox` until you're convinced.

@zepumph would you mind verifying, since you and I looked at this problem briefly today?

**Comment by zepumph** [comment]
I followed the steps above and I am convinced! Thanks @pixelzoom.
