### ISSUE TITLE
problem with a11y listeners for sun buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#463]
a11y has introduced a general problem with sun buttons. In button listeners, we need to know whether a button fired due to an event involving accessible input (e.g. keyboard) or pointer.    And button listeners are currently provided with no information to make that decisions. 

E.g. in ComboBox, here's what we currently had to do:

```js
      // Clicking on the button toggles visibility of the list box
      this.button.addListener( () => {
        if ( !this.listBox.visible ) {
          this.showListBox();
        }
        else {
          this.hideListBox();
        }
      } );

      // Handle button clicks, for a11y
      this.button.addInputListener( {
        click: () => {

          //TODO sun#314 order dependency, requires that button's listener has called showList
          if ( this.listBox.visible ) {
            this.listBox.focus();
          }
        }
      } );
```

This requires a completely different listener for the button to handle button clicks for a11y, outside of sun/buttons/ listener API.  And a11y is not at all integrated (or integratabtle) into a standard button listener.  

We need a solution that allows us to write button listeners that handle all forms of input.

**Comment by pixelzoom** [comment]
In ComboBox, something better might look like:

```js
      // Clicking on the button toggles visibility of the list box
      this.button.addListener( event => {
        if ( !this.listBox.visible ) {
          this.showListBox();
          this.listBox.focus();
        }
        else {
          this.hideListBox();
          this.button.focus();
        }
      } );
```

**Comment by pixelzoom** [comment]
But see also the problem with `if ( event.point.type === 'a11y' )`, https://github.com/phetsims/scenery/issues/932.

**Comment by zepumph** [comment]
Looks like this is already solved, @jessegreenberg offered to just clean it up.

**Comment by zepumph** [comment]
This is not duplicated anymore:

https://github.com/phetsims/sun/blob/ee93abec9729f56a2deadb3aec7c604050bea11d/js/ComboBox.ts#L364-L368

Also noting that sun buttons use a `PressListener` now, thus supporting keyboard in addition to mouse touch input.

**Comment by jessegreenberg** [comment]
OK thanks, you were right @zepumph - I don't see anything else for this issue. There is also `SceneryEvent.isFromPDOM` if there is a need for code like https://github.com/phetsims/sun/issues/463#issuecomment-456606382.
