### ISSUE TITLE
add mouseArea options to RectangularButtonView

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#464]
Discovered in https://github.com/phetsims/scenery-phet/issues/459.

RectangularButtonView has options for touchArea, but no support for mouseArea:

```js
      touchAreaXDilation: 0,
      touchAreaYDilation: 0,
```

RoundButtonView correctly supports both touchArea and mouseArea:

```js
      touchAreaDilation: 0, // radius dilation for touch area
      mouseAreaDilation: 0, // radius dilation for mouse area
```

**Comment by pixelzoom** [comment]
Done in the above commit.  The computation of touchArea was overly complex, so I change that too. 

Formerly:

this.mouseArea = Shape.rectangle( 0, 0, buttonWidth, buttonHeight );
this.touchArea = Shape.rectangle(
  -options.touchAreaXDilation,
  -options.touchAreaYDilation,
  buttonWidth + options.touchAreaXDilation * 2,
  buttonHeight + options.touchAreaYDilation * 2
);
```

now:

```js
    this.touchArea = button.localBounds.dilatedXY( options.touchAreaXDilation, options.touchAreaYDilation );
    this.mouseArea = button.localBounds.dilatedXY( options.mouseAreaXDilation, options.mouseAreaYDilation );
```

Pointer area options are demonstrated in the Buttons screen of sun demo.  In ButtonScreenView:

```js
    var buttonA = new RectangularPushButton( {
      content: new Text( '--- A ---', { font: BUTTON_FONT } ),
      listener: function() { message( 'Button A pressed ' + ( ++buttonAFireCount ) + 'x' ); },
      
      // demonstrate pointer areas, see https://github.com/phetsims/sun/issues/464
      touchAreaXDilation: 10,
      touchAreaYDilation: 10,
      mouseAreaXDilation: 5,
      mouseAreaYDilation: 5
    } );
```

@jessegreenberg Since this was needed for https://github.com/phetsims/scenery-phet/issues/459, would you mind reviewing?

**Comment by jessegreenberg** [comment]
Looks great, thanks!
