### ISSUE TITLE
inaccurate documentation for ComboBoxIO

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#466]
In ComboBoxIO:

```js
 documentation: 'A traditional combo box',
```

This combo box is far from "traditional".   Most notably, it has no text field. 

Can `documentation` be deleted? Or changed to something else?

**Comment by samreid** [comment]
I committed a draft improvement, @zepumph can you please take a look and see if you can improve it further?

**Comment by pixelzoom** [comment]
I guess my opinion is that we should just delete `documentation`.   A combo box is a standard UI component, at the same level of abstraction as push button, check box, radio button, etc.  And I don't really see a reason to provide `documentation` for any of those. 

On the other hand, if you do feel a need to provide `documentation` for ComboBox, then it should presumably tell the reader something specific to PhET-iO, perhaps the structure.  Maybe something like:

"A combo box is composed of a button and a listbox containing items that represent choices. Pressing the button pops up the listbox.   Selecting from an item in the listbox sets the value of an associated Property.  The button shows the item that is currently selected."

**Comment by zepumph** [comment]
Yes I like @pixelzoom's doc. Anything else here?

**Comment by pixelzoom** [comment]
👍 Closing.
