### ISSUE TITLE
ComboBox: incorrect handling of enabledProperty 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#467]
Like other PhET UI components, `enabledProperty` can be passed in as an option.  If you don't set `options enabledProperty`, then a default is provided.  So...

(1) The default needs to be instrumented for PhET-iO.

(2) We need to keep track of whether ComboBox owns `enabledProperty`, and handle it accordingly when ComboBox.dispose is called.  If it owns `enabledProperty`, the call `enabledProperty.dispose`. Otherwise remove the listener that we added.

**Comment by pixelzoom** [comment]
@jessegreenberg since you just did a similar instrumentation and handling of enabledProperty in FineCoarseSpinner, would you mind reviewing this?

**Comment by jessegreenberg** [comment]
Looks great! And I tested disposal with and without passing an optional `enabledProperty`.
