### ISSUE TITLE
types mixing AccessibleSlider should document it as such

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#468]
While working on GFL I noticed there are no annotations for when this is being mixed into types. 
Accessibility.js is mixed in with appropriate doc in `Node.js`, like `* @mixes Accessibility`

I see 10 usages of  `initializeAccessibleSlider`, and no documentation for it.

**Comment by zepumph** [comment]
@jessegreenberg anything else to do here?

**Comment by jessegreenberg** [comment]
Thanks @zepumph - and documentation is probably also lacking for things using AccessibleNumberSpinner.

**Comment by jessegreenberg** [comment]
I searched for all `initializeAccessible*`, you get em all! I similarly documented the only two usages of AccessibleNumberSpinner. Thanks, closing.
