### ISSUE TITLE
NumberSpinner: support named placeholders in valuePattern option

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#472]
Similar to the work that was done for NumberDisplay and NumberControl (see https://github.com/phetsims/scenery-phet/issues/446), NumberSpinner should be upgraded to work with named placeholders with `'{{value}}'`, while continuing to support numbered placeholders with `'{0}'`.

@ariel-phet Since I did the work on NumberDisplay and NumberControl, it makes sense for me to do NumberSpinner.  OK to proceed?

**Comment by ariel-phet** [comment]
@pixelzoom yes, definitely OK to proceed

**Comment by pixelzoom** [comment]
Oh, happy days! There are only 4 sims that use NumberSpinner:

- [ ] expression-exchange
- [ ] reactants-products-and-leftovers
- [ ] sun demo
- [ ] tambo demo

Only sun demo uses '{0}' in an example, easily converted to '{{value}}'.

So I can just switch NumberSpinner over to named placeholders, and don't need to be backward compatible with numbered placeholders.

**Comment by pixelzoom** [comment]
Conversion completed in above commit. Tested with sun demo.

@ariel-phet please assign someone to review.

**Comment by pixelzoom** [comment]
Conversion completed in above commit. Tested with sun demo.

@ariel-phet please assign someone to review. @samreid is reviewing similar changes to NumberDisplay and NumberControl.

**Comment by ariel-phet** [comment]
@samreid please review (if you are currently too swamped, let me know)

**Comment by samreid** [comment]
```js
valuePattern: NumberSpinner.DEFAULT_VALUE_PATTERN, // {string} must contain '{{value}}'
```

Would you like to add an assertion for this?

**Comment by pixelzoom** [comment]
Probably a good idea.  There should be a similar assertion in NumberDisplay.

**Comment by pixelzoom** [comment]
I've added validation of `valuePattern` to NumberSpinner and NumberDisplay, and (similarly) validation of `noValuePattern` to NumberDisplay.   Validation uses the new constants that were added to SunConstants in https://github.com/phetsims/sun/issues/474.  

Back to @samreid for review.

**Comment by pixelzoom** [comment]
Looks like this is causing problems in RPAL, where the spinners are now super wide:

<img width="917" alt="screenshot_1085" src="https://user-images.githubusercontent.com/3046552/53441869-019e4180-39c5-11e9-9379-8b00f4ddf64f.png">

**Comment by pixelzoom** [comment]
Rechecking all users of NumberSpinner:

- [ ] expression-exchange
- [ ]  reactants-products-and-leftovers
- [ ]  sun demo
- [ ]  tambo demo

**Comment by pixelzoom** [comment]
Expression Exchange also looks wrong, here's the initial state of the Variables accordion box (Basics screen) in production (left) vs master (right):

<img width="176" alt="screenshot_1089" src="https://user-images.githubusercontent.com/3046552/53442302-3e1e6d00-39c6-11e9-93a5-daa63e8342c4.png"> <img width="178" alt="screenshot_1088" src="https://user-images.githubusercontent.com/3046552/53442310-41195d80-39c6-11e9-8311-35c388a18e85.png">

**Comment by pixelzoom** [comment]
sun demo also affected, though more subtly.  Before (top) vs after (bottom):

<img width="943" alt="screenshot_1090" src="https://user-images.githubusercontent.com/3046552/53442528-b8e78800-39c6-11e9-9b65-5a1cc07fb908.png">

<img width="880" alt="screenshot_1091" src="https://user-images.githubusercontent.com/3046552/53442509-aff6b680-39c6-11e9-9743-a537f1a34136.png">

**Comment by pixelzoom** [comment]
First screen in tambo before (top) and after (bottom).  Good to know that I consistently overlooked all problems when I completed the checklist in https://github.com/phetsims/sun/issues/472#issuecomment-460786006 :)

<img width="360" alt="screenshot_1092" src="https://user-images.githubusercontent.com/3046552/53442700-20053c80-39c7-11e9-9ab1-f7a19447f4aa.png"> 
<img width="367" alt="screenshot_1093" src="https://user-images.githubusercontent.com/3046552/53442706-22679680-39c7-11e9-8954-c89dc27a77b6.png">

**Comment by pixelzoom** [comment]
Fixed in the above commit.  There was a stray `StringUtils.format` that needed to be converted to `StringUtils.fillIn`, and it was in the code that computed the maxWidth of the spinner.  Verified in all clients of NumberSpinner.

Back to @samreid for review.

**Comment by pixelzoom** [comment]
Re the suggestion in https://github.com/phetsims/sun/issues/472#issuecomment-461165542 to verify that `valuePattern` contains `{{value}}`...   That caused problems with `stringTest`, which replaces the entire strings, e.g. https://github.com/phetsims/masses-and-springs/issues/344.   So in the above commit, that verification is done only if `stringTest` is not present.

**Comment by samreid** [comment]
I reviewed the preceding commits and didn't see any other trouble.  Regarding this problem:

> There was a stray StringUtils.format that needed to be converted to StringUtils.fillIn

Would it be possible to check that `format` doesn't have any `{{string}}` and `fillIn` doesn't have any `{number}`?  Or do we have cases that overlap?  I'm guessing there are cases that overlap, but I haven't run runtime tests to verify--thought it would be good to discuss first.

**Comment by pixelzoom** [comment]
Could do, but I'm not convinced that it's worth the effort, or the added complication to StringUtils (factoring out regexs, etc.) If it's something you'd like to pursue, create another issue.

**Comment by pixelzoom** [comment]
> Would it be possible to check that `format` doesn't have any `{{string}}` and `fillIn` doesn't have any `{number}`?

If you proceed, keep in mind that we need to be able to convert from numbered to named placeholder format, e.g. in NumberDisplay:

```js
    if ( options.valuePattern.indexOf( SunConstants.VALUE_NUMBERED_PLACEHOLDER ) !== -1 ) {
      options.valuePattern = StringUtils.format( options.valuePattern, SunConstants.VALUE_NAMED_PLACEHOLDER );
    }
```

**Comment by samreid** [comment]
That seems reasonable, let's proceed without this for now.
