### ISSUE TITLE
create constants for common placeholders in string patterns

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#474]
SCENERY_PHET/NumberDisplay and SUN/NumberSpinner both use `'{{value}}'` as a named placeholder in string patterns.  And some sims (e.g.  unit-rates) use `{{value}}` as a placeholder independently of NumberDisplay and NumberSpinner.  So this should be factored out as a constant.  My plan is to create `SUN/SunConstants` and put it there.

Ditto for the numbered placeholder`'{0}'`.

**Comment by pixelzoom** [comment]
I created `SunConstants` and it contains:

```js

    // Named placeholder in string patterns where a value will be substituted.
    // Typically appears in translated strings (e.g. "{{value}} nm") and used with StringUtils.fillIn.
    VALUE_NAMED_PLACEHOLDER: '{{value}}',

    // Numbered placeholder in string patterns where a value will be substituted.
    // Typically appears in translated strings (e.g. "{0} nm") and used with StringUtils.format.
    // Named placeholders are the new standard, and numbered placeholders should not be used in new code.
    VALUE_NUMBERED_PLACEHOLDER: '{0}'
```

These constants are now used in SUN/NumberSpinner, SCENERY_PHET/NumberDisplay, and in sims that were previously using similar `NumberDisplay` constants.

@samreid would you mind reviewing, since this is somewhat related to https://github.com/phetsims/scenery-phet/issues/446?

**Comment by samreid** [comment]
I reviewed the commits for this issue and didn't see any problems.  I found one outstanding occurrence of DEFAULT_VALUE_PATTERN and opened new issue https://github.com/phetsims/energy-skate-park/issues/63 for it.  I think this issue can be closed.
