### ISSUE TITLE
CombBox button changes color after using a11y features

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#475]
Here's what ComboBox looks like in Molarity after pressing its button to open the listbox. The pointer is over the button in this screenshot:

<img width="426" alt="screenshot_1064" src="https://user-images.githubusercontent.com/3046552/52822315-940e1f00-306e-11e9-85bd-8c4c3e6d5e43.png">

If I tab to the button, then use the spacebar to open and close the ComboBox, then the button turns dark gray.  And it now turns gray whenever the pointer is over the button, regardless of whether the listbox is opened or closed.   In these 2 screenshots, the pointer is over the button:

<img width="359" alt="screenshot_1068" src="https://user-images.githubusercontent.com/3046552/52822659-8f963600-306f-11e9-8325-ee8b0d78f7b8.png">

<img width="374" alt="screenshot_1067" src="https://user-images.githubusercontent.com/3046552/52822668-93c25380-306f-11e9-8fc0-6ea84016143d.png">

I don't recall seeing this the last time I was working on ComboBox (2/2/19), so I suspect that something has changed.

ComboBoxButton is a RectangularPushButton, so I'd probably start with those 2 classes.

**Comment by pixelzoom** [comment]
The dark gray appears to be `rgb( 153, 153, 153 )`, which is `#999999`. I don't see that color specified explicitly anywhere in PhET code.

**Comment by pixelzoom** [comment]
When using the mouse, I see the CombBox button change to dark gray on pointer down.  But it returns to white on pointer up.   It's not until a11y input is used that it remains dark gray on pointer over.

**Comment by pixelzoom** [comment]
When using the keyboard to interact with the button, it gets confused and thinks that it's pressed when it isn't. 

In RectangularButtonView, add a `console.log` statement to `updateAppearance`:

```js
    function updateAppearance( interactionState ) {
      console.log( 'interactionState=' + interactionState );//XXX
```

Now follow these steps:

1. Run Molarity with `?a11y`
2. Click and release on the ComboBox button 2x with the mouse, then move the mouse out of the button.  You'll see this output in the console:

interactionState=IDLE
interactionState=OVER
interactionState=PRESSED
interactionState=OVER
interactionState=PRESSED
interactionState=OVER
interactionState=IDLE

3. Now tab to the ComboBox. You'll see this in the console:

interactionState=OVER

4. Press Space key twice.  You'll see this in the console:

interactionState=PRESSED
interactionState=IDLE
interactionState=PRESSED

So the button thinks that it is still pressed and is therefore displayed with the same color used when the pointer is pressed.

**Comment by pixelzoom** [comment]
So... It looks like the mismatch between pointer and keyboard (a11y) interaction behavior is getting `RectangularButtonView` (and therefore `RectangularPushButton` and `ComboBox`) confused.

**Comment by pixelzoom** [comment]
To explain why the button is dark gray...  I temporarily changed ResetAllButton to have these defaults:

```js
      baseColor: 'white',
      buttonAppearanceStrategy: RectangularButtonView.FlatAppearanceStrategy,
```

... and it behaves the same as ComboBoxButton.  That is, it's white on pointer up (IDLE), and dark gray on pointer down (PRESSED).

**Comment by jessegreenberg** [comment]
I tracked this down to https://github.com/phetsims/scenery/commit/4f0bb509cad9a5d5a2557ef3b271abfa8d3b36b2 change to PressListener (from three days ago), where we added the a11y portion to `interrupt` from https://github.com/phetsims/scenery/issues/884.

**Comment by jessegreenberg** [comment]
> I don't see that color specified explicitly anywhere in PhET code.

I assume it is the `downFill` generated from RectangularButtonView.FlatAppearanceStrategy.

**Comment by pixelzoom** [comment]
I didn't verify, but yes, it probably is the `downFill` generated from RectangularButtonView.FlatAppearanceStrategy.   That seems like an odd color choice for a 'white' button, perhaps worthy of an additional GitHub issue.

**Comment by jessegreenberg** [comment]
OK, the above commit should fix this. @pixelzoom can you please pull scenery and verify?

**Comment by pixelzoom** [comment]
👍 Closing.
