### ISSUE TITLE
binder documentation is not specific to a11y

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#479]
I see 6 occurrences of this comment in sun UI components:

```js
    // a11y - support for binder documentation, stripped out in builds and only runs when ?binder is specified
    assert && phet.chipper.queryParameters.binder && InstanceRegistry.registerDataURL( 'sun', 'ABSwitch', this );
```

Just a nit, but binder documentation is not specific to a11y.  The .md files are general design documents, which include a11y considerations.   Since the majority of similar comments don't mention a11y, I'm going to remove the "a11y -" prefix from these comments.

**Comment by pixelzoom** [comment]
@mbarlow12 FYI. Feel free to close.

**Comment by ariel-phet** [comment]
seems reasonable to close. Closing
