### ISSUE TITLE
AccordionBox: bad implementation of titleBarOptions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#481]
I ran into this while adding nested options to AccordionBox in https://github.com/phetsims/sun/issues/480.

In https://github.com/phetsims/sun/commit/89ffb3b65e75731283538574ad8fdb5aa5eba84c, @jonathanolson added this to AccordionBox options:

```js
      // Options will be provided to both title bar nodes
      titleBarOptions: null
    }, options );

    options.titleBarOptions = _.extend( {
      // a11y
      tagName: 'button'
    }, options.titleBarOptions );
```

I don't know if it was an oversight or for expediency, but existing titlebar options were not moved to `titleBarOptions`. So this is misleading and incorrect.  The existing options related to titlebar are:

```js
    titleBarFill: null, // {Color|string} title bar fill
    titleBarStroke: null, // {Color|string} title bar stroke, used only for the expanded title bar
```

@ariel-phet please assign someone to clean this up.

**Comment by pixelzoom** [comment]
Here are the number of usages for the options that need to be nested:

titlebarFill (1)
titlebarStroke (0)

Looks relatively easy, so I'm just going to do this.

**Comment by pixelzoom** [comment]
titleBar options are now nested, see above commits.

@ariel-phet please assign someone to review. Should be a quick one.

**Comment by jonathanolson** [comment]
Looks good to me. Sorry about that!
