### ISSUE TITLE
implement ExpandCollapseButton as a sun button

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#483]
I ran into this problem in https://github.com/phetsims/sun/issues/480.   We want to pass nested options to AccordionBox's ExpandCollapseButton instance, and those options include pointerArea options that are generally supported by sun buttons.  But (after considerable work had been done) I discovered that ExpandCollapseButton is not a button at all.  It's a Node that's made to look like a button.  This needs to be changed to address https://github.com/phetsims/sun/issues/480, support general phet-io, and support a11y. 

Assigning to @ariel-phet to prioritize and assign.

**Comment by pixelzoom** [comment]
This is going to be a non-trivial change.  To continue with #480, I temporarily added these options, along with code to set pointer areas:

```
      // TODO https://github.com/phetsims/sun/issues/483
      // These pointer area options were added temporarily to support button-like behavior.
      // They should be removed when this button is converted to a sun button.
      touchAreaXDilation: 0,
      touchAreaYDilation: 0,
      mouseAreaXDilation: 0,
      mouseAreaYDilation: 0,
```

**Comment by jessegreenberg** [comment]
Discussion over slack, @jessegreenberg will work on this.

**Comment by jessegreenberg** [comment]
ExpandCollapseButton is used in these places which I will spot check before committing.

 - [ ] curve-fitting\js\curve-fitting\view\EquationGraphPanelNode.js
 - [ ] optics-lab\js\optics-lab\view\ControlPanel.js
 - [ ] optics-lab\js\optics-lab\view\SelectedPieceControlPanel.js
 - [ ] ph-scale\js\common\view\PHMeterNode.js:
 - [ ] scenery-phet\js\demo\MemoryTestsScreenView.js
 - [ ] sun\js\AccordionBox.js (will spot check a few usages)
 - [ ] sun\js\ExpandCollapseBar.js (ph-scale)
 - [ ] trig-tour\js\trig-tour\view\GraphView.js
 - [ ] unit-rates\js\common\view\ValuePanel.js

**Comment by pixelzoom** [comment]
While you're in ExpandCollapseButton, could you please fix dispose?  

If `expandedProperty` is disposed by the client before the ExpandCollapseButton, this will fail:

```js
    this.disposeExpandCollapseButton = function() {
      this.expandedProperty.unlink( this.expandedPropertyObserver );
    };
```

It should be:

```js
    this.disposeExpandCollapseButton = function() {
      if ( his.expandedProperty.hasListener( this.expandedPropertyObserver ) ) {
        this.expandedProperty.unlink( this.expandedPropertyObserver );
      }
    };
```

**Comment by pixelzoom** [comment]
@jessegreenberg you can ignore the previous comment. In https://github.com/phetsims/scenery-phet/issues/476#issuecomment-469825394, @zepumph pointed out that Emitter.removeListener now skips the assertion if the Emitter (Property) has been disposed.   So it's safe to omit the `hasListener` check.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/sun/issues/483#issuecomment-469832151

OK, thanks.

**Comment by jessegreenberg** [comment]
This is done, ExpandCollapseButton now extends BooleanRectangularToggleButton. I did a spot check of the usages in https://github.com/phetsims/sun/issues/483#issuecomment-469784867 to make sure the button looked the same. The only visual changes I noticed are that the button now has "over" and "down" styling, which is a good thing.

@pixelzoom can you please review?

**Comment by jessegreenberg** [comment]
Over slack @pixelzoom suggested
> `'rgb( 255, 85, 0 )'` should be `PhetColorScheme.RED_COLORBLIND`

**Comment by pixelzoom** [comment]
Looks super @jessegreenberg.  I added you as `@author`.  

Re PhetColorScheme... It lives in scenery-phet, so sadly can't be used in sun (circular dependency).  I created issue #485 and a TODO in ExpandCollapseButton.

Closing.
