### ISSUE TITLE
why does Checkbox need a separate listener for keyboard input?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#487]
Noted while working on https://github.com/phetsims/sun/issues/488.

Checkbox has this code related to "firing" of its state change:

```js
    // interactivity
    var fire = function() {
      if ( self.enabledProperty.value ) {
        var newValue = !property.value;
        toggledEmitter.emit( newValue );
      }
    };

    var checkboxButtonListener = new ButtonListener( {
      fire: fire
    } );
    this.addInputListener( checkboxButtonListener );

    // a11y - fire the listener when checkbox is clicked with keyboard or assistive technology
    var changeListener = {
      change: fire
    };
    this.addInputListener( changeListener );
```

Why do we need to add another listener for a11y that calls the exact same function as the ButtonListener that was already added?  This should be handled by ButtonListener; it should be able to handle _all types_ of button input, including keyboard/AT, not just pointer.

**Comment by jessegreenberg** [comment]
This listener was added before https://github.com/phetsims/scenery/issues/888, but since that is done there is no need to have a separate listener for a11y.

Response to a11y input should probably be moved to ButtonListener, but I am going to review usages of ButtonListener to make sure.

**Comment by jessegreenberg** [comment]
ButtonListener was instrumented for a11y in #959, and this a11y listener was removed from Checkbox.

**Comment by jessegreenberg** [comment]
Closing since the listener was removed from Checkbox.
