### ISSUE TITLE
Checkbox cleanup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#488]
Noticed while working on enabledProperty in another UI component.

- [x] `this.content` and `this.ownsEnabledProperty` do not need to be instance fields. They are used only in the constructor. Convert them to local variables.

- [x] `this.enabledProperty` has no visibility annotation.  Typically `@public` in other UI components.

- [x] Multiple lines are longer than 120 chars.

- [x] Checkbox doesn't have a demo/test in the sun demo app.

- [x] options `checkboxAppearanceStrategy` and `contentAppearanceStrategy` are unused. Other UI components have been fine with using opacity to indicate disabled, and other UI components typically have `disabledOpacity`.  So switch to this in anticipation of boilerplate being replaced with a mixin or trait.

- [x] Use SunConstants.DISABLE_OPACITY, rather than duplicating it.

**Comment by pixelzoom** [comment]
Work completed in the above commits.  @chrisklus randomly selected to review.

**Comment by pixelzoom** [comment]
It's been a long time since this was assigned for review.  @ariel-phet please prioritize.

**Comment by chrisklus** [comment]
Dang, sorry @pixelzoom. Review complete, changes look straightforward and good to go. Back to @pixelzoom to close.

**Comment by pixelzoom** [comment]
👍
