### ISSUE TITLE
disposeActions pattern for dispose

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#492]
AccordionBox uses a different pattern for `dispose`.  It does not have `disposeAccordionBox` function to encapsulates all dispose actions that are specific to AccordionBox. Instead, it has `{function[]} disposalActions`, a queue of functions that are called by `dispose`.  

This pattern is described in [phet-software-design-patterns.md](https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md#dispose). But it indicates that the name should be `disposeActions`. And it is deprecated. 

Searching for `disposeActions` and `disposalActions`, I see that this pattern appears to be limited to AccordionBox, CCKC/CircuitElementNode, and CCKC/ValueNode.

Recommendations:

(1) Since this pattern is deprecated and there are only 2 occurrences, replace them. Or at least replace the occurrence in AccordionBox. This caused me some head scratching in #491, so keeping this around is not without cost.

(2)  If we keep these deprecated usages... Standardize on the name.  Include the type name to prevent shadowing.  E.g. `disposeActionsAccordionBox`. 

(3) Based on what we do in (1) and (2), update phet-software-design-patterns.md accordingly.

**Comment by pixelzoom** [comment]
I rename `disposalActions` to `disposeActions` in AccordionBox, so that it at least matches what is described in phet-software-design-patterns.md.

**Comment by samreid** [comment]
It seems straightforward to move these occurrences to the `disposeEmitter` pattern.

**Comment by pixelzoom** [comment]
Self-assigning to convert AccordionBox to `disposeAccordionBox`.

@samreid Your call on whether to convert `CCKC/CircuitElementNode` and `CCKC/ValueNode`.

**Comment by pixelzoom** [comment]
Tracking AccordionBox conversion in https://github.com/phetsims/sun/issues/493.

**Comment by pixelzoom** [comment]
Tracking CCKC changes in https://github.com/phetsims/circuit-construction-kit-common/issues/475.

This issue can be closed.
