### ISSUE TITLE
AccordionBox: convert disposeActions to disposeAccordionBox

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#493]
In https://github.com/phetsims/sun/issues/492#issuecomment-480035006 we decided to convert AccordionBox from the deprecated `disposeActions` pattern to the `disposeAccordionBox` pattern.  I'll do the conversion.

**Comment by pixelzoom** [comment]
Note to self: If I do this after https://github.com/phetsims/circuit-construction-kit-common/issues/475, I should update phet-software-design-patterns.md. Remove the note about disposeActions, since it will no longer exist.

**Comment by samreid** [comment]
> Note to self: If I do this after phetsims/circuit-construction-kit-common#475, I should update phet-software-design-patterns.md. Remove the note about disposeActions, since it will no longer exist.

CCK is converted

**Comment by pixelzoom** [comment]
As I started to convert this, the `disposeAccordionBox` function quickly got complicated, with the need for additional flags (`ownsTitleNode`, `ownsEnabledProperty`) and conditional logic.  So now I'm leaning towards leaving this alone.  And perhaps we should revisit the decision to deprecate this pattern.  

@samreid @jonathanolson thoughts?

**Comment by samreid** [comment]
Let's use the `disposeEmitter{{TypeName}}` pattern and deprecate the `disposeActions` pattern.

**Comment by pixelzoom** [comment]
No feedback from @jonathanolson, so I'll proceed with `disposeEmitter{{TypeName}}`.

**Comment by pixelzoom** [comment]
I converted to `disposeEmitterAccordionBox` in the above commit, tested in sun demo and in console.

While doing this conversion, I noticed `dispose` calls for some subcomponents that seem unnecessary. @samreid could you check me on this and confirm whether these `dispose` calls can be deleted?

```js
174  self.expandedBox.dispose();
183  self.collapsedBox.dispose();
232 self.expandedBoxOutline.dispose();
242 self.collapsedBoxOutline.dispose();
```

**Comment by pixelzoom** [comment]
I removed dispose listeners for the a case shown in https://github.com/phetsims/sun/issues/493#issuecomment-481770956.  I also cleaned up some odd options for these components.  

@samreid would you mind reviewing, since you did a similar conversion for CCK?

**Comment by samreid** [comment]
I reviewed the commits, tested functionality in Build an Atom and checked memory usage over about 5 minutes and creation of 6000+ AccordionBoxes in the sun demo memory tester.

![image](https://user-images.githubusercontent.com/679486/56044474-7d95e400-5cfc-11e9-9ba6-91c4d6ccd89c.png)

No problems noted, closing.
