### ISSUE TITLE
ComboBoxListBox must be PhET-iO instrumented to support playback for a11y 

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#496]
I ran into this while working on https://github.com/phetsims/molarity/issues/77. I saw a comment pointing back to https://github.com/phetsims/phet-io/issues/1102, but I need this working for an interview tomorrow, so I'm adding the tandem back in for now. Let's discuss more here.

**Comment by samreid** [comment]
Is this what I discovered in https://github.com/phetsims/phet-io/issues/1205#issuecomment-678654918 ?

**Comment by zepumph** [comment]
No I don't think so. I believe that was https://github.com/phetsims/phet-io/issues/1720

**Comment by zepumph** [comment]
It seems like we didn't instrument the list box because making it manually visible was buggy (https://github.com/phetsims/phet-io/issues/1102#issuecomment-293102248), so likely we wouldn't want to feature it.

**Comment by zepumph** [comment]
Reviewing https://github.com/phetsims/molarity/issues/77 (why this issue was open), I can't find details about why we needed the listbox instrumented, but it seems to be for sonification-wrapper specific logic. My guess is that we shouldn't instrument this anymore, since that is a deprecated approach to sonification.

**Comment by zepumph** [comment]
@samreid, does it seem reasonable that the listbox doesn't get instrumented? Please review.

**Comment by samreid** [comment]
The listbox doesn't need to be instrumented.  Can this issue be closed?
