### ISSUE TITLE
add ability to shift pointer areas for buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#500]
In https://github.com/phetsims/unit-rates/issues/212, we identified a need to shift the pointer area for a `RectangularButtonView`.  In that case, it's the ExpandCollapseButton for AccordionBox. 

If we need arbitrary shifting, we could add this to `RectangularButtonView`:

```js
touchAreaXShift: 0,
touchAreaYShift: 0,
mouseAreaXShift: 0,
mouseAreaYShift: 0,
```

and the code that sets the pointer areas becomes:

```js
// set pointer areas
this.touchArea = button.localBounds.dilatedXY( options.touchAreaXDilation, options.touchAreaYDilation ).shifted( options.touchAreaXShift,  options.touchAreaYShift );
this.mouseArea = button.localBounds.dilatedXY( options.mouseAreaXDilation, options.mouseAreaYDilation ).shifted( options.mouseAreaXShift,  options.mouseAreaYShift );
```

If we don't need arbitrary shifting and want to keep the pointer areas aligned with the button, then the API might be:

```
touchAreaXAlign: 'center', // {string} left, right, center
touchAreaYAlign: 'center', // {string} top, bottom, center
```

and the code to set the pointer areas would be significantly more complicated.

And depending on what API we choose, we should probably add something similar to `RoundButtonView`.

**Comment by pixelzoom** [comment]
Summary of @zepumph suggestion on Slack:

> ```js
> touchAreaShift: {Vector2}
> mouseAreaShift: {Vector2}
> ```

The current API uses `{number}` for `touchAreaXDilation` et. al.  So while I appreciate the fact that using Vector2 require fewer options, it's not in the spirit of the existing API (which would be costly to change) and requires allocation of a Vector2.

**Comment by pixelzoom** [comment]
Since I can easily imagine a designer asking to "expand the touch area a bit below and a more above" (which is what we'd probably want to do in  phetsims/unit-rates#212), I think that the `touchAreaXShift` et. al. API is probably the way to go.

**Comment by jonathanolson** [comment]
A generalization (that wouldn't include as many options) would presumably be a function that returns the mouse/touch area. It could take in the as-of-yet-constructed node, e.g.:

```js
new ExpandCollapseButton( ..., {
  touchAreaGenerator( node ) {
    return node.localBounds.dilatedXY( 10, 9 ).shifted( -3, -3 );
  }
} );
```

**Comment by pixelzoom** [comment]
@jonathanolson's suggestion above is indeed very general.  But...

*  4 existing options will be come obsolete: `touchAreaXDilation`, `touchAreaYDilation`, `mouseAreaXDilation`, `mouseAreaXDilation`.   Keeping those options and doing something sensible with them will complicate the implementation. Tracking them down in client code and replacing them will be expensive. 

* The most common case (symmetric dilation) will be more complicated for the client to specify, e.g.:  

```js
new RectangularPushButton( ..., {
  touchAreaXDilation: 10, 
  touchAreaYDilation: 5
  }
} );
```

... would become:

```js
new RectangularPushButton( ..., {
  touchAreaGenerator( node ) {
    return node.localBounds.dilatedXY( 10, 5 );
  }
} );
```

**Comment by samreid** [comment]
Would it read any clearer with arrows?

**Comment by pixelzoom** [comment]
Do you mean arrow functions? Still seem heavy for the typical case:

```js
new RectangularPushButton( ..., {
  touchAreaGenerator: node => node.localBounds.dilatedXY( 10, 5 )
} );
``

**Comment by pixelzoom** [comment]
Occurrences of the options that would be obsoleted by @jonathanolson's proposal.  Unlikely that all of these are for buttons, but all of them would need to be examined.

touchAreaXDilation 131
touchAreaYDilation 125
mouseAreaXDilation 28
mouseAreaYDilation 27

**Comment by pixelzoom** [comment]
And since we'd presumably want to do something similar for RoundButtonView:

touchAreaDilation 37
mouseAreaDilation 3

**Comment by samreid** [comment]
I'm not sure how to balance the flexibility of 1 function vs the ease of 4 variables which are often all we need.  I'd like to discuss further in the dev meeting.

**Comment by pixelzoom** [comment]
4/25/19 dev meeting:

I'll proceed with new options for RectangularButtonView and RoundButtonView. We can change in the future if needed.  The options are:

```js
touchAreaXShift: 0,
touchAreaYShift: 0,
mouseAreaXShift: 0,
mouseAreaYShift: 0,
```

**Comment by pixelzoom** [comment]
This is blocked until we resolve #502.

**Comment by pixelzoom** [comment]
Done for round and rectangular push buttons. Demonstrated in sun demo application, see annotated screenshot below.

@ariel-phet please assign someone to review.

![screenshot_1174](https://user-images.githubusercontent.com/3046552/57095735-c8d65d80-6cd0-11e9-8d1e-f2c122bc6706.jpg)

**Comment by ariel-phet** [comment]
@chrisklus can you review?

**Comment by chrisklus** [comment]
@pixelzoom looks good. The code changes make sense and I tested the shifted pointer areas with a mouse and simulated touch device. Back to you.
