### ISSUE TITLE
Opt out of linking checkbox Property in studio

### ISSUE THREAD

**Issue by chrisklus** [phetsims/sun#501]
When working on https://github.com/phetsims/blackbody-spectrum/issues/83, I needed to instrument the Property that is used for ProjectorModeCheckbox. However, Blackbody Spectrum doesn't pass in its own Property, but links to one that ProjectorModeCheckbox creates if no Property is provided. @zepumph suggested that I instrument that Property within ProjectorModeCheckbox.

Then in that case, since ProjectorModeCheckbox has a child tandem projectorModeEnabledProperty, there is no need for the typical property* link in Studio. So, I'm going to add the option `phetioLinkProperty` to Checkbox, which defaults to true, and only creates a Property link if it's true.

**Comment by chrisklus** [comment]
This worked well. I tested that the linked Property is not appearing in Blackbody Spectrum, but is still appearing in Charges and Fields. Assigning to @zepumph for review.

**Comment by zepumph** [comment]
Looks great. Nicely done.
