### ISSUE TITLE
standardize location of AccordionBox expand/collapse button?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#504]
This is a tangent discussion that started in https://github.com/phetsims/sun/issues/502.

Should we standardize on the location of the AccordionBox expand/collapse button? By default it is on the left, but several sims (see below) put it on the right.  If we choose to standardized, we would remove option `buttonAlign`.

Relevant comments from https://github.com/phetsims/sun/issues/502:

@kathy-phet said:
> ... But I'm finding now that the behavior is changed is that the sim is not as fluid to use when I need to be more precise and move my cursor further (in cases like BAA) to hit the box.

@arouinfar said:
> @kathy-phet I think an easy way to address this would be to move the ExpandCollapseButton to the left side of the box. BAA is somewhat unusual in that the ExpandCollapseButton is on the right.

@ariel-phet said:
> Agreed with @arouinfar comment that the open close buttons on the right of the accordion box in BAA is a bit odd...I think we might have been overly concerned about occlusion issues when that sim was designed, but I think we could make those work just find on the left.

@kathy-phet said:
> [For BAA] I do recall that the RHS alignment was on purpose to bring the words closer to the atom itself. I think we had tried the original LHS and it felt disconnected during the design process.

I said:
> RPAL also has expand/collapse buttons on the right, and it was one of the first sims (maybe the first sim) to have an AccordionBox. If we want standardization, then we should remove the buttonAlign option from AccordionBox.
> 
> List of sims that use `buttonAlign: 'right'`, expand/collapse button on the right:
>
> balancing-chemical-equations
build-an-atom
fluid-pressure-and-flow
isotopes-and-atomic-mass
models-of-the-hydrogen-atom
plinko-probability
reactants-products-and-leftovers
states-of-matter

**Comment by ariel-phet** [comment]
@pixelzoom I am not sure we want to standardize (though it would be nice). I think certainly it might make sense to revisit some designs (BAA seems like a good example where I see no reason to put the expand/collapse on the right)

However, for a sim like Plinko Probability, I can see why it was done. This is a math sim and given the color scheme, the collapse button would look suspiciously like a potential math symbol if used on the left. So it seems like having this flexibility is important in at least some cases.

**Comment by pixelzoom** [comment]
I have no strong feelings on this one.  I created the issue only because it was brought up for discussion.   If there's consensus that there's no need to standardize, please close this issue.  If there are sims that you'd like to revisit (see list above) please create sim-specific issues.

**Comment by ariel-phet** [comment]
I think for the moment, no need to standardize. Closing
