### ISSUE TITLE
Radio buttons should have a default sound

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#505]
From this week's sonification meeting:

@kathy-phet: Will radio buttons have a default sound?
@Ashton-Morris: Yes, that's more likely than sliders having a default sound.  We'll need to make it good, since it will be pervasive.
@Ashton-Morris: Different pitches for each radio button.  N radio buttons have same min and max playbackRate, it will be divided up between the steps, like playbackRate maps proportionately from i/N.

**Comment by jbphet** [comment]
@Ashton-Morris and @emily-phet - the latest versions are available in the https://phet-dev.colorado.edu/html/tambo/1.0.0-dev.11/phet/tambo_en_phet.html prototype, 2nd screen.  Please review and provide feedback (we can do this during the weekly sound design meeting if you like).

**Comment by jbphet** [comment]
We reviewed this at the 6/18/2019 dev meeting and are feeling pretty good about choice 1 in version 1.0.0-dev.11 for radio button sounds.

**Comment by jbphet** [comment]
The radio buttons sounds have been in use for a while and there have been no complaints, so I'm going to call this good.  I'll close this issue, and we can open a new one if we ever decide that changes are needed.
