### ISSUE TITLE
Push buttons should have a default sound

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#506]
Like https://github.com/phetsims/sun/issues/505 but for push buttons.

**Comment by jbphet** [comment]
@Ashton-Morris and @emily-phet - the latest versions are available in the https://phet-dev.colorado.edu/html/tambo/1.0.0-dev.11/phet/tambo_en_phet.html prototype, 2nd screen.  Please review and provide feedback (we can do this during the weekly sound design meeting if you like).

**Comment by jbphet** [comment]
@Ashton-Morris is going to make some mods to try to "thicken up" the sound used in version 1.0.0-dev.11.

**Comment by jbphet** [comment]
The new sound from @Ashton-Morris has been integrated as sound 1 in the tambo demo, please review and provide feedback.  The demo can be found at https://phet-dev.colorado.edu/html/tambo/1.0.0-dev.13/phet/tambo_en_phet.html.

**Comment by jbphet** [comment]
The default sounds has been in use for a while with no major issues.  Closing.
