### ISSUE TITLE
synchronize enabled state of AccordionBox titleBar and ExpandCollapseButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#514]
Noted while working on phetsims/graphing-quadratics#112 with @amanda-phet.

When AccordionBox's ExpandCollapseButton !enabledProperty.value, you should not be able to click in the title bar to expand/collapse.

**Comment by pixelzoom** [comment]
Unlike other PhET UI components, sun buttons don't provide `options.enabledProperty` and they don't provide public `this.enabledProperty`. 

There is an `enabledProperty` internally, but it's in `ButtonModel`:

```js
    // @public - Is the button enabled?
    this.enabledProperty = new BooleanProperty( options.enabled, {
```

... but it's `@protected` in the view part of the button. For example in RectangularButtonView:

```js
    this.buttonModel = buttonModel; // @protected
```

And you're apparently supposed to call `setEnabled` and `getEnabled` to indirectly access `this.buttonModel.enabledProperty.set( value )`.

This is a problem in the case of AccordionBox, because the enabled state of its `ExpandCollapseButton` needs to be synchronized with whether clicking on the title bar expands/collapses the box.

@jbphet what do you recommend here?

**Comment by pixelzoom** [comment]
I've found a workaround for this, but it's not pretty.  It involves checking `this.expandCollapseButton.getEnabled()` when the titlebar is clicked.

**Comment by pixelzoom** [comment]
Rats, my workaround does prevent clicking on the titlebar when `expandCollapseButton` is disabled. But the titlebar should be set to `pickable:false` when `expandCollapseButton` becomes disabled, and I have no way to do that.

**Comment by pixelzoom** [comment]
Here a patch that address clicking on the titlebar, but not the titlebar cursor.

<details>
<summary>Patch</summary>

Index: js/AccordionBox.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/AccordionBox.js	(revision dd6b04ce0389a1a1362db306d5e3dd65e4d72ef4)
+++ js/AccordionBox.js	(date 1560364499000)
@@ -216,9 +216,11 @@
     if ( options.titleBarExpandCollapse ) {
       this.collapsedTitleBar.addInputListener( {
         down: function() {
-          self.phetioStartEvent( 'expanded' );
-          self.expandedProperty.value = true;
-          self.phetioEndEvent();
+          if ( self.expandCollapseButton.getEnabled() ) {
+            self.phetioStartEvent( 'expanded' );
+            self.expandedProperty.value = true;
+            self.phetioEndEvent();
+          }
         }
       } );
     }
@@ -228,9 +230,11 @@
       if ( options.titleBarExpandCollapse ) {
         this.expandedTitleBar.addInputListener( {
           down: function() {
-            self.phetioStartEvent( 'collapsed' );
-            self.expandedProperty.value = false;
-            self.phetioEndEvent();
+            if ( self.expandCollapseButton.getEnabled() ) {
+              self.phetioStartEvent( 'collapsed' );
+              self.expandedProperty.value = false;
+              self.phetioEndEvent();
+            }
           }
         } );
       }
</details>

**Comment by jbphet** [comment]
> @jbphet what do you recommend here?

I'd recommend taking the time to add the `enabledProperty`.  Over Slack @pixelzoom said that this would be fairly hard, but if it's a problem that is going to cause issues in the future, I just think we should do it anyway.

**Comment by pixelzoom** [comment]
The Property in question will not be featured in Graphing Quadratics, so this is not needed for GQIO milestone and phetsims/graphing-quadratics#112.

**Comment by zepumph** [comment]
@jbphet @pixelzoom while this may not block GQIO, it is strange to not have a consistent api for AccordioBox. Could you please let me know what you think of this patch? I'm pretty sure it would work, but don't want to commit when I don't own the common code element. 

<details>

```
Index: js/AccordionBox.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/AccordionBox.js	(revision cdeb2bd44edf4413fa4e86f7276fd2c0390bd183)
+++ js/AccordionBox.js	(date 1561595819901)
@@ -136,6 +136,15 @@
     // @private Add listeners to handle dispose
     this.disposeEmitterAccordionBox = new Emitter();
 
+    // @private
+    this.enabledProperty = new BooleanProperty( true, {
+      tandem: options.tandem.createTandem( 'enabledProperty' ),
+      phetioFeatured: true
+    } );
+    this.disposeEmitterAccordionBox.addListener( function() {
+      self.enabledProperty.dispose();
+    } );
+
     // @private {Node}
     this.titleNode = options.titleNode;
 
@@ -216,9 +225,11 @@
     if ( options.titleBarExpandCollapse ) {
       this.collapsedTitleBar.addInputListener( {
         down: function() {
-          self.phetioStartEvent( 'expanded' );
-          self.expandedProperty.value = true;
-          self.phetioEndEvent();
+          if ( self.enabledProperty.get() ) {
+            self.phetioStartEvent( 'expanded' );
+            self.expandedProperty.value = true;
+            self.phetioEndEvent();
+          }
         }
       } );
     }
@@ -228,13 +239,22 @@
       if ( options.titleBarExpandCollapse ) {
         this.expandedTitleBar.addInputListener( {
           down: function() {
-            self.phetioStartEvent( 'collapsed' );
-            self.expandedProperty.value = false;
-            self.phetioEndEvent();
+            if ( self.enabledProperty.get() ) {
+              self.phetioStartEvent( 'collapsed' );
+              self.expandedProperty.value = false;
+              self.phetioEndEvent();
+            }
           }
         } );
       }
     }
+
+    // TODO: do we need to do this the other way? see https://github.com/phetsims/sun/issues/514
+    this.enabledProperty.link( enabled => {
+      this.expandCollapseButton.setEnabled( enabled );
+      this.collapsedTitleBar.cursor = enabled ? options.cursor : null;
+      this.expandedTitleBar.cursor = enabled ? options.cursor : null;
+    } );
 
     // If we hide the button, disable interactivity of the title bar, see https://github.com/phetsims/sun/issues/477
     this.expandCollapseButton.on( 'visibility', () => {

```

</details>

**Comment by zepumph** [comment]
Actually I'm going to promote the priority, because if this is as simple as applying the patch, we should get it done with before GQIO.

**Comment by pixelzoom** [comment]
@zepumph that patch will yield the desired end result, so proceed if you'd like.  But a few things:

* The new private Property `enabledProperty` has a misleading name.  We're not enabling/disabling the AccordionBox, we're enabling/disabling the ExpandCollapseButton.  Disabling the AccordionBox would gray out the entire AccordionBox.  If you want to proceed with this, please name the Property `expandCollapseButtonEnabledProperty`.

* It doesn't address the root cause in sun buttons, which is https://github.com/phetsims/sun/issues/515.  When that issue is addressed, it would be nice if someone remembers to remove this workaround.

* It doesn't address the even more fundamental problem of a uniform API for `enabledProperty` in https://github.com/phetsims/sun/issues/257#issuecomment-502900733.   It adds yet-another (odd) way that a button gets enabled/disabled.

**Comment by zepumph** [comment]
>It adds yet-another (odd) way that a button gets enabled/disabled.


I'm not sure I agree. I thought the goal of this was to sync up the titlebar interaction with the button. So in fact this is a scope outside of just the button. 

Would you instead prefer to link to the button's enabledProperty and change the cursor that way?

**Comment by pixelzoom** [comment]
> I'm not sure I agree. I thought the goal of this was to sync up the titlebar interaction with the button. So in fact this is a scope outside of just the button.

Yes, the goal is to disable interactivity of the titlebar when the ExpandCollapseButton is hidden or disabled. That has nothing to do with whether the AccordionBox itself is enabled or disabled (which is currently not supported, and will be addressed by https://github.com/phetsims/sun/issues/257#issuecomment-502900733). 

> Would you instead prefer to link to the button's enabledProperty and change the cursor that way?

Yes, definitely.

**Comment by zepumph** [comment]
Oh I see. Thanks! Then I'll see you over in https://github.com/phetsims/sun/issues/515.

**Comment by pixelzoom** [comment]
>> Would you instead prefer to link to the button's enabledProperty and change the cursor that way?
> Yes, definitely.

To clarify...  Yes, I would like to sync with the ExpandCollapseButton's `enabledProperty`.  But no, I do not want to reach inside ExpandCollapseButton and link to `buttonModel.enabledProperty`.   I'm advocating addressing #515, then doing this correctly in AccordionBox.

As for whether this needs to be addressed for GQIO...  The use-case for AccordionBoxes was originally to hide the ExpandCollapseButton, and that works correctly.  I see little value in disabling the ExpandCollapseButton, so my feeling is there is no urgency to address this for GQIO.

**Comment by pixelzoom** [comment]
@zepumph Also apologies if the title of this issue, "AccordionBox should have an enabledProperty ..." sent you down the garden path in your patch.   I believe that I created this issue hurriedly during a design meeting.

**Comment by zepumph** [comment]
No problem!

**Comment by zepumph** [comment]
Above I added a fix for this. It may not be best, but I like its simplicity and look forward to making it that much better as part of https://github.com/phetsims/sun/issues/257. @pixelzoom please review this change. Does this seem like a reasonable stop gap for GQIO? See also the supporting commit in https://github.com/phetsims/sun/issues/515 that made this work possible.

**Comment by pixelzoom** [comment]
As I said over in https://github.com/phetsims/sun/issues/515#issuecomment-508195615 ... 
> If it were me, I would have just deferred #514, I don't enabledProperty for AccordionBox’s ExpandCollapseButton should be a priority for GQIO. The use case for GQ (and I believe sims in general) is to hide the button so that students could not collapse the AccordionBoxes. I see little value in disabling the button.

That said... I think that  https://github.com/phetsims/sun/commit/87a8115334cb6adf3a5f9ab1be5402f0ee3d616b should be documented as a temporary solution, with a TODO that links back to this issue. Otherwise it's likely to become permanent.    And this issue should remain open until we have a permanent solution.

**Comment by zepumph** [comment]
I definitely agree with that sentiment as it pertains to https://github.com/phetsims/sun/issues/515#issuecomment-508195615. I don't know if that carries over here as much though. To me https://github.com/phetsims/sun/commit/87a8115334cb6adf3a5f9ab1be5402f0ee3d616b feels like a reasonable solution. Whatever is solution that is come up with in https://github.com/phetsims/sun/issues/257 should have the ability to expose an enabledProperty for the button, and we can update the usages in AccordionBox to use the new pattern whenever we update the other usages of enabledProperty related functions in RectangularButtonView. 

To me this issue feels good to close. @pixelzoom would you please close or recommend why you think the above commit isn't up to code standards?

**Comment by pixelzoom** [comment]
Yes that seems reasonable.  Presumably when RectangularButtonView `getEnabledProperty` goes away, we'll have no choice but to switch to the permanent solution for #515 here.

Closing.
