### ISSUE TITLE
branch: enabledDisabledMixinExperiments

### ISSUE THREAD

**Issue by jbphet** [phetsims/sun#516]
This branch is intended to be used to experiment on using a mixin or a trait to implement enabled/disabled behavior in a way that is consistent across sun UI components and doesn't result in a bunch of boilerplate code.  See https://github.com/phetsims/sun/issues/257.

**Comment by pixelzoom** [comment]
@jbphet I see no branch with this name. Was it deleted?

**Comment by jbphet** [comment]
Nope, just not yet pushed.

**Comment by jbphet** [comment]
@zepumph has taken on much of the work for creating a mixin to handle enabled/disabled functionality, please see https://github.com/phetsims/sun/issues/257.  That's progressing well, so I'm going to delete the enabledDisabledMixinExperiments branch.

**Comment by jbphet** [comment]
Turns out I never pushed the branch anyway, so I just deleted my local copy.  Closing.
