### ISSUE TITLE
opening a modal Dialog should interrupt interactions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#520]
Over in https://github.com/phetsims/gas-properties/issues/149, it was noted that opening a modal Dialog does not cancel interactions that are in progress.  For example, in Gas Properties, a Dialog may open as the result of the user is interacting with a slider or other UI component.  If the user hasn't release the slider thumb, they can continue to interact after the Dialog has been opened.   

It seems like (in general) all interactions should be interrupted when a modal Dialog is opened. And this should be handled in common code, not in sim code.

Since this issue is likely to take awhile, and Gas Properties publication is top priority, https://github.com/phetsims/gas-properties/issues/149 will be addressed in sim code.  So when this issue is addressed, please reexamine Gas Properties.

Assigning to @ariel-phet for prioritization and assignment.

**Comment by ariel-phet** [comment]
I highly doubt this issue will get worked on until there is some pressing need reported (although the Gas properties example is not a great UX, it is not particularly problematic from a pedagogical standpoint or such). Closing.
