### ISSUE TITLE
Depressed buttons on iOS 13 look wrong

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/sun#526]
For https://github.com/phetsims/QA/issues/427.  Not caused by that update however.
The image for the depressed button that starts a wave seems wrong on iOS 13.  Also seen when depressing buttons such as reset all on any sim.
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/65062297-fb5bbc80-d938-11e9-8d65-56a10ebd4962.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/65062298-fb5bbc80-d938-11e9-8b9f-25eb0c6ef497.png)

**Comment by jonathanolson** [comment]
This is live in a bad state on iOS 13 on my phone. Elevating the priority, investigating workarounds.

**Comment by jonathanolson** [comment]
It looks like the general SVG and Canvas radial gradients with different start/end points are failing to display. This is also visible for https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Gradients where on iOS 13 it shows up badly:

![IMG_1906](https://user-images.githubusercontent.com/480878/65274210-09980d00-dae0-11e9-9f79-0cf9304148f9.PNG)

**Comment by jonathanolson** [comment]
This has been noticed in https://bugs.webkit.org/show_bug.cgi?id=201390 a few days ago, is marked as a problem in a lower framework (which makes sense). I added a comment with my reproducible example.

**Comment by KatieWoe** [comment]
@loganbraywork just suggested, and I checked, this does hit the app, including the Rutherford Scattering part.

**Comment by ariel-phet** [comment]
@KatieWoe I assume if https://github.com/phetsims/QA/issues/432 fixes the remaining platform, this issue can be closed

**Comment by KatieWoe** [comment]
It looks like it does.  I'll close as soon as everything is confirmed there

**Comment by KatieWoe** [comment]
Looks good there
