### ISSUE TITLE
Thumb is positioned incorrectly with Slider's enabledRangeProperty

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/sun#527]
For example, in density, see how the thumb is outside of the enabled range marked on the track. The track range is correct, the thumb is out of place.
![image](https://user-images.githubusercontent.com/6396244/65555375-82410400-defa-11e9-9d14-d375bccf196c.png)
 
And in a more simple example:
![image](https://user-images.githubusercontent.com/6396244/65555388-8d942f80-defa-11e9-84f0-81ad28489279.png)

```js
    const testProperty = new Property( 1 );
    const testControl = new NumberControl( 'Test', testProperty, new Range( 0, 27 ), {
      sliderOptions: {
        enabledRangeProperty: new Property( new Range( 0.4, 4 ) )
      }
    } );
```

**Comment by jessegreenberg** [comment]
This is happening because the track is centered in Slider.js with `valueToPosition` (dependent on the enabledRangeProperty) rather than the entire range of the slider with `fullRangeValueToPosition`. This could be fixed by changing the slider to be positioned relative to the full track rather than the enabled portion.

But I think it would be clearer if there was just one `valueToPosition` function that returns the correct position along the track for a value so we don't run into this again. Having two is confusing. The `valueToPosition` function only needs to change so that the position gets clamped within the enable range. We can accomplish that by constraining the value elsewhere.

**Comment by jessegreenberg** [comment]
Should be fixed with the above commit, tested with a number of enabled ranges and density the usage in density is looking good.

@jonathanolson can you please confirm?

**Comment by jonathanolson** [comment]
Looking great, thanks!
