### ISSUE TITLE
branch: customZoom

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/sun#529]
Motivated by https://github.com/phetsims/scenery/issues/974, but mostly for https://github.com/phetsims/sun/issues/524.  #524 needs to be resolved before I can continue with https://github.com/phetsims/scenery/issues/974,. This branch has a potential solution for #524 but I don't feel confident enough to unleash on master yet. Changes will be considered here first.

**Comment by jbphet** [comment]
I came across this GitHub issue while working on https://github.com/phetsims/special-ops/issues/198, and noticed that it's almost two years old and the linked issues are all closed.  @jessegreenberg - can this branch be deleted and this issue closed?

**Comment by jessegreenberg** [comment]
Yes, thanks - branch deleted.
