### ISSUE TITLE
Changes to the AccessibleValueHandler API

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#530]
From https://github.com/phetsims/gravity-force-lab-basics/issues/181, @twant, @jessegreenberg, and I are interested in making some tweaks to the AccessibleValueHandler api. In general it is more complicated that it needs to be, and could use some more documentation. 

- [x] delete a11yDecimalPlaces because it can be filled by a11yMapValue
- [x] delete a11yValuePattern because it can be filled by the aria valuetext creator
- [x] a11yMapValue to apply to min/max too
- [x] check case where a11yMapValue would invert
- [x] add doc that a11yMapValue applies to the min and max too
- [x] rename a11yCreateValueChangeAriaValueText -> a11yCreateAriaValueText
- [x] document roundToStepSize that it changes the valueProperty
- [x] Use numberOfDecimalPlaces to calculate `step` instead of `a11yDecimalPlaces`
- [x] Check in on the implementation of setting the 'step' attribute. Perhaps @jessegreenberg can speak to its purpose.

**Comment by zepumph** [comment]
@twant and I worked on this today, and we got pretty far. There is still a bit more to work on, and a few questions came up. 

>check case where a11yMapValue would invert

@jessegreenberg we found that this failed in area model sims when we tried to assert that the mapped min was always smaller than the mapped max. I'm not sure how to proceed from here, but we commented out the assertion with a todo pointing to this issue.

> Check in on the implementation of setting the 'step' attribute. Perhaps @jessegreenberg can speak to its purpose.

@twant and I weren't really sure what went into calculating the step. We know that if it is too small than there is a problem, but are there any other considerations? Here is what the current algorithm is doing:

```js
        updateSiblingStepAttribute() {
          const smallestStep = Math.min( Math.min( this.keyboardStep, this.shiftKeyboardStep ), this.pageKeyboardStep );
          let stepValue = Math.pow( 10, -Util.numberOfDecimalPlaces( smallestStep ) );

          const fullRange = this._rangeProperty.get().getLength();

          // step is too small relative to full range for VoiceOver to receive input, fall back to portion of
          // full range
          if ( stepValue / fullRange < 1e-5 ) {
            stepValue = fullRange / 100;
          }

          this.setAccessibleAttribute( 'step', this.getMappedValue( stepValue ) );
        }


```

I don't feel like the stepValue is calculated that intelligently, in fact for https://github.com/phetsims/gravity-force-lab-basics/commit/477075b9366e6bae8634c8da7895e2d486919c39 we had to add the `Math.ceil` part so the step was not `0`. Is this sim-specific workaround alright? I don't know how else to handle this. Over in https://github.com/phetsims/gravity-force-lab-basics/issues/170#issuecomment-524118376 there was talk of adding a `step` feature directly to a NumberProperty, what if a11y used that too in some cases?

**Comment by jessegreenberg** [comment]
> check case where a11yMapValue would invert

I am remembering now that a11yMapValue was specifically added for this case. The case in area-model is that we want the "up" arrow key to make the model Property go down because a decreasing model Property has the view representation go higher in the screen. We should decide whether or not to allow this.  If we do not allow, the client will need to create an adapter Property to get the right behavior. If we allow, we cannot apply a11yMapValue to min and max values of the slider.

I think my preference is to require an adapter Property in this case.

**Comment by jessegreenberg** [comment]
> weren't really sure what went into calculating the step. 

For the full rational and history please see documtation for updateSiblingStepAttribute. I am not sure how usability with keyboard or AT will be impacted by these changes. Before this, we could assume that `step` attribute use purely an implementation detail calculated to make sure that the slider was usable and the screen reader didn't say "Invalid" every value change.

To work will, the `min`, `max`, `step`, and `value` attributes must conform to 
`value` = `min` + n * `step` where `value` <= max.

PhET sliders do not conform to this, but this limitation is enforced by the DOM.

**Comment by jessegreenberg** [comment]
I checked a number of sims with sliders, `min` `max` and `value` attributes all look correct to me! But I think the following commit is more accurate to what `updateSiblingStepAttribute` was before this issue. And this way the `step` attribute cannot be modified directly with `a11yMapValue`. @zepumph and @twant what do you think?

**Comment by jessegreenberg** [comment]
I just noticed that `smallestStep` in `updateSiblingStepAttribute` probably wont work in the case that one of the step values is zero. We may need to add a11yDecimalPlaces or something like it back in for this.

**Comment by jessegreenberg** [comment]
In https://github.com/phetsims/scenery/issues/1001 @KatieWoe reported that the mass spinners cannot be incremented on mobile VO (though they can be decremented), and I verified it wasn't related to that issue. Just posting here because it seems like it could be related to changes in this issue.

**Comment by zepumph** [comment]
>I just noticed that smallestStep in updateSiblingStepAttribute probably wont work in the case that one of the step values is zero.

What about `          const smallestStep = Math.min( ...[ this.keyboardStep, this.shiftKeyboardStep, this.pageKeyboardStep ].filter( x => x !== 0 ) );` ?

**Comment by jessegreenberg** [comment]
> mass spinners cannot be incremented on mobile VO (though they can be decremented),

Fixed in the above commit.

**Comment by zepumph** [comment]
>Fixed in the above commit.

Thank you so much! I sorta thought that `a11yMapValue` was more of a "view" related feature, and that it wouldn't effect the setting of the valueProperty. I guess I was wrong.

**Comment by jessegreenberg** [comment]
> I sorta thought that a11yMapValue was more of a "view" related feature, 

I agree with this! But `handleInput` has to break that pattern unfortunately to work correctly. Maybe there is a better way, but that is for another issue.

> What about const smallestStep = Math.min( ...[ this.keyboardStep, this.shiftKeyboardStep, this.pageKeyboardStep ].filter( x => x !== 0 ) );

Oh I see. I am thinking about the usage with NumberControl. Ideally the smallestStep would be equal to the delta of the arrow buttons.

**Comment by zepumph** [comment]
>I agree with this! But handleInput has to break that pattern unfortunately to work correctly. Maybe there is a better way, but that is for another issue.

see https://github.com/phetsims/sun/issues/531

>Oh I see. I am thinking about the usage with NumberControl. Ideally the smallestStep would be equal to the delta of the arrow buttons.

I think that this is an typical case. I don't think that should define the rule for `AccessibleValueHandler`. Maybe we just need a way to override it. Do you think our life would be easier if we just created an option to calculate step, or a step setting function specifically? If so would you make another issue for that?

**Comment by zepumph** [comment]
>check case where a11yMapValue would invert

I think that https://github.com/phetsims/sun/issues/531 will test this one further. @jessegreenberg is there anything else for this issue? Please review.

**Comment by pixelzoom** [comment]
Reminder that there is still dead code in AccessibleValueHandler.ts that references this issue:

```js
        // TODO: should this assert be added back in? Right now area model fails it, see https://github.com/phetsims/sun/issues/530
        // assert && assert( mappedMin <= mappedMax, 'min should be less than max' );
```

**Comment by zepumph** [comment]
@jessegreenberg I'd say get rid of it. It makes an assumption about our mapping that won't last generall.

**Comment by jessegreenberg** [comment]
OK, I removed that assertion. While reviewing this issue I found more reasons to remove it in https://github.com/phetsims/sun/issues/530#issuecomment-537630694.

Otherwise, there is nothing left to do here. Discussion starting https://github.com/phetsims/sun/issues/530#issuecomment-537630694 is review that already happened for this issue. https://github.com/phetsims/sun/issues/531 was opened as a side issue, but there are no commits there yet. The last comment in https://github.com/phetsims/sun/issues/530#issuecomment-539126666 is just confirming that this is ready to close. Commits that came after that are from merges.

Closing.
