### ISSUE TITLE
Questions for AccordionBox layout

### ISSUE THREAD

**Issue by chrisklus** [phetsims/sun#533]
I'm attempting to explicitly set the size of an AccordionBox with its contentNode, and am getting behavior that I wouldn't expect, given the descriptions of its options.

With this rectangle as the contentNode:

```js
const contentNode = new Rectangle( {
  rectWidth: NumberPlayConstants.NUMERAL_ACCORDION_BOX_WIDTH, // (193)
  rectHeight: 120,
  fill: 'red',
  lineWidth: 0
} );
```

and these AccordionBox options:

```js
ACCORDION_BOX_OPTIONS: {
  resize: false,
  titleAlignX: 'left',
  titleXSpacing: 8,
  showTitleWhenExpanded: false,
  cornerRadius: 6,
  titleYMargin: 10,
  buttonXMargin: 10,
  buttonYMargin: 10,
  contentXMargin: 0,    // <---- this is the most relevant option
  contentYMargin: 0,
  contentAlign: 'center', // <-- default, but changing this gives different results, see below 
  minWidth: 0, // <------------- also default, but included for clarity
  expandCollapseButtonOptions: {
    sideLength: 20
  }
},
```

Here is the result with `contentAlign: 'left'`:
![image](https://user-images.githubusercontent.com/5618316/66694411-e85eb280-ec80-11e9-8142-a82178db2365.png)

`contentAlign: 'center'`:
![image](https://user-images.githubusercontent.com/5618316/66694417-0a583500-ec81-11e9-828e-73ad5f9e2a24.png)

`contentAlign: 'right'`:
![image](https://user-images.githubusercontent.com/5618316/66694357-78502c80-ec80-11e9-8088-0046678c4f03.png)

Here is `contentXMargin` option, from AccordionBox.js:

```js
contentXMargin: 15, // horizontal space between content and left/right edges of box
```

Given "edges of box" from comment above, along with leaving `minWidth` set to 0, and `contentXMargin` set to 0, shouldn't the content take up the full width of the accordion box? And then shouldn't `contentAlign` not change any behavior?

As a substitute, I'm passing `minWidth`/`maxWidth` to the AccordionBox options and just using a height in my contentNode, and that's working nicely (and I'm doing a sprint, so these details aren't critical for my purposes). But I was wondering if this behavior seemed odd to anyone else too, or if I'm missing something, and this is expected. @pixelzoom what do you think?

**Comment by pixelzoom** [comment]
As you've discovered, AccordionBox has two many options, some of them don't play nice together, many (most) of them haven't been tested together.  It has reached the point inn its lifecycle where its entropy (disorder) is high, and that's starting to manifest as unexpected/buggy behavior.   That said...

I suspect that your specific problem manifests with `showTitleWhenExpanded: false`.  To test that suspicion, what is the behavior with `showTitleWhenExpanded: true`?   Do the margins and and alignment of content behave as expected?

**Comment by pixelzoom** [comment]
As you've discovered, AccordionBox has two many options, some of them don't play nice together, many (most) of them haven't been tested together.  It has reached the point in its lifecycle where its entropy (disorder) is high, and that's starting to manifest as unexpected/buggy behavior.   That said...

I don't see anything obviously wrong with how you're using the options. And I agree that the behavior looks buggy. 

I suspect that your specific problem manifests with `showTitleWhenExpanded: false`.  To test that suspicion, what is the behavior with `showTitleWhenExpanded: true`?   Do the margins and and alignment of content behave as expected?

**Comment by chrisklus** [comment]
>I suspect that your specific problem manifests with `showTitleWhenExpanded: false`.  To test that suspicion, what is the behavior with `showTitleWhenExpanded: true`?   Do the margins and alignment of content behave as expected? 

Thanks @pixelzoom - that's it, yep. The contentNode takes up the full width with `showTitleWhenExpanded: true`.

It looks like this else is (intentionally) the cause:

```js
// Compare width of title section to content section of the accordion box
// content is below button+title
if ( this._showTitleWhenExpanded ) {
  return Math.max( width, this._contentNode.width + ( 2 * this._contentXMargin ) );
}
// content is next to button
else {
  return Math.max( width, this.expandCollapseButton.width + this._contentNode.width + this._buttonXMargin + this._contentXMargin + this._contentXSpacing );
}
```

If I change that line to:
```js
return Math.max( width, this._contentNode.width + this._contentXMargin + this._contentXSpacing );
```
with these options (all necessary):

```js
showTitleWhenExpanded: false,
contentXMargin: 0,
contentYMargin: 0,
contentXSpacing: 0
contentAlign: 'right' // ??
```

then I get my desired behavior:

<img width="457" alt="Screen Shot 2019-10-12 at 12 09 02 PM" src="https://user-images.githubusercontent.com/5618316/66704353-22639f00-ece9-11e9-816d-d8527675c06e.png">

The only thing I have time to do to help my case is add a new boolean option for if the content node goes to the right of the button or not when the title bar is not shown when expanded. But based on your thoughts in https://github.com/phetsims/sun/issues/533#issuecomment-541289977, another option may not be desirable. 

As I mentioned in https://github.com/phetsims/sun/issues/533#issue-506126734, I have an alternate solution that is working well enough, so I'm happy to call this a no-op. But, if you think this potential new option would be worth including, then I'd be glad to add it (and it would make my sim code a little nicer).

**Comment by pixelzoom** [comment]
I think we should hold off on adding additional options. 

Before adding more features to AccordionBox, I would push back on the design, and explain that it's not supported by AccordionBox.  If it's imperative to support, then consider adding options.
 
As a last resort (or maybe OK for a sprint)... You could support the above design by setting `showTitleWhenExpanded: true` and making the title invisible yourself when expanded.

**Comment by chrisklus** [comment]
Sounds good, thanks. Adjusting the design should be fine for now, especially since we're not including the language components of that accordion box yet.

@amanda-phet is this okay with you? This issue will be more noticeable when we have the same problem on the Ones and Objects accordion box, so if that's a bigger deal I can try out @pixelzoom's suggestion from above.

![image](https://user-images.githubusercontent.com/5618316/66790030-1bd95100-eebc-11e9-8152-ca54016e1ef9.png)

**Comment by amanda-phet** [comment]
I don't think this is really an issue in this particular accordion box, but more with the "objects" and "ones" boxes. We will be fine proceeding with the constraints on accordion box. 

However, it makes me wonder if there is a more appropriate UI component for what we want to accomplish... should it just be a panel, with a title and expandCollapseButton outside the panel? Should we brainstorm a better solution? In any case, moving forward with accordion box and the constraints on the content is just a design compromise I am fine making, but it makes me wonder if we are simply picking the wrong tool for the job. 

Back to @chrisklus to close if this resolves the issue, or leave open in case you want to keep working out a solution for the content bounds for "ones" and "objects."

**Comment by chrisklus** [comment]
I ended up using a different solution than anything discussed in this issue in order to have full access to the accordion box bounds, basically just by overriding the accordion box `localBounds`, see https://github.com/phetsims/number-suite-common/blob/master/js/common/view/NumberSuiteCommonAccordionBox.ts. This enabled me to allow dragging an object anywhere in the accordion box, see drag behavior in the Object and Ones accordion box here: https://phet.colorado.edu/sims/html/number-play/latest/number-play_all.html

I think we are set to close here.
