### ISSUE TITLE
Add the ability to expand the combo box touch area

### ISSUE THREAD

**Issue by jbphet** [phetsims/sun#537]
For https://github.com/phetsims/number-line-integers/issues/34 we have been asked to expand the touch area for the combo box, but `ComboBox.js` doesn't seem to support this ability.

**Comment by jbphet** [comment]
I've added the ability to dilate the button, and I've done so by following the pattern that has been used thus far, which is to have non-nested options that are specific to the button.

@pixelzoom - you're the only listed author on this.  Can  you please review this change and, first of all, make sure that it's not misguided in general and second, decide if we should log a separate issue to migrate this towards a nested option approach?

**Comment by pixelzoom** [comment]
> make sure that it's not misguided in general and second, decide if we should log a separate issue to migrate this towards a nested option approach?

The approach looks good, and I don't think you need to do anything about nested options at this time. But...

You've only added touchArea dilation. And it's not OK to just add dilation for the pointer area that you're interested in.  We decided awhile back that touchArea and mouseArea dilation should be added uniformly. So please add mouseArea dilation.

**Comment by jbphet** [comment]
Thanks for the reminder @pixelzoom, I had forgotten about the requirement to also add mouse area dilation.  I've done this, and tested it in the context of the Number Line: Integers sim (dilated the mouse are of one combo box but not the other) and it appeared to work fine.  Back to you in case you want a final look.

**Comment by pixelzoom** [comment]
👍 closing.
