### ISSUE TITLE
VSlider should "flip" trackSize and thumbSize for you

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#544]
From https://github.com/phetsims/molarity/issues/165.

When passing `trackSize` to `VSlider`, the first dimension (width), ends up being the vertical dimension, since `Slider.js` was originally implemented as only horizontal, this change seems understandable and reasonable.

There are 17 usages of VSlider, and any of those usages using these `size` options needed to understand the inner workings of Slider well enough to know that they needed to flip that Dimension2 manually.

**Comment by zepumph** [comment]
Implemented above. I  didn't end up touching any other options besides `trackSize` and `thumbSize`.

@samreid would you please review. Note that some usages were a little bit weird to swap next to `*Dilation` options, for example see change in `HeaterCoolerFront.js`. Do you think that this is alright?

**Comment by samreid** [comment]
Should VSlider use `flip` for its implementation instead of:
```js
    if ( options.trackSize !== undefined ) {
      options.trackSize = new Dimension2( options.trackSize.height, options.trackSize.width );
    }
    if ( options.thumbSize !== undefined ) {
      options.thumbSize = new Dimension2( options.thumbSize.height, options.thumbSize.width );
    }
```

This a11y annotation looks misplaced:

```js
        // a11y
        sliderOptions: {
          trackSize: new Dimension2( SLIDER_TRACK_WIDTH, cylinderSize.height ),
          accessibleName: soluteAmountNoNewlineString,
          a11yCreateAriaValueText: () => soluteAmountDescriber.getSoluteAmountValueText()
        }
```

And it was unclear why molarity was changed, since it doesn't use VSlider, can you please comment?

**Comment by zepumph** [comment]
VerticalSlider.js does use VSlider. The reason why usages in MolarityScreenView.js weren't changed is because VerticalSlider was doing the work of flipping the track dimensions that I added to VSlider in this issue. See https://github.com/phetsims/molarity/commit/92dfa1b83705c2683028f0b7014aab30d86c8ff7#diff-c0d9c552a6bcfab85ab88e73b3701e9aL87

Now VSlider is doing that work.

**Comment by samreid** [comment]
> @samreid would you please review. Note that some usages were a little bit weird to swap next to *Dilation options, for example see change in HeaterCoolerFront.js. Do you think that this is alright?

Are the dilations also swapped?

One more note, I think we should rename `flip` to `flipped` because `flip` sounds more like it will mutate the Vector2.

**Comment by zepumph** [comment]
@chrisklus mentioned that heater-cooler node's slider thumb is tall and skinny instead of wide  and short.

**Comment by zepumph** [comment]
EFAC was providing custom thumbs to HeaterCoolerFront that also needed switching. I'll do another pass through all VSlider instances looking for these changes.

While doing this I will also look through and swap the X and Y options for :
* thumbTouchAreaXDilation
* thumbTouchAreaYDilation
* thumbMouseAreaXDilation
* thumbMouseAreaYDilation


* I will also rename `flip` to `flipped`

**Comment by zepumph** [comment]
I implemented the flipping of the dilation options by creating `swapObjectKeys`, which made things much nicer and simpler in VSlider. In general this was much easier than the dimension options because for the most part usages were dilating by the same amount for X and Y, thus no change was needed. 

I also implemented `flipped` rename. I didn't see any other issues with dimension options, after I followed usages a bit further (not just to option blocks but to were instances pass in options).

I also looked through Slider.js for other options that may be orientation dependent, and didn't find any others.

@samreid please review these final steps. Anything else here?

**Comment by samreid** [comment]
Can you please speculate about an alternative API where we no longer refer to width and height, but rather refer to the dimension along the length of the track and its perpendicular?  This way we wouldn't need to do any `flipped()` and when converting an HSlider to VSlider or vice versa, no code changes would be necessary in the options.

**Comment by zepumph** [comment]
GQ was using `extends VSlider` instead of `new VSlider`. Updated above quickly. I also looked for `VSlider.call`.

**Comment by samreid** [comment]
Also, what about using the features of the new Orientation enumeration to generalize this?

**Comment by samreid** [comment]
Back to @zepumph to comment on the 2 brainstorm-y ideas from the past 3 comments.  We can open new issues for them if they are worth proceeding but outside of the scope of this issue.

**Comment by zepumph** [comment]
I personally feel like swapping makes the most sense. width/height or x/y make a lot of sense and are conventional to our project. Refactoring to have options more like "alongTrack/acrossTrack" seems like it would be more confusing. 

If you feel like exploring using Orientation to solve VSlider vs HSlider differences, would you please open a new issue to investigate and explain?

**Comment by samreid** [comment]
I don't think we need an issue for that potential future change.  If we are working more in Slider, we may think of it again.  Everything else seems ready to close.
