### ISSUE TITLE
Dialog: add option to specify color of close button 'X'

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#545]
The current implementation assumes that the close button ('X') is always black.  That doesn't work for Natural Selection, where we want this:

<img width="564" alt="screenshot_11" src="https://user-images.githubusercontent.com/3046552/70162011-38069c80-167a-11ea-88ef-fe2e1597f595.png">

So I'm going to add an option to specify the close button color.

**Comment by pixelzoom** [comment]
I added this option in the above commit, which I'm using in natural-selection:

```js
112 closeButtonColor: 'black', // {Color|null} color for the close button 'X'
```

@ariel-phet please assign someone to review.

**Comment by jessegreenberg** [comment]
Looks great!
