### ISSUE TITLE
RadioButtonGroup does not create LinkedElements

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#549]
Related to https://github.com/phetsims/sun/issues/420.

RadioButtonGroup does not currently create a link between the radio buttons that it creates and the Property associated with the group.  This was identified as a defect in Natural Selection during preliminary review of instrumentation.  See https://github.com/phetsims/natural-selection/issues/35.

I'm also surprised that this hasn't shown up as an instrumentation defect in more "mature" PhET-iO sims, e.g. BASE.  Are there any other sims that need to be republished due to this issue?

I'll leave this up to the PhET-iO team to prioritize.  But it would be nice to get it addressed sooner rather than later.

**Comment by samreid** [comment]
I added support for this in the preceding commits.  @pixelzoom can you please confirm it works as expected in Natural Selection?  @zepumph would you like to review more generally?

**Comment by pixelzoom** [comment]
The first comment in this issue says:

> RadioButtonGroup does not currently create a link between the radio buttons that it creates and the Property associated with the group.

It still doesn't do this. The Property is associated with the group element, not with the radio buttons.  Is that what you intended? Is that acceptable to designers, or are they expecting to drill down to the radio buttons and find associate Properties (as is the case with Checkbox)?  

Here's what I see for `naturalSelection.labScreen.view.environmentDisplayNode.environmentRadioButtonGroup`, an instance of `EnvironmentRadioButtonGroup`, in Natural Selection:

<img width="380" alt="screenshot_28" src="https://user-images.githubusercontent.com/3046552/71043079-c2bfb080-20ea-11ea-8b4f-4f277dc9c931.png">

**Comment by pixelzoom** [comment]
With `VerticalAquaRadioButtonGroup`, the Property is associate with each button.  See example below from Natural Selection, `GraphsRadioButtonGroup`.  Why should `RadioButtonGroup` and `VerticalAquaRadioButtonGroup` be instrumented differently?   This seems like another impediment to unifying the  implementations of radio buttons and their groups, see https://github.com/phetsims/sun/issues/523.

<img width="375" alt="screenshot_29" src="https://user-images.githubusercontent.com/3046552/71043956-7de94900-20ed-11ea-955b-dba669080692.png">

**Comment by samreid** [comment]
> The Property is associated with the group element, not with the radio buttons. Is that what you intended?

Yes, I intended to associate one Property per RadioButtonGroup.  Perhaps we should change `VerticalAquaRadioButtonGroup` to do the same.  It seems odd that the `property` should be repeated over and over for a composite group like this.  Let's raise for discussion at an upcoming phet-io design meeting.

**Comment by pixelzoom** [comment]
>  It seems odd that the `property` should be repeated over and over for a composite group like this. 

It doesn't seem odd to me, especially if (1) you expect linked Properties to be associated with the UI components that modify and observe them, and (2) you want uniformity of instrumentation across UI components (checkboxes, radio buttons, sliders, ...)

**Comment by pixelzoom** [comment]
> Perhaps we should change `VerticalAquaRadioButtonGroup` to do the same.

And what about sims that are using `AquaRadioButtonGroup` and not `VerticalAquaRadioButtonGroup`?  Should they be modified to use `VerticalAquaRadioButtonGroup`? Are there any cases where that's problematic?  Can of worms...

**Comment by pixelzoom** [comment]
It also seems a bit odd that radio buttons don't indicate what value is associated with them.  For example in Natural Selection (screenshot below), the radio buttons in `GraphsRadioButtonGroup` don't indicate which value of the `Graphs` enumeration correspond to which buttons. Tandem naming convention, e.g. 'pedigreeRadioButton' and 'PEDIGREE', implies a button-value connection, but nothing enforces that.   And I can chose the '*property' associated with `pedigreeRadioButton` and change it to something other than 'PEDIGREE'.

<img width="1135" alt="screenshot_33" src="https://user-images.githubusercontent.com/3046552/71048207-c576d180-20fb-11ea-93a0-f973e4cc4f8b.png">

**Comment by pixelzoom** [comment]
12/19/19 phet-io meeting notes

Designers said they'd prefer to have the linked Property associated with the group, as is currently done for RadioButtonGroup.  So this needs to be changed for VerticalAquaRadioButtonGroup.  

This also means that all AquaRadioButtons will need to be instantiated via VeticalAquaRadioButtonGroup, not instantiated directly and added to a custom "group" implementation.  This is probably a good constraint, since the group needs to support both phet-io and a11y.

**Comment by pixelzoom** [comment]
How do we move forward with relocating linked Property to the group level for VerticalAquaRadioButtonGroup?

**Comment by pixelzoom** [comment]
This patch seems to do the trick for Natural Selection.  But I'm not committing it because I'm not sure what might break (are there instrumented AquaRadioButtons that are not in a VerticalAquaRadioButtonGroup?) and I'm not familiar with how to update all APIs.

<details>
<summary>Patch</summary>

```
Index: js/AquaRadioButton.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/AquaRadioButton.js	(revision e40e57150a95d047b8c0b6db61994aaf83c1845b)
+++ js/AquaRadioButton.js	(date 1578084535095)
@@ -46,7 +46,6 @@
 
       // phet-io
       tandem: Tandem.REQUIRED,
-      phetioLinkProperty: true,
 
       // {Playable|null} - sound generator, if set to null default will be used, set to Playable.NO_SOUND to disable
       soundPlayer: null,
@@ -159,11 +158,6 @@
 
     this.mutate( options );
 
-    // Add linked element after the radio button is instrumented
-    options.phetioLinkProperty && this.addLinkedElement( property, {
-      tandem: options.tandem.createTandem( 'property' )
-    } );
-
     this.enabledProperty.link( this.updateEnabled.bind( this ) );
 
     // @private
Index: js/VerticalAquaRadioButtonGroup.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/VerticalAquaRadioButtonGroup.js	(revision e40e57150a95d047b8c0b6db61994aaf83c1845b)
+++ js/VerticalAquaRadioButtonGroup.js	(date 1578084535091)
@@ -57,6 +57,7 @@
 
         // phet-io
         tandem: Tandem.REQUIRED,
+        phetioLinkProperty: true,
 
         // supertype a11y options
         tagName: 'ul',
@@ -103,6 +104,11 @@
 
       super( options );
 
+      // Add linked element after the radio button is instrumented
+      options.phetioLinkProperty && this.addLinkedElement( property, {
+        tandem: options.tandem.createTandem( 'property' )
+      } );
+
       // @private
       this.disposeVerticalAquaRadioButtonGroup = () => {
         for ( let i = 0; i < radioButtons.length; i++ ) {
```

</details>

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/sun/issues/555, I identified sims that need to be converted to use VerticalRadioButtonGroup.  It's a surprisingly long list.

**Comment by zepumph** [comment]
@pixelzoom, we moved the linked element declaration out of AquaRadioButton and into VerticalAquaRadioButtonGroup. Thank you for #555, as the phet-io team thinks it is the right way to go. Is there anything else for this issue?

**Comment by pixelzoom** [comment]
Reopening.

PhET-iO team: Over in #555, I ran into seriously problems with trying to use VerticalAquaRadioButtonGroup. We need to rethink this.

**Comment by zepumph** [comment]
So continuing with the assumption that not all AquaRadioButtons can be housed inside a VerticalAquaRadioButtonGroup. One thing we could do to solve this immediate problem is to create `AquaRadioButtonGroup` and make `Vertical. . .` extend it. Then we can put the linked element logic into `AquaRadioButtonGroup` and over in https://github.com/phetsims/sun/issues/550 usages can either convert to be a `Vertical. . . ` (if applicable) or just a `AquaRadioButtonGroup`. 

The only thing I don't like about this is that it is working in a separate direction from https://github.com/phetsims/sun/issues/523 which we know is the end goal. 


I think we should:
1. Not let a PhET-iO sim be published if it has ungrouped AquaRadioButtons.
2. Close this issue.
3. Note that https://github.com/phetsims/sun/issues/550 will fix this once https://github.com/phetsims/sun/issues/523 is further along.

**Comment by pixelzoom** [comment]
> 2. Close this issue.
3. Note that #550 will fix this once #523 is further along.

I disagree.  #550 was (and still is?) about metadata and names.  This issue is more fundamental - it deals with where the linked Property lives.

**Comment by pixelzoom** [comment]
>  One thing we could do to solve this immediate problem is to create `AquaRadioButtonGroup` and make `Vertical. . .` extend it. 

You haven't described the responsibilities of `AquaRadioButtonGroup` so I'm not sure what you had in mind.  Are you suggesting something like `LayoutBox` hierarchy? I.e. `AquaRadioButtonGroup` with convenience subclasses `VerticalAquaRadioButtonGroup` and `HorizontalAquaRadioButtonGroup`.  If so, that doesn't solve the layout problem noted in #555, where radio buttons and (e.g.) checkboxes are interleaved. If you're suggesting that `AquaRadioButtonGroup` should be something that's responsible only for the linked Property, that's very different than other `LayoutBox` or even `RadioButtonGroup`.

**Comment by samreid** [comment]
> You haven't described the responsibilities of `AquaRadioButtonGroup` so I'm not sure what you had in mind. 

In #555 and https://github.com/phetsims/sun/commit/c60001e8409f8671cd57c41df80f950153b4642d we introduced AquaRadioButtonGroup which automatically creates the linked element like so:

```js
    // Add linked element after the radio button is instrumented
    this.addLinkedElement( property, {
      tandem: options.tandem.createTandem( 'property' )
    } );
```

> Then we can put the linked element logic into AquaRadioButtonGroup and over in #550 usages can either convert to be a Vertical. . . (if applicable) or just a AquaRadioButtonGroup.

That won't work well with the way `AquaRadioButtonGroup` is currently implemented--it extends `LayoutBox` and not an arbitrary layout.

Let's look at Acid Base Solutions, which has an interleaved checkbox:

![image](https://user-images.githubusercontent.com/679486/91295740-c2d37e00-e758-11ea-9638-4df96a15120c.png)

Would it be sufficient to leave that code mostly as it is, and manually create the linked element and tandems accordingly?  Like this untested patch:

<details>

```diff
Index: js/common/view/ViewsPanel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/ViewsPanel.js	(revision b3729f51ebca5b28df2d2727969d186a4c2a90c5)
+++ js/common/view/ViewsPanel.js	(date 1598439772621)
@@ -18,6 +18,7 @@
 import AquaRadioButton from '../../../../sun/js/AquaRadioButton.js';
 import Checkbox from '../../../../sun/js/Checkbox.js';
 import Panel from '../../../../sun/js/Panel.js';
+import PhetioObject from '../../../../tandem/js/PhetioObject.js';
 import magnifierImage from '../../../images/magnifier-icon_png.js';
 import acidBaseSolutions from '../../acidBaseSolutions.js';
 import acidBaseSolutionsStrings from '../../acidBaseSolutionsStrings.js';
@@ -64,7 +65,17 @@
         new Image( magnifierImage, ICON_OPTIONS )
       ]
     } );
-    const moleculesRadioButton = new AquaRadioButton( viewModeProperty, ViewMode.MOLECULES, moleculesLabel, RADIO_BUTTON_OPTIONS );
+
+    const radioButtonGroupTandem = tandem.createTandem( 'radioButtonGroup' );
+    const radioButtonGroup = new PhetioObject( {
+      tandem: radioButtonGroupTandem
+    } );
+    radioButtonGroup.addLinkedElement( viewModeProperty, {
+      tandem: options.tandem.createTandem( 'property' )
+    } );
+    const moleculesRadioButton = new AquaRadioButton( viewModeProperty, ViewMode.MOLECULES, moleculesLabel, merge( {
+      tandem: radioButtonGroupTandem.createTandem( 'moleculesRadioButton' )
+    }, RADIO_BUTTON_OPTIONS ) );
     moleculesRadioButton.touchArea = moleculesRadioButton.localBounds.dilatedXY( TOUCH_AREA_X_DILATION, TOUCH_AREA_Y_DILATION );
 
     // Solvent

```

</details>

My main complaint about the patch is that it calls something a `radioButtonGroup` which is not a `Node` and hence cannot be made invisible, etc.  But I don't know that it's practical in this case to combine all of the radio buttons into one Node.

Leaving assigned to @zepumph and reassigning to @pixelzoom for feedback.

**Comment by pixelzoom** [comment]
I don't know where to go with this issue. I'm still of the opinion that the design of these "Group" classes is fundamentally flawed.  It mixes 3 responsibilities (radio button creation, "grouping", and layout) that should not be independent.  E.g. a vertical layout with uniform pointer areas is equally applicable to a collection of radio buttons, checkboxes, or whatever.  For an example of separation of responsibilities, see Java's ButtonGroup and BoxLayout.

**Comment by samreid** [comment]
Did you review the idea and patch in https://github.com/phetsims/sun/issues/549#issuecomment-680812399 which identifies a Group pattern that doesn't include "radio button creation" or "layout" and only includes "tandem-specific grouping"?

**Comment by pixelzoom** [comment]
Yes, I reviewed your patch. I though you were proposing this patch as a workaround for cases like ABS, not a new general pattern.  It basically makes the client responsible for "group" and layout, which isn't much of a solution.  So yeah, we could work around cases like ABS, if the client has to handle everything, and we don't mind losing (or hacking around) the ability to hide the group.   

My point is that we shouldn't need a workaround like this, and it's needed because the fundamental design of PhET's radio-button groups is flawed.

**Comment by samreid** [comment]
What do you recommend we investigate next?

**Comment by pixelzoom** [comment]
Perhaps we should steer this issue back to it's original intent, which was to decide how radio button groups would link to their associated Property.  

In https://github.com/phetsims/sun/issues/549#issuecomment-568003921, designers decided that the Property should be linked to the group, not the individual buttons.   And I can see by the RadioButtonGroup and AquaRadioButtonGroup that I'm using in Natural Selection that that is now the case. 

Examples in NS:

EnvironmentRadioButtonGroup extends RadioButtonGroup:
<img width="245" alt="screenshot_556" src="https://user-images.githubusercontent.com/3046552/92531893-68243280-f1ec-11ea-9e70-ed8cef558313.png">

GraphChoiceRadioButtonGroup extends VerticalAquaRadioButtonGroup:
<img width="239" alt="screenshot_555" src="https://user-images.githubusercontent.com/3046552/92531936-783c1200-f1ec-11ea-895f-f50e300effea.png">

So mission accomplished. And I suggest that we create a new issue (or find the issue that might already exist) that deals with layout problems like this one:

![image](https://user-images.githubusercontent.com/679486/91295740-c2d37e00-e758-11ea-9638-4df96a15120c.png)

**Comment by samreid** [comment]
I believe that problem is described in https://github.com/phetsims/sun/issues/555#issuecomment-570730096.  If you agree, then this issue can be closed.

**Comment by pixelzoom** [comment]
👍🏻 closing
