### ISSUE TITLE
OnOffSwitch: drag-to-toggle vs click-to-toggle

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#552]
Related to https://github.com/phetsims/tasks/issues/1017.

This TODO was added to `OnOffSwitch` by @samreid on 4/16/2015. 

```js
// TODO: A way to distinguish between drag-to-toggle vs click-to-toggle
```

No idea why it would be useful to distinguish, or what this might have been related to.

**Comment by samreid** [comment]
That comment was added during PhET-iO instrumentation, perhaps we were considering a different message for drag vs click.  But maybe that level of detail is irrelevant for data studies.  @zepumph what do you think?  If you think it's unimportant, we can remove the TODO and close this issue.

**Comment by zepumph** [comment]
I do not think that this is a necessary amount of granularity!
