### ISSUE TITLE
use options.enabledProperty in sun 'Buttons' demo

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#554]
Related to https://github.com/phetsims/tasks/issues/1017.

In ButtonsScreenView (the 'Buttons' screen of the sun demo), there's one giant listeners that is setting the enabled state of all demo buttons: 

```js
    //TODO Shouldn't all of these buttons be able to observe buttonEnabledProperty?
    // Set up a property for testing button enable/disable.
    const buttonsEnabledProperty = new Property( true );
    buttonsEnabledProperty.link( function( enabled ) {
      arrowButton.enabled = enabled;
      radioButtonGroup.enabled = enabled;
      verticalAquaRadioButtons.children.forEach( function( radioButton ) {radioButton.enabled = enabled;} );
      buttonA.enabled = enabled;
      buttonB.enabled = enabled;
      buttonC.enabled = enabled;
      buttonD.enabled = enabled;
      buttonE.enabled = enabled;
      button1.enabled = enabled;
      button2.enabled = enabled;
      button3.enabled = enabled;
      button4.enabled = enabled;
      fireButton.enabled = enabled;
      goButton.enabled = enabled;
      helpButton.enabled = enabled;
      fireOnDownButton.enabled = enabled;
      htmlButton.enabled = enabled;
      transparentButton.enabled = enabled;
      roundStickyToggleButton.enabled = enabled;
      booleanRectangularStickyToggleButton.enabled = enabled;
      fireQuicklyWhenHeldButton.enabled = enabled;
      fireSlowlyWhenHeldButton.enabled = enabled;
      upperLeftContentButton.enabled = enabled;
      lowerRightContentButton.enabled = enabled;
      rectangularMomentaryButton.enabled = enabled;
      roundMomentaryButton.enabled = enabled;
    } );
```

It would be preferable to instantiate each of these buttons with option `enabledProperty: buttonsEnabledProperty`.

**Comment by samreid** [comment]
@chrisklus and I noticed this issue did not have an assignee.  Should it be assigned to the person that originally introduced the TODO, at least for triaging?

**Comment by pixelzoom** [comment]
The problem here is that there's no way to pass an `enabledProperty` to sun buttons.   That's being addressed by @jbphet in https://github.com/phetsims/sun/issues/515, so I'm going to assign this one to him as well.

**Comment by pixelzoom** [comment]
In the above commits, I added one test for the enabledProperty option:

```js
    const arrowButton = new ArrowButton( 'left', function() { message( 'ArrowButton pressed' ); }, {
      enabledProperty: buttonsEnabledProperty
    } );
```

I don't see the point in doing this for all buttons, so I left the `buttonsEnabledProperty` listener alone.  Future buttons added to the demo should either use the `enabledProperty` option, or should be added to the `buttonsEnabledProperty` listener.

Closing.
