### ISSUE TITLE
Close ComboBox when focus leaves it

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/sun#557]
Requested in https://github.com/phetsims/molarity/issues/213 - When DOM focus leaves the ComboBox it should close. We have listeners that close the ComboBox on "tab" and "enter" and "esc". But with mobile screen reader with gestures, it is still possible to move somewhere else and interact with other things without closing the ComboBox.

**Comment by jessegreenberg** [comment]
Fixed with the above commit, @zepumph would you mind reviewing this change?

**Comment by zepumph** [comment]
I think that what you have is a workable solution, but I don't think that we should go this direction.

To me it feels better to parallel the strategy used for pointer input. The logic is based around `ComboBox.clickToDismissListener`. I think you could basically move the same logic over to ComboBox.

One other benefit here is that I think calling `ComboBox.hideListBox` will be better than just calling the callback (for example then we get the phet-io event on the data stream).

Let me know if I can help.

**Comment by jessegreenberg** [comment]
Thanks for reviewing, that makes sense. I essentially just moved the listener from ComboBoxListBox to ComboBox and used `hideListBox` instead.

Back to @zepumph, does this look right?

**Comment by zepumph** [comment]
Sorry I don't see a commit.

**Comment by zepumph** [comment]
That looks really nice! It is simple, and well written. Thanks!

**Comment by jessegreenberg** [comment]
Great, thanks for reviewing.
