### ISSUE TITLE
Audit button IO types

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#558]
While working on https://github.com/phetsims/studio/issues/35, I found some weird events in `ResetAllButtonIO` and `RoundMomentaryButtonIO`. At first glance these don't appear to be used. Perhaps we can simplify the IO types for our buttons, and I'm trying to figure out what the ideal data stream would look like for the UI component directly (as we already have input and listener events in addition to the model Property change when applicable).

**Comment by samreid** [comment]
ResetAllButtonIO was deleted in https://github.com/phetsims/scenery-phet/issues/572 and I couldn't find any usages of RoundMomentaryButtonIO.  I deleted it in the commit, and used ph-scale to make sure the API change looked reasonable.  I think this issue can be closed.
