### ISSUE TITLE
Improvements for OnOffSwitch and ABSwitch

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#559]
From discussion with @pixelzoom and @chrisklus today, based on https://github.com/phetsims/balancing-act/issues/101

* Rename ABSwitch to LabeledABSwitch
* Rename OnOffSwitch to ABSwitch, and provide required arguments for aValue, bValue
* Create new type OnOffSwitch which extends ABSwitch and specifies aValue = false, bValue = true.

Assigning to @ariel-phet to decide who can make these improvements.

**Comment by pixelzoom** [comment]
I took a quick look at this, and there are some complications:

* What to do about `OnOffSwitchIO`? Should it just be renamed to `ABSwitchIO`? Will we need a new `OnOffSwitchIO`?
* This adapter Property in the current ABSwitch should probably be moved to the new OnOffSwitch:

```js
64 // property for adapting to OnOffSwitch. 'true' is 'B', the object on the 'on' end of the OnOffSwitch.
65 const onProperty = new Property( valueB === property.get() );
``` 

WAG is 1-3 hours to do this work.

**Comment by ariel-phet** [comment]
I recall there being some complications with ABSwitch and a11y, so I want to get @jessegreenberg weighing in on this question before moving forward.

**Comment by jessegreenberg** [comment]
I did some digging to jog my memory and I think found the a11y issues that you are referring to. Mostly https://github.com/phetsims/balloons-and-static-electricity/issues/112 and then https://github.com/phetsims/balloons-and-static-electricity/issues/213. To summarize, the discussion was about how to handle two radio buttons for accessibility. There was a thought that they could be implemented as an [ARIA switch](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Switch_role) to simplify things for a screen reader user. But I don't recall challenges with the ABSwitch itself.

I can't think of anything from a11y that would change the proposal in https://github.com/phetsims/sun/issues/559#issue-557027536.

**Comment by pixelzoom** [comment]
This issue affects instrumentation of ph-scale, which uses 2 ABSwitches.  Labeling with blocks-sim-publication.

**Comment by samreid** [comment]
@pixelzoom volunteered, thanks!

**Comment by pixelzoom** [comment]
Before I start on this, and because it will significantly affect how I do this...  @arouinfar @ariel-phet Do you think that we'll ever want to have an `OnOffSwitch` with option "On" and "Off" labels?  Like this:

<img width="211" alt="screenshot_113" src="https://user-images.githubusercontent.com/3046552/74204725-95e2d200-4c31-11ea-8cfb-b7e8305968bf.png">

**Comment by pixelzoom** [comment]
Before I start on this, and because it will significantly affect how I do this...  @arouinfar @ariel-phet Do you think that we'll ever want to have an `OnOffSwitch` with option "On" and "Off" labels?  Like this:

<img width="211" alt="screenshot_113" src="https://user-images.githubusercontent.com/3046552/74204725-95e2d200-4c31-11ea-8cfb-b7e8305968bf.png">

I personally don't like labeling the On/Off positions, it's redundant and the "green" is supposed to communicate "on" (and does so very effectively on iOS).

**Comment by pixelzoom** [comment]
A reminder of where OnOffSwitch came from, in case anyone has forgotten:

![IMG_4193](https://user-images.githubusercontent.com/3046552/74204984-9e87d800-4c32-11ea-905c-b4115ecb4e33.PNG)

**Comment by pixelzoom** [comment]
I took a swing at this and ran into the general problem described in https://github.com/phetsims/phet-io/issues/1617.

**Comment by pixelzoom** [comment]
Here's `GraphScaleSwitch`, the ABSwitch that switches the graph between "Logarithmic" and "Linear" scales in pH Scale:

<img width="289" alt="screenshot_115" src="https://user-images.githubusercontent.com/3046552/74208675-ccc0e400-4c41-11ea-9044-515ce6470080.png">

Here's what the Studio tree looks like. Note that the labels are not included, because they are created outside of (and before) the ABSwitch, and passed to the ABSwitch. (This is known as dependency injection.)

<img width="246" alt="screenshot_114" src="https://user-images.githubusercontent.com/3046552/74208682-d4808880-4c41-11ea-9e82-65b0e9dcb70e.png">

Now... How do we want the Studio tree to look?

**Comment by pixelzoom** [comment]
2/13/20 design meeting:

* We will never have an OnOffSwitch labeled with 'On' and 'Off'.

**Comment by pixelzoom** [comment]
ABSwitch tandem structure was modified in the above commits, to match what is shown in https://github.com/phetsims/sun/issues/559#issuecomment-585982604.   There is a SimpleDragHandler in OnOffSwitch that still need to be changed to DragListener. 

This also required instrumenting the A/B label Nodes is a couple of sims:
* balancing-act @jbphet 
* energy-skate-park @jessegreenberg

**Comment by pixelzoom** [comment]
ABSwitch and OnOffSwitch were converted to ES6 classes in the above commits, and constants were factored out for default option values.

**Comment by pixelzoom** [comment]
OnOffSwitch was converted from SimpleDragHandler to DragListener in the above commits, with assistance from @jonathanolson.

**Comment by pixelzoom** [comment]
I'm having second thoughts about the class names that were chosen in https://github.com/phetsims/sun/issues/559#issue-557027536.

Here's the direction that I'm currently considering:

```js
// ToggleSwitch toggle between any 2 values
class ToggleSwitch

// ABSwitch combines a ToggleSwitch and 2 Node labels
class ABSwitch extends Node 

// OnOffSwitch is a ToggleSwitch whose Property value is boolean
class OnOffSwitch extend ToggleSwitch
```

**Comment by pixelzoom** [comment]
A couple of PhET-iO related things that I'm wondering about @samreid @zepumph @chrisklus:

* Why do we have OnOffSwitchIO but no ABSwitchIO?  Why is an IO type needed at all? 

* OnOffSwitch drag listener contains `phetioStartEvent` and `phetioEndEvent` calls to indicate when the value is toggled, see below.  Why is this necessary?  The same info comes from `onProperty`. 

```js
              this.phetioStartEvent( 'toggled', {
                data: {
                  oldValue: !value,
                  newValue: value
                }
              } );
```

**Comment by pixelzoom** [comment]
From Slack conversation with @chrisklus....

* create IO types for things that have events
* use `Action` instead of `phetioStartEvent` (see Checkbox.js)

So I guess that I'll have `ToggleSwitchIO` that prints the new & old values to the data stream when the value changes.  But... ToggleSwitch can toggle between 2 values of any type.  How do I handle that in the 'toggled' event?

**Comment by pixelzoom** [comment]
Discussed with @samreid and @chrisklus via Zoom...

`Action` in ToggleSwitch should look something like this:

```js
      const toggleAction = new Action( function( value ) {
        property.value = value;
      }, {
        parameters: [
          { name: 'oldValue', phetioType: property.phetioType.parameterTypes[ 0 ] },
          { name: 'newValue', phetioType: property.phetioType.parameterTypes[ 0 ] }
        ],
        tandem: options.tandem.createTandem( 'toggleAction' ),
        phetioDocumentation: 'Emits when user input causes the switch is toggled',
        phetioReadOnly: options.phetioReadOnly,
        phetioEventType: EventType.USER
      } );
```

**Comment by pixelzoom** [comment]
Ha! Well that didn't take long to disprove.  @kathy-phet @arouinfar @ariel-phet 

> 2/13/20 design meeting:
> 
> * Re #559 (comment), there is no need to support 'On' and 'Off' labels for OnOffSwitch.

<img width="987" alt="screenshot_129" src="https://user-images.githubusercontent.com/3046552/74799339-809f2080-528d-11ea-91f9-be8dd6f931ed.png">

**Comment by pixelzoom** [comment]
And another @jbphet:

<img width="987" alt="screenshot_130" src="https://user-images.githubusercontent.com/3046552/74799678-67e33a80-528e-11ea-8cce-8914da938241.png">

**Comment by pixelzoom** [comment]
Ha! Well that didn't take long to disprove.  @kathy-phet @arouinfar @ariel-phet @amanda-phet 

> 2/13/20 design meeting:
> 
> * Re #559 (comment), there is no need to support 'On' and 'Off' labels for OnOffSwitch.

In Molecule Polarity, but yours truly:

<img width="987" alt="screenshot_129" src="https://user-images.githubusercontent.com/3046552/74799339-809f2080-528d-11ea-91f9-be8dd6f931ed.png">

In Tambo, by @jbphet:

<img width="987" alt="screenshot_130" src="https://user-images.githubusercontent.com/3046552/74799678-67e33a80-528e-11ea-8cce-8914da938241.png">

**Comment by pixelzoom** [comment]
@arouinfar please review in master, by running ph-scale in Studio.  You can check either of these switches:

phScale.microScreen.view.graphNode.graphControlPanel.graphUnitsSwitch
phScale.microScreen.view.graphNode.graphScaleSwitch

When you're done, assign back to me so that I can have this reviewed by someone on the PhET-iO team.

**Comment by pixelzoom** [comment]
Here's what `phScale.microScreen.view.graphNode.graphScaleSwitch` looks like:

<img width="230" alt="screenshot_131" src="https://user-images.githubusercontent.com/3046552/74801404-af1ffa00-5293-11ea-86ee-a7d19671e0df.png">

**Comment by kathy-phet** [comment]
I guess I owe you a 6-pack. ;)

Sent from my iPhone

On Feb 18, 2020, at 9:15 PM, Chris Malley <notifications@github.com> wrote:

﻿

Here's what phScale.microScreen.view.graphNode.graphScaleSwitch looks like:

[screenshot_131]<https://user-images.githubusercontent.com/3046552/74801404-af1ffa00-5293-11ea-86ee-a7d19671e0df.png>

**Comment by pixelzoom** [comment]
I thought of one more thing that needed to be added - a link from the toggleSwitch to the Property that it controls.  Here's the revised structure of `phScale.microScreen.view.graphNode.graphScaleSwitch`. 

<img width="221" alt="screenshot_133" src="https://user-images.githubusercontent.com/3046552/74884986-b0076900-5331-11ea-8356-946540540055.png">

**Comment by arouinfar** [comment]
@pixelzoom the `graphUnitsSwitch` and `graphScaleSwitch` both look good in studio.

**Comment by pixelzoom** [comment]
Thanks @arouinfar.

@samreid @zepumph @chrisklus I need someone from the PhET-iO team to review this work with high priority.  I'll let you decide who the lucky person is :).  I need a review of general code, tandem structure, and data stream.

**Comment by pixelzoom** [comment]
Reviewer, note this requirement at the top of `ToggleSwitch` constructor:

```js
      // PhET-iO requirements
      assert && assert( property.phetioType, 'property must have phetioType' );
      assert && assert( property.phetioType.parameterTypes, 'property.phetioType must have parameterTypes' );
```

This means that your Property _must_ be instrumented, regardless of whether your sim is instrumented yet or not.   I don't particularly like this requirement, and I also don't the reason for it's use, also in `ToggleSwitch`:

```js
      // Get the phetioType of the Property's value.  This is needed for the message sent by toggleAction.
      const valuePhetioType = property.phetioType.parameterTypes[ 0 ];
```

But this is what was recommended by @samreid.  If you have a better solution, let's discuss.

**Comment by pixelzoom** [comment]
Reviewer, note these requirements at the top of `ToggleSwitch` constructor:

```js
// PhET-iO requirements
assert && assert( property.phetioType, 'property must have phetioType' );
assert && assert( property.phetioType.parameterTypes, 'property.phetioType must have parameterTypes' );
```

This means that your Property _must_ be instrumented, regardless of whether your sim is instrumented yet or not.   I don't particularly like this requirement, and I also don't like the reason for why it's necessary, also in `ToggleSwitch`:

```js
// Get the phetioType of the Property's value.  This is needed for the message sent by toggleAction.
const valuePhetioType = property.phetioType.parameterTypes[ 0 ];
```

Reaching info `phetioType` to get `parameterTypes[ 0 ]` feels unclean.  Especially when some IO types (e.g. ObjectIO) do not have `parameterTypes`.  But this is what was recommended by @samreid.  If you have a better solution, let's discuss.

**Comment by zepumph** [comment]
>Reaching info phetioType to get parameterTypes[ 0 ] feels unclean.

I would say that in general that is true, but for `Property` we have done that a fair amount. To me it is pretty safe to reach into there, especially if you assert that `property instanceof Property`. To me the bigger issue is how much of this code is not only run, but required for phet brand. I want to try to see if we can make it more clear that the phet-io code is only for phet-io brand, but so far it isn't obvious for ToggleSwitch.

**Comment by zepumph** [comment]
For the data stream I thought it was weird that one interaction where it toggled once could potentially yield 2 data stream events. For example in ph-scale, take the switch and drag it to the other state. This will trigger an appropriate switch with the right data stream event. Then when you mouse up, there will be another data stream event. Notice that last even in each of the two event stacks below when I mouse down, drag over, and mouse up:

```json
{
  "index": 170,
  "time": 1582251134756,
  "type": "USER",
  "phetioID": "phScale.general.controller.input.mouseDownAction",
  "name": "emitted",
  "componentType": "ActionIO<Vector2IO, EventIO>",
  "data": {
    "point": {
      "x": 130.40000915527344,
      "y": 577.2000122070312
    },
    "event": {
      "pointerId": 1,
      "pointerType": "mouse",
      "clientX": 130.40000915527344,
      "clientY": 577.2000122070312,
      "ctrlKey": false,
      "shiftKey": false,
      "altKey": false,
      "metaKey": false,
      "button": 0,
      "which": 1,
      "type": "pointerdown",
      "target": {}
    }
  },
  "metadata": {
    "dataKeys": [
      "point",
      "event"
    ],
    "playback": true
  },
  "children": [
    {
      "index": 171,
      "time": 1582251134757,
      "type": "USER",
      "phetioID": "phScale.microScreen.view.graphNode.graphScaleSwitch.toggleSwitch.dragListener.pressAction",
      "name": "emitted",
      "componentType": "ActionIO<SceneryEventIO>",
      "data": {
        "event": {
          "type": "down",
          "domEventType": "pointerdown",
          "point": {
            "x": 130.40000915527344,
            "y": 577.2000122070312
          }
        }
      }
    }
  ]
}
 {
  "index": 172,
  "time": 1582251135372,
  "type": "USER",
  "phetioID": "phScale.microScreen.view.graphNode.graphScaleSwitch.toggleSwitch.toggleAction",
  "name": "emitted",
  "componentType": "ActionIO<EnumerationIO(LOGARITHMIC|LINEAR), EnumerationIO(LOGARITHMIC|LINEAR)>",
  "data": {
    "oldValue": "LOGARITHMIC",
    "newValue": "LINEAR"
  },
  "children": [
 . . . .
      ]
}
 {
  "index": 178,
  "time": 1582251135571,
  "type": "USER",
  "phetioID": "phScale.general.controller.input.mouseUpAction",
  "name": "emitted",
  "componentType": "ActionIO<Vector2IO, EventIO>",
  "data": {
    "point": {
      "x": 248.8000030517578,
      "y": 574.7999877929688
    },
    "event": {
      "pointerId": 1,
      "pointerType": "mouse",
      "clientX": 248.8000030517578,
      "clientY": 574.7999877929688,
      "ctrlKey": false,
      "shiftKey": false,
      "altKey": false,
      "metaKey": false,
      "button": 0,
      "which": 1,
      "type": "pointerup",
      "target": {}
    }
  },
  "metadata": {
    "dataKeys": [
      "point",
      "event"
    ],
    "playback": true
  },
  "children": [
    {
      "index": 179,
      "time": 1582251135571,
      "type": "USER",
      "phetioID": "phScale.microScreen.view.graphNode.graphScaleSwitch.toggleSwitch.dragListener.releaseAction",
      "name": "emitted",
      "componentType": "ActionIO<NullableIO<SceneryEventIO>>",
      "data": {
        "event": {
          "type": "up",
          "domEventType": "pointerup",
          "point": {
            "x": 248.8000030517578,
            "y": 574.7999877929688
          }
        }
      },
      "children": [
        {
          "index": 180,
          "time": 1582251135571,
          "type": "USER",
          "phetioID": "phScale.microScreen.view.graphNode.graphScaleSwitch.toggleSwitch.toggleAction",
          "name": "emitted",
          "componentType": "ActionIO<EnumerationIO(LOGARITHMIC|LINEAR), EnumerationIO(LOGARITHMIC|LINEAR)>",
          "data": {
            "oldValue": "LINEAR",
            "newValue": "LINEAR"
          }
        }
      ]
    }
  ]
}


- [ ] I think that the action event where it says `            "oldValue": "LINEAR", ` and `"newValue": "LINEAR"` should not be there. This may be as simple as a guard in the `end` callback:
`         oldValue !== newValue && toggleAction.execute( oldValue, newValue );`

**Comment by zepumph** [comment]
* I want to note that `ToggleSwitchIO` doesn't look like it is needed for anything. That said, keeping it such that `ToggleSwitchIO` shows up in studio instead of `NodeIO` is good with me if desired.

**Comment by zepumph** [comment]
>I would say that in general that is true, but for Property we have done that a fair amount. To me it is pretty safe to reach into there, especially if you assert that property instanceof Property. To me the bigger issue is how much of this code is not only run, but required for phet brand. I want to try to see if we can make it more clear that the phet-io code is only for phet-io brand, but so far it isn't obvious for ToggleSwitch.

@samreid and I just paired for a bit and found a solution that I'm very excited about, and can't wait to use in other UI components. In this. . . 
* we don't assert except when validating tandems
* we always provide as much information as we can (i.e. passing the phetioType if we have it)
* we can support phet brand with phet-io code that is clearly annexed into a phet-io specify.

@pixelzoom please review the commit and offer suggestions.


@samreid and I also wanted to challenge the reason for this particule Action structure in the first place? Isn't it literally saying the same thing as the nested Property changing event? We thought it may be good to ask in an upcoming phet-io design meeting. @pixelzoom do you have any ideas about this? Has it already been addressed as a phet-io design requirement.

**Comment by zepumph** [comment]
`ABSwitch` looks really good. All above comments are about `ToggleSwitch`. Review complete, thanks for the instrumentation. Back to you.

**Comment by pixelzoom** [comment]
Discussed with @samreid and @zepumph on Zoom.  Decisions, implemented in above commit:

* deleted ToggleSwitchIO
* removed params from toggleAction
* made sure to use present tense for action ('toggleAction' vs 'toggledAction')
* add `if ( property.value !== value )` guard in `end`

**Comment by terracoda** [comment]
I didn't know you folks were working on an AB Switch. I would like to add this article by Heydon Pickering, [Inclusive Toggle Buttons](https://www.smashingmagazine.com/2017/09/building-inclusive-toggle-buttons/). MAL now has two toggle buttons, one a somewhat traditional push button which can be made accessible with `aria-pressed=true/false`). The other is a play/pause button which has a label change. In addition the push button could be considered an on/off button. 

For MAL we are exploring some solutions in issues https://github.com/phetsims/molecules-and-light/issues/296 and https://github.com/phetsims/molecules-and-light/issues/299

There are several types of interactions that are toggle like, and at least a few different ways to represent a toggle button. We may likely need different design patterns in the PDOM for different toggle interactions.

**Comment by pixelzoom** [comment]
Thanks for the nice info and reference @terracoda.  Since this issue has been reviewed and closed, I recommend creating a new "sun" issue and putting this information there - something like "strategies for accessible toggle buttons".

**Comment by pixelzoom** [comment]
@terracoda I took the liberty of creating the new issue: https://github.com/phetsims/sun/issues/580
