### ISSUE TITLE
Can listParent be removed from ComboBox?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/sun#563]
While working on https://github.com/phetsims/molarity/issues/213

ComboBoxes require a `listParent` Node with documentation
>node that will be used as the list's parent, use this to ensure that the list is in front of everything else

Is it possible to use `sim.showPopup` (like Dialog) to put the ComboBoxListBox on top of everything so that `listParent` isn't needed?

**Comment by pixelzoom** [comment]
The longterm goal is to have a pane (similar to Java's glass pane) that can be used by all popups -- menus, listbox, dialog,...  See https://github.com/phetsims/sun/issues/347.   But we're obviously not there yet.  

2 problems with using `sim.showPopup`...

(1) `sim.showPopup` likely assumes that the popup is modal.  That's not the case for listbox.  It's supposed to behave more like a menu, not a modal dialog.  And it certainly shouldn't dim the rest of the screen (like a dialog does) while the listbox is open.

(2) It doesn't address what appear to be a bug in ComboBox.  Clicking anywhere outside of the listbox is supposed to close it.  Relevant code:

ComboBox line 197:
```
     // @private Clicking anywhere other than the button or list box will hide the list box.
```

ComboBox line 208:

````js
      // @private - (PDOM) when focus leaves the ComboBoxListBox, it should be closed. This could happen from keyboard
      // or from other screen reader controls (like VoiceOver gestures)
```

According to  phetsims/molarity#213, that's not happening.  So I recommend fixing the problem.

**Comment by jessegreenberg** [comment]
> (1) sim.showPopup likely assumes that the popup is modal. That's not the case for listbox. 

`sim.showPopup` allows for non-modal pop ups with a boolean `isModal` arg. When false the rest of the screen isn't dimmed.

> It doesn't address what appear to be a bug in ComboBox

It correctly closes when focus leaves it. Remaining request in https://github.com/phetsims/molarity/issues/213 is to also trap the virtual cursor in the ComboBoxListBox when open. One way to do that is to change the scene graph and move the ComboBoxListBox to `sim.topLayer` or `sim.modalNodeStack`. But separate from that issue, requiring a `listParent` is not an ideal API so I am wondering if using `sim.showPopup` would be an improvement anyway. But if not advised/possible we can proceed another way or defer until we have a "pane" solution.

**Comment by pixelzoom** [comment]
Yes, `sim.showPopup` does have a boolean `isModal` arg.  But so does Dialog, and it's very broken.  And I'm not aware of any non-modal use of `sim.showPopup`.  That said... I'm fine with changing it to `sim.showPopup` if you want to investigate.

**Comment by jessegreenberg** [comment]
OK thanks, thats helpful. I am going to check in with design team and make sure it is important to constrain the virtual cursor to the ComboBoxListBox in https://github.com/phetsims/sun/issues/565 before spending more time on that.

**Comment by jessegreenberg** [comment]
This was discussed with a11y designers, who also checked current behavior with the ARIA working group. They agreed that the virtual cursor should not be constrained to the open combo box so this is not necessary for accessibility. So I am not going to work on this, closing.
