### ISSUE TITLE
VerticalAquaRadioButtonGroup phetioFeatured defaults

### ISSUE THREAD

**Issue by arouinfar** [phetsims/sun#564]
VerticalAquaRadioButtonGroup and AquaRadioButton do not appear to have anything phetioFeatured by default in the same way other common UI components do (such as buttons).

At the group level, the visibleProperty should be phetioFeatured. Each individual radio button should also have its enabledProperty and visibleProperty featured. This is a pattern we expect to use across all sims, so it would be preferable to handle this in common code rather than overriding it every single time.

Assigning to the PhET-iO team.

**Comment by arouinfar** [comment]
@samreid I reviewed this in the context of https://github.com/phetsims/gravity-and-orbits/issues/294 and it looks good.

**Comment by samreid** [comment]
Thanks @arouinfar, @zepumph or @chrisklus can you please review the implementation?  Close if all is well.

**Comment by zepumph** [comment]
- [ ] The assertion in for enabledProperty in TimeControlNode should be guarded on `Tandem.errorOnFailedValidation()` in my opinion.


Otherwise this seems great. Thanks for implementing.

**Comment by zepumph** [comment]
@pixelzoom reported that this assertion was blocking him in collision lab, so I just committed the change https://github.com/phetsims/scenery-phet/commit/d90eeca8eff761bebf61322345de6875b2544e1b

This largely applies to https://github.com/phetsims/scenery-phet/issues/577 too.

**Comment by samreid** [comment]
The commit looks good.  Anything else for this issue?

**Comment by zepumph** [comment]
I don't think so
