### ISSUE TITLE
need to get radio buttons from AquaRadioButtonGroup 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#569]
Related to https://github.com/phetsims/sun/issues/555, converting sims to use AquaRadioButtonGroup.  

Over in gas-properties, I ran into a problem when trying to use `VerticalAquaRadioButtonGroup`. `HoldConstantControl` observers other Properties to decide which of the radio buttons should be enabled. So I need references to the radio buttons, which `AquaRadioButtonGroup` does not provide.

@zepumph suggested adding this method to `AquaRadioButtonGroup`:

```js
    /**
     * Gets the radio button that corresponds to the specified value.
     * @param {*} value
     * @returns {AquaRadioButton}
     */
    getRadioButton( value ) {
```

Looks like I'll also need to add `this.value` to `AquaRadioButton`, because it doesn't currently expose its associated value.

**Comment by pixelzoom** [comment]
Done in the above commits, and used in gas-properties.

@ariel-phet please assign someone to review.

**Comment by ariel-phet** [comment]
@chrisklus is on the review case

**Comment by chrisklus** [comment]
Looks good @pixelzoom, back to you.

**Comment by pixelzoom** [comment]
Thanks @chrisklus. Closing.
