### ISSUE TITLE
Sound for opening and closing panel only when using button

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/sun#570]
Found during https://github.com/phetsims/QA/issues/482
When you open and close the accordion panels there seems to be a sound involved now. It only plays when you use the +/- button. If it is done by clicking on the title bar, it closes or opens, but doesn't make the sound.
![thesethings](https://user-images.githubusercontent.com/41024075/75177218-f58db280-56f2-11ea-97a1-4a1725a9788b.png)

**Comment by jbphet** [comment]
This is more of a general issue with `AccordionBox` rather than a specific build-an-atom issue, so I'm transferring it to sun.

**Comment by jbphet** [comment]
@Ashton-Morris - We need open and close sounds for the accordion box.  Shall I use the ones that are now used for combo box and dialogs, or would you like to come up with something unique for this case?  

If it's the latter, please go ahead and create the new sounds.  In either case, when it is ready for me to implement the sound, please assign this issue back to me.

**Comment by Ashton-Morris** [comment]
@jbphet I feel like making them a tiny bit shorter and more subdued would fit better since its a common on screen function. I have created those files here.

[accordian-open](https://drive.google.com/open?id=1aiu-FUB3HcGBx5p3XhzqI6hUPXLCNACw)

[accordian-close](https://drive.google.com/open?id=1OeCOMoVqQSs8glb-jfsUn29fU2fkBVOD)

**Comment by jbphet** [comment]
This was discussed in the 3/3/2020 UI sound design meeting, and @emily-phet said that we are using soon-to-be-released sims to drive which common code components have sound added to them, and we don't really have time and funding at this point to work towards adding sound to all components.  With this in mind, I'm going to mark this issue as "deferred" until we have a sim in the sound design pipeline that includes accordion boxes.

**Comment by marlitas** [comment]
It seems like these sounds are now added to accordion box. Center and Variability has an "open/close" sound for any accordion box interaction wether it's with the button or the title bar. I'm closing this issue as completed, but please feel free to re-open if I missed something.
