### ISSUE TITLE
AccordionBox: titleBar remains interactive when expandedProperty is pickable:false

### ISSUE THREAD

**Issue by arouinfar** [phetsims/sun#573]
Discovered in phetsims/ph-scale#117 

The `view.pHMeterNode.expandCollapseButton.pickableProperty` is not behaving as expected. The button remains interactive when the pickableProperty is set to false.

Steps to reproduce:
1. Open the sim in studio
2. Navigate to `phScale.microScreen.view.pHMeterNode.expandCollapseButton.pickableProperty` or `phScale.mySolutionsScreen.view.pHMeterNode.expandCollapseButton.pickableProperty`
3. Use studio control to set it to false
4. Click on the ExpandCollapseButton in the sim, and the pH meter will collapse (clearly still pickable).

Oddly, this issue only affects the ExpandCollapseButton on the pHMeterNode. Setting `view.graphNode.graphControlPanel.expandCollapseButton.pickableProperty` to false correctly disables the graph's ExpandCollapseButton.

**Comment by pixelzoom** [comment]
3/5/20 design meeting:  @arouinfar @kathy-phet and I came up with a solution for this, see above commit.  @arouinfar please review in master.

**Comment by arouinfar** [comment]
@pixelzoom I reviewed this in master in ph-scale and gas-properties. Everything's looking good, closing.
