### ISSUE TITLE
PhET-iO design for NumberSpinner

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#575]
`NumberSpinner` is a spinner that deals with a numeric value. sun demo demonstrates some of its features and configurations:

<img width="1041" alt="screenshot_167" src="https://user-images.githubusercontent.com/3046552/76011189-6726e700-5ed1-11ea-88f2-70e6e8b1dce6.png">

The tandem hierarchy looks like this in Studio, e.g. `gasProperties.diffusionScreen.view.controlPanel.settingsNode.massControl.leftSpinner`:

<img width="207" alt="screenshot_168" src="https://user-images.githubusercontent.com/3046552/76011436-cedd3200-5ed1-11ea-970e-38aeceae172f.png">

From @arouinfar in https://github.com/phetsims/ph-scale/issues/135:

> * Should the increment/decrement buttons be grouped? If grouped, instructional designers could remove them through a single visibleProperty. There may be a11y implications for this, though.
> 
> * What is the best name for the buttons? Increment/Decrement is accurate, but something like up/down might be friendlier. (These are somewhat similar to the tweaker buttons on a NumberControl which have been called `leftArrowButton` and `rightArrowButton` in Projectile Motion.)

Also note that `NumberSpinner` is not the only spinner. Decisions in this issue should be applied to other spinners:

*  `FineCoarseSpinner` is a similar UI component.
* We should review https://github.com/phetsims/sun/issues/436 (evaluate the various "spinner" UI components)
* Some sims have their own spinner implementations, e.g. fractions-common/RoundNumberSpinner

**Comment by pixelzoom** [comment]
3/5/20 design meeting:

* I will group the buttons, named `buttonGroup`.
* Stick with `incrementButton` and `decrementButton`, since NumberSpinner supports different layouts.

**Comment by pixelzoom** [comment]
I've renamed the buttons in FineCoarseSpinner.  But I've run into a problem with grouping the buttons in both classes, which I'll need to discuss with @arouinfar.

**Comment by arouinfar** [comment]
@pixelzoom I reviewed the NumberSpinner in the ph-scale tree, and it's looking good.
![image](https://user-images.githubusercontent.com/8419308/76037724-02857f80-5f05-11ea-8424-271a20d50b81.png)

>What I heard in design meeting was that grouping the buttons would be "nice to have", but not essential. So assigning this back to @arouinfar to discuss with designers.

I confirmed this with @kathy-phet. Grouping the buttons is not essential.

I believe the only thing remaining is to decide on the phetioFeatured defaults. My best guess is that we'll want the tree to look like this when viewing featured elements:
![image](https://user-images.githubusercontent.com/8419308/76038129-1087d000-5f06-11ea-8633-9eb73b3d39af.png)

The buttons already have the correct featured behavior, we'd just need to change feature `spinner.visibleProperty` in NumberSpinner.

Leaving self-assigned to confirm this with @kathy-phet in our next meeting.

**Comment by pixelzoom** [comment]
@arouinfar I think that NumberSpinner and FineCoarseSpinner should also have links to their associated Properties, like Checkbox, Slider, and other UI components.  Do you agree?

**Comment by arouinfar** [comment]
>  I think that NumberSpinner and FineCoarseSpinner should also have links to their associated Properties -- like Checkbox, Slider, and other UI components. Do you agree?

I'd generally agree, but it seems less clear-cut for pH Scale. There's already a link to pHProperty in the pHMeterNode which contains the spinner. Would you move the linked property down into the spinner, or would you add a 2nd linked property?

<img src="https://user-images.githubusercontent.com/8419308/76236208-f3971980-61f1-11ea-9752-2330b006cf4c.png" width=200>

In Gas Properties, I think it would make sense for `view.particlesAccordionBox.numberOfHeavyParticlesControl.spinner` to have a link to `model.particleSystem.numberOfHeavyParticlesProperty` since its parent doesn't already have a link to the model property.

@pixelzoom not sure if you're still working on `FineCoarseNumberSpinner`, but we noticed that the tree structure includes the `numberDisplay`. We don't think this needs to be instrumented, since it can lead to some strange situations (like hiding the readout but leaving the buttons). 

<img src="https://user-images.githubusercontent.com/8419308/76236571-7fa94100-61f2-11ea-8e1e-8a7acaa6f4f1.png" width=200>

![image](https://user-images.githubusercontent.com/8419308/76236715-b54e2a00-61f2-11ea-890d-c580efb85b99.png)

**Comment by pixelzoom** [comment]
Re ph-scale...  I would either remove the `pHMeterNode.pHProperty` linked element, or just leave it, whichever you prefer.

Re numberDisplay in FineCoarseSpinner... We generally instrument NumberDisplay so you can see what value is actually displayed, since it may have a different number of decimal places than the Property value.   NumberControl is another example -- it's NumberDisplay is instrumented so that you can see the actual value displayed, and that means you can also make it invisible.    Let me know if you'd like to do something different with FineCoarseSpinner.

**Comment by pixelzoom** [comment]
> Re ph-scale... I would either remove the pHMeterNode.pHProperty linked element, or just leave it, whichever you prefer.

Actually...  There would be a problem with removing the pHMeterNode.pHProperty linked element.  The _Micro_ and _My Solution_ screens use the same pH meter.  But the _Micro_ screen has no spinner, so would have no link to the pH Property.

**Comment by pixelzoom** [comment]
@arouinfar I've added `*property` links to NumberSpinner and FineCoarseSpinner, if you want to see how that looks in ph-scale and gas-properties respectively.

**Comment by pixelzoom** [comment]
@arouinfar I've added `*property` links to NumberSpinner and FineCoarseSpinner, if you want to see how that looks in ph-scale and gas-properties respectively.

**Comment by pixelzoom** [comment]
@arouinfar in the above commit, I've added a link to `pHProperty` only if `pHMeterNode` doesn't have a spinner.   The downside is a lack of consistency -- the `pHMeterNode` in _Macro_ and _Micro_ screens have a link , the one in _My Solutions_ does not.  See Studio trees below.

phScale.mySolutionScreen.view.pHMeterNode:
<img width="208" alt="screenshot_174" src="https://user-images.githubusercontent.com/3046552/76240004-1c221200-61f8-11ea-91dd-4be28c62879c.png">

phScale.microScreen.view.pHMeterNode:
<img width="238" alt="screenshot_175" src="https://user-images.githubusercontent.com/3046552/76240219-7a4ef500-61f8-11ea-9334-875843094028.png">

phScale.mySolutionScreen.view.pHMeterNode:
<img width="233" alt="screenshot_176" src="https://user-images.githubusercontent.com/3046552/76240278-9357a600-61f8-11ea-9a3b-d0fc9a0352d2.png">

**Comment by pixelzoom** [comment]
Actually... I'm going to move the ph-scale specific part of this to https://github.com/phetsims/ph-scale/issues/138.

**Comment by pixelzoom** [comment]
Over in https://github.com/phetsims/ph-scale/issues/139, @kathy-phet said:
> @arouinfar and I noticed that for the MySolutions screen, the enabledProperty of pH increment and decrement buttons are controlled by the sim, so those should be made "read only" and "not featured" in the studio tree.
> 
> Can you do one or either of this in the code, or do we need to do that manually overrides? We are thinking overrides, because you would need to reach into button and that is not clean, but let us know.
> 
> It seems like most spinners take over control of enabledProperty, so perhaps this is a general spinner sun issue?

So it sounds like you'd like NumberSpinner `incrementButton. enabledProperty` and `decrementButton.enabledProperty` to be `phetioReadOnly: true` and `phetioFeatured: false`.   @arouinfar is that correct?  And should the same be done for FineCoarseSpinner?

**Comment by arouinfar** [comment]
> Re numberDisplay in FineCoarseSpinner... We generally instrument NumberDisplay instances so you can see what value is actually displayed, since it may have a different number of decimal places than the Property value. NumberControl is another example -- it's NumberDisplay is instrumented so that you can see the actual value displayed, and that means you can also make it invisible. Let me know if you'd like to do something different with FineCoarseSpinner.

@pixelzoom thanks for this explanation. I can now see why `FineCoarseSpinner` has its numberDisplay instrumented, but it seems like we should be doing the same for `NumberSpinner`.

> So it sounds like you'd like NumberSpinner incrementButton. enabledProperty and decrementButton.enabledProperty to be phetioReadOnly: true and phetioFeatured: false. @arouinfar is that correct? And should the same be done for FineCoarseSpinner?

Yes, that would be correct. If this is straightforward to do in `NumberSpinner` and `FineCoarseSpinner` that would be great. We weren't sure how messy this would be since the featured behavior is coming from the button itself.

**Comment by pixelzoom** [comment]
Ugh. I just discovered that `NumberSpinner` doesn't use `NumberDisplay`, likely because it pre-dates it.   Guess I'll have to take another detour here and fix that.  

Buttons `enabledProperty` instrumented with `phetioReadOnly: true` and `phetioFeatured: false` in the above commits.

**Comment by pixelzoom** [comment]
I took a stab at converting NumberSpinner to use NumberDisplay.  Every use of NumberSpinner looked significantly different, and I couldn't figure out why.   So I reverted my changes.   This is going to be a bigger job than I have time for.   

@arouinfar is this needed for the upcoming PhET-iO version of ph-scale?

**Comment by pixelzoom** [comment]
According to @arouinfar in 3/12/20 status meeting, this is not a prerequisite for the first PhET-iO release of ph-scale.

**Comment by pixelzoom** [comment]
@ariel-phet As noted in https://github.com/phetsims/sun/issues/575#issuecomment-596842234, I ran into problems when converting NumberSpinner to use NumberDisplay.  It's going to be more work than I currently have time for.  Please prioritize and assign.

**Comment by pixelzoom** [comment]
I converted NumberSpinner to `class` in the above commit, so that it will be easier to work on.  There were only 2 cases when NumberSpinner was uses as a superclass, and they were already using `class`, so no sim changes were necessary.  I confirmed that `AccessibleNumberSpinner.mixInto` is working by running the sun demo with `?a11y`, then using arrow keys to increment/decrement.

**Comment by ariel-phet** [comment]
@Denz1994 take a look over this issue and see if it is something you can take on

**Comment by pixelzoom** [comment]
Natural Selection is now using NumberSpinner, so using NumberDisplay herein is also desirable for that sim. Milestones: 6/1/2020 dev version to client, 8/1/2020 publication.

**Comment by Denz1994** [comment]
I refactored `valueNode` in NumberSpinner to use NumberDisplay. It was mentioned, in https://github.com/phetsims/sun/issues/575#issuecomment-596842234 that use cases of NumberSpinner looked different. The changes I saw (Sun, Collision-Lab and EE)  were related to NumberSpinner.options that needed to be passed into NumberDisplay. 

@pixelzoom Is this the only blocking item in this issue for Natural Selection?

**Comment by pixelzoom** [comment]
> @pixelzoom Is this the only blocking item in this issue for Natural Selection?

Yes, I believe so.

**Comment by pixelzoom** [comment]
> @pixelzoom Is this the only blocking item in this issue for Natural Selection?

Yes, I believe so.  It's also on the "wish list" for ph-scale.

**Comment by pixelzoom** [comment]
Things are not looking right.

Here's Gas Properties 1.0.4 before the change:

<img width="1060" alt="screenshot_238" src="https://user-images.githubusercontent.com/3046552/78202323-3f378e80-7451-11ea-82ae-0b8490069b11.png">

Here's what master looks like:

<img width="1057" alt="screenshot_237" src="https://user-images.githubusercontent.com/3046552/78202263-16af9480-7451-11ea-9a6d-26059fcde7cd.png">

Note the spinners. They're not even close to the same, and the values are all scaled differently.

I see a similar problem in ph-scale, reactants-products-and-leftovers, .... every sim I've looked at that uses NumberSpinner.  You'll need to compare changes to dev versions, to make sure the visual changes are not this extreme.

Marking this as "block-publication", because we cannot publish with things in this state.

**Comment by Denz1994** [comment]
Along with the above Gas Properties example listed above, I didn't update the `PhET-iO API` causing this error in ph-scale: 
```
Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
```

A note on future development related to this issue provided by @pixelzoom on slack:
- make common-code changes
- run for-each.sh phet-io grunt update
- test a few IO sims (Studio, State Wrapper,...)
- commit and push common-code and API changes together

**Comment by Denz1994** [comment]
Regarding my above comment: 

For more direct reference see the newly updated https://github.com/phetsims/phet-io/blob/master/doc/phet-io-instrumentation-guide.md#before-instrumentation

**Comment by Denz1994** [comment]
Raising priority on this issue so I'll pick up on it this week.

**Comment by pixelzoom** [comment]
Assigned to me in 7/2/2020 natural-selection design meeting.

**Comment by pixelzoom** [comment]
Uses of NumberSpinner that must be visually inspected after changing to NumberDisplay:

- [ ] circuit-construction-kit-common
- [ ] collision-lab
- [ ] expression-exchange
- [ ] gas-properties
- [ ] griddle (demo)
- [ ] natural-selection
- [ ] ph-scale
- [ ] reactants-products-and-leftovers
- [ ] sun (demo)
- [ ] tambo (demo)

**Comment by pixelzoom** [comment]
This is done. @ariel-phet please assign someone to review.

For the reviewer:

There are 3 main commits:

*  In https://github.com/phetsims/sun/commit/3a6227ccefd59ae1b6dfca8493a01d06176d6f95, NumberSpinner was changed to use NumberDisplay, but NumberSpinner options remained "flat".
* In https://github.com/phetsims/sun/commit/8904776e0efa12fe3915359ff0ab704612497fe2, options related to NumberDisplay were nested in `numberDisplayOptions`.
* In https://github.com/phetsims/sun/commit/9ad387001995d17350093942a476bd6319078efb, the default value for `numberDisplayOptions` was simplified.

To verify that the results are visually identical... The table below shows the runnables that use NumberSpinner, with dev versions that were published before and after making the changes.  Open the **before** and **after** versions in separate tabs, then switch between them to verify that they look the same. Where possible, the dev versions have query parameters that put the sim in an initial state that shows the NumberSpinner(s).  See also the footnotes below the table for how to locate less-obvious NumberSpinners. 

| runnable | before | after |
| :--- | --- | --- |
| circuit-construction-kit-ac <sup>1</sup> | [1.0.0-dev.13](https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.13/phet/circuit-construction-kit-ac_en_phet.html?initialScreen=3) | [1.0.0-dev.14](https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.14/phet/circuit-construction-kit-ac_en_phet.html?initialScreen=3) |
| collision-lab | [1.0.0-dev.28](https://phet-dev.colorado.edu/html/collision-lab/1.0.0-dev.28/phet/collision-lab_en_phet.html?initialScreen=2) | [1.0.0-dev.29](https://phet-dev.colorado.edu/html/collision-lab/1.0.0-dev.29/phet/collision-lab_en_phet.html?initialScreen=2) |
| expression-exchange <sup>2</sup> | [1.2.0-dev.1](https://phet-dev.colorado.edu/html/expression-exchange/1.2.0-dev.1/phet/expression-exchange_en_phet.html?initialScreen=3) | [1.2.0-dev.2](https://phet-dev.colorado.edu/html/expression-exchange/1.2.0-dev.2/phet/expression-exchange_en_phet.html?initialScreen=3) |
| gas-properties | [1.1.0-dev.2](https://phet-dev.colorado.edu/html/gas-properties/1.1.0-dev.2/phet/gas-properties_en_phet.html?initialScreen=4) | [1.1.0-dev.3](https://phet-dev.colorado.edu/html/gas-properties/1.1.0-dev.3/phet/gas-properties_en_phet.html?initialScreen=4) |
| griddle (demo) | [1.0.0-dev.1](https://phet-dev.colorado.edu/html/griddle/1.0.0-dev.1/phet/griddle_en_phet.html?component=GridNode) | [1.0.0-dev.2](https://phet-dev.colorado.edu/html/griddle/1.0.0-dev.2/phet/griddle_en_phet.html?component=GridNode) |
| natural-selection <sup>3</sup> | [1.0.0-dev.65](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.65/phet/natural-selection_en_phet.html?initialScreen=1) | [1.0.0-dev.66](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.66/phet/natural-selection_en_phet.html?initialScreen=1) |
| ph-scale | [1.4.0-dev.21]( https://phet-dev.colorado.edu/html/ph-scale/1.4.0-dev.21/phet/ph-scale_en_phet.html?initialScreen=3) | [1.4.0-dev.22]( https://phet-dev.colorado.edu/html/ph-scale/1.4.0-dev.22/phet/ph-scale_en_phet.html?initialScreen=3) |
| reactants-products-and-leftovers <sup>4</sup> | [1.3.0-dev.1](https://phet-dev.colorado.edu/html/reactants-products-and-leftovers/1.3.0-dev.1/phet/reactants-products-and-leftovers_en_phet.html?initialScreen=1) | [1.3.0-dev.2](https://phet-dev.colorado.edu/html/reactants-products-and-leftovers/1.3.0-dev.2/phet/reactants-products-and-leftovers_en_phet.html?initialScreen=1) |
| sun (demo) | [1.0.0-dev.12](https://phet-dev.colorado.edu/html/sun/1.0.0-dev.12/phet/sun_en_phet.html?initialScreen=2&component=NumberSpinner) | [1.0.0-dev.13](https://phet-dev.colorado.edu/html/sun/1.0.0-dev.13/phet/sun_en_phet.html?initialScreen=2&component=NumberSpinner) |
| tambo (demo) | [1.0.0-dev.15](https://phet-dev.colorado.edu/html/tambo/1.0.0-dev.15/phet/tambo_en_phet.html?initialScreen=1) | [1.0.0-dev.16](https://phet-dev.colorado.edu/html/tambo/1.0.0-dev.16/phet/tambo_en_phet.html?initialScreen=1) |

<sup>1</sup> On the Lab screen, add an "AC Voltage" element. Then press on it to see "Phase Shift" spinner.
<sup>2</sup> On the Negatives screen, expand the "Variables" accordion box.
<sup>3</sup> Add a Mate" button. Then select the "Proportions" radio button to see the "Generation" spinner below the graph. 
<sup>4</sup> On the Sandwiches screen, select the "Custom" radio button.

Finally... The Studio tree now looks like this example from pH Scale, for element `phScale.mySolutionScreen.view.pHMeterNode.spinner.numberDisplay`:

<img width="238" alt="screenshot_421" src="https://user-images.githubusercontent.com/3046552/86975780-4c41d900-c136-11ea-899d-e699813921a2.png">

**Comment by jonathanolson** [comment]
Review looks good! (Reviewed the 3 commits mentioned above, did NOT review client changes)

**Comment by pixelzoom** [comment]
Thanks @jonathanolson. Closing.
