### ISSUE TITLE
NumberSpinner: add options for incrementFunction and decrementFunction

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#576]
NumberSpinner current defines the listeners for its arrow buttons like this:

```js
  const incrementFunction = function() {
    numberProperty.set( numberProperty.get() + options.deltaValue );
  };

  const decrementFunction = function() {
    numberProperty.set( numberProperty.get() - options.deltaValue );
  };
``` 

Over in https://github.com/phetsims/ph-scale/issues/143, `options.delta` isn't enough, I need more sophisticated behavior for the listeners.  So I'm going to add these options:

```js
// {function|null} function called when the increment button is pressed, defaults to adding options.deltaValue
incrementFunction: null,

// {function|null} function called when the decrement button is pressed, defaults to subtracting options.deltaValue
decrementFunction: null,
```

**Comment by pixelzoom** [comment]
Done in the above commit.  Now being used in pH Scale.  

@ariel-phet please assign someone to review.

**Comment by chrisklus** [comment]
Looks good @pixelzoom, back to you to close.

**Comment by pixelzoom** [comment]
Thanks @chrisklus. Closing.

**Comment by pixelzoom** [comment]
Reopening.  This new feature fails to take into account disabling of the buttons, and is causing https://github.com/phetsims/ph-scale/issues/152.

**Comment by pixelzoom** [comment]
Luckily this was only used in ph-scale so far.  I changed the API for incrementFunction and decrementFunction, and used those functions for both the button listeners and changing the enabled/disabled state of the buttons.  I tested the defaults in gas-properties, and I tested custom values in ph-scale.

@chrisklus sorry, but would you mind taking a peek at this again?  If it looks OK, feel free to close.

**Comment by chrisklus** [comment]
Looks good @pixelzoom - and looks like that was a bug waiting to happen since the original enabled listener was basically duplicating the incrementFunctions, so nice improvement. Closing.
