### ISSUE TITLE
use SunConstants.DISABLED_OPACITY in sun buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#579]
Related to https://github.com/phetsims/sun/issues/489 and https://github.com/phetsims/sun/issues/578.

Disabled opacity of 0.3 is still hard-coded in sun buttons.  It should be replaced with `SunConstants.DISABLED_OPACITY`.

```js
// RectangularButtonView.js
      content.opacity = state === ButtonInteractionState.DISABLED ||
                        state === ButtonInteractionState.DISABLED_PRESSED ? 0.3 : 1;

// RoundButtonView.js
      content.opacity = state === ButtonInteractionState.DISABLED ||
                        state === ButtonInteractionState.DISABLED_PRESSED ? 0.3 : 1;
```

**Comment by pixelzoom** [comment]
Done in the above commit.  The current value of `SunConstants.DISABLED_PROPERTY` can be evaluated in the _Buttons_ screen of sun demo, by pressing the "Disable Buttons" button.

@samreid please review.

**Comment by samreid** [comment]
I reviewed the commit and it looks great, thanks!  Closing.
