### ISSUE TITLE
add enabledProperty to AquaRadioButtonGroup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#582]
This is required for https://github.com/phetsims/hookes-law/issues/76 and possibly other sims.

This should be done via `EnabledComponent` mixin. 

Assigning to @ariel-phet to prioritize and assign.

**Comment by ariel-phet** [comment]
@zepumph is up for this. Marking medium since this should not be an huge project.

**Comment by zepumph** [comment]
On hold until review of https://github.com/phetsims/sun/issues/257 is finished.

**Comment by zepumph** [comment]
https://github.com/phetsims/sun/issues/257 has made good progress, and this issue would be useful for https://github.com/phetsims/ohms-law/issues/159. I'm going to go ahead and implement now.

**Comment by zepumph** [comment]
Added above. Things are looking great in studios and in sim runs. I linted and built a few sims. 

I think getting @pixelzoom to review the change in sun is important. I also think that designers should take a look to see if there are any spots where this phetioFeatured enabledProperty shouldn't be featured. For example somewhere like `projectileMotion.introScreen.view.timeControlNode.speedRadioButtonGroup.enabledProperty`

Assigning to @arouinfar in addition to @pixelzoom.

**Comment by pixelzoom** [comment]
AquaRadtioButtonGroup is missing a call to `disposeEnabledComponent()`. Added in the above commit.  Back to @zepumph for review.

**Comment by pixelzoom** [comment]
One more commit.  I moved the call to `this.disposeEnabledComponent()` into `dispose`, rather than putting it in `disposeAquaRadioButtonGroup`.   This is the way it's done in other class where `EnabledComponent` is used.  And it makes sense to me, because calling `super.dispose()` and `this.disposeEnabledComponent()` are somewhat similar.

**Comment by arouinfar** [comment]
@zepumph said:
> I also think that designers should take a look to see if there are any spots where this phetioFeatured enabledProperty shouldn't be featured. For example somewhere like `projectileMotion.introScreen.view.timeControlNode.speedRadioButtonGroup.enabledProperty`

I think it's nice to have the top-level `enabledProperty` of the RadioButtonGroup be phetioFeatured: true. When @kathy-phet and I requested updates the default behavior in #564, we would have included the `enabledProperty` had it existed at the time.

Even in something like TimeControlNode, it seems appropriate to have `speedRadioButtonGroup.enabledProperty` be phetioFeatured: true.

**Comment by zepumph** [comment]
Excellent @arouinfar, thanks for the update. All of that sounds good to me!

@pixelzoom your commits look very good. I think that is the appropriate pattern. 

 >One more commit. I moved the call to this.disposeEnabledComponent() into dispose, rather than putting it in disposeAquaRadioButtonGroup. This is the way it's done in other class where EnabledComponent is used. And it makes sense to me, because calling super.dispose() and this.disposeEnabledComponent() are somewhat similar.

I think someone recommended that to me when I did ABSwitch and ToggleSwitch. Thanks for doing that.

I'm ready to close this issue. Please reopen if anyone feels differently.
