### ISSUE TITLE
Convert Slider from SimpleDragHandler to DragListener

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#590]
This will help make a more consistent PhET-iO API. Furthermore SimpleDragHandler is deprecated, and  Slider.js is used enough that we should definitely do this.

@jonathanolson was volunteered(told) to do this. Thanks @jonathanolson!

**Comment by zepumph** [comment]
We also found usages in scenery-phet too. Can we do those too?

* ConductivityTesterNode.js
* FaucetNode.js
* MeasuringTapeNode.js
* SpectrumSlider.js

**Comment by jonathanolson** [comment]
Implemented, assigning to @ariel-phet to decide on review.

**Comment by zepumph** [comment]
Everything above looks very good. It seemed to be a clean transition and I am happy for the added consistency for our common code. Tandem names are a bit jenky now. I will take a look at changing those. This will be an improvement that breaks the api, but I don't see any usages of these phetioIDs in our code that I worry about breaking.

**Comment by zepumph** [comment]
I renamed tandems above. Hopefully tests can be added for the tandem changes over in https://github.com/phetsims/phet-io/issues/1657 and with further work over there. Closing
