### ISSUE TITLE
ComboBox: selected item may not appear in the list

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#591]
Pulling this issue out of #588.

If the selected item is made invisible in the list box, you end up with something like this:

<img width="192" alt="screenshot_274" src="https://user-images.githubusercontent.com/3046552/79620139-3212d480-80cc-11ea-8504-a42ca938757f.png">

This seems odd to me, but I don't have a proposal for addressing it. And it doesn't cause a problem.

In https://github.com/phetsims/sun/issues/588#issuecomment-613049512, @arouinfar replied with:
> It also seems a bit odd to me, but I think it is acceptable since it doesn't break the sim or cause it to crash. PhET-iO is not foolproof, and there are myriad ways that clients can do odd things when customizing a sim. Our stance so far has been to put the burden on the client, and I don't really see how this case is any different.

I've used the same assignment and labels as #588. Feel free to adjust.

**Comment by pixelzoom** [comment]
This was discussed in 5/7/2020 dev meeting, and I agreed to move it forward, since it's on the list of issues to evaluate before ph-scale 1.4 RC.    

It's not at all clear what an appropriate solution to this is.  Any solution that I can think of is complicated and may have unintended side-effects.  And as is, it doesn't break anything - the sim continues to function properly - it just feels odd.  

So my recommendation is to "do nothing" and close this issue.  @arouinfar do you agree?

**Comment by arouinfar** [comment]
I agree @pixelzoom. Let's close.
