### ISSUE TITLE
ABSwitch label Nodes should have a 'pointer' cursor

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/sun#592]
In https://github.com/phetsims/energy-skate-park/issues/262#issuecomment-620161307 @arouinfar pointed out that the label Nodes for ABSwitch don't have a 'pointer' cursor until they are pressed.

ABSwitch used to have `cursor: 'pointer'` but that was removed in phetsims/sun@8030fd0 from https://github.com/phetsims/sun/issues/559.

**Comment by jessegreenberg** [comment]
`cursor: 'pointer'` is default for the ToggleSwitch, but it still needs to be set on the ABSwitch for the labels. I added it back, assigning to @pixelzoom to review (author of ABSwitch.)

**Comment by pixelzoom** [comment]
Since the listeners are added to the labels, not to ABSwitch, and the client may have set pointer areas for the labels, my first instinct would have been to set `cursor` on the labels, not the ABSwitch.  But this seems to work, so closing.
