### ISSUE TITLE
AquaRadioButton labelTagName should default to h3

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#593]
While working on https://github.com/phetsims/ratio-and-proportion/issues/34, I noticed that this is the case for RadioButtonGroup, but not for AquaRadioButtonGroup. I'll add it and then remove duplications in usages.

**Comment by zepumph** [comment]
@jessegreenberg please spot check the above commits.

**Comment by jessegreenberg** [comment]
Cool, looks good thanks!
