### ISSUE TITLE
dynamic layout doesn't consider visibility of children on construction

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#594]
Related to https://github.com/phetsims/joist/issues/608.

I believe I've found a bug in dynamic layout... Visibility of children does not seem to be taken into account on construction.  For example, when I create a VBox that has an invisible child, there's a gap where that child would be.  If I create the same VBox with the same children, but make the child invisible after the VBox constructor is called, then there is no gap.

There's an example in natural-selection.EnvironmentalFactorsPanel, see `toughFoodCheckbox`.  

```js
    const toughFoodCheckbox = new ToughFoodCheckbox( foodSupply.isToughProperty, {
      visible: options.toughFoodCheckboxVisible,
      tandem: options.tandem.createTandem( 'toughFoodCheckbox' )
    } );
```

The value of `options.toughFoodCheckboxVisible` is false for the Intro screen, which results in a gap where toughFoodCheckbox would be:

<img width="226" alt="screenshot_297" src="https://user-images.githubusercontent.com/3046552/81240045-9508d480-8fc3-11ea-9a11-7c8c8ba89049.png">

**Comment by jonathanolson** [comment]
This should be resolved. Turns out we were setting children (due to mutate options order) before the excludeInvisibleChildrenFromBounds. The change of that flag didn't trigger a re-layout. Now if there are invisible children, changing that flag will trigger a layout, which fixes this case and others.

**Comment by pixelzoom** [comment]
👍 Closing.
