### ISSUE TITLE
CT: Slider PhET-iO API validation failed: error report should be empty

### ISSUE THREAD

**Issue by chrisklus** [phetsims/sun#595]
```
sun : top-level-unit-tests : require.js?ea&brand=phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588815845865/sun/sun-tests.html?ea&brand=phet-io
3 out of 4 tests passed. 1 failed.
Slider: Slider PhET-iO API validation failed:
error report should be empty:

missing phetioID: sun.general.slider.thumbInputListener.isDraggingProperty
missing phetioID: sun.general.slider.thumbInputListener.dragStartAction
invalid metadata for sun.general.slider.thumbInputListener.dragAction, key=phetioEventType, expected MODEL but received USER
invalid metadata for sun.general.slider.thumbInputListener.dragAction, key=phetioReadOnly, expected true but received false
invalid metadata for sun.general.slider.thumbInputListener.dragAction, key=phetioTypeName, expected ActionIO<Vector2IO> but received ActionIO<SceneryEventIO>
missing phetioID: sun.general.slider.thumbInputListener.dragEndAction
missing phetioID: sun.general.slider.thumbInputListener
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588815845865/sun/js/SliderTests.js:318:12)

id: Bayes Chrome
Snapshot from 5/6/2020, 9:44:05 PM
```

**Comment by chrisklus** [comment]
From slack:

@samreid said in response to the above error mentioned on dev-public:
>In https://github.com/phetsims/phet-io/issues/1648 and https://github.com/phetsims/phet-io/issues/1657 we started with experimenting about how to test and validate phet-io design specifications.
(in a modular way as opposed to testing the full phet-io API file)

@chrisklus 
>should we comment out this line? `assert.ok( report.length === 0, 'error report should be empty: \n\n' + report.join( '\n' ) );`

@samreid 
>Yes, let’s comment that out for now so we don’t cloud CT, then we can take a closer look and see how SimpleDragHandler=>DragListener had different phet-io APIs.  Then we will probably revise the tests accordingly.
Or go with a strategy like the patch in https://github.com/phetsims/phet-io/issues/1657

**Comment by samreid** [comment]
On hold until we choose a direction for https://github.com/phetsims/phet-io/issues/1657

**Comment by samreid** [comment]
@zepumph can this be closed?
