### ISSUE TITLE
deprecation warnings in Slider

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#599]
I ran into this while doing a code review for https://github.com/heldentodd/xray-diffraction/issues/1.  This item is part of the CRC:

> - [ ] Does the sim output any deprecation warnings? Run with `?deprecationWarnings`. Do not use deprecated methods in new code.

All but 1 of the warnings for this sim occurred in Slider.js subcomponents, and those warnings are:

SliderTrack:
> SimpleDragHandler is deprecated, please use DragListener instead.

SliderThumb:
> ButtonListener is deprecated, please use FireListener instead
> DownUpListener is deprecated, please use PressListener instead

Having these warning come from common-code, especially something as ubiquitous as Slider, may mask real problems. Because of these warnings I almost missed the 1 warning that was important. So recommended to clean this up, so that  `?deprecationWarnings` is more useful.

Assigning to @ariel-phet to prioritize and assign.

**Comment by ariel-phet** [comment]
Sounds like @jonathanolson has a common code issue related to this one so would be good for him to tackle.

**Comment by jonathanolson** [comment]
Looks like the original Slider code was already converted, this I guess was technically a separate issue. Converted above. Can you verify you're getting no warnings now?

**Comment by pixelzoom** [comment]
I'm see new CT errors related to this for multiple sims (see example below), so I'm not even going to look at the changes.  Back to @jonathanolson.

```
hookes-law : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591219063277/hookes-law/hookes-law_en.html?continuousTest=%7B%22test%22%3A%5B%22hookes-law%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1591219063277%22%2C%22timestamp%22%3A1591223591407%7D&brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591219063277/assert/js/assert.js:22:13)
at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591219063277/tandem/js/Tandem.js:125:19)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591219063277/tandem/js/PhetioObject.js:355:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591219063277/tandem/js/PhetioObject.js:191:10)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591219063277/axon/js/Action.js:91:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591219063277/scenery/js/listeners/PressListener.js:242:23)
at new SliderThumb (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591219063277/sun/js/SliderThumb.js:67:25)
at HSlider.Slider [as constructor] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591219063277/sun/js/Slider.js:216:38)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591219063277/sun/js/HSlider.js:27:10)
at new NumberControl (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591219063277/scenery-phet/js/NumberControl.js:251:17)
id: Bayes Chrome
Snapshot from 6/3/2020, 3:17:43 PM
```

**Comment by samreid** [comment]
I pushed a fix that corrects the problem on my working copy.

**Comment by jonathanolson** [comment]
In Slack:

> Jonathan Olson  8:49 AM
Since we're now using code that requires a tandem (a PressListener) for handling slider thumb highlighting... is there any way to hide that? Or do we want to expose > that to the client?
> 
> Chris Malley  8:50 AM
> This listener is responsible for highlighting only?
> 8:51
> If so... That seems like an implementation detail that could be hidden.  And you could do so by passing tandem: Tandem.OPTIONAL to the PressListener.
> 8:52
> Or if it's phetioFeatured: false by default, then it might be OK to just leave it instrumented. It's really a question for the designers.
> 
> Sam Reid  9:36 AM
I agree it is a question for designers, the main thing we would get from it is a message in the data stream, but it’s not clear that is necessary, especially since we > aren’t doing that uniformly across all UI components.
> 
> Jonathan Olson  10:00 AM
> Yes, it's responsible for highlighting only. Who would I assign the issue to (in order to get the designers' opinion?)
> New
> 
> Sam Reid  10:02 AM
Maybe label it for “meeting:phet-io” and/or put it at the top of the bullet list for phet-io meeting today?  https://docs.google.com/document/> d/1-nqTlDtLtPB8JrdDrE8KdJB-4Phwe6QvTV_UnsZrteg/edit
> 
> Michael Kauzmann:spiral_calendar_pad:  10:05 AM
> By convention, we use Tandem.OPT_OUT for these cases. It sounds like not instrumenting it is correct.
> 
> Chris Malley  10:06 AM
> It would also be good to capture this discussion in the GitHub issue.
> 
> Sam Reid  10:06 AM
> Thanks Michael, that sounds good.  I think the same should be done for that recent issue about move to front listener.
> 
> Michael Kauzmann:spiral_calendar_pad:  10:07 AM
> Yes both feel like implementation details. We can check with designers, but it feels like something I would remove instrumentation for and then confirm with designers.
> 
> Jonathan Olson  10:08 AM
> The issue is https://github.com/phetsims/sun/issues/599. How about I pass Tandem.OPT_OUT and tag it for the meeting to verify? (I'll record this conversation)

**Comment by zepumph** [comment]
@kathy-phet, @arouinfar, @samreid, @jonathanolson, @pixelzoom, @zepumph discussed during PhET-iO Meeting today. We think it is OK to opt out here, and in general for hover behavior. Here is the code: 

https://github.com/phetsims/sun/blob/6351a940918f1f2de223731b8b966e9d6db6395f/js/SliderThumb.js#L61-L70


I will add documentation about opting out of hover behavior in general. Then I will close.
