### ISSUE TITLE
Should Dialogs call update layout when its isShowingProperty is toggled.

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/sun#600]
In, https://github.com/phetsims/collision-lab/issues/89, I attempted to position my custom KeypadDialog to the right of the panel at the bottom (BallValuesPanel)

![Screen Shot 2020-06-05 at 11 56 32 AM](https://user-images.githubusercontent.com/42391580/83908055-b1fc0900-a723-11ea-811c-0321e9f02d40.png)

I used the layoutStrategy option, which works great.

However, the width of the BallValuesPanel changes when "More Data" checkbox is hit, and reopening the Keypad (by pressing one of the NumberDisplays) yields a incorrectly positioned Keypad (should be exactly next to the panel, like in the ss above)

![Screen Shot 2020-06-05 at 11 59 11 AM](https://user-images.githubusercontent.com/42391580/83908272-0d2dfb80-a724-11ea-97a0-823f1764a6de.png)

Here is the call site:
```

    const keypad = new KeypadDialog( {
      layoutStrategy: ( keypadDialog, simBounds, screenBounds, scale ) => {
        keypadDialog.leftBottom = this.localToGlobalPoint( ballValuesPanel.rightBottom.plusXY( 10, 0 ) ).times( 1 / scale );
      }
    } );

```

---- 
The problem is that Dialog doesn't call its layoutStrategy option when its `isShowingProperty` changes, resulting in a misplaced Keypad, and I believe that it should.

Here is the code in Dialog
```
  this.updateLayoutMultilink = Property.multilink( [
    sim.boundsProperty,
    sim.screenBoundsProperty,
    sim.scaleProperty,
    sim.screenProperty
  ], ...
```
which updates the layout and calls its layoutStrategy option. The positioning of the keypad is corrected when the browser is resized, which makes sense based on this multilink. I believe that this multilink should have its 
`isShowingProperty` as a dependency, which would fix this issue.

Assigning the authors of Dialog (@pixelzoom, @samreid, @jonathanolson) for comment.

**Comment by pixelzoom** [comment]
A lot has changed in Dialog since I last worked on it.  And I'm not familiar with `isShowingProperty`, it's something that was added by @samreid.   That said...

@brandonLi8 your proposed fix seems reasonable to me, and I confirmed that it works in the context of collision-lab.  If this is blocking your work, you might ping @samreid on Slack to see if he sees any problems with applying this fix.

**Comment by samreid** [comment]
Yes, it seems `isShowingProperty` should be a dependency, thanks for identifying this.  @brandonLi8 you can proceed at will.

**Comment by brandonLi8** [comment]
Done in the commit above. Problem fixed in Collision Lab. Closing.
