### ISSUE TITLE
pressListener shows up as phetioFeatured in studio tree

### ISSUE THREAD

**Issue by arouinfar** [phetsims/sun#601]
Noticed while reviewing SOM for https://github.com/phetsims/states-of-matter/issues/296.

I noticed that buttons and radio buttons now show the `pressListener` when viewing the featured elements in studio. None of the children are featured, so it looks like an empty container. Here are a few examples:

<img src="https://user-images.githubusercontent.com/8419308/85359586-e87fa500-b4d3-11ea-9f21-e876d7b19917.png" width=300> <img src="https://user-images.githubusercontent.com/8419308/85359620-ffbe9280-b4d3-11ea-92b6-19e3a4eb6e66.png">

This doesn't seem like a particularly useful thing to be featured. Assigning the PhET-iO team for investigation.

Since this affects the upcoming client preview dev releases of SOM and GAO, I'm marking this as high priority. Apologies if this is the incorrect repo. Since I noticed this in buttons and radio buttons, sun seemed like the right place.

**Comment by samreid** [comment]
It looks like this is the same problem as https://github.com/phetsims/studio/issues/28, I'll copy the additional information there and close this issue.

**Comment by arouinfar** [comment]
@samreid I'm also questioning why the `pressListener` is featured in the first place. I do not remember seeing it being featured until recently.

**Comment by samreid** [comment]
The `pressListener` is not instrumented so it is neither `phetioFeatured: true` nor `phetioFeatured: false`.  The fact that it is showing in the featured view in studio is a bug related to https://github.com/phetsims/studio/issues/28.

**Comment by arouinfar** [comment]
Got it, thanks for the explanation @samreid!
