### ISSUE TITLE
Add general sound support to ComboBox

### ISSUE THREAD

**Issue by jbphet** [phetsims/sun#602]
For the sound design of the ratio-and-proportion sim, we need a sound when the combo box closes up.  We did a sort of one-off implementation for this in molarity, but it would be good at this point to add general support.

**Comment by jbphet** [comment]
@pixelzoom - I just added basic open and close sound players for the combo box.  I think it would be an improvement to have a different sound that is played when the selection changes versus when the combo box is closed without any change being made.  I recall that the sound design team wanted to do this for Molarity, but it wasn't easy to do so because the list box was hidden before the property value was changed, so I couldn't have code that tracked what the property was when the list box was opened versus what it was when closed and make a decision on which sound to play at that time.  We ended up bailing on it and making no sound in the combo-box-closed-with-no-change case.

My question for you is: Can we rearrange the code in `ComboBoxListBox.js` such that the property value is updated *before* the list box is hidden instead of after?  I tried it locally and didn't notice any consequences, but I know this is a complicated component and I'm reluctant to make a change like that without consulting with the original author.  So, would that change be safe or is there a reason that it's done in this order (that you recall)?

**Comment by pixelzoom** [comment]
If you're proposing to change the order of this bit in ComboBoxListBox:

```js
      // hide the list
      hideListBoxCallback();

      // prevent nodes (eg, controls) behind the list from receiving the event
      event.abort();

      // set value based on which item was chosen in the list box
      property.value = listItemNode.item.value;
```

I don't see any problem with moving `property.value =...` before `hideListBoxCallback()`.   But I don't see how that tells ComboBox which sound to play. 

You might also consider making ComboBoxListBox responsible for playing the sounds that are associated with it, rather than having ComboBox do that.

**Comment by jbphet** [comment]
We discussed this at today's sound design meeting, and @Ashton-Morris is going to supply a new sound for the "something new was selected" case.

**Comment by Ashton-Morris** [comment]
@jbphet [Please add this to test out with ComboBox](https://drive.google.com/drive/folders/1YHLFqMsM_lXnnTT_Ec-yGK86mTqgX9Ec?usp=sharing)

- ui-combobox-selection.mp3
- ui-combobox-selection.wav

**Comment by jbphet** [comment]
@Ashton-Morris - the selection sound has been integrated.  Please note that I changed the file names to `combo-box-selection` instead of `ui-combobox-selection` for greater consistency with other sound names.  Let's review this in the 7/7/2020 sound design meeting.

**Comment by pixelzoom** [comment]
In ComboBox.js, I see:

```js
// sound generation - assumes that value has been updated before list box is hidden
```

You asked about this, and my feedback in https://github.com/phetsims/sun/issues/602#issuecomment-652032599 was that this order dependency is probably not necessary.  Can you explain why the responsibility for the listbox sound needs to be in ComboBox.js instead of ComboBoxListBox.js?

**Comment by pixelzoom** [comment]
To elaborate... If I had sounds associated with a menu, I would expect them to be handled by the menu, not by the control used to pop up the menu.  Especially the sound used to pop down the menu, since the control should have no responsibility related to that action.  ComboBox is similar - the listbox is a type of menu, and ComboBox is the mechanism used to pop it up.

**Comment by jbphet** [comment]
Indeed.  I wasn't quite done with all the changes I'd planned yet, and will likely move them.

**Comment by jbphet** [comment]
Sound generation has been moved to `ComboBoxListBox`.  @pixelzoom - please review.

**Comment by pixelzoom** [comment]
While working on an unrelated issue (https://github.com/phetsims/axon/issues/306), I had to fuzz test ESP.  I immediately hit this failure, which I also see in CT:

```
assert.js:22 Uncaught Error: Assertion failed: no value for when the list box was opened
    at window.assertions.assertFunction (assert.js:22)
    at ComboBoxListBox.js:182
    at TinyForwardingProperty.emit (TinyEmitter.js:69)
    at TinyForwardingProperty.notifyListeners (TinyForwardingProperty.js:120)
    at forwardingListener (TinyForwardingProperty.js:41)
    at TinyEmitter.emit (TinyEmitter.js:69)
    at BooleanProperty._notifyListeners (Property.js:273)
    at BooleanProperty.set (Property.js:171)
    at TinyForwardingProperty.set (TinyForwardingProperty.js:101)
    at TinyForwardingProperty.set value [as value] (TinyProperty.js:87)
```

Here's the code around the failing assertion in ComboBoxListBox.js:

```js
        // sound generation - assumes that the property value has been updated before this list box is hidden
        assert && assert( selectionWhenListBoxOpened !== null, 'no value for when the list box was opened' );
        if ( selectionWhenListBoxOpened === property.value ) {
          closedNoChangeSoundPlayer.play();
```

So I'm going to defer my review until this issue is addressed.

**Comment by jbphet** [comment]
The issue with ESP failing CT was recorded in https://github.com/phetsims/energy-skate-park/issues/277 and should now be addressed.

**Comment by jbphet** [comment]
In the 7/7/2020 sounds design meeting we (@emily-phet, @Ashton-Morris, @zepumph, @BLFiedler and myself) reviewed the sounds from the combo box in the context of the Ratio & Proportion simulation.  We decided that the general open and close sounds were fine, but would like to make a change to the selection sound.  For now, I'm going to try using the sounds used for the radio buttons, since they produce a slightly different sound for each choice, are fairly generic, and are programmatically based so can accommodate a large number of choices.

**Comment by jbphet** [comment]
@pixelzoom - I'll unassign you for now and you can review once the changes that were decided upon in the sound design meeting are complete.  They won't affect the logic much, but it's still probably best to get it all done before doing any review.

**Comment by jbphet** [comment]
Latest sounds approved during today's sound design meeting.  Next steps:

- [ ] Rename `radioButtonSoundPlayerFactory` to something more general, since it is now used in an additional context
- [ ] Simplify default usages for the open and close sound players

**Comment by jbphet** [comment]
A number of refinements have been made since this was initially created, and it seems like now would be a good to to have it reviewed.  Assigning to @pixelzoom.

**Comment by pixelzoom** [comment]
@jbphet what's the priority of this review? I'm unlikely to get to it for a couple of weeks.

**Comment by jbphet** [comment]
Medium, in my opinion.  I know that's a milquetoast sort of answer, so here is my justification: I think the changes are low risk and any significantly negative consequences would likely be caught by QA.  However, having said that, both default and non-default sound generation by combo boxes is now being used in ratio-and-proportion, and that sim will likely enter the RC process some time in September.  So, if it's done within the next couple weeks, that's probably fine, but it would be nice to get it done in that time frame.

**Comment by pixelzoom** [comment]
I started to review this and can't wrap my arms around it. ComboBox and its subcomponents is a lot of code, and there have been a lot of commits.  Back to @jbphet to identify specifically what I need to look at -- sections of code, specific commits,... anything specific.

**Comment by jbphet** [comment]
Here is what I would suggest: Start in `ComboBox.js` and search for the word 'sound', case insensitive, in any context (i.e. the "Words" search options is off in WebStorm), and review all the lines of code that comes up.  Then do the same in `ComboBoxListBox.js`.  That should allow you to see all the sound-related code that was added for this effort.

**Comment by pixelzoom** [comment]
Review completed, looks good. One type expression fixed in the above commit.

Back to @jbphet in case there's more to do here.

**Comment by jbphet** [comment]
Thanks for the review and the type expression fix.  I think we're done here, closing.
