### ISSUE TITLE
ComboBox crashes when all items in list box are invisible

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#606]
Originally reported in https://github.com/phetsims/ph-scale/issues/177, for phetsims/QA#514 and phetsims/QA#515. 

PhET-iO allows you to control the `visibleProperty` or each item in a ComboBox's list box.  It all of the items are made invisible, then pressing the combo box button (to popup the list box) will crash the sim.  

For example, if you perform these steps for ph-scale:

1. Open ph-scale in Studio
2. Go to a screen with the list box (element `soluteComboBox.listBox`)
3. While list box is closed, set `visibleProperty` to false for all items in the list box
4. Press the combo box button to open the list box.

... then the failure in ph-scale is:

```js
Uncaught Error: Assertion failed: scales should be finite
    at window.assertions.assertFunction (assert.js:22)
    at ComboBoxListBox.scale (Node.js:2109)
    at SoluteComboBox.scaleListBox (ComboBox.js:372)
    at ComboBox.js:250
    at TinyForwardingProperty.emit (TinyEmitter.js:69)
    at TinyForwardingProperty.notifyListeners (TinyForwardingProperty.js:120)
    at forwardingListener (TinyForwardingProperty.js:41)
    at TinyEmitter.emit (TinyEmitter.js:69)
    at BooleanProperty._notifyListeners (Property.js:273)
    at BooleanProperty.set (Property.js:171)
```

ComboBox was not designed (or implemented) to accommodate an empty list, since an empty list makes no sense in practice. But since an empty list is now possible via PhET-iO, we need to modify ComboBox so that it does something other than crash when the list is "empty" (all items are invisible).

In https://github.com/phetsims/ph-scale/issues/177#issuecomment-662159126, @arouinfar said:
> It would be nice if there could be some solution that would prevent the sim from crashing, so let's check in with the PhET-iO team. I believe @zepumph is on deck for the pH Scale rc, but please feel free to reassign as necessary.

 My recommendation is to make the combo box button do nothing when the list box contains no visible items.

This issue blocks publication of all instrumented sims that have a ComboBox, including the in-progress RC tests of ph-scale and ph-scale-basics.  And changes will need to be cherry-picked to the 1.4 branches of ph-scale and ph-scale-basics.

**Comment by zepumph** [comment]
Suggestions:

* When you hide all elements, then you toggle displayOnlyProperty or enabledProperty. In PhET-iO customization you could still toggle these other Properties back, click on the combo box and then break the sim.
* Open a dialog that says "you must have at least 1 item in this combo box." This would be complicated
* Put a single, hstrut-like element that is behind the first element, so that the listbox always has a min size of 1 element.
* @samreid mentioned we could just guard the failing code

We went with the last option, and it fixed the error immediately. It is possible that this problem may come up again in the future, and would be hard to test.

@samreid also mentioned that it may be better to check if the listBox bounds `isEmpty`, instead of  using `Number.isFinite`. @samreid could you please take this from here?

**Comment by pixelzoom** [comment]
> @samreid also mentioned that it may be better to check if the listBox bounds isEmpty, instead of using Number.isFinite.

Adding this to ComboBox `scaleListBox`:

> console.log( `buttonScale=${buttonScale} listBoxScale=${listBoxScale}` );

... logs this when you try to pop up an empty list:

> buttonScale=0.4918181818181818 listBoxScale=NaN

So yes, the correct way to detect this is to test `this.listBox.localBounds`.

**Comment by pixelzoom** [comment]
Since I was in `scaleListBox`, I went ahead and made the change.  It seems to be working correctly in Studio.  @samreid @zepumph please review.

**Comment by pixelzoom** [comment]
Since I was in `scaleListBox`, I went ahead and made the change.  It seems to be working correctly in Studio.  @samreid or @zepumph please review.  

If it looks OK, assign back to me to cherry-pick to ph-scale and ph-scale-basics 1.4.

**Comment by zepumph** [comment]
It looks very excellent to me, thanks for implementing, and thanks @samreid for the idea. I tested the macro screen in ph-scale, and all looks smooth and good. Thanks!

**Comment by pixelzoom** [comment]
👍 Closing.

**Comment by pixelzoom** [comment]
Reopening. I need to cherry-pick to ph-scale and ph-scale-basics 1.4.

**Comment by pixelzoom** [comment]
Cherry-pick completed, closing.
