### ISSUE TITLE
UI sound when clicking the title bar of the AccordionBox?

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#607]
Right now we only get a sound from the push button. I think this may be our first accordion box in a sound designed sim. Over to @emily-phet to decide what to do.

**Comment by jbphet** [comment]
We reviewed these in the 7/22/2020 sound design meeting and decided to go with `accordion-box-open-combobox-related-004` for the open sound and `accordion-box-close-combobox-related-002` for the close sound.  

@Ashton-Morris - these files were renamed when committed to the code base to simply `accordion-box-open` and `accordion-box-close, and I thought you might want to know this in case you're tracking the source files that you used to create them.  Once noted, you can go ahead and close this issue.

**Comment by Ashton-Morris** [comment]
Noted
