### ISSUE TITLE
Don't use pickable in RadioButtonGroup

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/sun#609]
To make the selected button non-clickable and to change its cursor, `pickable` is used in RadioButtonGroup:
```js

  // make the unselected buttons pickable and have a pointer cursor
  const propertyListener = function( value ) {
    if ( self.enabledProperty.get() ) {
      for ( i = 0; i < contentArray.length; i++ ) {
        if ( contentArray[ i ].value === value ) {
          buttons[ i ].pickable = false;
          buttons[ i ].cursor = null;
        }
        else {
          buttons[ i ].pickable = true;
          buttons[ i ].cursor = 'pointer';
        }
      }
    }
  };
  property.link( propertyListener );
```

but `pickable = false` is blocking PDOM related events too, and we still need `keydown` events to fire on the selected radio button in https://github.com/phetsims/scenery/issues/1056#issuecomment-665313661.

This patch has the same behavior for the RadioButtonGroup member but doesn't use `pickable`. Instead it uses PressListener's `canStartPress` to control whether or not the button can fire.

<details>

```diff
Index: js/buttons/RadioButtonGroupMember.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/buttons/RadioButtonGroupMember.js	(revision 3c0403f118539a6bce3e7fb009974044a871b34e)
+++ js/buttons/RadioButtonGroupMember.js	(date 1596077015223)
@@ -33,6 +33,12 @@
 
   const self = this;
 
+  // the selected RadioButtonGroupMember as a default cursor to indicate that it is
+  // not clickable
+  const updateCursor = () => {
+    this.cursor = property.value === value ? 'default' : 'pointer';
+  };
+
   options = merge( {
     // The fill for the rectangle behind the radio buttons.  Default color is bluish color, as in the other button library.
     baseColor: ColorConstants.LIGHT_BLUE,
@@ -78,6 +84,21 @@
     phetioReadOnly: PhetioObject.DEFAULT_OPTIONS.phetioReadOnly // to support properly passing this to children, see https://github.com/phetsims/tandem/issues/60
   }, options );
 
+  assert && assert( options.listenerOptions === undefined, 'RadioButtonGroupMember sets options for PressListener' );
+  options.listenerOptions = {
+
+    // button can only fire if Property value is not the value for this button
+    canStartPress: () => {
+      return value !== property.value;
+    },
+
+    // Update the cursor on release. Doing so on Property change will not work because
+    // RectangularButtonView tries to set the cursor based on ButtonInteractionState - this
+    // overrides that. Could the cursor of RectangularButtonView can be more customizable
+    // somehow?
+    release: updateCursor
+  };
+
   // @private
   // Note it shares a tandem with this, so the emitter will be instrumented as a child of the button
   this.buttonModel = new ButtonModel( {
@@ -96,6 +117,8 @@
 
   RectangularButtonView.call( this, this.buttonModel, this.interactionStateProperty, options );
 
+  updateCursor();
+
   // pdom - Specify the default value for assistive technology, this attribute is needed in addition to
   // the 'checked' property to mark this element as the default selection since 'checked' may be set before
   // we are finished adding RadioButtonGroupMembers to the RadioButtonGroup.
Index: js/buttons/RadioButtonGroup.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/buttons/RadioButtonGroup.js	(revision 3c0403f118539a6bce3e7fb009974044a871b34e)
+++ js/buttons/RadioButtonGroup.js	(date 1596076172566)
@@ -336,23 +336,6 @@
   };
   this.enabledProperty.link( enabledListener );
 
-  // make the unselected buttons pickable and have a pointer cursor
-  const propertyListener = function( value ) {
-    if ( self.enabledProperty.get() ) {
-      for ( i = 0; i < contentArray.length; i++ ) {
-        if ( contentArray[ i ].value === value ) {
-          buttons[ i ].pickable = false;
-          buttons[ i ].cursor = null;
-        }
-        else {
-          buttons[ i ].pickable = true;
-          buttons[ i ].cursor = 'pointer';
-        }
-      }
-    }
-  };
-  property.link( propertyListener );
-
   // must be done after this instance is instrumented
   this.addLinkedElement( property, {
     tandem: options.tandem.createTandem( 'property' )
@@ -361,7 +344,6 @@
   // @private - remove listeners from buttons and make eligible for garbage collection
   this.disposeRadioButtonGroup = function() {
     self.enabledProperty.unlink( enabledListener );
-    property.unlink( propertyListener );
     self.removeInputListener( intentListener );
 
     // dispose all buttons
```
</details>

I am not sure who the keeper of RadioButtonGroup is, @ariel-phet can you please assign a reviewer for this change?

For the reviewer, please take a look at `updateCursor` in this patch, can you see a better way?

**Comment by ariel-phet** [comment]
@pixelzoom will give an initial look, but this might be a dev meeting topic as it seems like potentially a larger issue

**Comment by pixelzoom** [comment]
Personally, I don't see the need to set `pickable` or use `canStartPress`. There's no harm done if the selected button can still be pressed, it simply doesn't do anything - it sets a Property to its current value, which is a no-op.  Yes, there's still a visual cue that the button has been pressed, but that's typical of radio buttons -- see for example https://www.w3schools.com/html/tryit.asp?filename=tryhtml_form_radio.  So my preferred solution would be to just get rid of the the `pickable = false` assignments in `propertyListener`.

If must be identical (you'll have to ask @ariel-phet or designers), then yeah, `canStartPress` looks OK.

But...  If `pickable: false` is a problem, is it specific to RadioButtonGroup? Or is it a more general problem with PhET UI components?  We use `pickable: false` all over the place when a UI component is disabled.

**Comment by jessegreenberg** [comment]
Thanks for reviewing.

> There's no harm done if the selected button can still be pressed, it simply doesn't do anything...

Interesting, I don't mind this idea either. @ariel-phet what do you think about this behavior change? Here is an example in molecules-and-light to try it out.
https://phet-dev.colorado.edu/html/molecules-and-light/1.6.0-dev.3/phet/molecules-and-light_en_phet.html

I noticed this is how aqua radio buttons work already (though maybe unintentionally), you can hear the button sound after clicking on the button that is already selected.

> If pickable: false is a problem, is it specific to RadioButtonGroup? Or is it a more general problem with PhET UI components? We use pickable: false all over the place when a UI component is disabled.

I don't think this is a problem. For disabled components, using `pickable: false` is correct and we don't want PDOM related events to fire in that case either.

**Comment by pixelzoom** [comment]
> I noticed this is how aqua radio buttons work already (though maybe unintentionally), you can hear the button sound after clicking on the button that is already selected.

Indeed.  Aqua radio buttons behave like most radio buttons do in UI toolkits.  It sure would be nice if all radio buttons had similar behavior.  And I see no reason for RadioButtonGroup to behave differently.  So you know what my decision would be :)

> I don't think this is a problem. For disabled components, using pickable: false is correct and we don't want PDOM related events to fire in that case either.

Thanks for clarifying about disabled components, that makes sense.

**Comment by ariel-phet** [comment]
@jessegreenberg I would actually say this seems like the correct behavior. When you click on the button, it makes a sound, but nothing happens because the button is already pressed. I feel like lots of interactions on a computer happen this way (some "warning dings" on windows are like this, you keep clicking on something you cannot do and it keeps dinging). So you get the feedback that you have click, which is correct, but nothing happening is not unexpected. 

I am fine with this behavior.

**Comment by jessegreenberg** [comment]
OK! In that case, the `propertyListener` in https://github.com/phetsims/sun/issues/609#issue-668319515 can be entirely removed and thats all that should be all that is necessary for this issue.

**Comment by jessegreenberg** [comment]
The listener was removed, and I made the commit after running fuzz tests with aqua. @pixelzoom any final review or anything else to do for this issue?

**Comment by pixelzoom** [comment]
Changes look great, closing.
