### ISSUE TITLE
X button on dialog may have too small pointer area

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/sun#610]
Found during https://github.com/phetsims/QA/issues/520. Seems to be a common component.
While testing iOS I noticed the x button was a bit hard to press. The dialog can still be exited by pressing outside the dialog, so it may not need to be addressed, but if you are aiming for the button it may be a bit difficult.
![Image from iOS](https://user-images.githubusercontent.com/41024075/89068104-cfb5ab00-d32d-11ea-9cec-2a4e669fe561.png)

**Comment by jessegreenberg** [comment]
@ariel-phet can you take a look at this issue? This is the default touch/mouse area for all Dialog close buttons. Should it be made larger for all dialogs or were these defaults purposefully chosen?

```js
    closeButtonTouchAreaXDilation: 0,
    closeButtonTouchAreaYDilation: 0,
    closeButtonMouseAreaXDilation: 0,
    closeButtonMouseAreaYDilation: 0,
```

**Comment by ariel-phet** [comment]
@jessegreenberg I think these defaults were chosen without phones in mind (iOS). The touch area is certainly generous enough on desktop or such, but I think it would fine to dilate the area by 10 percent for touch. It looks like that will in general not interfere with anything in our dialogs and would increase usability.

So yes, go ahead and make the touch pointer are bigger (by about 10 percent)

**Comment by jessegreenberg** [comment]
The button is pretty small, probably smaller than it used to be after https://github.com/phetsims/joist/issues/586. 10% was almost imperceptible so I went with closer to 35%.

![image](https://user-images.githubusercontent.com/6396244/89230943-4662da80-d5b2-11ea-8927-65b71d31f688.png)

And I reviewed a few other Dialogs which are correctly sized after changes in https://github.com/phetsims/joist/issues/586

<details>

![image](https://user-images.githubusercontent.com/6396244/89231111-a9ed0800-d5b2-11ea-80a3-3dba6f33f96f.png)
![image](https://user-images.githubusercontent.com/6396244/89231591-a27a2e80-d5b3-11ea-9a4e-511a441f0b5a.png)
![image](https://user-images.githubusercontent.com/6396244/89231997-7dd28680-d5b4-11ea-8989-7b9ecf2fdf94.png)

</details>

**Comment by jessegreenberg** [comment]
@pixelzoom would you mind reviewing this change? I found https://github.com/phetsims/joist/issues/341 where the original defaults were chosen.

**Comment by jessegreenberg** [comment]
@ariel-phet can you also please review and comment on whether this change should be cherry-picked into all existing RC's or is just an improvement for the future?

**Comment by pixelzoom** [comment]
This problem originated in https://github.com/phetsims/joist/issues/586.  Now that Dialogs are scaled differently, everything (fonts, spacing,...) needs to be increased in size by ~1.3x.   And that (probably) includes the 'X' close button, not just its touch area.   So I think you need to play around with increasing the size of the 'X', make sure it looks good with AboutDialog, OptionsDialog, OopsDialog, and some custom Dialogs.

**Comment by pixelzoom** [comment]
Also...  

(1) Dialog should be using scenery-phet.CloseButton, see #613.

(2) I really don't like setting non-zero defaults for pointer area dilation in general-purpose UI components, like 426e7945e49ec162790e2a7564f879a0c2de91a3.  If I decide to make a big CloseButton by setting options `iconLength`, it's not going to need dilated pointer areas, and I shouldn't have to set their related options to 0.

**Comment by jessegreenberg** [comment]
OK, thanks - I changed the size of the button instead so that it looks as it did prior to phetsims/joist#586. Spot checked in the same dialogs as https://github.com/phetsims/sun/issues/610#issuecomment-668273931, and the OptionsDialog and OopsDialog

> I really don't like setting non-zero defaults for pointer area dilation in general-purpose UI components...

Makes sense. But the original issue in https://github.com/phetsims/sun/issues/610#issue-670118160 was for SHAs from before phetsims/joist#586. So should we make the button even larger, or have default touch areas that work well on small screens, or best to leave as is?

**Comment by ariel-phet** [comment]
@jessegreenberg probably matching the close button to the previous size would be best if possible. I don't think you must cherry pick this change, I don't think it is a particularly big deal. However, if it is only a 10-15 minute affair, probably better to cherry pick now instead of the (low) potential of having to do a maintenance release later. 

If for this sim it was just the about dialog, I would say definitely do not cherry pick, not worth the time, but since the light spectrum dialog is fairly integral to the sim, it is worth considering if not a huge hassle.

**Comment by pixelzoom** [comment]
The size of the close button good to me in the above commits.   But I see in https://github.com/phetsims/sun/issues/613 that @ariel-phet asked @jessegreenberg to replace Dialog.CloseButton with scenery-phet.CloseButton.   So I should probably wait to review this until that work is done.

**Comment by jessegreenberg** [comment]
The commit to cherry pick is https://github.com/phetsims/sun/commit/9c9f26324b8635536e8fcacb01f8c634afd5940b. The RCs that could benefit from cherry-picking this are those that were made after phetsims/joist#586 but before https://github.com/phetsims/sun/commit/9c9f26324b8635536e8fcacb01f8c634afd5940b. This is the list I noticed by checking the current QA queue. Pinging responsible devs so they are aware.

- https://github.com/phetsims/QA/issues/528 (@chrisklus)
- https://github.com/phetsims/QA/issues/527 (@jbphet)
- https://github.com/phetsims/QA/issues/526 (@jbphet)
- https://github.com/phetsims/QA/issues/525 (@jbphet)
- https://github.com/phetsims/QA/issues/514 (@pixelzoom - if joist#586 changes are also cherry-picked into sim)
- https://github.com/phetsims/QA/issues/515 (@pixelzoom - if joist#586 changes are also cherry-picked into sim)

Finally, this is ready for review again now that #613 is closed. @pixelzoom anything else for this issue?

**Comment by pixelzoom** [comment]
@jessegreenberg Just to be clear.... You're recommending that we cherry-pick the changes to Dialog, but not the work that was done to factor out CloseButton.  Is that correct?

**Comment by jessegreenberg** [comment]
Yes, that is correct - only https://github.com/phetsims/sun/commit/9c9f26324b8635536e8fcacb01f8c634afd5940b should be necessary.

**Comment by pixelzoom** [comment]
Ugh... I get numerous merge conflict when attempting to cherry-pick 9c9f263 to the ph-scale-1.4 branch of sun.

**Comment by jessegreenberg** [comment]
For ph-scale-1.4 branch it may be easier to cherry-pick https://github.com/phetsims/sun/commit/9c9f26324b8635536e8fcacb01f8c634afd5940b after changes from https://github.com/phetsims/joist/issues/586 are moved to release branches.

**Comment by pixelzoom** [comment]
Since there are only 2 lines of code modified by 9c9f263, I ended up applying the changes manually for phetsims/ph-scale#194.

**Comment by pixelzoom** [comment]
I see that @jbphet created phetsims/states-of-matter#320.   I don't see whether @chrisklus did anything related to phetsims/QA#528, so assigning to him.  Then it's OK to close this issue.

**Comment by chrisklus** [comment]
All set for EFAC, thanks much. Closing.
