### ISSUE TITLE
disposed Dialog blocks interaction with the sim

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#618]
There appears to be a new bug in Dialog, possibly introduced when PopupablePanel was factored out.  It is currently manifesting in RewardDialog, in the vegas demo.   To reproduce:

1. Run the vegas demo
2. Go to _Reward_ screen.
3. Press the "open Reward" button
4. Press either the "Keep Going" or "New Level" button

The dialog is disposed, but the barrier rectangle is still present and you can't interact with the ScreenView.

The vegas demo uses `dispose` to dismiss the dialogs, see RewardScreenView.js:

```js
          keepGoingButtonListener: () => {
            console.log( 'Keep Going button' );
            rewardDialog.dispose();
          },
          newLevelButtonListener: () => {
            console.log( 'New Level button' );
            rewardDialog.dispose();
          }
```

So possibly this problem is specific to `dispose`, and maybe `hide` works OK? 

Assigning to @jonathanolson to investigate, since he did the PopupablePanel refactor.  Sorry I didn't have more time to investigate, or reproduce with a vanilla Dialog.

**Comment by pixelzoom** [comment]
Reported again in https://github.com/phetsims/vegas/issues/85.  @ariel-phet please prioritize.

**Comment by samreid** [comment]
Based on the behavior reported in https://github.com/phetsims/vegas/issues/85, these symptoms may need to block publication.  I'll mark accordingly--this can be revised when we know more.

**Comment by jonathanolson** [comment]
`isShowingProperty` was being improperly disposed in Dialog. This ALSO resulted in it being disposed BEFORE hide(), so that hide wasn't functioning properly. Should be fixed with the above commit, @samreid can you review/verify?

**Comment by samreid** [comment]
Great fix, I reviewed the code change and tested in vegas.  Looks great.  I presume if this affected any in-progress sims, it would have been identified by QA, so I don't think it needs to be cherry picked anywhere.  Closing.
