### ISSUE TITLE
buttons do not resize to accommodate dynamic content size

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#623]
This came up while investigating https://github.com/phetsims/natural-selection/issues/223 and https://github.com/phetsims/studio/issues/190.

sun buttons assume that their label (aka content) has a fixed size. If their label is changed after startup, they do not resize to accommodate.  This causes problems when changing the textProperty of button labels in Studio.  If the new text is longer than the text that was used to initialize the button, then the button will not grow and there will be trouble, as shown in example is shown below.  If the text is shorter, there's still a less severe problem -- the button will not shrink, and the margins will be incorrect.

<img width="677" alt="screenshot_547" src="https://user-images.githubusercontent.com/3046552/92502614-642cec00-f1bd-11ea-9f9e-fe782922bac6.png">

**Comment by pixelzoom** [comment]
From today's PhET-iO meeting....

It's unlikely that we'll address this problem by making sun buttons resize to fit dynamic content.  Instead, there was discussion about adding a Rosetta-like UI to Studio for changing strings, and eventually un-instrumenting most textProperty elements. But that's going to be a ways off.  In the meantime, rather than trying to handle this dynamically resizing buttons, @kathy-phet said that we should ignore problems of this sort, and (if the client brings them up) say that we're working on a long-term solutions. 

@samreid @zepumph should we just close this issue?

**Comment by samreid** [comment]
I opened a studio issue, we will continue there.  Closing.
