### ISSUE TITLE
Checkbox input listener is not instrumented

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#624]
Discovered while working on https://github.com/phetsims/scenery/issues/1078, converting Checkbox from ButtonListener to FireListener. 

When you press on a Checkbox, that listener is currently not instrumented, so that event does not appear in the data stream.  And that seems like a significant problem.

**Comment by pixelzoom** [comment]
The listener is now instrumented, and it is not featured, and its tandem name is `buttonListener`. This changes the PhET-iO API for any sim that has a Checkbox.  And the API will change again when `ButtonListener` is replaced with `FireListener` for phetsims/scenery#1078.

Here's how it looks in NS:

<img width="158" alt="screenshot_559" src="https://user-images.githubusercontent.com/3046552/92792295-a6476080-f36a-11ea-930d-9674226430f7.png">

@samreid please review the above commit.  Note that I handled dispose of `buttonListener`.

@arouinfar do you see any problem with this from a design perspective?

**Comment by pixelzoom** [comment]
Checkbox was converted from ButtonListener to FireListener in #625.  Here's the same example from Natural Selection:

<img width="193" alt="screenshot_560" src="https://user-images.githubusercontent.com/3046552/92808715-37bdcf00-f379-11ea-83d7-9f01f122b69f.png">

**Comment by samreid** [comment]
The commit seems good to me, unassigning.

**Comment by pixelzoom** [comment]
@arouinfar if this looks OK to you, feel free to close.

**Comment by pixelzoom** [comment]
Raising priority. This is a blocking issues for https://github.com/phetsims/natural-selection/issues/208. Deadline for taking shas is Thursday 9/17.

**Comment by arouinfar** [comment]
Looks fine to me.
