### ISSUE TITLE
Twixt dependencies not registered in build.json

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/sun#626]
It appears that some sun components rely on twixt as a repo, without it being documented as a requirement incredibly clearly. It seems like the best course of action is to add twixt to build.json, so that it is tracked with SHAs.

It looks like only build-a-molecule 1.0 and collision-lab 1.0 use twixt without declaring it as a dependency (for release branches), identified with:
```js

const build = require( './js/common/build.js' );
const fs = require( 'fs' );
const ChipperVersion = require( './js/common/ChipperVersion.js' );
const getDependencies = require( './js/common/getDependencies.js' );
const ReleaseBranch = require( './js/common/ReleaseBranch.js' );

( async () => {
  const releaseBranches = await ReleaseBranch.getMaintenanceBranches();

  for ( let releaseBranch of releaseBranches ) {
    if ( releaseBranch.repo < 'build' ) {
      continue;
    }
    await releaseBranch.checkout( true );

    try {
      await build( releaseBranch.repo );

      const dependencies = await getDependencies( releaseBranch.repo );

      const chipperVersion = ChipperVersion.getFromRepository();

      let filename;
      if ( chipperVersion.major !== 0 ) {
        filename = `../${releaseBranch.repo}/build/phet/${releaseBranch.repo}_en_phet.html`;
      }
      else {
        filename = `../${releaseBranch.repo}/build/${releaseBranch.repo}_en.html`;
      }

      const usesTwixt = fs.readFileSync( filename, 'utf-8' ).includes( '("twixt")' );
      const referencesTwixt = !!dependencies.twixt;

      if ( !usesTwixt || referencesTwixt ) {
        console.log( `OK: ${releaseBranch} ${usesTwixt} ${referencesTwixt}` );
      }
      else {
        console.log( `WARNING: ${releaseBranch} ${usesTwixt} ${referencesTwixt}` );
      }
    }
    catch ( e ) {
      console.log( `ERROR: ${releaseBranch}` );
      console.log( e );
    }
  }
} )();
```

Builds failed on both of those branches, so they'll need to be patched up. If we have this situation get deployed to production in general, it would mean future translation builds could break the sim (since it would be using master, or potentially an old version of whatever dependency wasn't declared).

I'll plan to patch up those two sims, and add twixt to build.json as a default dependency.

**Comment by jonathanolson** [comment]
collision-lab is also... missing griddle. Better automated support for detection would be nice.

**Comment by jonathanolson** [comment]
Should have things patched up with the state at which they were release-branched, closing.

**Comment by zepumph** [comment]
Grunt update was not run on every sim, so each dev html and readme is out of date. I discovered this while running grunt update on every sim over in https://github.com/phetsims/chipper/issues/981
