### ISSUE TITLE
deprecate ClosestDragListener

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#629]
Related to phetsims/scenery#1078.

ClosestDragListener looks like a vanilla input listener, and it doesn't even extend DragListener.  So I'm pretty sure that it should be deprecated.  It's used in make-a-ten, masses-and-springs, number-play, and pendulum-lab.

@jonathanolson you are the author - your opinion?

**Comment by jonathanolson** [comment]
It seems like it's filling a need, so I'm confused. Why deprecate it, and what could possibly replace it? It seems 100% compatible with PressListener-derived variants.

**Comment by pixelzoom** [comment]
I certainly expected it to extend DragListener, and I'm kind of surprised that you don't think it could be a specialization of DragListener.  But up to you.  If you want to just close this, that's OK with me.

**Comment by pixelzoom** [comment]
I'm also wondering how you can describe this as "PressListener-derived variants" when it isn't derived from PressListener at all.

**Comment by jonathanolson** [comment]
I'm mainly interested in how I can improve the documentation (or potentially the name of ClosestDragListener), I'll explain the main relationships.

ClosestDragListener is kind of like DragListener.createForwardingListener. It doesn't forward the events and start the drags on a true PressListener itself (like createForwardingListener), but instead is a bit more flexible where it calls a custom callback with an event. Both ClosestDragListener and DragListener.createForwardingListener are listeners, but they don't extend DragListener. They see a simple event, and usually this ends in code getting called that hooks into an actual DragListener. ClosestDragListener just does this with MULTIPLE other potential objects/listeners (picking the closest one to the pointer), AND it's more general.

> I certainly expected ClosestDragListener to extend DragListener.
> And I'm kind of surprised that you don't think it could be a specialization of DragListener.

Explained above, they have very different purposes, and it would not be possible to function if it extended DragListener (similar to DragListener.createForwardingListener).

> I'm also wondering how you can categorize it as "PressListener-derived variants" when it isn't derived from PressListener at all.

I didn't categorize it as a variant. I specifically said it seemed "100% compatible with PressListener-derived variants."

Would a rename to something like ClosestDragForwardingListener help? I'll adjust the documentation that references SimpleDragHandler, and note the generalization in the code.

**Comment by pixelzoom** [comment]
Thanks for clarifying.

> Would a rename to something like ClosestDragForwardingListener help? I'll adjust the documentation that references SimpleDragHandler, and note the generalization in the code.

Yes, that seems like an improvement.

**Comment by samreid** [comment]
I'll do this rename, and see if documentation needs to be updated.

**Comment by samreid** [comment]
I renamed it, tested pendulum lab, tested all precommit hooks. I spent time trying to improve the documentation, but it already seems great.  Closing.
