### ISSUE TITLE
how to handle dependency injection of {DerivedProperty} someProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#641]
Breaking this new issue out of https://github.com/phetsims/sun/issues/257.

In https://github.com/phetsims/sun/issues/257#issuecomment-711082727, @samreid reported:

CT is showing errors when a `DerivedProperty` is passed in as `enabledProperty`, for instance, in Number Play:

```
number-play : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602966524474/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1602966524474%22%2C%22timestamp%22%3A1602967915033%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Cannot set values directly to a DerivedProperty, tried to set: false
Error: Cannot set values directly to a DerivedProperty, tried to set: false
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602966524474/axon/js/DerivedProperty.js:120:24)
at RoundArrowButton.setEnabled (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602966524474/sun/js/buttons/RoundButtonView.js:213:38)
at RoundArrowButton.set enabled [as enabled] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602966524474/sun/js/buttons/RoundButtonView.js:191:31)
at RoundArrowButton.onEnabledChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602966524474/fractions-common/js/common/view/RoundArrowButton.js:64:18)
at DerivedProperty.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602966524474/axon/js/Property.js:387:5)
at new RoundArrowButton (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602966524474/fractions-common/js/common/view/RoundArrowButton.js:54:26)
at new ShapeGroupNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602966524474/fractions-common/js/building/view/ShapeGroupNode.js:154:41)
at Function.createIcon (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602966524474/fractions-common/js/building/view/ShapeGroupNode.js:355:22)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602966524474/fractions-common/js/building/view/ShapeGroupStackNode.js:22:113
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1602966524474/phet-core/js/EnumerationMap.js:23:23
id: Bayes Chrome
Snapshot from 10/17/2020, 2:28:44 PM
```

This is because RoundArrowButton sets the enabledProperty value in `onEnabledChange`:

```js
    // @private {function}
    this.enabledListener = this.onEnabledChange.bind( this );
    this.enabledProperty.link( this.enabledListener );
  }

  /**
   * Sets whether this is enabled.
   * @private
   *
   * @param {boolean} enabled
   */
  onEnabledChange( enabled ) {
    this.enabled = this.enabledProperty.value;
  }
```

This can be averted by changing the DerivedProperty to only throw an error if you try to set a different value.  I'm not sure if this is a good solution, or if there should be a guard somewhere else.  But setting the same value to a Property is a no-op, so perhaps setting the same value to a DerivedProperty should also be a no-op?  I'll commit it and request review.

UPDATE: Also `  onEnabledChange( enabled ) {` seems buggy because it ignores its argument.

**Comment by pixelzoom** [comment]
@samreid committed 9b01dfc, then said in https://github.com/phetsims/sun/issues/257#issuecomment-711082862:

> I committed the change to DerivedProperty, @pixelzoom can you please review/discuss/advise?

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/sun/issues/257#issuecomment-711101723, I said:

@samreid said:
> ... But setting the same value to a Property is a no-op, so perhaps setting the same value to a DerivedProperty should also be a no-op? 

I don't think that should be the case. _Any_ attempt to directly set a DerivedProperty is incorrect.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/sun/issues/257#issuecomment-711103244, @samreid said:

Here is a patch that reverts the change to DerivedProperty and moves the guard to RoundButtonView. 

<details>

```diff

Index: main/sun/js/buttons/RoundButtonView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/sun/js/buttons/RoundButtonView.js	(revision a52e5196b2c8a3c02064b005f6142e9b294af415)
+++ main/sun/js/buttons/RoundButtonView.js	(date 1602983778136)
@@ -210,7 +210,9 @@
    */
   setEnabled( value ) {
     assert && assert( typeof value === 'boolean', 'RoundButtonView.enabled must be a boolean value' );
-    this.buttonModel.enabledProperty.set( value );
+    if ( !this.buttonModel.enabledProperty.equalsValue( value ) ) {
+      this.buttonModel.enabledProperty.set( value );
+    }
   }
 
   /**
Index: main/axon/js/DerivedProperty.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/axon/js/DerivedProperty.js	(revision 9b01dfccb2456017b771abff767bd3fe2b317e6f)
+++ main/axon/js/DerivedProperty.js	(date 1602983684323)
@@ -118,9 +118,7 @@
    * @public
    */
   set( value ) {
-    if ( !this.equalsValue( value ) ) {
-      throw new Error( 'Cannot set values directly to a DerivedProperty, tried to set: ' + value );
-    }
+    throw new Error( 'Cannot set values directly to a DerivedProperty, tried to set: ' + value );
   }
 
   /**

```

</details>

The problem is that EnabledComponent allows the user to pass in a `Property`, and some client code passes in a `DerivedProperty`, which does not support `set`.  Do you prefer this patch?  If so, won't we end up proliferating guards like this to other places? This example is in RoundButtonView, but maybe we would need one in RectangularButtonView, and elsewhere--should it be factored out?

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/sun/issues/257#issuecomment-712299607, @zepumph said:

I hadn't yet thought about the fact that `EnabledComponent.enabledProperty` should able to be a passed DerivedProperty. I feel like it is a case we need to support. In this instance, it is `RoundArrowButton's` fault for not supporting the enabledProperty interface, in which options.enabledProperty is of type `Property` (which could be derived). 

>Do you prefer this patch? 

I do not think this patch gets to the bottom of things. First ask ourselves what is the enabledProperty logic in RoundButtonView doing? It seems like it is vestigial to a time when we didn't run enabled on a Property, and instead things were based on `MutableOptionsNode`, see the conversion in https://github.com/phetsims/fractions-common/commit/a203a54e2618c5a80299ed9ab7d009c8381a7442. 

I would recommend removing this code because sun button supertypes now have this enabled support build-in. I tested this patch by running fractions-equality on the first screen. RoundArrowButtons are the colored spinner buttons for changing the fraction.

<details>

```diff
Index: js/common/view/RoundArrowButton.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/RoundArrowButton.js	(revision fe9a2b55924b4fcf9cdd6d9b23ccc8b91dc1a11e)
+++ js/common/view/RoundArrowButton.js	(date 1603126483509)
@@ -45,34 +45,6 @@
     options.yContentOffset = arrowPath.centerY;
 
     super( options );
-
-    // @private {Property.<boolean>}
-    this.enabledProperty = options.enabledProperty;
-
-    // @private {function}
-    this.enabledListener = this.onEnabledChange.bind( this );
-    this.enabledProperty.link( this.enabledListener );
-  }
-
-  /**
-   * Sets whether this is enabled.
-   * @private
-   *
-   * @param {boolean} enabled
-   */
-  onEnabledChange( enabled ) {
-    this.enabled = this.enabledProperty.value;
-  }
-
-  /**
-   * Releases references.
-   * @public
-   * @override
-   */
-  dispose() {
-    this.enabledProperty.unlink( this.enabledListener );
-
-    super.dispose();
   }
 }
 

```
</details>


>If so, won't we end up proliferating guards like this to other places? 

There are 263 usages of `enabled(Property\.value)? = ` in the project. I looked through maybe 50, and found that most of the cases were changing instances. I feel like we will just need to make sure that all usages of enabledProperty work with the central interface we want (which includes `DerivedProperty`).

I would recommending making a new issue to apply this patch so that responsible dev can double check on it.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/sun/issues/257#issuecomment-712340541, I said:

@zepumph said:
>  In this instance, it is RoundArrowButton's fault for not supporting the enabledProperty interface, in which options.enabledProperty is of type Property (which could be derived).

I think I understand the spirit of this comment. But to clarify... RoundArrowButton DOES support the Property API (which includes `setValue`) and cannot possibly forsee the fact that subclasses of Property (like DerivedProperty) may break that contract.  The "fault" here is with the design of DerivedProperty - it extends Property, and then immediately breaks the Property contract for 4 methods, including `setValue`. This is an anti-pattern.

**Comment by pixelzoom** [comment]
First priority here should be reverting phetsims/axon@9b01dfc .

**Comment by samreid** [comment]
I reverted the change to `DerivedProperty`.  For RoundArrowButton, I removed redundant code which is already covered in the EnabledComponent mixin.

**Comment by pixelzoom** [comment]
Commits looks good.

Anything else to discuss or do here?

**Comment by samreid** [comment]
For practical purposes, I think this issue can be closed.  But I think we should have a discussion to get on the same page about the nature of DerivedProperty.  I don't believe we should treat `DerivedProperty` as a subtype of `Property`, even though we used subclassing as the mechanism by which to factor out code.  If this warrants further discussion, I recommend marking for developer meeting.

**Comment by pixelzoom** [comment]
> I don't believe we should treat `DerivedProperty` as a subtype of `Property`,  even though we used subclassing as the mechanism by which to factor out code.  If this warrants further discussion, I recommend marking for developer meeting.

Yes, I think we should discuss at developer meeting.

I'm not clear on what you're proposing here. But we should not use subclassing and then expect to treat DerivedProperty like it's not a subclass.  It's either a subclass or it isn't.  If it shouldn't be a subclass, then change the implementation and share code with Property in some other way.

**Comment by samreid** [comment]
How about factoring out a new type `ReadOnlyProperty` which has everything `Property` has except for the setters (or makes the setters protected therefore not part of the public interface).  Then `DerivedProperty extends ReadOnlyProperty` and `Property extends ReadOnlyProperty`.

**Comment by pixelzoom** [comment]
That would probably get the job done, but has some design issues.  Like why would`ReadOnlyProperty` would have an interface for adding listeners when the value is never going to change?

**Comment by pixelzoom** [comment]
I think that what we want is a base class that has a mutable value, but requires subclass to specify how the value is mutated.  Property mutates by setting directly.  DerivedProperty mutates by deriving a value from dependencies (where the dependencies are instances of this new base class).

**Comment by samreid** [comment]
How about `AbstractProperty` where the abstract part is how the value is set?

**Comment by pixelzoom** [comment]
The about sounds right.  But there may be other things... For example, DerivedProperty also breaks the contract for `reset` and `getInitalValue`.

**Comment by pixelzoom** [comment]
Looks like we also need to include DynamicProperty in this conversation.  Like DerivedProperty, it breaks the contract for `set`, `reset` and `getInitialValue`.   Curiously, it uses assertions instead of throwing Errors, and tries to actually do something -- which seems really wrong.

**Comment by Denz1994** [comment]
SR/JO: We could consider an inheritance tree that looks like 'DerivedProperty' extending`ReadOnlyProperty` and Property extending from 'SettableProperty'. This would add technical debt to changing documentation and setting a bunch of "settable" Property.

JO/SR: Have a method that sets an attribute to determine if a Property is settable. Subtypes would call this function and assertions should fail we are setting a property that isn't settable.

MK: Adds a third layer to our Property interface (i.e. getters/setters, isPhetio, and isSettable)

MK/SR: We could use a typedef to test against and define these types. Consider using a settable or readable Property typdefs. This would also include assertions for isSettable to make sure Properties are settable.

JO: The typedef model works if this is a documentation issue regarding how Properties are expected to be used. We don't want isSettable to not change during the Property.

Proposal: Adding an `isSettable` method, 3 typedefs for Property, and unit tests that check that the implementations match the typedef. These unit should be built so they can be factored out for other instance/typedef comparisons. This is the closest we can get to building an interface for Property.

**Comment by jbphet** [comment]
Discussed in the 1/25/2021 supplemental design meeting.

- A full refactoring of the `Property` type hierarchy might resolve this, but it would be prohibitively expensive, and might not work for things like `DynamicProperty`.  In this approach, the base type would essentially be immutable, and mutability would be added in a sub-type.
- The typedef proposal (see previous comment) would help, but it would also be a lot of work to go through all uses of `Property` in our code and update these, and there is some question about whether this is worth it.
- It was noted that we could just do nothing and probably be okay.  These cases, i.e. passing in `DerivedProperty` instances in places where `set` is need, are generally caught pretty quickly.
- Mixins were discussed.  Again, this would be a big refactor of the existing hierarchy.

We concluded that we should add the `isSettable` method and leave it at that for now, and we will put this on our "bucket list" for future work.  @samreid will take the lead on this, @zepumph stepped up to do the review when it's ready.

**Comment by samreid** [comment]
I added Property.isSettable.  I wasn't sure if there was more to do for this commit.  For instance, there are no usage sites. 
 @zepumph can you please review and advise?

**Comment by samreid** [comment]
The TinyProperty method seems necessary.  Please feel free to commit that or let me know if you prefer me to.

The assertion in Node seems like it may trigger some false positives on CT, where a DerivedProperty is passed in but never attempted to set.  Perhaps the assertion error we already have in DerivedProperty is already appropriate?

**Comment by zepumph** [comment]
I used this example to understand what you were saying about the assertion in Node. 

![image](https://user-images.githubusercontent.com/6856943/106344932-1fcbe680-6259-11eb-9e96-b917d5dc8852.png)


This issue was created to handle enabledProperty though. It seems like a large amount of enabledProperty work has occurred since this issue was created, and onEnabledChange has been refactored substantially. With this patch I am able to use a derivedProperty for Node.enabledProperty.

```diff

Index: js/demo/ComponentsScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/demo/ComponentsScreenView.js b/js/demo/ComponentsScreenView.js
--- a/js/demo/ComponentsScreenView.js	(revision b7c2e3ddaa148e5934a9133cf5bff5dd037aff1a)
+++ b/js/demo/ComponentsScreenView.js	(date 1611974750795)
@@ -1478,7 +1478,12 @@
 // creates a demo for the TimeControlNode
 function demoTimeControlNode( layoutBounds ) {
 
-  const defaultTimeControlNode = new TimeControlNode( new BooleanProperty( true ) );
+  window.property = new BooleanProperty( true );
+  const derived = new DerivedProperty( [ window.property ], x => x );
+  const defaultTimeControlNode = new TimeControlNode( new BooleanProperty( true ), {
+    enabledProperty: derived
+
+  } );
 
   // a TimeControlNode with all push buttons
   const pushButtonTimeControlNode = new TimeControlNode( new BooleanProperty( true ), {
@@ -1487,21 +1492,25 @@
       playPauseButtonOptions: {
         scaleFactorWhenPaused: 1.3
       }
-    }
+    },
+    enabledProperty: derived
   } );
 
   // a TimeControlNode with default speed radio buttons
   const speedTimeControlNode = new TimeControlNode( new BooleanProperty( true ), {
-    timeSpeedProperty: new Property( TimeSpeed.NORMAL )
+    timeSpeedProperty: new Property( TimeSpeed.NORMAL ),
+    enabledProperty: derived
+
   } );
 
-  const enabledProperty = new BooleanProperty( true );
+  const enabledProperty = derived;
 
   // a TimeControlNode with swapped layout for radio buttons with radio buttons wrapped in a panel
   const customTimeControlNode = new TimeControlNode( new BooleanProperty( true ), {
     timeSpeedProperty: new Property( TimeSpeed.SLOW ),
     timeSpeeds: [ TimeSpeed.NORMAL, TimeSpeed.FAST, TimeSpeed.SLOW ],
     speedRadioButtonGroupOnLeft: true,
+
     wrapSpeedButtonsInPanel: true,
     speedRadioButtonGroupPanelOptions: {
       fill: 'rgb(239,239,195)'

```

I can't think of a case where we want to check logic or assert on isSettable(), but I like that it is part of our toolbox now. Perhaps we will have more use for it if we can split functionality in a method and handle the derivedProperty case separately?

What do you think?

**Comment by samreid** [comment]
My apologies, I'm not following the previous comment.  If I apply the patch, and click Components => Time Control Panel => enabled, then I get this error:

> Error: Cannot es5-set values directly to a DerivedProperty, tried to set: false

This error seems to be expected, but I think I didn't follow the point.

> Perhaps we will have more use for it if we can split functionality in a method and handle the derivedProperty case separately?

Are you picturing something at the moment, or for potential future use?

**Comment by zepumph** [comment]
>This error seems to be expected, but I think I didn't follow the point.

Right, I don't think there should be an enabled-specific error when you try to set enabled, it just throws the general one in `DerivedProperty.set()`. Because you tried to set a DerivedProperty

>Perhaps we will have more use for it if we can split functionality in a method and handle the derivedProperty case separately?

My thought was that there may be cases that want to be general and graceful to unsettable Properties. In my example above, I was able to control enabled by setting window.property. I didn't try to set the Node's enabled directly because I knew it would fail. Perhaps we can use that understanding to state a case like "in common code, we won't directly set a property unless we check and see that it is settable. Then we can gracefully no-op if you passed in a DerivedProperty.

For example, what if it was a feature of Slider that when you go to the min in a certain case, you disable the component (horrible UX, but bare with me). In that case, the sun code is depending on getting a settable Property for the enabledProperty. I was thinking that since sun is common code, and should be general, then it may be best to have that "min-disabling" feature guard around if your enabledProperty is settable, and perhaps no-op if it isn't. This contrived example tries to demonstrate the potential of using `isSettable` to split on logic/behavior in the code. 

It is quite possible that for every example that comes up here we agree, "we would rather be strict and error loudly than provide graceful features." If that is the case, then perhaps `isSettable` is not longed for this world! At least in terms of use outside assertions.

**Comment by samreid** [comment]
We may have opportunities to use a graceful guard like you described.  In the same way, if we redo the inheritance hierarchy to be:

```js
class AbstractProperty{}
class DerivedProperty extends AbstractProperty{}
class Property extends AbstractProperty{set(){...}}
```
we may have common code that takes a parameter type `AbstractProperty` and checks instanceof to see if we want to try to set it.

Anything else to do on this issue at the moment?

**Comment by zepumph** [comment]
I don't think so, perhaps a new issue to encapsulate Property hierarchy refactoring, and then perhaps close this issue?

**Comment by samreid** [comment]
Thanks, I opened a new issue, closing.
