### ISSUE TITLE
ButtonModel has an odd way of interrupting listeners

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#642]
Related to https://github.com/phetsims/sun/issues/515 (buttons have a different API for enabledProperty), I'm trying to determine if it's possible to move enabledProperty out of ButtonModel.

This was added to ButtonModel.js by @zepumph in 02a5bff5366732ba6559ef37fb500e2adf13d2e8:

```js
    // interrupt listeners when enabled is set to false
    this.enabledProperty.link( function( enabled ) {
      if ( !enabled ) {
        for ( var i = 0; i < self.listeners.length; i++ ) {
          var listener = self.listeners[ i ];
          listener.interrupt && listener.interrupt();
        }
      }
    } );
```

This is very odd.  There's nothing in the ButtonModel listener contract that indicates the presence of an `interrupt` method.  @zepumph why was this added?  Was it for some specific sim?

**Comment by pixelzoom** [comment]
Ah, I see ButtonModel `createListener` creates and adds instances of PressListener, which defines `interrupt.  And I'm guessing that you didn't use `interruptSubtreeInput` because ButtonModel is not a Node.

**Comment by zepumph** [comment]
Yes, that sounds right to me. If this was in Node, then we could just call `interruptSubtreeInputIO` and wouldn't need to do this weirdness. Anything else here?

**Comment by pixelzoom** [comment]
In the above commits, I renamed ButtonModel `createListener` to `createPressListener`, and improved the doc.  @zepumph feel free to take a peek, but I'm going to go ahead and close this issue.
