### ISSUE TITLE
EnabledNode should be solely responsible for enabled/disabled look of sun buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#644]
Discovered in https://github.com/phetsims/sun/issues/643.

EnabledNode, contentAppearanceStrategy, and appearanceStrategy are all changing the button's appearance when disabled. This is causing the button to look doubly disabled. You can see this in the sun demo Buttons screen.  

Three changes are necessary:

- [x] Delete contentAppearanceStrategy. It handles how the button content looks when disabled, and that is now the responsibility of EnabledNode. So it is no longer relevant, and conflicts with EnabledNode.

- [x] Change buttonAppearanceStrategy so that it does not do anything related to enabled/disabled state.  The look for ButtonInteractionState.IDLE and case ButtonInteractionState.DISABLED should be the same, and the look for ButtonInteractionState.PRESSED and ButtonInteractionState.DISABLED_PRESSED should be the same. EnabledNode will then handle the "enabled" part of the look.

- [x] delete `options.disabledBaseColor`

**Comment by pixelzoom** [comment]
contentAppearanceStrategy should also be deleted from sun buttons. It handles how the button content looks when disabled, and that is now handled by EnabledNode.

**Comment by pixelzoom** [comment]
In the above commit, I did away entirely with contentAppearanceStrategy.

**Comment by pixelzoom** [comment]
Before messing with buttonAppearanceStrategy, I published these dev versions of sun and scenery-phet demos, for before/after comparison:

https://phet-dev.colorado.edu/html/sun/1.0.0-dev.14/phet/sun_en_phet.html
https://phet-dev.colorado.edu/html/scenery-phet/1.0.0-dev.21/phet/scenery-phet_en_phet.html

**Comment by pixelzoom** [comment]
In the above commit, I remove handling of the disabled state from buttonAppearanceStrategy.  EnabledNode is now solely responsible for making sun buttons look disabled.  The major change here is that buttons do not change their color, only their opacity, when disabled.  This is consistent with all other PhET UI components, but is worth mentioning. 

For example, here's the Button screen of the sun demo, showing enabled buttons:

<img width="1049" alt="screenshot_590" src="https://user-images.githubusercontent.com/3046552/97061652-ca46b600-1554-11eb-8994-1d5e08ba9232.png">

Here are the disabled buttons before the buttonAppearanceStrategy changes:

<img width="1050" alt="screenshot_591" src="https://user-images.githubusercontent.com/3046552/97061681-dfbbe000-1554-11eb-81bd-7af9df7e6b21.png">

And after the changes:

<img width="1049" alt="screenshot_589" src="https://user-images.githubusercontent.com/3046552/97061576-92d80980-1554-11eb-8731-e94c3e14a0eb.png">

**Comment by pixelzoom** [comment]
Discussion with @jbphet on Slack about these changes:

Chris Malley  5:38 PM
FYI, since you are the primary author of sun buttons... contentAppearanceStrategy no longer exists, and buttonAppearanceStrategy no longer deals with "disabled" look.  That's all handled by EnabledNode now.  See https://github.com/phetsims/sun/issues/644

John Blanco:house_with_garden:  5:45 PM
Thanks for the heads up.  It all seems reasonable to me.  From the standpoint of just the buttons, I think I'll miss the grayed out appearance when they are disabled, but I understand that it's important to be consistent across UI components, and I think out users will figure it out.

Chris Malley  5:46 PM
Yeah, there were 2 main goals in factoring out enabledProperty: (1) consistent UI, and (2) consistent PhET-iO API.  Really complicated to have one without the other using a mixin. I also can't think of a good reason why buttons should turn grey, while everything else changes opacity.

John Blanco:house_with_garden:  5:50 PM
Agreed - consistent behavior is better.

**Comment by pixelzoom** [comment]
@ariel-phet please have someone review.

**Comment by pixelzoom** [comment]
@ariel-phet please have someone review.  Not that this issue block publication.

**Comment by pixelzoom** [comment]
@ariel-phet please have someone review.  Note that this issue blocks publication.

**Comment by jbphet** [comment]
Review complete.  The basic idea of removing `contentAppearanceStrategy` seems sound given that the responsibility for changing the appearance when disabled now rests elsewhere.  The commits look reasonable, and I tested the behavior in the sun demo, in "States of Matter" (looking at the disabled appearance of the step button) and in "Number Line: Operations" (looking at the disabled behavior of the erase button in the 3rd screen).  It all seems to behave correctly, so overall it looks good.

I have two follow-up questions:
+ Why not have `FlatAppearanceStrategy` in `RectangularButton` instead of `RectangularRadioButton`? Then is would be next to the 3D strategy, and would be apparent to anyone who might want a flat button in some other context in the future.
+ Should @pixelzoom add himself as an author after making major changes such as these?

That's it.  Back to you @pixelzoom.  Feel free to close after addressing the questions, and I'm fine with whatever you choose to do for both.

**Comment by pixelzoom** [comment]
> Why not have FlatAppearanceStrategy in RectangularButton instead of RectangularRadioButton?

They cannot be unified, they deal with different interaction states. 
ButtonNode.FlatAppearanceStrategy has interactionStateProperty of type {Property.<ButtonInteractionState>}.  RectangularRadioButton has a totally different implementation of FlatAppearanceStrategy, whose interactionStateProperty is {Property.<RadioButtonInteractionState>}.

> Should @pixelzoom add himself as an author after making major changes such as these?

@zepumph and I have been throwing this work back and forth, so we will consider adding our names.

**Comment by pixelzoom** [comment]
@ariel-phet reopened without commenting, so assigning to him to clarify.

**Comment by ariel-phet** [comment]
@pixelzoom I initially reopened to discuss the "disabled" look and options with regards to that look. But after our discussion with @jonathanolson yesterday I think we can consider this issue closed.

**Comment by pixelzoom** [comment]
Reopening. There are some vestigial uses of `disabledBaseColor` that need to be removed.

**Comment by pixelzoom** [comment]
Vestigial uses of `disabledBaseColor` where removed in the above commits. CT is clear. Closing.
