### ISSUE TITLE
Factor out duplicated FlatAppearanceStrategies To ButtonNode

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#647]
When I compare RectangularButton.FlatAppearanceStrategy to RoundButton.FlatAppearanceStrategy, they are basically identical:

![image](https://user-images.githubusercontent.com/6856943/97088644-d0817480-15de-11eb-9c88-8e1f0504ce1a.png)

From work over in #643, I am trying to move the `buttonAppearanceStrategy` option up to ButtonNode anyways, so factoring these out to a central strategy seems really nice. Tagging @pixelzoom.

**Comment by zepumph** [comment]
@pixelzoom please review this refactor in correlation with https://github.com/phetsims/sun/issues/643#issuecomment-716037524.

**Comment by pixelzoom** [comment]
Since you renamed `button` to `buttonBackground` in ButtonNode, RoundButton, and RectangularButton, I renamed that parameter to all of the appearance strategies. E.g.:

```js
class FlatAppearanceStrategy {

  /*
   * @param {Node} buttonBackground - the Node for the button's background, sans content
   * @param {Property.<boolean>} interactionStateProperty
   * @param {Property.<Color>} baseColorProperty
   * @param {Object} [options]
   */
  constructor( buttonBackground, interactionStateProperty, baseColorProperty, options ) {
```

**Comment by pixelzoom** [comment]
I think it makes sense to move FlatAppearanceStrategy to ButtonNode. What still bothers me a bit is that param `buttonBackground` is:

```
@param {Node} buttonBackground - the Node for the button's background, sans content
```

And then FlatAppearanceStrategy does things that are not supported by Node, like:

```js
          buttonBackground.fill = baseColorProperty;
          buttonBackground.stroke = options.selectedStroke;
          buttonBackground.lineWidth = options.selectedLineWidth;
```

This is not specific to FlatAppearanceStrategy, the other strategies do the same.  That said, I'm inclined to leave this alone.  So...

@zepumph feel free to close if there's nothing else to do here.

**Comment by zepumph** [comment]
Type docs were updated in another issue. Closing.
