### ISSUE TITLE
selected state is broken for RectangularRadioButtons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#648]
In https://github.com/phetsims/sun/issues/643#issuecomment-717331490, @jessegreenberg  reported:

> I noticed that opacity of content for deselected RadioButtonGroupMembers is no longer changing and tracked it down to https://github.com/phetsims/sun/commit/4f6ed2827256acd1f10e1bc0c524731db62520b4#diff-847130871035dab4cf7080a2b28b5fe5ec50c7dd3f45e13652e98e4bba0a0963 referencing this issue. Was this change intentional? If so, can the RadioButtonGroupMember options relating to content opacity be removed?

**Comment by pixelzoom** [comment]
Looks like that change to RadioButtonGroupMember was not intentional. EnabledNode should have responsibility for enabled state, but RadioButtonGroupMember should have responsibility for selected state.

**Comment by pixelzoom** [comment]
This is definitely a different "look" for unselected radio buttons, but it's behaving as intended.  Opacity is now (uniformly) used to signal "disabled", not "unselected".

For example, for the radio buttons in Molecules and Light:

master:
<img width="707" alt="screenshot_612" src="https://user-images.githubusercontent.com/3046552/97348897-683bc880-1854-11eb-9d73-9f757ba9b122.png">

published (1.5.5.):
<img width="694" alt="screenshot_613" src="https://user-images.githubusercontent.com/3046552/97348914-6d991300-1854-11eb-9297-e73176c698d8.png">

We could restore this behavior.  But the buttons are not disabled, so I see  no reason to change their (or their content's) opacity.  We don't change the opacity of Aqua radio buttons when they are unselected. So I'd like to hear why we should do so for rectangular radio buttons.  If it's an aesthetic preference, that's fine, but do consider the cost and impact on uniformity.

@ariel-phet your opinion on how to proceed?

**Comment by pixelzoom** [comment]
Hmmm... Taking a closer look at RectangularRadioButton.FlatAppearanceStrategy, it looks like the intention was to preserve the old behavior (change opacity when deselect). But the options in RectangularRadioButtonGroup are not being propagated to the RectangularRadioButtons.

**Comment by pixelzoom** [comment]
The  options in RectangularRadioButtonGroup _ARE_ being propagated to the RectangularRadioButtons.  But there is no longer a contentAppearanceStrategy to use them.  Do we need to restore contentAppearanceStrategy?

**Comment by pixelzoom** [comment]
In the above commit, I restored the contentAppearanceStrategy option to ButtonNode. It is now null by default.  I also restored RectangularRadioButton.ContentAppearanceStrategy, which is where content appearance was formerly modified based on interaction state.  

Testing in scenery-phet demo and MAL, the "look" has been restored for the radio buttons.   

But comparing MAL master to [1.5.5](https://phet-dev.colorado.edu/html/molecules-and-light/1.5.5/phet/molecules-and-light_en_phet.html), I see one a different in the labels below the radio buttons.  The labels used to gray out with the radio buttons, but no longer do so.  @jessegreenberg was there some change that was made to MAL?

**Comment by pixelzoom** [comment]
I discussed the MAL button labels mentioned in https://github.com/phetsims/sun/issues/648#issuecomment-717614811 with  @jessegreenberg.  Labels are apparently supported as an optional field in RectangularRadioButtonGroup's `contentArray` constructor parameter.  So I need to track down why those labels are not changing opacity based on button selection.

**Comment by pixelzoom** [comment]
Behavior of the optional button labels is restored in the above commit.  The contentAppearanceStrategy (if provided) needed to be applied to the labels.  I also fixed a memory leak -- the contentAppearanceStrategy instances created for labels were previously not being disposed. 

MAL master and 1.5.5 behavior are now the same, and I spot checked a couple of other sims. 

@jessegreenberg please confirm that this addresses the issue, and close if it looks OK. Please review with relatively high priority, since this is a blocking issue.

**Comment by pixelzoom** [comment]
Hmmm... Something is suddenly wrong in master.  The selected radio button is missing its thicker stroke, see screenshot below. Not sure how I produced the correct-looking screenshot in https://github.com/phetsims/sun/issues/648#issuecomment-717614811. Investigating...

<img width="691" alt="screenshot_616" src="https://user-images.githubusercontent.com/3046552/97476329-e57a4280-1913-11eb-9866-4b0222833271.png">

**Comment by pixelzoom** [comment]
Selected button stroke fixed in the above commit. Ready for review.

**Comment by jessegreenberg** [comment]
> MAL master and 1.5.5 behavior are now the same

I also verified this, they look identical to me. I double checked a few sims that use RectangularRadioButtonGroup and they also look identical to production versions.

I scanned through commits, the optional `contentAppearanceStrategy` looks good.

> and close if it looks OK

Thanks, closing!
