### ISSUE TITLE
ButtonNode xContentOffset and yContentOffset options are broken

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#649]
In https://github.com/phetsims/sun/issues/643#issuecomment-717332418, @jonathanolson reported:

> It looks like the forward/back buttons now look uncentered (a regression):

![image](https://user-images.githubusercontent.com/480878/97325461-a1663f80-1838-11eb-928c-46e81ac6212a.png)

**Comment by pixelzoom** [comment]
Definitely a regression. 

StepButton sets xContentOffset like this:

```js
      xContentOffset: ( DIRECTION === 'forward' ) ? ( 0.075 * BUTTON_RADIUS ) : ( -0.15 * BUTTON_RADIUS ),
```

1.0.0-dev.21 (before changes):

<img width="123" alt="screenshot_611" src="https://user-images.githubusercontent.com/3046552/97328907-1e46e880-183c-11eb-9688-d0d405828081.png">

master (after changes):

<img width="119" alt="screenshot_610" src="https://user-images.githubusercontent.com/3046552/97328932-230b9c80-183c-11eb-9add-e3c264602cc5.png">

@zepumph how did you verify when you moved `xContentOffset` and `yContentOffset` into ButtonNode?

**Comment by pixelzoom** [comment]
The problem here is that ButtonNode wraps the content in an AlignBox, which negates the offsets that were applied:

```js
      const contentContainer = new Node( {
        children: [ options.content ],
        center: new Vector2( options.xContentOffset, options.yContentOffset )
      } );

      // Align content in the button rectangle. Must be disposed since it adds listener to content bounds.
      alignBox = new AlignBox( contentContainer, {
        alignBounds: new Bounds2(
          options.xMargin,
          options.yMargin,
          buttonBackground.width - options.xMargin,
          buttonBackground.height - options.yMargin
        ),
        xAlign: options.xAlign,
        yAlign: options.yAlign,
        center: buttonBackground.center,
        pickable: false // for performance
      } );
```

**Comment by pixelzoom** [comment]
This is affecting all UI components that use options `xContentOffset` and `yContentOffset` -- ResetButton, ResetAllButton, StepButton, LeftRightSpinner, UpDownSpinner, and a couple of sim-specific buttons.

**Comment by pixelzoom** [comment]
This patch fixes the icon positioning problem. But it also changes the bounds of the button, and that manifests as increased spacing around some buttons (like the StepButtons) in scenery-phet demo.  So that creates a new kind of layout problem.

<details>
<summary>patch</summary>

```diff
Index: js/buttons/ButtonNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/buttons/ButtonNode.js	(revision 00423bb53d826830a5ca9b5e3305052350bd1970)
+++ js/buttons/ButtonNode.js	(date 1603816638366)
@@ -111,27 +111,17 @@
     let alignBox = null;
     if ( options.content ) {
 
-      // TODO: there is likely a simpler way to support this content offset, https://github.com/phetsims/sun/issues/643
-      const contentContainer = new Node( {
-        children: [ options.content ],
-        center: new Vector2( options.xContentOffset, options.yContentOffset )
-      } );
-
       // Align content in the button rectangle. Must be disposed since it adds listener to content bounds.
-      alignBox = new AlignBox( contentContainer, {
+      alignBox = new AlignBox( options.content, {
 
         // TODO https://github.com/phetsims/sun/issues/643 Margins here would be broken for round buttons if they
         //  don't use the same value for x and y. Because they are used here differently from how they are used to
         //  calculate radius in RoundButton (as a minimum). Is that OK?
-        alignBounds: new Bounds2(
-          options.xMargin,
-          options.yMargin,
-          buttonBackground.width - options.xMargin,
-          buttonBackground.height - options.yMargin
-        ),
+        alignBounds: buttonBackground.bounds.shifted( options.xContentOffset, options.yContentOffset ),
         xAlign: options.xAlign,
         yAlign: options.yAlign,
-        center: buttonBackground.center,
+        xMargin: options.xMargin,
+        yMargin: options.yMargin,
         pickable: false // for performance
       } );
       this.addChild( alignBox );
```

</details>

**Comment by zepumph** [comment]
>@zepumph how did you verify when you moved xContentOffset and yContentOffset into ButtonNode?

I had a copy of the scenery-phet demo open loaded from pre-changes, and then I compared it to a new sim instance loaded post changes. I didn't see this spacing bug, oops.

**Comment by pixelzoom** [comment]
Fixed in the above commit. The tricky part was using AlignBox in a way that didn't cause it's bounds to unnecessarily spill outside the button's background, thus cause other layout problems. 

Test in scenery-phet (compare to 1.0.0-dev.21) and collision-lab (compare to https://phet-dev.colorado.edu/html/collision-lab/1.1.0-dev.9/phet/collision-lab_en_phet.html).

@zepumph please review the changes.
@jonathanolson please verify that collision-lab is OK.

**Comment by zepumph** [comment]
Your commit looks really nice. Thanks! I'm ready to close this issue. Ignore the above commit, it is for another issue.

**Comment by jonathanolson** [comment]
Looks great!
