### ISSUE TITLE
remove disabled states from InteractionStateProperties

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#651]
Related to https://github.com/phetsims/sun/issues/644.

Removed "disabled" states from *InteractionState, *InteractionStateProperty, and *AppearanceStrategy.  EnabledNode is now responsible for the enabled/disabled "look", and interrupts listeners when disabled. So appearance strategies should not be concerned with whether a button is enabled or disabled. 

The values to remove are:

ButtonInteractionState.DISABLED
ButtonInteractionState.DISABLED_PRESSED
RadioButtonInteractionState.DISABLED_SELECTED
RadioButtonInteractionState.DISABLED_DESELECTED

Classes that this is relevant to:

- [x] ButtonInteractionState
- [x] RadioButtonInteractionState
- [x] MomentaryButtonInteractionStateProperty
- [x] PushButtonInteractionStateProperty
- [x] RadioButtonInteractionStateProperty
- [x] StickyToggleButtonInteractionStateProperty
- [x] ToggleButtonInteractionStateProperty
- [x] ButtonNode.FlatAppearanceStrategy
- [x] RectangularButton.ThreeDAppearanceStrategy
- [x] RoundButton.ThreeDAppearanceStrategy
- [x] RectangularRadioButton.FlatAppearanceStrategy

**Comment by pixelzoom** [comment]
Done in the above commit.  @zepumph please review, since you've been working in this code recently and therefore are probably most familiar with it.

**Comment by zepumph** [comment]
I really like this. Personally I prefer the consistent opacity-driven disabled look to the grayed-out one. Thanks for taking care of this. It feels pretty safe, closing
