### ISSUE TITLE
use Enumeration for button interaction states

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#652]
This occurred to me when responding to https://github.com/phetsims/sun/issues/644#issuecomment-717526958.

ButtonInteractionState and RadioButtonInteractionState are currently old-style enums. They should be converted to Enumeration.

**Comment by pixelzoom** [comment]
Summary of above commit:

* converted ButtonInteractionState and RadioButtonInteractionState to Enumeration
* added `isValidValue` check to all *InteractionStateProperty classes
* added type expression for `@param interactionStateProperty` for all appearance strategy classes, e.g. `@param {Property.<ButtonInteractionState>} interactionStateProperty`

**Comment by pixelzoom** [comment]
@zepumph would you mind taking a quick look at this? If all looks well, feel free to close.

**Comment by zepumph** [comment]
Looks great. ValidatorDef supports `Enumeration` as a valueType, so I simplified the validators. Anything else here?

**Comment by pixelzoom** [comment]
Thanks for the `valueType` change, that's much better.

Closing.
