### ISSUE TITLE
Carousel buttons do not work

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#654]
Slack bug report:

> John Blanco:house_with_garden:  4:10 PM
>  The scroll buttons in Carousel instances appear to be broken.  Shall I log an issue, or do you just want to take a quick look?  I saw it in number-line-operations first, then verified it in expression-exchange (since it's a published sim).  
> 
> Chris Malley  4:24 PM
> "Broken" as in don't work, don't look right, something else?
>
> John Blanco:house_with_garden:  4:25 PM
> Doesn't work, and the pointer doesn't change when hovering on it.

I reproduced in number-line-operations and expression-exchange, and I also see the problem in function-builder.  It's not a problem in sun demo for some reason. 

Carousel hasn't been touched since ES6 conversion on 9/22, so it's probably related to one of the many changes that have been made to sun buttons over the past week.

**Comment by pixelzoom** [comment]
This is probably related to changes to addListener for push buttons.

CarouselButton extends RectangularPushButton.  Carousel adds listeners by calling CarouselButton.addListener.  

Because addListener and removeListener are specific to PushButtonModel, they were moved to RectangularPushButton and RoundPushButton in c547c3d548dd63f7bbe133fa41afba04bd51a6b1.

**Comment by pixelzoom** [comment]
In sun demo ButtonScreenView, I verified that both of these ways of adding listeners to a push button work:

```js
const buttonA = new RectangularPushButton( {
  listener: () => console.log( 'buttonA fired' ),
  ...
} );
```

```js
const buttonA = new RectangularPushButton( { ... } );
buttonA.addListener( () => console.log( 'buttonA fired' ) );
```

**Comment by pixelzoom** [comment]
I added CarouselButton to the sun buttons demo (ButtonsScreenView) and reproduced the problem there.  It appears to be related to pointer areas.  The problem goes away if I comment out these lines at the end of  CarouselButton's constructor:

```js
    // pointer areas
    this.touchArea = computePointerArea( this, arrowDirection, options.touchAreaXDilation, options.touchAreaYDilation );
    this.mouseArea = computePointerArea( this, arrowDirection, options.mouseAreaXDilation, options.mouseAreaYDilation );
```

**Comment by pixelzoom** [comment]
These options to CarouselButton all default to zero:

```js
      // Convenience options for dilating pointer areas such that they do not overlap with Carousel content.
      // See computePointerArea.
      touchAreaXDilation: 0,
      touchAreaYDilation: 0,
      mouseAreaXDilation: 0,
      mouseAreaYDilation: 0
```

When zero values are used, the problem occurs.  When non-zero values are used, there's no problem.  For example, if I comment out these option values in ComponentsScreenView, then I can cause the problem in the sun demo:

```js
  // vertical carousel
  const vCarousel = new Carousel( vItems, {
    orientation: 'vertical',
    separatorsVisible: true,
    // buttonTouchAreaXDilation: 5,
    // buttonTouchAreaYDilation: 15,
    // buttonMouseAreaXDilation: 2,
    // buttonMouseAreaYDilation: 7
  } );
```

**Comment by pixelzoom** [comment]
What's happening when the option values are 0 is that touchArea and mouseArea are set to null.  According to Node `setTouchArea`, this is supposed to result in "the default behavior".   This still seems to work OK for other UI components (e.g. Checkbox), but is broken for sun buttons.  For example, this change to ButtonsScreenView results in `aButton` becoming unresponsive to mouse events:

```diff
    const buttonA = new RectangularPushButton( {
      content: new Text( '--- A ---', { font: BUTTON_FONT } ),
      listener: () => console.log( 'buttonA fired' ),

      // demonstrate pointer areas, see https://github.com/phetsims/sun/issues/464
      touchAreaXDilation: 10,
      touchAreaYDilation: 10,
      mouseAreaXDilation: 5,
      mouseAreaYDilation: 5
    } );
+   buttonA.mouseArea = null;
```

**Comment by pixelzoom** [comment]
I'm stumped, no idea what change to sun buttons might have caused this.

@zepumph does anything come to mind?

**Comment by zepumph** [comment]
With this patch, I do not get pointer areas in the sun demo around the CarouselButton. I'll keep poking around.

Index: js/buttons/CarouselButton.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/buttons/CarouselButton.js	(revision d1fb82f3656d41298c6f0f440a537fbf59a30d4d)
+++ js/buttons/CarouselButton.js	(date 1603943089380)
@@ -86,8 +86,8 @@
     super( options );
 
     // pointer areas
-    this.touchArea = computePointerArea( this, arrowDirection, options.touchAreaXDilation, options.touchAreaYDilation );
-    this.mouseArea = computePointerArea( this, arrowDirection, options.mouseAreaXDilation, options.mouseAreaYDilation );
+    this.touchArea = null;
+    this.mouseArea = null;
   }
 }

**Comment by zepumph** [comment]
This patch fixes the problem, and I can use the button again.

```diff
Index: js/buttons/CarouselButton.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/buttons/CarouselButton.js	(revision d1fb82f3656d41298c6f0f440a537fbf59a30d4d)
+++ js/buttons/CarouselButton.js	(date 1603943308073)
@@ -85,9 +85,6 @@
 
     super( options );
 
-    // pointer areas
-    this.touchArea = computePointerArea( this, arrowDirection, options.touchAreaXDilation, options.touchAreaYDilation );
-    this.mouseArea = computePointerArea( this, arrowDirection, options.mouseAreaXDilation, options.mouseAreaYDilation );
   }
 }
 

```

It seems to be something about setting the touchArea to null, because setting the touch area to null in RectangularButton.js like:

```diff
Index: js/buttons/RectangularButton.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/buttons/RectangularButton.js	(revision d1fb82f3656d41298c6f0f440a537fbf59a30d4d)
+++ js/buttons/RectangularButton.js	(date 1603943409746)
@@ -92,12 +92,8 @@
     super( buttonModel, buttonBackground, interactionStateProperty, options );
 
     // Set pointer areas.
-    this.touchArea = buttonBackground.localBounds
-      .dilatedXY( options.touchAreaXDilation, options.touchAreaYDilation )
-      .shifted( options.touchAreaXShift, options.touchAreaYShift );
-    this.mouseArea = buttonBackground.localBounds
-      .dilatedXY( options.mouseAreaXDilation, options.mouseAreaYDilation )
-      .shifted( options.mouseAreaXShift, options.mouseAreaYShift );
+    this.touchArea = null;
+    this.mouseArea = null;
   }
 }
 

```

Breaks all the RectangularButtons:

![image](https://user-images.githubusercontent.com/6856943/97523456-3a8b7800-1957-11eb-8c04-1ac145b95cde.png)



@jonathanolson, I poked around Picker.js but couldn't figure out where `null` was handled as a case for `Node.mouseArea` or `Node.touchArea`. Can you please explain how `null` as a hit area value is recognized?

**Comment by jonathanolson** [comment]
Looks like the content under the buttons has pickable:false, so this is the expected Scenery behavior. Looks like it relies on the mouse/touch area (probably for performance?)

**Comment by zepumph** [comment]
Thanks @jonathanolson!

@pixelzoom, I think that the best way forward is to not null our the touch are, since the super type will have set the default one in the super call. How about this (untested):

```diff
Index: js/buttons/CarouselButton.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/buttons/CarouselButton.js	(revision d1fb82f3656d41298c6f0f440a537fbf59a30d4d)
+++ js/buttons/CarouselButton.js	(date 1603995370283)
@@ -86,8 +86,14 @@
     super( options );
 
     // pointer areas
-    this.touchArea = computePointerArea( this, arrowDirection, options.touchAreaXDilation, options.touchAreaYDilation );
-    this.mouseArea = computePointerArea( this, arrowDirection, options.mouseAreaXDilation, options.mouseAreaYDilation );
+    const touchArea = computePointerArea( this, arrowDirection, options.touchAreaXDilation, options.touchAreaYDilation );
+    if ( touchArea ) {
+      this.touchArea = touchArea;
+    }
+    const mouseArea = computePointerArea( this, arrowDirection, options.mouseAreaXDilation, options.mouseAreaYDilation );
+    if ( mouseArea ) {
+      this.mouseArea = mouseArea;
+    }
   }
 }
 

```

**Comment by pixelzoom** [comment]
Discussed in 10/29/2020 dev meeting. The problem is in ButtonNode. Both the button background and content are set to `pickable:false` "for performance":

```js
buttonBackground.fill = null;
...
alignBox = new AlignBox( options.content, {
  ...
  pickable: false
} );
```

When pointer areas are set to null, this causes the problem reported for this issue.

I'm skeptical that there's any significant performance improvement by setting `pickable: false` in this case, so I've removed them in the above commit.  We could probably set `pickable: false` directly on `options.content`, but that could cause problems if button content is reused elsewhere in the scenegraph.

@jonathanolson could you please review, and comment on whether there should be any use of `pickable: false` in ButtonNode?

**Comment by jonathanolson** [comment]
> @jonathanolson could you please review, and comment on whether there should be any use of pickable: false in ButtonNode?

> I'm skeptical that there's any significant performance improvement by setting pickable: false in this case

Button content can have complicated icons or shapes, which would in this case likely be hit-tested (and can be potentially non-trivial). I'd presumably want to measure performance impact, hear a good reason why things are different (I recall performance testing showing a benefit before), or have this handled somehow.

**Comment by pixelzoom** [comment]
@zepumph said:
> @pixelzoom, I think that the best way forward is to not null our the touch are, since the super type will have set the default one in the super call. How about this (untested):

If we wanted to do that, I think this patch is preferable:

```diff
Index: js/buttons/CarouselButton.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/buttons/CarouselButton.js	(revision afe36bc6806de13b36bccf5113e747ca0fa02d67)
+++ js/buttons/CarouselButton.js	(date 1603996274793)
@@ -104,7 +104,6 @@
  */
 function computePointerArea( button, arrowDirection, x, y ) {
   let pointerArea = null;
-  if ( x || y ) {
     switch( arrowDirection ) {
       case 'up':
         pointerArea = button.localBounds.dilatedXY( x, y / 2 ).shiftedY( -y / 2 );
@@ -121,7 +120,6 @@
       default:
         throw new Error( 'unsupported arrowDirection: ' + arrowDirection );
     }
-  }
   return pointerArea;
 }
 ```

But that wouldn't fix the root problem. sun buttons are (were) broken when setting `null` pointer areas, and `null` is a legitimate value.

**Comment by pixelzoom** [comment]
> Button content can have complicated icons or shapes, which would in this case likely be hit-tested (and can be potentially non-trivial). I'd presumably want to measure performance impact, hear a good reason why things are different (I recall performance testing showing a benefit before), or have this handled somehow.

OK. I'll revert to what was done before we started work on sun buttons, which is to set `options.content.pickable = false`.

**Comment by pixelzoom** [comment]
`options.content.pickable = false` has been restored, to address performance concerns.

Back to @jonathanolson for review.

**Comment by zepumph** [comment]
>If we wanted to do that, I think this patch is preferable. Designers (I think) would be happy to see pointer areas for CarouselButton, even if they had no dilation.

I'm confused, there is no reason to set pointer areas in CarouselButton in the case we are talking about, because RectangularButton will handle the default. That is why I decided to surround the entire setter in CarouselButton.

**Comment by pixelzoom** [comment]
CarouselButton has very different needs for pointer areas, as implemented in `computePointerArea`. Returning `null` was a design decision, not a coincidence.  The `*Shift` options to RectangleButton should generally be ignored, so RectangularButton's behavior of pointer areas is generally not correct.  If you feel strongly otherwise, then by all means make your change to CarouselButton.

**Comment by zepumph** [comment]
Sounds good to me! https://github.com/phetsims/sun/commit/061e6e5c197e5fe8c1007e677d30be634fcc39b9 seems like the right decision.

**Comment by pixelzoom** [comment]
@jonathanolson We need to wrap this up for RCs to move forward.  You expressed concerns about changes to pickable in https://github.com/phetsims/sun/issues/654#issuecomment-718941629.  I addressed them in https://github.com/phetsims/sun/issues/654#issuecomment-718946253.  Your review is needed with high priority.

**Comment by jonathanolson** [comment]
Looks good to me.
