### ISSUE TITLE
RoundButton and RectangularButton still have different APIs

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#657]
Though most of these two types were largely factored out into ButtonNode over in https://github.com/phetsims/sun/issues/643, there are still a couple of big differences between the two's apis. 

**1. The way in which the backgroundNode (a Circle or Rectangle) is computed.**

In RectangularButton, there is no way to specify the total width or height, you just pass in content, and then pass in margins that you would like the button to have. The background rectangle makes sure to account for the content dimensions and its associated margins. This can lead so some weird code to try to make sure that the output size of the button is as desired:

<details>

```js
class StarButton extends RectangularPushButton {

  /**
   * @param {Object} [options]
   */
  constructor( options ) {

    options = merge( {

      // Match the size of the star button to the refresh buttons, since they often appear together.
      // see https://github.com/phetsims/scenery-phet/issues/44
      xMargin: 8.134152255572697,
      baseColor: PhetColorScheme.BUTTON_YELLOW
    }, options );
```
</details>

In RoundButton, you specify a button radius through options. This is used to make the background circle, and in most cases, the content dimensions doesn't play into consideration at all. This means that it is a manual process size the content into the radius that you choose before passing the content to the button. 

@pixelzoom and I feel like both apis have their merits. Often you don't care about the size, and just want to make sure that there are appropriate margins around an icon. In other cases, perhaps like resetAllButton, it may be important to make a button with an exact size (by specifying a radius), so that it can be the same size as another button.

**2. RoundButton doesn't support margins at all**

Because of 1, and the fact that RoundButton runs on radius, its margins are a moot option. They don't actually work. For them to work, the content dimensions would need to be used to calculate the background circle.

@pixelzoom had a discussion about this because I ran into it while working on #655 and #649. In our opinion, supporting both ways to create buttons is the most robust. I will explain how we may implement this in RoundButton, and likely would want to make the same thing happen in RectangularButton:

* Support options.content + margin options as a way to calculate the button radius, then the margins will work when passed to ButtonNode's AlignBox.
* If options.radius is specified, scale the content down to support the desired margins within the specified background circle.
* Most buttons will probably want to use the first strategy, even though it doesn't exist yet. I see 61 usages of ` radius:` that could be looked at to make sure that they are being created in the best way possible. This would have to be done no matter what, because the current approach they are using doesn't account for margins, so after we add scaling, layout will likely change.

I am going to take a bit of a stab right now at what this may look like in RoundButton, but I don't plan on committing at this time. This is a sizeable amount of work, and I think I should touch base with @ariel-phet before making sun buttons more uniform in this manner.

**Comment by zepumph** [comment]
>but I don't plan on committing at this time.

Famous last words. . . it was only 2 hours. . . 


Anywho, I ended up adding scaling to RoundButton. The changes are pretty minimal, but the effects on any RoundButton in the project were large. I ended up writing code that threw an error if the scaling had any effect on the content, and then going to each spot and adding margin. I started in scenery-phet, so things weren't so bad. There were maybe 10 usages in sims to manually compute. 

Now a radius can be used, but it isn't required. Furthermore, margins are still respected if a button radius is provided. This is done by scaling down the content.

Next steps for this issue would be to support RectangularButton passing in a Dimension2 specifying exact dimensions of the button, but that may be for another issue. To me, the important thing here was allowing RoundButton to work with margins via ButtonNode's alignBox. That is now much better. 

I also added "button F" to the sun demo to demonstrate how margins can be used instead of a radius.

@pixelzoom, I understand that your time needs to move away from sun buttons right now, but can you take a look at least at https://github.com/phetsims/sun/commit/3483e0d164e04193194c42821f1c75b18ecdf624 to see what you think. Thanks!

**Comment by pixelzoom** [comment]
Thanks for the nice summary above.

A couple of clarifications:
> Because of 1, and the fact that RoundButton runs on radius, its margins are a moot option. They don't actually work. For them to work, the content dimensions would need to be used to calculate the background circle.

This is indeed the case with `xAlign: 'center'` and `yAlign: 'center'`. With other align values, the margins will be applied.

>  ... supporting both ways to create buttons is the most robust 

Something like this...

For RoundButtons:

```js
options = merge( {
  content: null, // {Node|null}
  radius: null, // {number|null}
  xMargin: 0,
  yMargin: 0,
  ...
}, options );

assert && assert( options.content || options.radius !== null, ... );

if ( options.radius === null ) {
   // size the button to fit the content and margins
   options.radius = Math.max( options.content.width + 2 * options.xMargin, options.content.height + 2 * options.yMargin );
}
else {
  // Scale options.content to fit in the button, accounting for margins.
  // Scale by wrapping options.content in another Node that is scaled, because client 
  // may have already scaled content, and/or content may be used elsewhere in the scenegraph.
}
```

For RectangularButtons:

```js
options = merge( {
  content: null, // {Node||null}
  size: null, // {Dimension2|null}
  xMargin: 0,
  yMargin: 0,
  ...
}, options );

assert && assert( options.content || options.radius !== null, ... );

if ( options.size === null ) {
   // size the button to fit the content and margins
   options.size = new Dimensions2( options.content.width + 2 * options.xMargin, options.content.height + 2 * options.yMargin );
}
else {
  // Scale options.content to fit in the button, accounting for margins.
  // Scale by wrapping options.content in another Node that is scaled, because client 
  // may have already scaled content, and/or content may be used elsewhere in the scenegraph.
}
```

**Comment by zepumph** [comment]
>Next steps for this issue would be to support RectangularButton passing in a Dimension2 specifying exact dimensions of the button,

That could potentially be quite simple, as @pixelzoom just demonstrated. This is because it wouldn't alter the current api, but just add to it. Once we figure out RoundButton and feel good about it, I bet we could just add the same thing to Rectangular button and an example or two in the sun demo and call it a day!

**Comment by zepumph** [comment]
>I also added "button F" to the sun demo to demonstrate how margins can be used instead of a radius.

For clarity I will include a screen capture. Note that even with alignment as "center", this still works:

![image](https://user-images.githubusercontent.com/6856943/97522338-66f1c500-1954-11eb-8c86-056c55c5aa8b.png)

**Comment by zepumph** [comment]
Oh! One particular thing I would like reviewed;

ResetAllButton and StepButton had automatic margins added to them based on the radius. These two, more than all others, had really finicky content that was set up without concern for margins (since RoundButton didn't support that when created).

Please make sure to review https://github.com/phetsims/scenery-phet/blob/1928025f0d14aebbe80656c8108e0107f6a9b21f/js/buttons/ResetAllButton.js#L69-L71 and https://github.com/phetsims/scenery-phet/blob/1928025f0d14aebbe80656c8108e0107f6a9b21f/js/buttons/StepButton.js#L57-L59. 

At the time it seemed like an appropriate way to handle this, but now I wonder if we shouldn't try to alter the icon to support working margins.

**Comment by pixelzoom** [comment]
Re ResetAllButton and StepButton... The assert in both cases should check for undefined, not falsey. E.g.:

```diff
-    assert && assert( !options.xMargin && !options.yMargin, 'resetAllButton sets margins' );
+    assert && assert( options.xMargin === undefined && options.yMargin === undefined, 'resetAllButton sets margins' );
```

Re RoundButton...  This looks good. And to convince myself that it was working correctly, I added examples to sun demo in  f2f0631.  See `roundButtonWithSize` and `roundButtonWithDerivedSize`:

<img width="145" alt="screenshot_634" src="https://user-images.githubusercontent.com/3046552/97648730-15f8d400-1a1b-11eb-97d5-50a917449742.png">

Now if we're going to make RoundButton and RectangularButton APIs the same, RectangularButton needs option `{Dimensions2} size`.

**Comment by zepumph** [comment]
I created https://github.com/phetsims/sun/issues/661, and I think we are ready to close this issue. Please reopen if there is more.
