### ISSUE TITLE
RoundButton doesn't account for lineWidth when setting pointer areas and focus highlight

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#660]
In RoundButton.js:

```js
    // Set pointer areas.
    this.touchArea = Shape.circle( options.touchAreaXShift, options.touchAreaYShift,
      buttonRadius + options.touchAreaDilation );
    this.mouseArea = Shape.circle( options.mouseAreaXShift, options.mouseAreaYShift,
      buttonRadius + options.mouseAreaDilation );

    // PDOM - focus highlight is circular for round buttons, with a little bit of padding
    // between button shape and inner edge of highlight
    this.focusHighlight = Shape.circle( 0, 0, buttonRadius + 5 );
```

Using `buttonRadius` for pointer areas and focus highlight does not account for button's stroke and lineWidth, so is not the actual radius.   For example, I made these changes to `buttonD` in sun ButtonsScreenView:

```diff
    const buttonD = new RoundPushButton( {
      content: new Text( '--- D ---', { font: BUTTON_FONT } ),
      listener: () => console.log( 'buttonD fired' ),
      baseColor: roundBaseColor,
+     radius: 50,
+     lineWidth: 20
    } );
```

... and the result is pointer areas and focus highlight that are _smaller_ than the button:

<img width="116" alt="screenshot_631" src="https://user-images.githubusercontent.com/3046552/97646862-733e5680-1a16-11eb-944b-b7f5548dd53f.png">

`buttonBackground.localBounds.width / 2` should be used instead of `buttonRadius`.

**Comment by pixelzoom** [comment]
In the above commit:

```js
    // Get this after calling super, so that buttonAppearanceStrategy has applied stroke.
     // This accounts for stroke + lineWidth when setting pointer areas and focus highlight.
     // See
     const buttonBackgroundRadius = buttonBackground.localBounds.width / 2;
```

And buttonD pointer areas and focus highlight now look correct:

<img width="118" alt="screenshot_629" src="https://user-images.githubusercontent.com/3046552/97646700-f14e2d80-1a15-11eb-9222-4a0f54e28506.png">

Assigning to @jessegreenberg to review, since he added focusHighlight and I'm less familiar with that feature.

**Comment by jessegreenberg** [comment]
This looks great, thanks. I see it working well in the example. Closing.
