### ISSUE TITLE
Add RectangularButton.size option

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#661]
From https://github.com/phetsims/sun/issues/657, basically this should follow the same pattern as with RoundButton in https://github.com/phetsims/sun/commit/3483e0d164e04193194c42821f1c75b18ecdf624.

This time we will do so with a `size {Dimension2}`. I should also add examples to sun buttons like https://github.com/phetsims/sun/commit/f2f0631d8757c5d0ae4c0dba3307c955a2f2781a

**Comment by zepumph** [comment]
I see `minWidth` and `maxWidth` that can be used to specify part of this feature. This doesn't scale down the content though, so I still think it makes sense to create a `size` that triggers the scaling down of the content.

**Comment by zepumph** [comment]
I added options.size above. It was generally smooth and easy. I found that people were hacking this feature by using `minWidth` and `minHeight` to get a button with no content. I added an assertion to try to make sure people use `size` instead. 

I then looked through all usages of `minHeight` on the project (most were for buttons), and found no places other than the sun demo where it was being used, but no content was being supplied. 

@pixelzoom please review, especially this assertion and change to the api:

`assert && assert( options.size instanceof Dimension2, 'button dimensions needed if no content is supplied.' );`

**Comment by pixelzoom** [comment]
Changes related to option `size` look good, including the assertion mentioned above.  

Should options `minWidth` and `minHeight` be deleted?  Or is it still useful to specific (for example) just a `minWidth` and let the height be taken care of based on the content?

**Comment by zepumph** [comment]
I'm not sure if it is useful, but it is currently available with not usages that I can see. Would you prefer removal, to simplify the API as much as possible, or do you think we should leave it, and add a button to the demo exercising the feature?

**Comment by pixelzoom** [comment]
I guess we can keep `minWidth` and `minHeight` for now.  I've added this doc:

```js
      // {number} If you want complete control of a button's dimensions, use options.size. If you want to specify
      // one dimensions while having the other dimension determined by content and margin, then use one of these
      // options.
      minWidth: HORIZONTAL_HIGHLIGHT_GRADIENT_LENGTH + SHADE_GRADIENT_LENGTH,
      minHeight: VERTICAL_HIGHLIGHT_GRADIENT_LENGTH + SHADE_GRADIENT_LENGTH,
```

If this looks OK, feel free to close.
