### ISSUE TITLE
Convert EnabledComponent from mixin to class

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#663]
From https://github.com/phetsims/scenery/issues/1100, @zepumph and I discussed that `EnabledComponent` only has 2 usages in our simulations, and in each case it is mixed into a type that extends `Object`.  This means that, at least at the moment, `EnabledComponent` would work as a `class` instead of a mixin.

Mixins are dynamically created types which should be used only when necessary.  They cannot be analyzed using static typing.  For instance, Webstorm reports that AmplitudeModulator is using an undefined attribute:

![image](https://user-images.githubusercontent.com/679486/97765041-45204b80-1ad6-11eb-81fd-1c15db8b08a5.png)

Similarly, we cannot use navigation or autocomplete.  These 3 problems would disappear if we convert `EnabledComponent` to a class.

Furthermore, using idiomatic strategies will make our code easier to read and understand by audiences not familiar with our mixin patterns.  Instead of having to call `this.initializeEnabledComponent( options );` and `EnabledComponent.mixInto( AmplitudeModulator );` at the right points, we can use the standard pattern of `class AmplitudeModulator extends EnabledComponent` and `super()`, which are well-established and built into the languge.

<details>

```diff
Index: js/AmplitudeModulator.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/AmplitudeModulator.js	(revision 4f70d3abb6e3c17119b0961e64e43beba0e9d5cd)
+++ js/AmplitudeModulator.js	(date 1604101093561)
@@ -20,13 +20,14 @@
 const DEFAULT_DEPTH = 0.9; // proportion
 const DEFAULT_WAVEFORM = 'sine'; // proportion
 
-class AmplitudeModulator {
+class AmplitudeModulator extends EnabledComponent {
 
   /**
    * @mixes EnabledComponent
    * @param {Object} [options]
    */
   constructor( options ) {
+    super( options );
 
     options = merge( {
 
@@ -43,9 +44,6 @@
 
     }, options );
 
-    // Initialize the mixin, which defines this.enabledProperty.
-    this.initializeEnabledComponent( options );
-
     // @public {NumberProperty}
     this.frequencyProperty = options.frequencyProperty || new NumberProperty( DEFAULT_FREQUENCY );
 
@@ -107,7 +105,7 @@
     };
     this.depthProperty.link( depthListener );
 
-    const waveformListener =  waveform => {
+    const waveformListener = waveform => {
       if ( lowFrequencyOscillator ) {
         lowFrequencyOscillator.type = waveform;
       }
@@ -157,7 +155,5 @@
   }
 }
 
-EnabledComponent.mixInto( AmplitudeModulator );
-
 tambo.register( 'AmplitudeModulator', AmplitudeModulator );
 export default AmplitudeModulator;
\ No newline at end of file
```

</details>

I should also comment that @zepumph indicated he was indifferent to whether EnabledComponent remained a mixin or transformed to a class.  To me it seems advantageous to be a class, so I decided to go for it.

**Comment by samreid** [comment]
I committed this, and tested in natural selection with studio and the reset all button enabledProperties.  It seems like it is working well.  It also reduced about 20 lines of code in EnabledComponent.js and eliminated one TODO (which referenced https://github.com/phetsims/sun/issues/638).

@zepumph can you please review?

**Comment by zepumph** [comment]
Looks great thanks.
