### ISSUE TITLE
pickable is likely not the way to disable sun components

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#666]
Almost all sun components (except for sun buttons), have been setting pickable:false on disabled components for quite some time (years?). @jonathanolson pointed out over in https://github.com/phetsims/scenery/issues/1112 that this is problematic.

Setting `pickable:false` results in behavior where disabled components can be clicked through, such that a draggable/pressable item behind the disabled component can be selected "through" the disabled component. The solution around this in sun Buttons is to manually address this directly on the listener, with `PressListener.canStartPress`. Should we stop setting pickable on other components?

Previous train of recent enabledProperty work (just the important ones, ordered by time):
#257 (create an EnabledNode mixin)
https://github.com/phetsims/scenery/issues/1100 (move EnabledNode to Node)
https://github.com/phetsims/scenery/issues/1112 (move the above hard coded listener logic into sun from scenery)

I don't think this is high priority, since the current behavior has been thoroughly tested/vetted through many sim publications. That said, the approach seems like an incorrect usage of pickable (in fact, I thought pickable meant something different until being corrected recently). 

Over to @ariel-phet to decide what to do about this.

**Comment by zepumph** [comment]
One other buggy behavior when using pickable. Hover state can be buggy, since enter/exit events won't keep the Pointer in check while disabled.

We want to make sure that this would work on a component with highlight behavior:
1. disable component
2. mouse over component
3. while over, reenable component. Highlight behavior should occur (like hover style).

**Comment by zepumph** [comment]
If we decide to remove pickable, we will need to re-integrate cursor behavior into the enabled listeners generally, since pickable:false used to do that for us (removed in https://github.com/phetsims/sun/commit/add7c947f1ff15b1f1519a63f02ace907440c141)

**Comment by zepumph** [comment]
After discussing the two issue cases above (press through, and hover state), @ariel-phet would like to add this to dev meeting. He is erroring towards not doing this work because things aren't that broken. I didn't feel really confident explaining the issue completely.  @ariel-phet feels like he needs to be convinced that this is a problem that is worth attention.

**Comment by zepumph** [comment]
Also noting that over in https://github.com/phetsims/scenery/issues/1105, it was brought up that toggling pickable between false and true blows away the default of `null`, and never brings that state back. Even still, it is likely that we will not change what is currently in master.

**Comment by chrisklus** [comment]
From 11/12/20 dev meeting:

`Node.interactive`, being handled over in https://github.com/phetsims/scenery/issues/1116, will be the way to handle this in the future.

**Comment by zepumph** [comment]
As of 2 seconds ago, we are using inputEnabled instead. see https://github.com/phetsims/sun/commit/1af3a31be1d4807550570e4a157c6f42d8e328cc. Closing (wahoo!)
