### ISSUE TITLE
[AccessibleValueHandler] add option to map value before setting Property value

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#669]
Over in https://github.com/phetsims/ratio-and-proportion/issues/175, we need a bit more control over the valueProperty being set by AccessibleValueHandler. We need to detect a case before setting the value. I think the best way to do this is to create a new option that is called before `constrainValue` is called. I thought about altering `constrainValue`, but since Slider.js supports that option, it would be best to keep the implementations consistent between Slider and AccessibleValueHandler.

**Comment by zepumph** [comment]
I renamed the PDOM value mapper and created `a11yMapValue` I tried to explain how one maps the Property value as it pertains to keyboard input, and the other is for mapping the value to a number to be displayed by assistive technology. This work was necessary for https://github.com/phetsims/ratio-and-proportion/issues/175, but it adds another option, and some complexity to AccessibleValueHandler. @jessegreenberg please review.

**Comment by zepumph** [comment]
Please also note https://github.com/phetsims/sun/commit/278bd57e33ca0bf57ed770e8eafb4b5e6a678ee2 while reviewing.

**Comment by zepumph** [comment]
While working on https://github.com/phetsims/ratio-and-proportion/issues/175, I have asked myself the following question three times:

"Why have this "map" function? Why not just use constrain value?" 

I'll answer it again explicitly here for the record, even though it is reiterating from the original comment in this issue. While the placement in AccessibleValueHandler makes me think that it could be interchangable, constrainValue is an option in Slider, so it is important to keep the same function signature for that function. this new "a11yMapValue` function has the flexibility of parameters we need to pass for particular a11y cases (like shiftKey).

**Comment by jessegreenberg** [comment]
Changes look good, and see the change at 278bd57e33ca0bf57ed770e8eafb4b5e6a678ee2. 

I am curious though if this could have been handled by the `roundToStepSize` option. I reviewed https://github.com/phetsims/ratio-and-proportion/issues/175 and it seems similar to the behavior in ohms-law, where you can drag the sliders outside of the keyboard step intervals with a mouse, but next alternative input will snap the value to the nearest interval of keyboard step. @zepumph can you comment?

**Comment by jessegreenberg** [comment]
Also, `setMapValueFunction` is unused should that be removed now?

**Comment by zepumph** [comment]
Yeah good idea. Let's simplify the API as we can. No need to add mutation until there is a good reason to.

**Comment by zepumph** [comment]
roundToStepSize is not quite enough functionality, because for Ratio and Proportion we needed to also support snapping directly to a value in between snaps that would create the "in proportion" state. That was important for usability and modality equity. 

Anything else here?

**Comment by jessegreenberg** [comment]
OK, thanks for clarifying, understood. Closing.
