### ISSUE TITLE
We need a way to get the width of the carousel (not including the dots)

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#670]
In https://github.com/phetsims/circuit-construction-kit-common/issues/618 it was requested to match the UI components to the carousel width (not including the dots).

**Comment by samreid** [comment]
I added a public, read-only accessor for the dimensions so they can be used for layout, and I'm using that in CCK.  @pixelzoom can you please review?

**Comment by pixelzoom** [comment]
I'm guessing that yor carousel must be vertical, and that you really want an API that works for width or height.   And it looks like adding `this.backgroundWidth` and `this.backgroundHeight` should give you that.  If I'm missing something, please clarify and assign to me again.

**Comment by samreid** [comment]
You're not missing anything, I suspect this issue can be closed.   Please reopen if there's more to discuss or review.
