### ISSUE TITLE
dynamically change items that are shown in ComboBoxListBox

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#671]
Fourier has a "Math Form" combo box.  The items to be shown in the listbox depend on the value of another Property (the domain: space, time, or space and time).  So I need to be able to dynamically change the items that are shown in the listbox.   

This feature is already available via PhET-iO (by setting `visibleProperty` of listbox items), but there is no programming API.  My plan is to add this method to ComboBox and ComboBoxListBox:

```js
  /**
   * Sets the visibility of listbox items that correspond to a value. If the selected item has this value, it's your
   * responsibility to change the Property value to something else. Otherwise the combo box button will 
   * continue to display this value.
   * @param {*} value - the value associated with the item
   * @param {boolean} visible
   * @public
   */
  setItemVisible( value, visible )
```

**Comment by pixelzoom** [comment]
Changes in the above commits:

* Added `setItemVisible` and `getItemVisible`
* Added an assertion verifying that items have unique values. This was an important assumption for the implementation of both of these new methods, and the developer consensus on Slack was that values should be unique.

@ariel-phet please assign to a reviewer.

**Comment by samreid** [comment]
I reviewed the changes and tested by removing items in Molarity, to see if it coordinated with PhET-iO visibility in studio, and everything worked out OK.  My main questions were:

* There is a bit of a mismatch because you pass an array of ComboBoxItem to the constructor, but setItemVisible takes a ComboBoxItem.value (not a ComboBoxItem).  I'm not sure whether I would change anything about this, but it was a little confusing during my trial run in Molarity.  Thought I'd bring it up.
* Normally I'd use `isItemVisible` instead of `getItemVisible`, but since it appears next to a setter, it seems nicer to use `get` and `set`.  I don't recommend any changes here, but I wanted to make sure were were thinking along the same lines.

Everything else looks great, nice work.

**Comment by pixelzoom** [comment]
> There is a bit of a mismatch because you pass an array of ComboBoxItem to the constructor, but setItemVisible takes a ComboBoxItem.value (not a ComboBoxItem).

In my experience, you don't keep references to the ComboBoxItem instances, you have references to their values. In Fourier it's not even currently possible to get references to the ComboBoxItems, because they are generated from a higher-level description (see FMWComboBox).

> Normally I'd use `isItemVisible` instead of `getItemVisible`, but since it appears next to a setter, it seems nicer to use `get` and `set`.

In the above commit, I've renamed to `isItemVisible`, for a better match with the Node API.

> UPDATE: One more question. Do we need to support a more powerful equality check? ...

I don't think so.  I think reference equality is most appropriate for combo box items.

> UPDATE: Another question: Is `new Set( items.map( item => item.value ) ).length preferable` to `_.uniqBy( items, item => item.value ).length` for the equality check? It seems a little clearer to me and doesn't require knowing how uniqBy works.

No, for multiple reasons:  Regardless of the assertion expression, the assertion message (`'items must have unique values'`) makes it crystal clear what's going on here.  PhET developers should be familiar with the lodash API, and the documentation is clear and easily accessed. I'm more familiar with `_.uniqBy` than `Set`.  `_.uniqBy` is used elsewhere, in PhET-iO code specifically.   And `new Set` is subjectively just as complicated (or maybe even more complicated, since it creates an object instance.). If you still feel strongly that it should be changed, let's discuss.

Back to @samreid. Feel free to close if there are no further changes needed.

**Comment by samreid** [comment]
Sounds great, thanks!  Closing.
