### ISSUE TITLE
Carousel foregroundNode is blocking input events

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#672]
@jbphet said:

> Carousels appear to be broken again.  In number-line-operations and expression-exchange, no interaction is possible in with the contents in the carousel or the carousel buttons.  The Sun demo appears to be fine.  I'll investigate, but any insights would be greatly appreciated.  The previous issue that might be related is https://github.com/phetsims/sun/issues/654.

**Comment by samreid** [comment]
I committed a fix that makes the carousel foreground non-pickable, and confirmed after this change Function Builder is usable again.  However, this issue (or a new, related issue) should remain open until we figure out how/when this broke in the first place, and see if that problem may impact other parts of the project.  @jonathanolson can you please advise?

**Comment by jbphet** [comment]
Thanks @samreid - I just pulled and this does appear to fix the problem that I was having in number-line-operations.

**Comment by jonathanolson** [comment]
Is there a good way I can reproduce this? Perhaps because the foreground has Paintable's default `fillPickable: true`, it was catching events? `strokePickable: true, fillPickable: false` almost sounds like a good strategy.

**Comment by samreid** [comment]
I was able to reproduce the problem just now by reverting https://github.com/phetsims/sun/commit/fe13dfe1ea3f3ae0721fa5ec1100cce08efa1464 then testing function builder--nothing can be dragged out of the carousel on the 1st screen.

**Comment by jonathanolson** [comment]
Confirmed. Since the foreground is in front of the content, AND the background covers the same area, presumably we prefer the foreground to not be pickable.

In the previous setup, it seems like it would block input. I'm not particularly concerned about why we entered a buggy state, but it seems good now. Thoughts?

**Comment by samreid** [comment]
It would be more satisfying to understand why we entered a buggy state, so that we could extrapolate and see if it may happen elsewhere.  But perhaps since we have no leads, its sufficient to wait until we detect another case and go from there.  The symptom seems pretty easy to detect.  Closing.

**Comment by jbphet** [comment]
Follow up note: There has been some work on pickability in input events over the last few days, and I checked in with @jonathanolson as to whether the code that was added to `Carousel` to set the foreground's pickability should stay or go.  He said (over Slack): "It should definitely be left, unless you want the foreground to intercept events.  I can clarify more at dev meeting (hopefully we'll be talking about that input issue)."

**Comment by zepumph** [comment]
Related to https://github.com/phetsims/sun/issues/676
