### ISSUE TITLE
ensure that ComboBox listbox selection occurs during fuzzing

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#677]
I've noticed when fuzz testing Fourier that combo box listbox is rarely exercised.  The listbox is popped up, but then immediately dismissed when fuzzing "clicks" elsewhere.   The first screen (Discrete) has 3 combo boxes. 2 of them are never exercised. The one that is exercised repeatedly selects the first item in the listbox.  I'd estimate something like 85% of the code is not being exercised. Consequently, I have little confidence that Fourier is being sufficiently exercised by CT fuzzing.

Various developers participated in discussing this on Slack developer channel.  @zepumph noted that the listbox is not getting exercised because clicking outside of it causes the listbox to close. So the solution that we came up with is to ignore the listener that handles "click outside to dismiss" when fuzzing is enabled.   That listener is in ComboBox.js:

```js
    // @private Clicking anywhere other than the button or list box will hide the list box.
    this.clickToDismissListener = {
      down: event => {
        // Ignore if we click over the button, since the button will handle hiding the list.
        if ( !( event.trail.containsNode( this.button ) || event.trail.containsNode( this.listBox ) ) ) {
          this.hideListBox();
        }
      }
    };
```

**Comment by pixelzoom** [comment]
Also on Slack, we decided that checking whether "fuzzing is enabled" should be handled via a new global function, added to initialize-globals.js.  It should be a function so that associated query parameters (eg `phet.chipper.queryParameters.fuzz`) can be changed in the console while the sim is running.

**Comment by pixelzoom** [comment]
Implemented in the above commits, and used in a couple of obvious places. 

Tested to verify that fuzzing can be dynamically turned on/off via the console:

```
> phet.chipper.queryParameters.fuzz = true
true
> phet.chipper.isFuzzEnabled()
true
> phet.chipper.queryParameters.fuzz = false
false
> phet.chipper.isFuzzEnabled()
false
```

**Comment by pixelzoom** [comment]
I noticed that PhetMenu was statically computing whether fuzzing is enabled:

```js
const fuzzes = phet.chipper.queryParameters.fuzz ||
               phet.chipper.queryParameters.fuzzMouse ||
               phet.chipper.queryParameters.fuzzTouch ||
               phet.chipper.queryParameters.fuzzBoard;
```

... so would not work with changes to query parameters via the console.  There were 6 uses of fuzzes in PhetMenu (5 in menu item callbacks), and I changed them to phet.chipper.isFuzzEnabled() in the above commit.

**Comment by pixelzoom** [comment]
@samreid volunteered to review. Thanks!

**Comment by pixelzoom** [comment]
In Slack, @zepumph pointed out that the approach used in ComboBox could be applied in a few other places. This issue is not going to address those proactively.  

> There seems to be a reasonable number of similar cases that we may just shoot for expanding the manual approach. . .
> <img width="933" alt="screenshot_829" src="https://user-images.githubusercontent.com/3046552/105425925-7311b980-5c07-11eb-9a61-10b5e7c09e23.png">

**Comment by samreid** [comment]
I tested fuzzing in Fourier with and without the ComboBox change, and the change looks good.  I reviewed the code and everything looks good.  I just had a few questions, and I'll open a side issue regarding the prior comment.

Should this be marked as `@public`, or is that obvious from context?

```js
    /**
     * Determines whether any type of fuzzing is enabled. This is a function so that the associated query parameters
     * can be changed from the console while the sim is running. See https://github.com/phetsims/sun/issues/677.
     * @returns {boolean}
     */
    window.phet.chipper.isFuzzEnabled = () =>
```

Some commits use `phet.chipper` whereas some prefix with `window.phet.chipper`.  What is the semantic difference?  Which should be prefer, and should we be consistent?

**Comment by pixelzoom** [comment]
> Should this be marked as @public, or is that obvious from context?

I don't see any other globals in initialize-globals.js with visibility annotations. And a private global makes no sense. I guess you could have a global that's intended to be used only in specific places, but again there's no precedent for that.  So I don't think a visibiltiy annotation is needed here. 

> Some commits use phet.chipper whereas some prefix with window.phet.chipper. What is the semantic difference? Which should be prefer, and should we be consistent?

I noticed that, for example:

`window.phet.chipper.brand = window.phet.chipper.brand || phet.chipper.queryParameters.brand || 'adapted-from-phet';`

I try to follow the style of the code that I'm working in. It looked to me like `window.phet` is used in the majority of cases in this file, and I figured it doesn't hurt to fully qualify. So I went with `window.phet`.  If you think there should be consistency, that's a new issue, not this issue.

**Comment by pixelzoom** [comment]
> Some commits use phet.chipper whereas some prefix with window.phet.chipper. What is the semantic difference? Which should be prefer, and should we be consistent?

Lots of subtleties here, another example of JavaScript taking something simple and making it unneessarily complicated. Demonstration by examples:

`window` is optional for defining and referencing globals:

```
> color = 'red'
> color
"red"
> window.color
"red"

> window.age = 30
30
> window.age
30
> age
30
```

`var` is automatically added to the global object -- `window` in the browser, `globals` in Node.js:

```
> var age = 40
undefined
> age
40
> window.age
40
```

`const` and `let` are _not_ added to the global object. They will shadow.  So using `window` is important if you're in a situation where a global might be shadowed. 

```
> const age = 10
undefined
> age
10
> window.age
40
```

**Comment by samreid** [comment]
Thanks, I think this issue can be closed.  Feel free to reopen or open a side issue at your discretion.
