### ISSUE TITLE
AccordionBox({stroke:null}) fails

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#678]
Discovered during https://github.com/phetsims/sun/issues/676, if you pass `stroke: null` to AccordionBox, you get this error:

```
AccordionBox.js:398 Uncaught TypeError: Cannot set property 'rectWidth' of undefined
    at AverageSpeedAccordionBox.layout (AccordionBox.js:398)
    at new AccordionBox (AccordionBox.js:320)
    at new AverageSpeedAccordionBox (AverageSpeedAccordionBox.js:109)
    at new EnergyScreenView (EnergyScreenView.js:43)
    at EnergyScreen.createView (EnergyScreen.js:26)
    at EnergyScreen.initializeView (Screen.js:252)
    at Array.<anonymous> (Sim.js:884)
    at Sim.js:892
```

Assigning to @jbphet and @pixelzoom who are listed as authors in AccordionBox.

**Comment by pixelzoom** [comment]
@samreid Please clarify. Do you have a use case where you want to be able to set `stroke: null`.  Or is it sufficient to add an assertion that required `stroke` to be non-null.

**Comment by samreid** [comment]
I don't have a use case that requires a `null`-stroked Accordion box. But the options look like so:

```js
      // box
      stroke: 'black',
```

and there is no indication that null is disallowed.  I don't have a preference about whether we add support for `null` or add an assertion that it is non-null.

**Comment by pixelzoom** [comment]
Fixed in the above commit, AccordionBox now supported `stroke: null`.

`this.expandedBoxOutline` and `this.collapsedBoxOutline` are created conditionally, if `options.stroke` is truthy.  So in `layout`, they should be updated only if they exist.

@samreid please review.

**Comment by samreid** [comment]
I reviewed the commit and tested with null in build an atom, everything seems nice!  Closing.
