### ISSUE TITLE
The fuzz-focusing solution in ComboBox may apply elsewhere

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#679]
From https://github.com/phetsims/sun/issues/677, @pixelzoom said:

> In Slack, @zepumph pointed out that the approach used in ComboBox could be applied in a few other places. This issue is not going to address those proactively.
>
>> There seems to be a reasonable number of similar cases that we may just shoot for expanding the manual approach. . .
>> <img width="933" alt="screenshot_829" src="https://user-images.githubusercontent.com/3046552/105425925-7311b980-5c07-11eb-9a61-10b5e7c09e23.png">

@pixelzoom or @zepumph can you recommend an initial priority for this issue?

**Comment by pixelzoom** [comment]
The additional cases involve sim-specific code:

area-model-common (GenericLayoutSelectionNode)
build-a-molecule (BAMScreenView)
cck-common (CircuitElementNode, VertexNode)
energy-skate-park (ControlPointUI)

I would assign to the responsible devs, let them evaluate/discuss to see if there's anything "common" to be done, then address those sims. 

Longterm, I think this is something that should be considered in the design and implementation of popups.

**Comment by pixelzoom** [comment]
@samreid did you intend to assign to responsible sim devs?  If so, none of these sims are mine, and @jessegreenberg is responsible for ESP.

**Comment by samreid** [comment]
Thanks, I'm not sure why I assigned you--probably an accident.  Thanks for fixing it.

**Comment by samreid** [comment]
In the commit, I short circuit the click to dismiss listeners for the CircuitElementNode and VertexNode.  I also want fuzzing to exercise the click to dismiss listeners some of the time, so I put it at 1% frequency.  @pixelzoom can you please review this part?

**Comment by pixelzoom** [comment]
CircuitElementNode and VertexNode changes look reasonable, though I'm not a fan of function that have multiple return points.

**Comment by pixelzoom** [comment]
> I also want fuzzing to exercise the click to dismiss listeners some of the time, so I put it at 1% frequency.

This seemed like a good thing to incorporate into ComboBox, so I did so in the above commit.  Rather than 1% frequency, I used 25%, and it still seems to be resulting in good coverage in Fourier.  @samreid does this seem reasonable?

**Comment by pixelzoom** [comment]
Oops, my logic in ComboBox was wrong -- I was actually exercising clickToDismissListener 75% of the time. Fixed in the above commit.

**Comment by pixelzoom** [comment]
> I also want fuzzing to exercise the click to dismiss listeners some of the time, so I put it at 1% frequency.

This seemed like a good thing to incorporate into ComboBox, so I did so in the above commit.  Rather than 1% frequency, I used 25%, and it still seems to be resulting in good coverage in Fourier.  @samreid does this seem reasonable? 

EDIT: Oops, my logic in ComboBox was wrong -- I was actually exercising clickToDismissListener 75% of the time. Fixed above.

**Comment by samreid** [comment]
I went with a small percent by estimating the fraction of area of the clickable regions compared to the screen size. That being said, I tested Fourier with the commits, and I did see the combo boxes exercised a good amount.

For the record, here is my comment from https://github.com/phetsims/joist/issues/685#issuecomment-767832937

> Thanks for fixing this--I mistakenly used `phet.dot.dotRandom` as an analogy with `phet.joist.random`, but should have used the import. My mistake was copied into ComboBox as part of https://github.com/phetsims/sun/issues/679.  Thanks again for the correction.

Also, during review I found a serious bug that should block publication of any sim with a ComboBox. Marking blocks publication and notifying slack.

**Comment by samreid** [comment]
I wrote on Slack:

> I have to step out for a bit, but anyone can change `if ( !phet.chipper.isFuzzEnabled() && dotRandom.nextDouble() < 0.25 ) {` to `if ( !phet.chipper.isFuzzEnabled() ) {` to temporarily unblock publication.  We should fix the boolean expression for the long term though.

**Comment by zepumph** [comment]
The above made the click to dismiss listener fire every time for me when fuzzing was not enabled. I think this can unblock.

**Comment by samreid** [comment]
That looks good to me, thanks @zepumph.

**Comment by jonathanolson** [comment]
If the BAM reference is about `phet.joist.display.addInputListener( this.clickToDismissListener );`, it seems like those low-chance things happen all the time with fuzzing, and that if we want better coverage we should do something more precise (like playing back recorded sim sessions, etc.)

I'm not concerned about changing things in that sim.

**Comment by jessegreenberg** [comment]
I tried something like this out in energy-skate-park, but it didn't work as well. It is important for the behavior of the sim that the `clickToDismissListener` is called unless input is on the dismissable UI components, so preventing it from dismissing at the right time put the sim in a buggy state. We might be able to support this by making other changes to the sim/listener, but more substantial changes don't feel worthwhile to me at this time.

Reassigning to @samreid to review comments.

**Comment by samreid** [comment]
Would you like to share your patch?  It seems like Energy Skate Park is similar to CCK, where sometimes you want to exercise the buttons for the component and sometimes want to allow the fuzzer to click away.  I solved this by adding some randomness, so it could only click away sometimes--increasing the odds that it clicked one of the popup buttons.

**Comment by jessegreenberg** [comment]
Sure, I tried something similar to https://github.com/phetsims/circuit-construction-kit-common/commit/a1a84ae9ad92f11752ff57c19fde92afcd56e71f, 


```patch
Index: js/common/view/ControlPointUI.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/ControlPointUI.js	(revision de18ba9771162cfce6bf0bece84a014a9e723d74)
+++ js/common/view/ControlPointUI.js	(date 1611705416451)
@@ -6,6 +6,7 @@
  * @author Sam Reid (PhET Interactive Simulations)
  */
 
+import dotRandom from '../../../../dot/js/dotRandom.js';
 import LinearFunction from '../../../../dot/js/LinearFunction.js';
 import Vector2 from '../../../../dot/js/Vector2.js';
 import Node from '../../../../scenery/js/nodes/Node.js';
@@ -38,6 +39,12 @@
     // listener for 'click outside to dismiss'
     this.clickToDismissListener = {
       down: () => {
+
+        // if fuzzing, increase the chances increase that input reaches one of the buttons
+        if ( phet.chipper.isFuzzEnabled() && dotRandom.nextDouble() < 0.99 ) {
+          return;
+        }
+
         if ( enableClickToDismissListener ) {
           if ( _.indexOf( phet.joist.display.getInputListeners(), this.clickToDismissListener ) !== -1 ) {
             phet.joist.display.removeInputListener( this.clickToDismissListener );

```

If the ControlPointUI is not dismissed but fuzzing happens to delete a Track or its control points, it might try to split or remove a ControlPoint that has already been removed. Maybe we should remove the ControlPointUI more aggressively when a track or control point is disposed, in addition to the dismiss listener.

**Comment by samreid** [comment]
Thanks for clarifying on the problem--I'm not convinced it is worth the additional effort to try to increase fuzzing coverage for this case.

If you agree, feel free to close this issue.

**Comment by jessegreenberg** [comment]
OK sounds good, that was my thinking as well. Closing.
