### ISSUE TITLE
expose DragListeners for Slider thumb and track

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#680]
For https://github.com/phetsims/fourier-making-waves/issues/31, we need to know the state of the DragListeners associated with a Slider's thumb and track -- specifically their `isHighlightedProperty` value.   Slider adds the DragListener to the thumb, SliderThumb adds its own DragListener. These listeners are currently not part of the public APIs.

@jonathanolson and I also considered added in `isHighlightedProperty` to Slider, derived from `isHighlightedProperty` of the thumb and track DragListeners.   But we suspect that there be a need to access other DragListener Properties in the future, so exposing them seems more general and future-proof.

**Comment by pixelzoom** [comment]
Done in the above commit.  @jonathanolson would you mind doing a quick review, since you and I discussed this?

**Comment by jonathanolson** [comment]
Looks great to me! Thanks.
