### ISSUE TITLE
Eliminate cacheDemos

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#692]
From https://github.com/phetsims/sun/issues/386 and discussion on slack, we would like to eliminate `cacheDemos`.

@samreid said:

> It seems cacheDemos is always true, do we need to keep it around for some reason?

@pixelzoom replied:

> Probably don’t need it.  If we did need it, it should probably be specified per demo, in case we had some demo that was a memory hog and wanted to reclaim memory when done with it.  But I realize that developers today tend to ignore resource (CPU, memory) usage until it becomes a problem.
> So sure, dump it.

**Comment by pixelzoom** [comment]
> It seems cacheDemos is always true

That's not the case.  It defaults to `false` in DemosScreenView.js, and I see no overrides.

**Comment by samreid** [comment]
Good point, thanks!  I was misled by a change in my working copy.  Closing for now.
