### ISSUE TITLE
Opening a modal popup should interrupt other user interactions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#700]
Opening a modal dialog does not currently interrupt other user interactions. For example, with multitouch, I can be dragging a slider, open a modal dialog, and continue dragging the slider.  And it does not seem like this should be the responsibility of the client.

A modal dialog is (by definition) supposed to prevent the user from interacting with the reset of the application until the dialog is closed.

**Comment by pixelzoom** [comment]
Dialog extends Popupable( Panel ).  Popupable calls phet.joist.sim.showPopup.   So Sim `showPopup` is where this should be handled.

**Comment by pixelzoom** [comment]
The first thing I did (in the above commit) was to clean up Sim `showPopup` and `hidePopup`.  Specifically, I renamed parameter `node` to `popup`, and improved the overall documentation.

**Comment by pixelzoom** [comment]
I added `this.rootNode.interruptSubtreeInput` in the above commit, and that seems to have the desired effect.  I'm not certain, but I probably also could have called `this.display.interruptInput`. 

@jonathanolson please review, feel free to change if there's a better way.  High priority, since this is a change to Sim.js.

**Comment by jonathanolson** [comment]
Looks great to me, and looks like the right approach. Thanks!
