### ISSUE TITLE
NumberSpinner support for "step" options

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#704]
For Fourier, the "step size" for NumberSpinner is specified by @arouinfar in https://github.com/phetsims/fourier-making-waves/issues/53#issuecomment-846284868:

> NumberSpinners:
> 
> * Bigger step (page up/down or fn up/down): 2
>
> I don't know if NumberSpinner has support for a bigger step like NumberPicker. If it does, great. If not, I'm fine with deferring until we get to a sim with a NumberSpinner with a larger range.

I tried passing there options to NumberSpinner:

```js
      // pdom
      keyboardStep: 1,
      pageKeyboardStep: 2
```

... and received this assertion failure:

> assert.js:25 Uncaught Error: Assertion failed: keyboardStep supported by arrow buttons, do not pass value to NumberSpinner
    at window.assertions.assertFunction (assert.js:25)
    at new NumberSpinner (NumberSpinner.js:238)
    at new HarmonicsSpinner (HarmonicsSpinner.js:48)

Here's the relevant code in NumberSpinner.js:

```js
    // pdom - initialize accessibility features
    assert && assert( !options.keyboardStep, 'keyboardStep supported by arrow buttons, do not pass value to NumberSpinner' );
    assert && assert( !options.shiftKeyboardStep, 'shiftKeyboardStep handled by arrow buttons' );
    options.keyboardStep = 0;
    options.shiftKeyboardStep = 0;
```

Several issues:

- [x] The error messages are not helpful, a little confusing even. 
- [x] Why are these options set to zero? Why are any default needed (or desirable) if the arrow buttons are handling this?
- [ ] Why is `pageKeyboardStep` allowed? There is no assertion. The options certainly doesn't work as expected. 
- [ ] What is the expected behavior with Page? It currently moves between the 2 arrow buttons. 
- [x] Why are step options supported for NumberPicker (another kind of spinner), but not for NumberSpinner?  Shouldn't similar UI components have similar APIs? 

@arouinfar has indicated that `pageKeyboardStep` is optional for Fourier, so not high priority. But it would be good to address this issue before it propagates to too many sims.

**Comment by pixelzoom** [comment]
We are not going to use this feature for Fourier.

**Comment by jessegreenberg** [comment]
I tried to clarify some of this by improving the documentation in https://github.com/phetsims/sun/commit/4f8c4f4258f9d98e5ff04400fcc815b9466bf5b2. @pixelzoom can you please review, does this answer questions?

> Why is pageKeyboardStep allowed? There is no assertion. The options certainly doesn't work as expected.
 What is the expected behavior with Page? It currently moves between the 2 arrow buttons.

`pageKeyboardStep` is allowed for NumberSpinner and it is working as I would expect. I just tried setting `pageKeyboardStep: 5` in HarmonicsSpinner of fourier-making-waves and the value changes by 5 when using the page modifier with arrow keys.

**Comment by pixelzoom** [comment]
Thanks @jessegreenberg, the improved documentation is helpful. It tells me that the intent is to have the ArrowButtons handle step size. 

But I'm still not clear on:

* How do I set `keyboardStep` and  `shiftKeyboardStep` for the ArrowButtons? There's no API to pass these options to its ArrowButtons. Shouldn't ArrowButton options be combined into `options.arrowButtonOptions`?
* Why isn't `pageKeyboardStep` also handled by the ArrowButtons? It's really confusing that some of the "step size" API is handled one way, some of it another way. 
* Why can't you have the same API as NumberPicker, and pass the step options to the ArrowButtons?  Or why isn't NumberPicker handled like NumberSpinner, delegating step size to its arrows?  Long-term, spinner implementation should be unified, see https://github.com/phetsims/sun/issues/436.  Having different "step size" APIs here is going to make that more difficult.

**Comment by jessegreenberg** [comment]
This can be closed, the `pageKeyboardStep` is handled like `keyboardStep` and `shiftKeyboardStep` now.  And the API for NumberSpinner and NumberPicker is the same for alt input.
