### ISSUE TITLE
NumberSpinner dispose does not clean up tandems for subcomponents.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#710]
As noted for NumberSpinner in https://github.com/phetsims/sun/issues/709#issuecomment-874352963:

>  It creates tandems for subcomponents (`numberDisplay`, `incrementButton`, `decrementButton`), but fails to clean those up in `disposeNumberDisplay`.

**Comment by pixelzoom** [comment]
It looks like this problem was introduced in https://github.com/phetsims/sun/commit/71bab21626297f898ff318e2463ea571bd620869 bby @samreid, and https://github.com/phetsims/sun/commit/3a6227ccefd59ae1b6dfca8493a01d06176d6f95 by @pixelzoom.

I'll take care of it, then ask @samreid to review.

**Comment by pixelzoom** [comment]
Note to self, add something like this to `disposeNumberSpinner`:

```js
      // dispose of subcomponents
      numberDisplay.dispose();
      incrementButton.dispose();
      decrementButton.dispose();
```

**Comment by pixelzoom** [comment]
Fixed in the above commit, tested in a few sims that use NumberSpinner (including Fourier).

Over to @samreid for review.

**Comment by samreid** [comment]
I reviewed the commit and it seems good.  I confirmed there are no other `createTandem` children that require disposal. @pixelzoom can this issue be closed?
