### ISSUE TITLE
Add pointer-area options to Checkbox.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#716]
For https://github.com/phetsims/fourier-making-waves/issues/165 code review, @jonathanolson had this REVIEW comment in FMWCheckbox:

```js
class FMWCheckbox extends Checkbox {
...
      // pointer area dilation REVIEW: Is this dilation not desired in CHECKBOX_OPTIONS?
      touchAreaXDilation: 6,
      touchAreaYDilation: 6,
      mouseAreaXDilation: 1,
      mouseAreaYDilation: 1
    }, options );
```

I guess I was trying to avoid Checkbox.  But yes, these options would be generally useful in Checkbox.  And the lack of these option in Checkbox is the only reason that FMWCheckbox exists.  So I'll bit the proverbial bullet and add these options to Checkbox.

**Comment by pixelzoom** [comment]
Done in the above commits, and used in Fourier.   I chose to set `touchArea` and `mouseArea` even if the option values are zero, because it simplifies the implementation, and (in my experience) designers/QA like to see the pointer areas regardless of whether they've been modified. 

@jonathanolson please review with high priority.

**Comment by jonathanolson** [comment]
Looks good to me, thanks!
