### ISSUE TITLE
Dialogs should focus the close button by default when shown

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/sun#719]
From https://github.com/phetsims/fourier-making-waves/issues/194. Focus behavior when opening a dialog is inconsistent because you currently need to call `focusCloseButton` explicitly after calling `show()`.

This is because we used to only focus the button when the dialog was opened from alternative input. Calling `focus` would immediately show the focus highlight and we did not want to do that for mouse and touch input. The general pattern was
```js
if ( button.isPDOMClicking() ) {
  dialog.show();
  dialog.focusCloseButton();
}
```

That is not necessary anymore since highlights have been improved to only be shown when the sim receives some form of alternative input.

Instead of a proliferation of `focusCloseButton` calls, lets make focusing the close button the default behavior for Dialog.

**Comment by jessegreenberg** [comment]
This was done in the above commit. In some spot checking I that Dialogs being opened from the PhET menu had focus going to the second interactive element. This is because of `handleFocusCallback` of MenuItem. After https://github.com/phetsims/sun/commit/214150ea6ba6b2b5975db9c35553b65c834a5097 this default behavior isn't necessary and it is an improvement to have this done in Dialog. 

This was fixed in https://github.com/phetsims/sun/commit/3440aab18041d6f1b3e3d0b84122649f4da2ff6a, which also gets rid of  a usage of `getNextFocusable` and `getGlobal`.

@zepumph can you please review this so far? If this direction looks OK we can remove `focusCloseButton` and usages.

**Comment by jessegreenberg** [comment]
I also considered moving this `focusOnOpenNode` and `focusOnCloseNode` to popupable. But I decided not to because there isn't a reasonable default there. The default might involve `getNextFocusable`. Or the default might be `null` indicating no behavior and Dialog could set the default to be the close node.

@zepumph do you think this should be moved to popupable?

**Comment by zepumph** [comment]
I think that popupable is the place for this. I would highly recommend again using `getNextFocusable` (as I feel like you probably agree with), and instead just no-op when `null`. The reason is that it will be so very easy to do this now (at least I think so from the outside), and I could see us easily using this in whatever we popup next. 

Good work with removing `focusCloseButton`.

**Comment by jessegreenberg** [comment]
Thanks @zepumph, Ill move these options into Popupable and set the close button as the default in Dialog.

**Comment by jessegreenberg** [comment]
I am having a hard time putting this in Popupable because of when Dialog calls `this.sim.setAccessibleViewsVisible( true );`. Popupable's listener on the `isShowingProperty` is called before Dialog's so it is trying to set focus on `focusOnCloseNode` before the Node to restore focus to has become visible again.

**Comment by zepumph** [comment]
What about instead of putting it in the listener, you put it directly in show/hide, after you set the Property? Would that work?

**Comment by pixelzoom** [comment]
Raising priority to high, since this is blocking the next Fourier RC, as noted in https://github.com/phetsims/fourier-making-waves/issues/194#issuecomment-931748651.

**Comment by jessegreenberg** [comment]
Yes @zepumph, thanks! That worked really well. These are now in Popupable. I renamed the options because Popupable uses `show`/`hide` terminology instead of Dialog's `open`/`close`. Can you please review this change?

**Comment by jessegreenberg** [comment]
Wait, `focusCloseButton` still exists, back to me to remove that.

**Comment by jessegreenberg** [comment]
It has been removed, back to @zepumph for https://github.com/phetsims/sun/issues/719#issuecomment-933911808. After review Ill collect the commits that are needed for a cherry-pick.

**Comment by pixelzoom** [comment]
Some feedback that should be addressed by this issue:

(1) Over in https://github.com/phetsims/vegas/issues/96#issuecomment-934994871, @arouinfar's feedback for RewardDialog is that she'd like to see the traversal order be content -> closeButton -> browser URL textfield, instead of the current content -> browser URL textfield -> closeButton.  I don't think this is specific to RewardDialog, and seems to make sense for any Dialog. 

(2) Also in https://github.com/phetsims/vegas/issues/96#issuecomment-934994871, @arouinfar noted that Dialog seems to be setting focus to `focusOnOpenNode` regardless of how the Dialog was opened.  If the Dialog was opened via the keyboard, pressing Tab therefore does not set focus to `focusOnOpenNode`, but to the next element in the traversal order. This seems like undesirable behavior, as denonstrated in RewardDialog.

**Comment by jessegreenberg** [comment]
Re https://github.com/phetsims/sun/issues/719#issuecomment-935099853, these are being tracked in different issues, 1) is being discussed in https://github.com/phetsims/vegas/issues/96 and 2) is being discussed in https://github.com/phetsims/joist/issues/750.

**Comment by arouinfar** [comment]
> (1) Over in phetsims/vegas#96 (comment), @arouinfar's feedback for RewardDialog is that she'd like to see the traversal order be content -> closeButton -> browser URL textfield, instead of the current content -> browser URL textfield -> closeButton. I don't think this is specific to RewardDialog, and seems to make sense for any Dialog.

To clarify, @jessegreenberg mentioned that the current traversal order was more optimal for screen readers, so I am fine with leaving this as-is, as I said in https://github.com/phetsims/vegas/issues/96#issuecomment-935149674. Dialogs can be closed with the esc hotkey, so users don't need to tab to the close button, anyway.

**Comment by jessegreenberg** [comment]
Thanks @zepumph. Here are the commits to cherry-pick, in order. I tried cherry-picking to test branches off of fourier 1.0 SHAs and saw things working OK. Let me know if you encounter a problem @pixelzoom.

sun:
 - https://github.com/phetsims/sun/commit/214150ea6ba6b2b5975db9c35553b65c834a5097
 - https://github.com/phetsims/sun/commit/3440aab18041d6f1b3e3d0b84122649f4da2ff6a
 - https://github.com/phetsims/sun/commit/4a56833060c6bfe8906b91e5bb9cdb6a1cf53f19
 - https://github.com/phetsims/sun/commit/1908da5c436821b00fae0e98e9849d651c5e7105
 - https://github.com/phetsims/sun/commit/abd131542addfe76fa7ec14d2f6f5aa2838d0348
 - https://github.com/phetsims/sun/commit/f6264422e477342001f8d66473f1c95f662824f9
 - https://github.com/phetsims/sun/commit/620d973bdcb877953e5e8286592447085f4e2f35

joist:
 - https://github.com/phetsims/joist/commit/da02403ebfcf04e289a2e52febffa0296078321c
 - https://github.com/phetsims/joist/commit/90231723fedd0d19d8d91a6a637600cdf3aa5b9d
 - https://github.com/phetsims/joist/commit/d28d37076f3187b30c7097a1e5ee16d75da3be11

**Comment by pixelzoom** [comment]
I'm not sure if there's more to do here, so back to @jessegreenberg.

**Comment by jessegreenberg** [comment]
We are ready to close this.
