### ISSUE TITLE
ComboBoxListBox does not consider visibility of items when setting focus.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#720]
This problem was encountered in https://github.com/phetsims/fourier-making-waves/issues/195.  The Equation combo box in Fourier (EquationComboBox.js) has a dynamic list.  The visibility of items in the list changes based on the setting of the "Function of" combo box. So when traversing this list, invisible items are being visited. 

The problem seems to be with this bit of code in ComboBoxListBox.js:

```js
          // Up/down arrow keys move the focus between items in the list box
          const direction = ( KeyboardUtils.isKeyEvent( event.domEvent, KeyboardUtils.KEY_DOWN_ARROW ) ) ? 1 : -1;
          for ( let i = 0; i < listItemNodes.length; i++ ) {
            if ( this.focusedItemNode === listItemNodes[ i ] ) {
              const nextListItemNode = listItemNodes[ i + direction ];
              if ( nextListItemNode ) {

                // set focus for next item
                this.focusedItemNode = nextListItemNode;
                this.focusedItemNode.focus();

                break;
              }
            }
          }
```

First, using a `for` loop and `break` here is very odd.  Recommended to rework this code.

But the main issue is that we need to check `nextListItemNode.visible` if it's false, we should move on to the next/previous list item.

**Comment by pixelzoom** [comment]
High-priority because Fourier is in RC testing.

**Comment by jessegreenberg** [comment]
I replaced the for loops with a better way and introduced `visibleListNodes` to just select from those when deciding which ComboBoxListItemNode to focus next. @pixelzoom could you please review?

**Comment by pixelzoom** [comment]
Looks good, and behaves correctly in Fourier.  Thanks @jessegreenberg!

Closing.
