### ISSUE TITLE
Add voicing to ToggleSwitch

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#731]
This issue is part of the general clean up of the voicing feature which @jessegreenberg is working on, but I need to do this eagerly because I ran into an inner class called VoicingToggleSwitch in PreferencesToggleSwitch that was buggy in how late it initializes Voicing. Adding the mixin to common code is the only (and best) way to fix this. 

I hit this while working on https://github.com/phetsims/scenery/issues/1283 (more specifically https://github.com/phetsims/scenery/issues/1283#issuecomment-992800551)

**Comment by zepumph** [comment]
@jessegreenberg can you please review? Does this make sense to you and seem complete?

**Comment by jessegreenberg** [comment]
Makes sense, thank you! I think this is all we need for Voicing in ToggleSwitch. I thought for a moment about whether we should implement the object/context response somehow in ToggleSwitch but decided it was not worth it and we have not put Interactive Description context responses in ToggleSwitch either.

Does that work for you/anything else for this?
