### ISSUE TITLE
Add voicing to Checkbox

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#742]
From https://github.com/phetsims/ratio-and-proportion/issues/363. This is pretty straight forward because of @jessegreenberg's work in https://github.com/phetsims/sun/commit/6afc6a986c4988c858dd3fc75360a33137103085.

**Comment by zepumph** [comment]
@jessegreenberg does this look right to you? You can test in RAP if you pull all.

Usage site:

https://github.com/phetsims/ratio-and-proportion/blob/4e406540591163ef905d196d5c10a5350c686065/js/create/view/CreateScreenView.ts#L71-L88

**Comment by zepumph** [comment]
@pixelzoom just found that the typing is wildly wrong for voicing. The checkedContextResponse is TAlertableDef for description, but basically just a `string` for voicing.

**Comment by zepumph** [comment]
It isn't clear to me how best to proceed with this. The easiest way would be to have each accept the same type, but there isn't really that support at this time, so I'm not really sure. I'm also quite surprised that we haven't run into this in any other common code just yet.

**Comment by jessegreenberg** [comment]
Maybe it should take the subset of types that both Voicing and PDOM support, that would basically just be `string` or `null`. Or the Voicing implementation in Checkbox can turn the TAlertableDef into a VoicingResponse. Maybe we have a utility function to convert a TAlertableDef into a VoicingResponse.

**Comment by pixelzoom** [comment]
Here are the TODOs in CheckBox that need to be addressed:

```js
      if ( property.value ) {
        options.checkedSoundPlayer.play();
        options.checkedContextResponse && this.alertDescriptionUtterance( options.checkedContextResponse );
        // @ts-ignore TODO https://github.com/phetsims/sun/issues/742
        this.voicingSpeakNameResponse( { contextResponse: options.checkedContextResponse } );
      }
      else {
        options.uncheckedSoundPlayer.play();
        options.uncheckedContextResponse && this.alertDescriptionUtterance( options.uncheckedContextResponse );
        // @ts-ignore TODO https://github.com/phetsims/sun/issues/742
        this.voicingSpeakNameResponse( { contextResponse: options.uncheckedContextResponse } );
      }
```
