### ISSUE TITLE
Missing `protected` modifiers in AccessibleNumberSpinner.ts and AcessibleValueHandler.ts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#753]
In AccessibleNumberSpinner.ts:

```js
    // @protected - emits events when increment and decrement actions occur, but only for changes
    // of keyboardStep and shiftKeyboardStep (not pageKeyboardStep)
    readonly incrementDownEmitter: Emitter<[ boolean ]>; // @protected
    readonly decrementDownEmitter: Emitter<[ boolean ]>; // @protected
```

In AccessibleValueHandler.ts:

```js
     * @protected
     */
    handleKeyUp( event: SceneryEvent<KeyboardEvent> ) {
...
     * @protected
     */
    handleChange( event: SceneryEvent ) {
...
     * @protected
     */
    handleInput( event: SceneryEvent<Event> ) {
```

If these are truly `protected`, then the TypeScript `protected` modifier should be used, and the JSDoc `@protected` annotations should be deleted. 

The methods also need return types.

**Comment by zepumph** [comment]
Yes. Ideally that would be the case, just like all items prefixed with `_` would be marked as private with typescript, but this cannot be done due to a limitation of how Typescript mixins work. If you do that, you get an error in which anonymous classes cannot have private or protected members.

**Comment by pixelzoom** [comment]
Well that certainly is unfortunate.   And I now see the comment in the code:

```js
  // Unfortunately, nothing can be private or protected in this class, see https://github.com/phetsims/scenery/issues/1340#issuecomment-1020692592
```

I've improved that comment to be a little more informative/correct, and not refer to the trait as "this class":

```js
  // Unfortunately, private and protected modifiers cannot be used in this trait, due to a limitation of how Typescript 
  // mixins/traits work. If you do that, you get an error in which anonymous classes cannot have private or protected 
  // members. See https://github.com/phetsims/scenery/issues/1340#issuecomment-1020692592
```

Closing.
