### ISSUE TITLE
Convert Popupable, Dialog, and Dialog subclasses to TypeScript.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#763]
Before I do https://github.com/phetsims/vegas/issues/107 (GameInfoDialog), or convert any other Dialog subclasses (like OopsDialog) to TypeScript, it makes sense to convert Dialog.  And that requires converting Popupable.   But I'm not sure how to convert Popupable.

@jonathanolson could you convert Popupable?  Then assign back to me, and I'll handle Dialog and its subclasses.

This issue blockes https://github.com/phetsims/vegas/issues/107.

**Comment by jonathanolson** [comment]
Popupable has gracefulBind on showPopup/hidePopup, followed by assertions that they are non-null. Unclear how "graceful" to be since that will error it out slightly later. @zepumph can you take a look after I convert?

**Comment by jonathanolson** [comment]
Converted in commits above.

**Comment by pixelzoom** [comment]
Popupable was a great name for a trait. But it now seems misleading, not appropriate for a Node subclass. Should it be renamed? (Popup? PopupNode?...)

**Comment by pixelzoom** [comment]
Ah...  I commented without looking at the changes. Based on Slack conversation, I was under the impression that it was being converted to a Node subclass.  But this is fine for my needs.

**Comment by pixelzoom** [comment]
@jonathanolson you lost the git history for Popupable. Should it be restored?

**Comment by pixelzoom** [comment]
In the above commits, I converted Dialog to TypeScript.  I was forced to use `any` in two places, to avoid introducing a depency on joist:

```typescript
  //TODO https://github.com/phetsims/chipper/issues/1253 type Sim will introduce a dependency on joist
  sim?: any;

  private readonly sim: any; //TODO https://github.com/phetsims/chipper/issues/1253 type Sim will introduce a dependency on joist
```

These uses of `any` will be tracked in https://github.com/phetsims/chipper/issues/1253 (`no-explicit-any` typescript-eslint rule).

**Comment by pixelzoom** [comment]
Common-code subclasses of Dialog that have not been converted to TypeScript include:

- [ ] AboutDialog
- [ ] KeyboardHelpDialog
- [ ] OptionsDialog
- [ ] UpdateDialog
- [ ] PreferencesDialog
- [ ] ContextLossFailureDialog
- [ ] OopsDialog

**Comment by pixelzoom** [comment]
I converted everything except `PreferencesDialog`.  It has many subcomponents that also need to be converted -- PreferencesTabs, PreferencesPanels, AudioPreferencesPanel, GeneralPreferencesPanel,…. So I'm going to put, and have @jessegreenberg handle PreferencesDialog when he converts the rest of joist/js/preferences/.

**Comment by pixelzoom** [comment]
Remaining work here:

- [ ] @zepumph review request in https://github.com/phetsims/sun/issues/763#issuecomment-1148092256

- [ ] @jessegreenberg convert `PreferencesDialog`

**Comment by zepumph** [comment]
>Popupable has gracefulBind on showPopup/hidePopup, followed by assertions that they are non-null. Unclear how "graceful" to be since that will error it out slightly later. @zepumph can you take a look after I convert?

What you have here seems totally good and fine with me. 

PreferencesDialog has been converted to Typescript. Thanks all! Closing
