### ISSUE TITLE
Restore git history for Popupable.ts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#764]
In https://github.com/phetsims/sun/commit/3e33f864b56e6025031cf2b04ccb6a6c9fb1e92f for https://github.com/phetsims/sun/issues/763, @jonathanolson lost the git history for Popupable.

**Comment by samreid** [comment]
It is unfortunate that Popupable lost its history and we should endeavor to keep history in future renames, but we now have 16 commits on the new variation. I do not think it is worth the effort to retrieve the history and re-apply the 16 commits. If someone needs to see the pre-June-2022 Popupable, they can check out https://github.com/phetsims/joist/commit/0084647c55f5957b95a824760b9312b3a508e805 or thereabouts and get the history from there.
