### ISSUE TITLE
Specify params for Popupable trait without using `any`

### ISSUE THREAD

**Issue by jbphet** [phetsims/sun#777]
In https://github.com/phetsims/chipper/issues/1253 we are adding a lint rule that, for the most part, forbid the use of the `any` type specification.  The `Popupable.ts` file is using `any` in its constructor so that it can work well with the other classes with which it is combined.  I don't have any idea how to make this more type-specific, so I'm going to add a comment that will tell lint to ignore this for now and assign to one of the original authors.

**Comment by samreid** [comment]
constructor any array is idiomatic for our mixin pattern, closing.
