### ISSUE TITLE
console.log in Dialog constructor

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#778]
Chris Malley
After a pull-all, I’m seeing this printed to the console when I start any sim, or open the About dialog.
> providedOptions.sim = undefined

Sam Reid
Introduced in https://github.com/phetsims/sun/commit/24d06e76001a99c05503cf70a26b95c688e2422e

Chris Malley
In Dialog.ts

```js
    if ( providedOptions ) {
      console.log( `providedOptions.sim = ${providedOptions.sim}` );
    }
    else {
      console.log( 'no provided options' );
    }
```

If this was temporary, it should be removed. If’s it permanent, it should likely be using phet.log instead of console.log.

**Comment by jbphet** [comment]
Removed in https://github.com/phetsims/sun/commit/dd9a4b974f7f36a8ee57564351c033ae799e2ba7, closing.
