### ISSUE TITLE
ComboBox does not resize properly when its items have dynamic bounds.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#785]
Related to https://github.com/phetsims/sun/issues/783 ...

ComboBox's button is not resizing properly when its items involve StringProperty.  There are multiple problems, enumerated in the example below.

To reproduce in Geometric Optics:

1. Run the sim, go to Lens screen, open ComboBox at upper-left. Select from the ComboBox listbox. Note that the selected item is left-aligned on the button, and the content part of the button matches the width of the listbox. For example:

<img width="238" alt="screenshot_1839" src="https://user-images.githubusercontent.com/3046552/187460470-c790bb67-1d72-4488-bd2b-a3f58e39332d.png">

2. Cycle through locales. Note that after awhile, there are multiple problems:
   * The button does not shrink to fit the content.
   * The alignment of the content is wrong.
   * The width of the button does not match the listbox.
   * The part of the button used to open the listbox (down arrow) has mysterious blank space to the right of it. This part of the button should never change.
  
For example:

<img width="246" alt="screenshot_1840" src="https://user-images.githubusercontent.com/3046552/187460702-5f10b533-9643-44d9-932f-70817f1e63b5.png">

**Comment by pixelzoom** [comment]
ComboBoxListBox seems to be behaving as expected. The problem is ComboBoxButton.

**Comment by jonathanolson** [comment]
This looks like it's related to the "button only grows instead of shrinks" issue. I'm looking into it.

**Comment by jonathanolson** [comment]
In my working copy, I've handled the button issue, however this is still showing up with keyboard navigation:

<img width="273" alt="image" src="https://user-images.githubusercontent.com/480878/187739743-9fe224d0-387d-4cec-9b17-54168527aad5.png">

**Comment by jonathanolson** [comment]
I believe https://github.com/phetsims/sun/issues/781 fixed the main layout work for this. @pixelzoom can you verify, or see if there is anything else that needs to be done?

**Comment by pixelzoom** [comment]
Reviewed in the context of Geometric Optics combo box. Resize behavior is now as expected, including focus highlight. I did not review code changes. Closing.
