### ISSUE TITLE
Buggy layout using ComboBox with layoutNode option

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#788]
To demonstrate, make this change in BLL SolutePanel.ts:

```diff
-      children: [ solutionComboBox, toggleNode ]
+      children: [ solutionComboBox ]
```

The result looks like this:

<img width="271" alt="screenshot_1862" src="https://user-images.githubusercontent.com/3046552/189503359-9d816b9d-5084-4273-b2bd-8f588e99c56b.png">

I'm guessing that the optional `labelNode` was not considered when resize behavior was implemented for ComboBox, and it's assuming that the ComboBoxButton designes the size. 

This is impacting https://github.com/phetsims/beers-law-lab/issues/288, dynamic layout for BLL.

**Comment by pixelzoom** [comment]
ComboBox is also not adjusting it's layout when `labelNode` changes size.  This bit of code probably needs to be replaced with an HBox:

```
    if ( options.labelNode ) {
      this.button.left = options.labelNode.right + options.labelXSpacing;
      this.button.centerY = options.labelNode.centerY;
    }
```

**Comment by pixelzoom** [comment]
To see this in BLL, you can look at the label + ComboBox in either screen.  Here's the Solute ComboBox in the Concentration screen.  Note (1) the extra space between the label and the ComboBox, (2) the incorrect ComboBox resize behavior, causing it's parent VBox to resize incorrectly.

<img width="395" alt="screenshot_1865" src="https://user-images.githubusercontent.com/3046552/189926679-589bf7d9-dc4e-4f34-90ea-334005da2baf.png">

**Comment by jonathanolson** [comment]
Confirmed that it's an oversight of mine in ComboBox layout, it's not respecting preferred sizes correctly with a labelNode. I should have this fixed up today.

**Comment by jonathanolson** [comment]
@marlitas and I fixed this in the above commit. @pixelzoom can you verify? Apologies about that.

**Comment by pixelzoom** [comment]
No apologies necessary. Looks and behaves great in BLL.  Thanks for the quick turnaround. Closing.
