### ISSUE TITLE
TextPushButton with a maxWidth can result in buggy layout cases

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/sun#791]
NOTE: Cases seem to be resolvable by using maxTextWidth instead (and that's preferable), but this indicates something broken in how we're doing layout.

To reproduce:

1. In WOAS's RestartButton, replace maxTextWidth with maxWidth.
2. Run WOAS with a long string test (e.g. `&stringTest=asrtaslrtknalrstknalsrktnalsrktnalsrktnalskrntalskrntalksrntasrt`)

Result:

<img width="423" alt="image" src="https://user-images.githubusercontent.com/480878/191357834-41f9f38b-bfd1-4201-a0e7-8b9f7a9cd141.png">

**Comment by jonathanolson** [comment]
The button is properly sized until it is put into an HBox.

Then it gets a preferred size somehow set that is iterating the scale up (and the localPreferredWidth goes WELL below the minimumWidth). This stops once the scale is approximately back at 1 (so no INFINITE loop)

If we increase the scale (due to maxWidth not needing as much of a reduction), then it lowers the localPreferredWidth to a buggy state. We're not hard-erroring when the preferred size goes BELOW the minimum size, perhaps that's worth more of an investigation.

I'm also curious if some "stroke" size thing is going on, a factor of `1.0006832027530936` is happening for the first scale adjustment.

Also, if I set the preferredWidth of the button to 250 before putting it in the HBox, all is fine.

**Comment by marlitas** [comment]
I believe I remember us fixing this, and I also tried to reproduce and couldn't, so closing as completed!
