### ISSUE TITLE
Deprecate legacy support in GroupItemOptions 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#794]
GroupItemOptions is used to specify the "items" in various "groups" -- AquaRadioButtonGroup, VerticalCheckboxGroup, etc.

It currently supports 2 mutually-exclusive ways of specifying options:

```
// the legacy way
{
  node: Node,
  tandem?: Tandem
}

// the new way
{
  createNode: ( tandem: Tandem ) => Node,
  tandemName: string
}
```

Supporting both complicates code, and can result in problems (e.g. https://github.com/phetsims/sun/issues/793#event-7472017982).   So we'd eventually like to deprecate and remove support for "the legacy way".

**Comment by pixelzoom** [comment]
VerticalCheckboxGroupItem and AquaRadioButtonGroupItem are currently the only places where GroupItemOptions is used.

There are 12 occurrences of `import VerticalCheckboxGroup  `, 14 occurrences of `import AquaRadioButtonGroup `.

**Comment by samreid** [comment]
I'm going to remove the legacy way and port all sims to use the new way.

**Comment by samreid** [comment]
After changes in https://github.com/phetsims/sun/issues/794, you can no longer specify node/tandem to AquaRadioButtonGroup and VerticalCheckboxGroup.  Instead, please use `createNode` and `tandemName`.

I've left a few ts-ignore TODOs in the code for this issue, for after a few CT cycles.

**Comment by pixelzoom** [comment]
Slack#continuous-testing:

Kathryn Woessner
 [Today at 9:30 AM](https://phetsims.slack.com/archives/C03D6JMPAHF/p1664379018228009)
A number of sims are failing with an error that contains e.createNode is not a function.  Any ideas?

Sam Reid
  [19 minutes ago](https://phetsims.slack.com/archives/C03D6JMPAHF/p1664379185091499?thread_ts=1664379018.228009&cid=C03D6JMPAHF)
That’s me, I’ll take a look, thanks

**Comment by samreid** [comment]
My earlier test unfortunately only ran aqua for the PhET-iO Sims. I reran aqua for all sims and things are looking much better now. Thank you for bringing this to my attention. I will continue to watch CT over the next few columns in case things were missed by fuzzing here.

**Comment by samreid** [comment]
This seems fixed, closing.
