### ISSUE TITLE
ToggleSwitch pixel polishes

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#800]
@chrisklus and I found a couple strange and small issues with toggleswitch.

1. When resting in either state, the lineWidth thickness is too thick on the left/right compared to all other spots in the circle
2. the Green background should never be to the right of the thumb node. This behavior is like an iPhone switch.

These will both be straightforward to do, so we will just try them out and see how it goes!

**Comment by chrisklus** [comment]
@zepumph and I made changes in the above commits. We like them! I'm very excited. Closing.
