### ISSUE TITLE
Agreement between AquaRadioButtonGroup and RectangularRadioButtonGroup

### ISSUE THREAD

**Issue by veillette** [phetsims/sun#806]
I am currently converting a AquaRadioButtonGroup to RectangularRadioButtonGroup in Calculus-Grapher.

There is a nice parallel between the API of AquaRadioButtonGroup and RectangularRadioButtonGroup. Since going from one group of buttons to the next is probably a frequent design change,  

It was almost a simple drop in, but I had to do some digging for the type.

For type checking in RectangularRadioButtonGroup, we have
export type RectangularRadioButtonGroupOptions
export type RectangularRadioButtonItem
export type RectangularRadioButtonLabelAlign    // Determines where the optional label appears, relative to the button

in AquaRadioButtonGroup, we have
export type AquaRadioButtonGroupOptions
export type AquaRadioButtonGroupItem

Because of its nature, AquaRadioButtonGroup doesn't need to have have a label align.

My proposal would be to rename RectangularRadioButtonItem to RectangularRadioButtonGroupItem
and RectangularRadioButtonLabelAlign to RectangularRadioButtonGroupLabelAlign to bring them in agreement, although I could see that renaming AquaRadioButtonGroupItem to AquaRadioButtonItem would work as well.

Assigning to @pixelzoom .

**Comment by pixelzoom** [comment]
Agreed, the naming is inconsistent. Since we also have VerticalCheckboxGroupItem for VerticalCheckboxGroup, let's rename RectangularRadioButtonItem to RectangularRadioButtonGroupItem.

**Comment by pixelzoom** [comment]
Agreed, the naming is inconsistent. Since we also have VerticalCheckboxGroupItem for VerticalCheckboxGroup, let's rename RectangularRadioButtonItem to RectangularRadioButtonGroupItem. I'll do the rename.

@samreid FYI, since you worked on RectangularRadioButtonGroup recently.

**Comment by pixelzoom** [comment]
Rename complete in the above commit. @veillette if this is what you had in mind, and I didn't miss anything, feel free to close.

**Comment by veillette** [comment]
Yes, this bring consistency between the types of the two classes. Closing.
