### ISSUE TITLE
AccessibleValueHandler makes bad assumptions about range when setting keyboard steps

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#817]
In AccessibleValueHandler.ts:

```typescript
keyboardStep: ( enabledRangeProperty.get().max - enabledRangeProperty.get().min ) / 20,
shiftKeyboardStep: ( enabledRangeProperty.get().max - enabledRangeProperty.get().min ) / 100,
pageKeyboardStep: ( enabledRangeProperty.get().max - enabledRangeProperty.get().min ) / 10,
```

This makes some bad assumptions about the range.  If I have range [-3,0] for example (which I do in acid-base-solution), then these steps will be negative, and this assertion (and others?) will fail in AccessibleValueHandler.ts:

```typsecript
public setShiftKeyboardStep( shiftKeyboardStep: number ): void {
  assert && assert( shiftKeyboardStep >= 0, 'shift keyboard step must be non-negative' );
```

It might simply be a matter of putting `Math.abs` around these values.  But I haven't had time to test.  

In the meantime, I'll explicitly set these options to workaround this.

**Comment by pixelzoom** [comment]
Note that you could also replace the instances of `enabledRangeProperty.get().max - enabledRangeProperty.get().min` with `enabledRangeProperty.get().getLength()` and this would probably behave propertly.  Because `new phet.dot.Range( -3, 0 ).getLength() => 3`.

**Comment by pixelzoom** [comment]
Hmmm... Now I'm confused about why the default steps are negative.  Because:

```
> var r = new phet.dot.Range( -3, 0 )
> r.max - r.min
3
```
```

**Comment by jessegreenberg** [comment]
I am trying to see this on my side but haven't been able to. I ran acid-base-solutions with `?supportsInteractiveDescription=true` and didn't hit an assertion and I didn't see workarounds committed related to this. I tried this patch in the sun demo (setting the range of the slider from -3 to 0) and it worked OK. 

It may not be from the option but using the `setShiftKeyboardStep` function later? Is there a reproducible example you can point me to?

**Comment by pixelzoom** [comment]
I ultimately punted on what I was trying to do in https://github.com/phetsims/acid-base-solutions/issues/167, so the case where I was experiencing this problem no longer exists. And I don't have time to invent a case to investigate.  So I'm just going to close this issue.  Thanks for having a look @jessegreenberg, and apologies for wasting your time.
