### ISSUE TITLE
Review Carousel accessibility modifiers

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#831]
Related to #814 and https://github.com/phetsims/sun/issues/829 ...

Do you really want `getAlignBoxForItem` and `scrollToItemVisibleIndex` to be `public`?   They seem specific to Carousel internals, and are in fact only used inside Carousel.

**Comment by samreid** [comment]
Yes, they are currently only used in Carousel. But `getAlignBoxForItem` is designed to allow clients to remove something from the carousel without collapsing the empty space.  

```ts
  /**
   * Can control the visibility of this AlignBox to determine whether the space inside the carousel is maintained
   */
  public getAlignBoxForItem( item: CarouselItem ): AlignBox {
```

I'll make `scrollToItemVisibleIndex` private (for now?)

**Comment by samreid** [comment]
Fixed, ready for review.

**Comment by pixelzoom** [comment]
> .... But `getAlignBoxForItem` is designed to allow clients to remove something from the carousel without collapsing the empty space.

It's unfortunate (and imo unnecessary) that you're exposing the internals of Carousel to support that.

**Comment by samreid** [comment]
What if we change the return type to `Node` and give it a more general name?

**Comment by pixelzoom** [comment]
@samreid and I reviewed on Zoom.  We made `getAlignBoxForItem`, because it's not actually useful for leaving holes.  

Closing.
