### ISSUE TITLE
AccordionBox does not support rendering nodes in titleNode area when opened.

### ISSUE THREAD

**Issue by marlitas** [phetsims/sun#843]
For Center and Variability, the design calls for an info button, and dot plot renderings to be shown on top of the titleNode area when the accordion box is open. 
![image](https://user-images.githubusercontent.com/42476338/235746204-e0be233e-62b8-40bf-aebc-859e358cf998.png)

This is currently not possible with accordion box, and results in the following:

![image](https://user-images.githubusercontent.com/42476338/235745015-4251a079-bc18-4b73-b80b-ff57bbfdea4c.png)

This line of code was used to create a hacky solution:
```js
    backgroundNode.localBounds = backgroundNode.localBounds.copy();
```

@samreid and I feel like it would be best to remove this line and allow accordionBox to properly apply the desired layout. @jonathanolson, does this feel like something that can be part of work for https://github.com/phetsims/sun/issues/803, or is it a much separate lift?

**Comment by samreid** [comment]
Likewise, here is a design mock-up calling for data points to render up past the title bar:

<img width="648" alt="image" src="https://user-images.githubusercontent.com/679486/235746696-130e4b5f-470b-4f40-9431-a5b4d50ad8ff.png">

**Comment by samreid** [comment]
See also related issue https://github.com/phetsims/sun/issues/803

**Comment by jonathanolson** [comment]
AccordionBox now supports width-sizable titleNode elements, so you could now HBox something if you want it right-aligned (note that titleAlignX would put whitespace at the right side if it's 'center' due to its design, use either other align)

**Comment by marlitas** [comment]
Sorry for the delayed review here. The logic in https://github.com/phetsims/sun/commit/d17cdcf987697d60ccbfc13bd9ab1096c355197a look appropriate, and this has also been tested by QA with the publication of CAV. I believe this issue can be closed. Thanks!
