### ISSUE TITLE
numeric spinner needed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#85]
Example shown below, from RPAL (HTML) design document. Consists of a numeric display with two instances of scenery-phet.ArrowButton. API probably looks something like what's shown below. ArrowButton should also be converted to use new sun buttons.

```javascript
function NumericSpinner( valueProperty, valueRange, options ) {
  options = _.extend( {
      font:  // {PhetFont}
      // support for all ArrowButton options?
  }, options );
}
```

![screenshot_259](https://cloud.githubusercontent.com/assets/3046552/2784674/debd0382-cb41-11e3-8a95-c5d6d1dd7c86.png)

**Comment by ariel-phet** [comment]
@pixelzoom this issue is pretty stale, and I am unsure of the current state, can it be closed?

**Comment by pixelzoom** [comment]
@ariel-phet As mentioned above, we have 3 different "looks" for spinners. It's not clear whether that's necessary, or whether it's a design oversight.  So the first step would be to have designers decide what the standard look(s) are for spinners.  Until that's sorted out, there's nothing to do on the implementation side. So back to you... You can either unassign (defer) or assign to a designer to champion the issue.

**Comment by pixelzoom** [comment]
Btw... There are some additional variants on this.

`NumberPicker` (generalized in scenery-phet) is used when putting up/down arrows to the right of the number would interfere in the visual flow. For example, in equations, like this:

![screenshot_69](https://cloud.githubusercontent.com/assets/3046552/11245841/048cb54a-8dd2-11e5-9786-8f438871ac20.png)

`NumberSpinner` (currently specific to reactants-products-and-leftovers) has this basic look:

![screenshot_73](https://cloud.githubusercontent.com/assets/3046552/11245994/f1b72d3c-8dd2-11e5-98cb-815d5a041c74.png)

You can also hide its up/down button, useful in Games, like this in "Balancing Chemical Equations":

![screenshot_71](https://cloud.githubusercontent.com/assets/3046552/11245883/45e6bc52-8dd2-11e5-8a0e-0db523095c1e.png)

It would also be relatively easy to hide the background on the number in `NumericSpinner` so that it has a look more similar to the spinner used in Fractions, like this:

![screenshot_72](https://cloud.githubusercontent.com/assets/3046552/11245944/b0146ef8-8dd2-11e5-9d8d-7d043311f14d.png)

@samreid @jbphet @jonathanolson Are there any additional sim-specific variations/implementations that I haven't mentioned here? If so, please describe and provide a screenshot.

**Comment by ariel-phet** [comment]
@pixelzoom thanks for the further thoughts.

@amanda-phet likely has yet another design in expression exchange (very similar, but with the spinners horizontally on each side). That does seem like something that should be unified with NumberSpinnner.

Assigning to @jbphet to look at when he works on Expression Exchange.

**Comment by pixelzoom** [comment]
scenery-phet has `UpDownSpinner` and `LeftRightSpinner`.  

`UpDownSpinner` example:

![screenshot_74](https://cloud.githubusercontent.com/assets/3046552/11246417/d5918056-8dd4-11e5-8f01-8be3e8aba73f.png)

`LeftRightSpinner` example:

![screenshot_75](https://cloud.githubusercontent.com/assets/3046552/11246418/d5ac2e56-8dd4-11e5-8770-8b1215d9934b.png)

Both of these are a bit misleading - neither one of them handles display of the numeric value.

**Comment by amanda-phet** [comment]
What I had in mind for Expression Exchange was something like these buttons: 
<img width="200" alt="screen shot 2015-11-18 at 9 32 03 am" src="https://cloud.githubusercontent.com/assets/7852916/11247155/1ae7c1f8-8dd8-11e5-9530-797719477445.png">
<img width="167" alt="screen shot 2015-11-18 at 9 33 43 am" src="https://cloud.githubusercontent.com/assets/7852916/11247161/1e9f64e0-8dd8-11e5-8aec-f02cc0765778.png">
<img width="150" alt="screen shot 2015-11-18 at 9 34 39 am" src="https://cloud.githubusercontent.com/assets/7852916/11247178/2c74abb6-8dd8-11e5-8d98-443781f940d3.png">

They seem to be often paired with sliders, so I'm not sure if it is the same as a spinner. However, I like the button style (which is similar to the RPAL numberspinner above), so I could see these being generalized for scenery-phet.

**Comment by ariel-phet** [comment]
@amanda-phet can you just paste in the mockup you have so far?

**Comment by amanda-phet** [comment]
![screen shot 2015-11-18 at 9 51 46 am](https://cloud.githubusercontent.com/assets/7852916/11247619/115b786c-8dda-11e5-94f5-86b9ef091f0e.png)

**Comment by jonathanolson** [comment]
> Are there any additional sim-specific variations/implementations that I haven't mentioned here?

My sims have been pretty much spinner-free.

**Comment by jbphet** [comment]
Build an Atom has some like this:

![baa-spinner-example](https://cloud.githubusercontent.com/assets/3082831/11248892/c11a06a0-8de0-11e5-8220-71fb78cb9771.png)

**Comment by pixelzoom** [comment]
The spinners in RPAL and Build an Atom look nearly identical.

There a need in Projectile Motion for spinners that looks like the ones in the Expression Exchange design.  But looking at the implementation, it appears that Expression Exchange ultimately had no spinners. Is that correct @jbphet?

**Comment by pixelzoom** [comment]
At 7/21/16 design meeting, @ariel-phet suggested that I work with @andrea-phet to generalize one of the spinner implementations (probably RPAL.NumberSpinner) for use in Projectile Motion.

**Comment by jbphet** [comment]
In response to https://github.com/phetsims/sun/issues/85#issuecomment-234353048, there **are** spinners in Expression Exchange, see the screenshot from the most recent dev version below.  Truth be known, I had forgotten that this UI element is referred to as a "spinner" and had called it a "tweaker", which is probably why @pixelzoom was unable to find it.  I've renamed it to LeftRightNumberSpinner and am happy to help with the effort to generalize it.  

I just discussed this with @andrea-phet, so she is aware of the current status.

![ex-ex-spinners](https://cloud.githubusercontent.com/assets/3082831/17065165/8f64c2e6-4ffd-11e6-8977-b6d950bcf89a.PNG)

**Comment by pixelzoom** [comment]
expression-exchange.LeftRightNumberSpinner also contains the label to the left of the spinner, e.g. "x =".   So I'm not going to attempt to generalize it, and will leave it to @jbphet to use rpal.NumberSpinner in expression-exchange.LeftRightNumberSpinner.

**Comment by pixelzoom** [comment]
Pairing with @andrea-phet on generalizing rpal.NumberSpinner.

TODO list

- [ ] move ArrowButton from scenery-phet to sun, since it's used by NumberSpinner
- [ ] move NumberSpinner to sun
- [ ] add NumberSpinner demo to sun
- [ ] add button layout options ('leftRight', 'upDown' ?)
- [ ] make range optional, instead of required constructor parameter
- [ ] support different formatting of value (so we can show units, etc.)
- [ ] options for value (font, fill,...)
- [ ] options for background (margin, fill, stroke,...)
- [ ] options for buttons (size, colors, margins,...)
- [ ] options for mouseArea (xy dilation)
- [ ] enabled/disabled feature

**Comment by pixelzoom** [comment]
@andrea-phet and I made good progress on this, but stopped at the "use NumberDisplay..." item in the checklist above.  That's going to be a fair bit of work, which we'll address at another pairing session.

In the meantime, NumberSpinner still works (and looks) the same for its sole client (RPAL).

**Comment by pixelzoom** [comment]
@andrea-phet I made a few additional changes after our pairing session yesterday, see above commits.  I occurred to me that there were a few things that I didn't want to leave in a semi-broken state between now and the next time we work on this.

**Comment by andrea-phet** [comment]
Thanks @pixelzoom!

**Comment by andrea-phet** [comment]
It would be nice if the width of the backgroundNode could be custom set. I'm running into this layout/alignment problem with projectile-motion, which could be resolved if I could fix the width of all three number spinners:
![image](https://cloud.githubusercontent.com/assets/7988696/17162056/b3a0afa6-536f-11e6-8e2c-64a93d9e6312.png)
So that it looks more like the design doc:
![image](https://cloud.githubusercontent.com/assets/7988696/17162035/810b9fec-536f-11e6-812a-ebd26532d8a2.png)

**Comment by andrea-phet** [comment]
Related to the images in the previous comment, it would be nice to be able to change the outline weight and color of the background node and arrows.

**Comment by pixelzoom** [comment]
@andrea-phet and I looked at using NumberDisplay in NumberSpinner, but NumberDisplay has some problems with how it formats the number and optional units. Rather than passing in pattern and units separately, it would be preferable to have default pattern of '{0}', and (if units are desire) add the units to the optional pattern (e.g. '{0} L'). Also complication the issue is that (1) NumberDisplay is in scenery-phet, and would need to be migrated to sun, and (2) there are many existing clients of NumberDisplay (including NumberControl).

I'll have a look at revising NumberDisplay in https://github.com/phetsims/scenery-phet/issues/253.

**Comment by pixelzoom** [comment]
We followed the enabled/disabled pattern that was agreed on in https://github.com/phetsims/sun/issues/241#issuecomment-234322865.

**Comment by pixelzoom** [comment]
We decided not to support the radically different look for the arrow buttons that's shown in https://github.com/phetsims/sun/issues/85#issuecomment-157766290.

**Comment by pixelzoom** [comment]
Our work here is done. Since we paired on this, we didn't feel the need to have a 3rd developer review, so closing.
