### ISSUE TITLE
`RectangularRadioButtonGroup` doesn't update layout when button widths change

### ISSUE THREAD

**Issue by jbphet** [phetsims/sun#852]
The widths of the buttons in a `RectangularRadioButtonGroup` don't appear to update when the size of one button changes in a different way from the others.  This was first reported as part of https://github.com/phetsims/greenhouse-effect/issues/349, and there is [another issue](https://github.com/phetsims/sun/issues/851) that was created for updating the just the highlight.

I read through the code in `RectangularRadioButtonGroup` and found a portion of the code that looks like it is intended to make the widths of all the buttons the same.  This code currently starts on line 181 of the source file and looks like this:

```ts
    // Calculate the maximum width and height of the content, so we can make all radio buttons the same size.
    const widestContentWidth = _.maxBy( nodes, node => node.width )!.width;
    const tallestContentHeight = _.maxBy( nodes, node => node.height )!.height;
```

This code probably needs to be re-run when the width changes for one or more of the buttons.

**Comment by jbphet** [comment]
Assigning to the original author, he can pass it on to the dynamic layout experts if necessary.

**Comment by jbphet** [comment]
I just realized a screenshot would be helpful, so here is an example that can be easily duplicated with the recent Greenhouse Effect dev test version.  To duplicate:

1. Go to https://phet-dev.colorado.edu/html/greenhouse-effect/1.2.0-dev.2/phet/greenhouse-effect_en_phet.html?stringTest=dynamic
2. Select the first screen (Waves), and then select the "date mode" by pressing the button with the calendar icon "Greenhouse Gas Concentration" control panel
3. Press the right arrow button to increase the string sizes

![image](https://github.com/phetsims/sun/assets/3082831/8ed24fc3-cfdd-4925-bf32-9e5f3ebcc199)

**Comment by pixelzoom** [comment]
Aaron Davis was the original author of `RectangularRadioButtonGroup`. I made changes at various points to keep manage the chaos that this class (and its supporting classes) have become.  I don't see any commits that indicate support for dynamic layout has been added.   @jonathanolson has generally been handling that for sun components, and it would be good to keep things consistent, so reassigning to him.

**Comment by marlitas** [comment]
Just to confirm, because I believe I was initially confused when looking at this issue. We want the radio button widths to match across all the buttons? The group is updating is minimumWidths as I would expect, however visually the buttons should all be the same size and that is currently not happening?

I will assign and take a look at this as well.

**Comment by marlitas** [comment]
@jonathanolson We would like you to prioritize this issue since it is now blocking Greenhouse: https://github.com/phetsims/sun/issues/851

**Comment by jbphet** [comment]
Wow - nice one-line fix @jonathanolson!  In fact, there was a significant reduction in code including all the related commits shown above.

I've verified that it's working correctly in Greenhouse Effect for the case described above.  I think we're good to go here.  Closing.
