### ISSUE TITLE
Address `strictAxonDependencies: false` in ComboBox

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#870]
For https://github.com/phetsims/axon/issues/441, @samreid added 2 occurrences of `strictAxonDependencies: false`to ComboBox. This means that there are missing dependencies, and should be addressed.

**Comment by samreid** [comment]
We decided to remove this feature in https://github.com/phetsims/axon/issues/441. I will remove the flag and the TODO, closing.
