### ISSUE TITLE
NVDA says "invalid entry" in Firefox when long numeric strings are present

### ISSUE THREAD

**Issue by jbphet** [phetsims/sun#873]
In https://github.com/phetsims/greenhouse-effect/issues/388 it was reported that Firefox and NVDA on Windows was sometimes saying "invalid entry" as part of its description of a slider.  I tracked this down to a long string for a numeric value being present in the PDOM, specifically for the `step` value, and when the length of the string was reduced the problem went away.  This is essentially a workaround for a problem in Firefox, and we should consider reporting the problem to them.

In the process of exploring this I found that it was not specific to Greenhouse Effect.  I was able to duplicate the issue on the published version of Fourier: Making Waves when navigating to the 3 lower sliders on the "Wave Packet" screen.  Changing the length of the `step` value did not fix the problem in Fourier, but inspection with the Firefox developer tools indicates several other long strings.  Here's a screenshot:

![image](https://github.com/phetsims/sun/assets/3082831/54d5ae9c-7b5e-4fc4-8da4-2d90a3c27baf)

I suspect that limiting the length of some or all of these values will stop NVDA from saying "invalid value".

For reference, Firefox version is 122.0.1, NVDA 2023.3.3, Fourier 1.0.17, OS is Windows 11.

**Comment by jbphet** [comment]
The following patch, which limits the precision of all or most of the PDOM attributes, makes the problem go away.  I'm not suggesting this as a fix, just further demonstrating the nature of the problem.

<details>

```diff
Subject: [PATCH] experimental patch for "invalid entry" problem
---
Index: js/accessibility/pdom/ParallelDOM.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/accessibility/pdom/ParallelDOM.ts b/js/accessibility/pdom/ParallelDOM.ts
--- a/js/accessibility/pdom/ParallelDOM.ts	(revision b1cdc5afbd6763c9a74e4ba5126554253dfd4799)
+++ b/js/accessibility/pdom/ParallelDOM.ts	(date 1707245481735)
@@ -2461,6 +2461,16 @@
     assert && providedOptions && assert( Object.getPrototypeOf( providedOptions ) === Object.prototype,
       'Extra prototype on pdomAttribute options object is a code smell' );
 
+    if ( typeof value === 'number' && value.toString().length > 10 ) {
+
+      // Limit precision to prevent weird behavior.
+      console.log( '--------------------' );
+      console.log( `attribute = ${attribute}` );
+      console.log( `value (before mod) = ${value}` );
+      value = value.toPrecision( 8 );
+      console.log( `value (after mod) = ${value}` );
+    }
+
     const options = optionize<SetPDOMAttributeOptions>()( {
 
       // {string|null} - If non-null, will set the attribute with the specified namespace. This can be required
```

</details>

**Comment by jbphet** [comment]
The following patch makes the problem go away.  I'm not suggesting this as a fix, just further demonstrating the nature of the problem and showing that it really is related to numeric string lengths.

<details>

```diff
Subject: [PATCH] experimental patch for "invalid entry" problem
---
Index: js/accessibility/pdom/ParallelDOM.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/accessibility/pdom/ParallelDOM.ts b/js/accessibility/pdom/ParallelDOM.ts
--- a/js/accessibility/pdom/ParallelDOM.ts	(revision b1cdc5afbd6763c9a74e4ba5126554253dfd4799)
+++ b/js/accessibility/pdom/ParallelDOM.ts	(date 1707245481735)
@@ -2461,6 +2461,16 @@
     assert && providedOptions && assert( Object.getPrototypeOf( providedOptions ) === Object.prototype,
       'Extra prototype on pdomAttribute options object is a code smell' );
 
+    if ( typeof value === 'number' && value.toString().length > 10 ) {
+
+      // Limit precision to prevent weird behavior.
+      console.log( '--------------------' );
+      console.log( `attribute = ${attribute}` );
+      console.log( `value (before mod) = ${value}` );
+      value = value.toPrecision( 8 );
+      console.log( `value (after mod) = ${value}` );
+    }
+
     const options = optionize<SetPDOMAttributeOptions>()( {
 
       // {string|null} - If non-null, will set the attribute with the specified namespace. This can be required
```

</details>

**Comment by jbphet** [comment]
Assigning to @jessegreenberg, since he is the main author for the PDOM code, and @pixelzoom, because he was the primary author of Fourier.

**Comment by jessegreenberg** [comment]
Thanks for diving into this @jbphet. Do you think the `toPrecision` fix you used in https://github.com/phetsims/greenhouse-effect/issues/388 could be used for these values as well? In the above commit I factored out `toPrecision` so it is used everywhere a value is set as an attribute in the PDOM. It sounds OK in greenhouse-effect and I am not hearing 'invalid entry" when testing in fourier. Can you please review?

**Comment by jessegreenberg** [comment]
Here is the description of the step attribute from MDN:

>The step sets the stepping interval when clicking up and down spinner buttons, moving a slider left and right on a range, and validating the different date types. If not explicitly included, step defaults to 1 for number and range, and 1 unit type (minute, week, month, day) for the date/time input types. The value must be a positive number - integer or float — or the special value any, which means no stepping is implied and any value is allowed (barring other constraints, such as [min](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/min) and [max](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/max)).

...

>If any is not explicitly set, valid values for the number, date/time input types, and range input types are equal to the basis for stepping - the [min](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/min) value and increments of the step value, up to the [max](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/max) value, if specified.

So... I think we should try the `any` value for `step`, and see if screen readers like that better.

**Comment by jessegreenberg** [comment]
Using `any` sounds great with NVDA. I am most worried about iOS VoiceOver based on comments above. I don't have access to a device with that right now, so I made https://github.com/phetsims/qa/issues/1035 to test.

**Comment by jessegreenberg** [comment]
From https://github.com/phetsims/qa/issues/1035, the `any` attribute is not supported by iOS VoiceOver and makes the slider unusable. Ill revert https://github.com/phetsims/sun/commit/a90b5d39cea71b74606049cb4e1dfd711164a70e.

**Comment by jessegreenberg** [comment]
Alright, I am proposing the above commit which uses a platform check to do some extra work on iOS Safari. This is a bummer but here is my thinking:

1) We use the `any` attribute everywhere except for iOS Safari, where we calculate the step value. This way we can use the simple `any` value for most platforms and avoid adding lots of complicated workarounds like https://github.com/phetsims/sun/commit/42be9030ee3141740b564e7a13c270e5ae54fb03.
2) We know that the step calculation sounds nice for iOS VoiceOver which doesn't say "invalid" like NVDA does.
3) We should submit a bug report to Apple to support the 'any' attribute and maybe someday we can remove this.

@jbphet can you please review? Does this seem reasonable to you?

**Comment by jbphet** [comment]
I tested this on Firefox on my Win 11 system and verified that the problem was no longer occurring in Greenhouse Effect and Fourier.  Looking over the code, the approach seems reasonable, although I agree that it's unfortunate to have to put platform-specific code in here.  Here are a few additional thoughts:

- I'd suggest adding a TODO about removing the workaround code, and link it to an issue about updating our code when and if the `any` attribute becomes supported in Safari+Voiceover.  Then the issue should be deferred.
- Have QA test this if they haven't already.  I was able to lightly test the Firefox case, but not MacOS+Safari+Voiceover.
- +1 for reporting the problem to Apple, and also to logging one with Mozilla.  I know that this is easy for me to say, but can be a pain to actually do, so I can help with this if you'd like.

Also note that I made a few minor editorial changes to the comments in this code.

**Comment by jessegreenberg** [comment]
OK, thanks for the review!

> I'd suggest adding a TODO...

Done, I made https://github.com/phetsims/a11y-research/issues/191 for the TODO and also to submit a bug report to Apple.

> Have QA test this if they haven't already.

OK, sounds good - I made https://github.com/phetsims/qa/issues/1040

> and also to logging one with Mozilla

Sounds good, I made https://github.com/phetsims/a11y-research/issues/192. I assigned this one to both of us for whoever can get to it first.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/qa/issues/1040 has been confirmed so this one can be closed. We will follow up on the bug reports in the new issues. Closing.
