### ISSUE TITLE
AccessibleNumberSpinner memory leak

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#879]
Related to changes made to NumberSpinner and AccessibleNumberSpinner in https://github.com/phetsims/sun/issues/804 and https://github.com/phetsims/sun/issues/869.

Those changes appear to be have introduced a memory leak, which is manifesting in graphing-lines RC testing, see https://github.com/phetsims/graphing-lines/issues/153.  

Graphing Lines creates and disposes NumberPicker instances. And NumberPicker uses the AccessibleNumberSpinner trait, which does this:

```ts
      this.setPDOMAttribute( 'aria-roledescription', SunStrings.a11y.numberSpinnerRoleDescriptionStringProperty );
```

... and then never unlinks from `SunStrings.a11y.numberSpinnerRoleDescriptionStringProperty` in dispose.

@jessegreenberg How do we unlink from this LocalizedStringProperty?

**Comment by pixelzoom** [comment]
I tried this fix:

```diff
      this._disposeAccessibleNumberSpinner = () => {
        this.removePDOMAttribute( 'aria-roledescription' );
```

It looks like `this._disposeAccessibleNumberSpinner` is never being called.   How does a trait's `dispose` method get called?

**Comment by pixelzoom** [comment]
More details from Slack#dev ...

ParallelDOM is the superclass of Node, and `disposeParallelDOM` is supposed to remove _all_ PDOM attributes:

```ts
    // PDOM attributes can potentially have listeners, so we will clear those out.
    this.removePDOMAttributes();
``` 

But that does not seem to be doing what it's supposed to do.  This change in AccessibleNumberSpinner resolved the memory leak, and should not be necessary if `removePDOMAttributes` is working correctly:

```diff
      this._disposeAccessibleNumberSpinner = () => {
+       this.removePDOMAttribute( 'aria-roledescription' );
```

**Comment by jessegreenberg** [comment]
I am not seeing a leak related to AccessibleNumberSpinner. I ran graphing-lines with `?fuzz&listenerLimit=600` and I see TinyEmitter listeners max out at 427. I am also seeing the aria-roledescription listener correctly unlinked in ParallelDOM.ts. 

For ~4 minutes of fuzzing, memory was stable at 87 MB.

But after about 4 minutes of fuzzing, the listener count started to go up quickly. ( I don't know why, maybe I clicked into the sim to turn on sound?) The limit assertion stopped here: https://github.com/phetsims/tambo/blob/ebe910a6ea4b9403e4e554125967455a518cef12/js/sound-generators/SoundGenerator.ts#L115

Stack trace goes through RichDragListener:
<details>

![image (3)](https://github.com/phetsims/sun/assets/6396244/415d272f-93c3-44d5-9aa1-4ad34fb3f204)
</details>

**Comment by pixelzoom** [comment]
Thanks @jessegreenberg.  t’s highly probable that I was confused about leakage in AccessibleNumberSpinner/ParallelDOM.  There were so many things leaking in Graphing Lines dues to LocalizedStringProperty.  Thanks for looking, and I’ll continue to investigate.

**Comment by pixelzoom** [comment]
I confirmed that AccessibleNumberSpinner's 'aria-roledescription' listener is correctly unlinked in ParallelDOM.ts.  Weird, not what I was seeing yesterday.   Sorry to bother you.  Closing.
