### ISSUE TITLE
Add support for sound to `CarouselComboBox`

### ISSUE THREAD

**Issue by jbphet** [phetsims/sun#891]
The `CarouselComboBox` UI component is currently not used much, if any, in sims, but it *is* used in a number of demos, such as the `scenery-phet` and `tambo` demos.  It currently doesn't generate any sound, which feels weird in the `tambo` demo, since `tambo` is all about sound.  It would be nice to add sound support to it.

**Comment by jbphet** [comment]
I've added rudimentary support for sound generation - just a basic open and close sound.  It seems to work fine in both the tambo and scenery-phet demos, and feels much better to me than no sound at all.  I didn't want to take the time to implement an equivalent scheme to `ComboBox`, where a different sound is played when the user changes the selection, because it seemed unnecessary at this point.

@pixelzoom - You were the main author of this component.  You cool with this?

**Comment by pixelzoom** [comment]
Looks good to me!

Back to @jbphet in case there's more to do.
