### ISSUE TITLE
Should RectangularStickyToggleButton use the 'pushButton' SoundPlayer?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/sun#894]
While working on https://github.com/phetsims/sun/issues/796 we noticed that RectangularStickyToggleButton does not use the same SoundPlayer that RoundStickyToggleButton uses. We were wondering if it should? 

I suspect we can copy the pattern used in RoundStickyToggleButton and I am happy to do it, but I wanted to run it by @jbphet first to make sure.

**Comment by jbphet** [comment]
Makes sense to me that they should be consistent.  I'd so go for it @jessegreenberg.  And thanks.

**Comment by jessegreenberg** [comment]
Great, thanks! I added the sound player, and also a required tandem so RectangularStickyToggleButton and RoundStickyToggleButton options are the same. Closing.
