### ISSUE TITLE
Sound is missing from RoundToggleButton.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#895]
Discovered while working on alt input for momentary toggle buttons in https://github.com/phetsims/sun/issues/796.

In https://github.com/phetsims/sun/commit/1df861f21c63e59f7046c04bf8505b059fdfbf5b, @samreid added sound to RectangularToggleButton, but did not add sound to RoundToggleButton.  I see no reason why the sound should be different because a button is rectangular vs round, so labeling this as a bug.

**Comment by pixelzoom** [comment]
It looks like sun buttons are in the (bad) habit of duplicating sound code in the round vs rectangular versions of buttons. For example, RectangularPushButton and RoundPushButton both contain these duplicated lines of code:

```ts
type SelfOptions = {
  soundPlayer?: TSoundPlayer;
};

      soundPlayer: sharedSoundPlayers.get( 'pushButton' ),

    // sound generation
    const playSound = () => { options.soundPlayer.play(); };
    pushButtonModel.produceSoundEmitter.addListener( playSound );

      pushButtonModel.produceSoundEmitter.removeListener( playSound );
```

Unfortunately, I don't see any easy option but to follow this same pattern of duplication (for now) with RectangularToggleButton and RoundToggleButton.

**Comment by jessegreenberg** [comment]
Sorry @pixelzoom I am confused, I see sounds in RoundToggleButton here:

https://github.com/phetsims/sun/blob/99ac78e1cff13f5e530470325e9cb2e8de54e4cb/js/buttons/RoundToggleButton.ts#L47-L48

Is there a sim or place where this isn't working?

**Comment by pixelzoom** [comment]
Hmm.... My bad.  Not sure what I was looking at.  I was probably confusing this RectangularStickyToggleButton, which I see @jessegreenberg fixed up in https://github.com/phetsims/sun/commit/b8622cb7bde4b3a37ee42c6df465bbd812a64576 on 9/26.  Sorry for the bother, closing.
