### ISSUE TITLE
Delete redundant pdom options for Dialog's CloseButton.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#897]
For https://github.com/phetsims/models-of-the-hydrogen-atom/issues/67 ...

In Dialog.ts:

```ts
    const closeButton = new CloseButton( {
...
      // pdom
      tagName: 'button',
      innerContent: SunStrings.a11y.closeStringProperty,
```

The pdom options are redundant and confusing.  `tagName` is set in superclass ButtonNode.  `innerContent` is set as `accessibleName` in CloseButton.

**Comment by pixelzoom** [comment]
@jessegreenberg and I discussed this in Slack, so assigning to him to review. Close if OK.

**Comment by jessegreenberg** [comment]
Great, thanks! 

My understanding is we can delete this a11y string from sun now too, so I removed it in https://github.com/phetsims/sun/commit/340c658ae71f1c6eed422662cfe57a0d8bd4755d. If @jbphet says otherwise I will revert that.
