### ISSUE TITLE
AccordionBox: support for `accessibleName` and `helpText`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#902]
Three are several problems with AccordionBox, which I'll attempt to describe below.   Some of these problem might be due to the fact that developers (including myself) are unclear about the pattern for sim code after reading AccordionBox.md.

---
1. Odd presentation of `accessibleName` in A11y View.

Adding `accessibleName` for an AccordionBox results in a push button in the A11y View, and this button never changes state.  Why a push button? For example, in the Mystery screen of Density:

UI:
<img width="123" alt="screenshot_3527" src="https://github.com/user-attachments/assets/d50f1d03-1f13-4b33-8218-acd2ffcc5660">

Implementation in DensityMysteryScreenView.ts:

```ts
const densityTableAccordionBox = new AccordionBox( ..., combineOptions<AccordionBoxOptions>( {
      ...
      accessibleName: DensityBuoyancyCommonStrings.densityTableStringProperty
    }, DensityBuoyancyCommonConstants.ACCORDION_BOX_OPTIONS ) );
```

And here's what appears in A11y View:

<img width="140" alt="screenshot_3528" src="https://github.com/user-attachments/assets/9b42496e-c8d3-414b-855d-8df355ee56e2">

---
2. No defaults for ExpandCollapseButton.

There's nothing in the A11y View for the AccordionBox's ExpandCollapseButton. Does it need to be explictly given an accessible name and help text? Why are there no defaults implemented by AccordionBox? The defaults could be something like `accessibleName: 'Expand or Collapse'` and `helpText: 'Expand or collapse accordion box.'`.

---
3. Help text appears after AccordionBox's content.

If I add both `accessibleName` and `helpText` to an AccordionBox, the `helpText` appears in the A11y View after the AccordionBox's content.  For example, for MOTHA SpectrometerAccordionBox:

UI:
<img width="426" alt="screenshot_3530" src="https://github.com/user-attachments/assets/ca6f98a4-4464-475c-aa59-6ed9253f7ae3">

A11y View:
<img width="380" alt="screenshot_3531" src="https://github.com/user-attachments/assets/cc33bcfd-9ac2-4e09-884d-c3784c9d0ede">

--- 
4. Term "panel" is used incorrectly.  

Throughout AccordionBox.md, the term "panel" is used incorrectly (14 times).  An AccordionBox does not have a "panel". It has "content", which can be any scenery Node.  The concept of a UI component having "content" is consistent terminology that is used throughout the PhET UI toolkit, for any UI component that is container-like.  It's familiar to PhET developers and will need to be familiar to SceneryStack users.  Panel is an entirely different UI component that is part of PhET's UI toolkit, it lives in sun, it also has "content", and it should have its own Panel.md file.

**Comment by jessegreenberg** [comment]
OK, I reviewed AccordionBox.ts and binder's AccordionBox.md to understand the history and expected design to figure some of these out.

> Odd presentation of accessibleName in A11y View...Why a push button?

This matches the design in binder, which is based heavily on https://www.w3.org/WAI/ARIA/apg/patterns/accordion/. The state of the button *does* change with an `aria-expanded` attribute and the design makes more sense if you know that is there. I added a display for it in the a11y view. A screen reader will read this out like "Spectrometer button, has pop-up, collapsed".
![image](https://github.com/user-attachments/assets/2b873216-7bbf-47f0-a6be-51c812c936e2)

> No defaults for ExpandCollapseButton.

For the reason above, the ExpandCollapseButton does not get an accessible name describing "expand" and "collapse".

> Help text appears after AccordionBox's content.

Based on the example markup in binder, I believe `helpText` should not be allowed. I have omitted it from options for now, but will double check this with @terracoda.

> Term "panel" is used incorrectly.

Likely because terms were borrowed from https://www.w3.org/WAI/ARIA/apg/patterns/accordion/. Ill run this by @terracoda too.

In addition, I changed the `pdomOrder` so that the order of heading, titleNode, contentNode is correct.

**Comment by jessegreenberg** [comment]
> Help text appears after AccordionBox's content.
>> Based on the example markup in binder, I believe helpText should not be allowed.

I see `helpText` has been requested for ElectronEnergyLevelAccordionBox. So Ill go ahead and add it.

**Comment by jessegreenberg** [comment]
@pixelzoom this TODO should be resolved
> //TODO description: https://github.com/phetsims/sun/issues/902 AccordionBox content is appearing above close button in A11y View.

And I think you should be unblocked for MOTHA. Can you please confirm? I will also follow up on https://github.com/phetsims/sun/issues/902#issuecomment-2442983052 with @terracoda when she returns.

**Comment by pixelzoom** [comment]
Confirmed, and thanks for the explanations above. 

In MOTHA, here's what I see for SpectrometerAccordionBox, which has content but no helpText:

<img width="414" alt="screenshot_3562" src="https://github.com/user-attachments/assets/e1e3e8d2-e989-461c-8200-c40e9e336551">

Here's what I see for ElectronEnergyLevelsAccordionBox, which has helpText but no describable content:

<img width="419" alt="screenshot_3563" src="https://github.com/user-attachments/assets/7fc7f4eb-20e3-4841-b412-45ed1375228a">

This probably needs to be reviewed by a designer, to confirm that they are OK with the presentation in A11y View.  Related to that... I'm wondering if the font for `(aria-expanded: true)` display in A11y View should be so much larger than the thing that it's related to.

**Comment by jessegreenberg** [comment]
Thanks for reviewing, Ill talk with @terracoda about this a11y view change.

**Comment by jessegreenberg** [comment]
@terracoda and I reviewed the change to the a11y view and it is all OK. More improvements to the a11y view will be discussed in https://github.com/phetsims/chipper/issues/1510. Closing.
