### ISSUE TITLE
Radio button groups: helpText appears after radio buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#903]
Related to https://github.com/phetsims/models-of-the-hydrogen-atom/issues/67 and https://github.com/phetsims/scenery-phet/issues/876 ...

While adding accessible names and help text to radio button groups in MOTHA, we saw that the help text appears _after_ the radio buttons.   For example:

LightModeRadioButtonGroup, a subclass of AquaRadioButtonGroup:
<img width="339" alt="screenshot_3532" src="https://github.com/user-attachments/assets/2670554a-97f3-42e4-8125-7296288da3a3">

ModelRadioButtonGroup, a subclass of RectangularRadioButtonGroup:
<img width="341" alt="screenshot_3533" src="https://github.com/user-attachments/assets/9d3247ac-4c3d-47af-80de-b69d3d394def">

It was requested that the help text should be above the content.  But this is not something that should be handled in sim-specific code.  It should be handled in the common-code implementations of these groups.

**Comment by jessegreenberg** [comment]
This is fixed in the above commit. @pixelzoom can you please review?

**Comment by pixelzoom** [comment]
Reviewed the commit and verified in MOTHA. Closing, thanks!
