### ISSUE TITLE
RectangularRadioButtonGroup is setting default accessible names that cannot be overridden.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#904]
Related to https://github.com/phetsims/sun/issues/899 and https://github.com/phetsims/scenery-phet/issues/876. This is blocking gor https://github.com/phetsims/models-of-the-hydrogen-atom/issues/67.

@samreid @zepumph I seem to recall an issue (density? buoyancy?) where you proposed deriving default accessible names from tandem names.  Did that get pushed?  Did you make it overridable? 

Here's more information....

In https://github.com/phetsims/sun/commit/15be3e7ec7b6b9ad89936a0f6ecdbf2e23885ea9, @samreid added this to RectangularRadioButtonGroup:

```ts
assert && assert( _.every( items, item => !item.node.hasPDOMContent ),
      'Accessibility is provided by RectangularRadioButton and RectangularRadioButtonItem.labelContent. ' +
      'Additional PDOM content in the provided Node could break accessibility.' );
```

... which seems to sugges that I can't set `accessibleName` or `helpText` for radio button items.  

Additionally, I'm running into a problem in MOTHA where I in fact cannot set `accessibleName` for the buttons in a RectangularRadioButtonGroup.   And the result is a subtle problem, where I appear to be getting default accessible names that are derived from the tandem names.  For ModelRadioButtonGroup, here's what I see in the A11y View:

<img width="274" alt="screenshot_3534" src="https://github.com/user-attachments/assets/c8441d75-1056-4596-8d95-89aba2dbea87">

My clue that the accessible names are coming from tandem names is "De Broglie".  My string Property value is "de Broglie".   The tandem name for the radio button is `deBroglieRadioButton`.   So I suspect something is taking `deBroglieRadioButton`, stripping off the "RadioButton", and converting the first letter to uppercase.

I do not see this problem with AquaRadioButtonGroup, so there is inconsistent behavior that appears to have been added to RectangularRadioButtonGroup.  This was very confusing to the MOTHA team.

**Comment by samreid** [comment]
Looks like the usage sites (2 of them) call `Tandem.toAccessibleName` and one is in RectangularRadioButton.ts

**Comment by pixelzoom** [comment]
> ... Did you make it overridable?

@samreid You added this to RectangularRadioButton:

```ts
      accessibleName: Tandem.toAccessibleName( providedOptions, 'RadioButton' ),
```

While RectangularRadioButtonGroupItem, which is used to instantiate RectangularRadioButton instances, expects to use labelContent for the accessible name:

```ts
export type RectangularRadioButtonGroupItem<T> = {
  ...
  labelContent?: PDOMValueType; // optional label for a11y (description and voicing)
  ...
} & GroupItemOptions;
```

So the answer to my questions is "no", you did not provide a way to override the default accessible name for RectangularRadioButtonGroup.

Also pointing out that by deriving accessible name from tandem name, you are ensuring that the accessible name is not translatable.

So I think we should delete this change from RectangularRadioButton, and delete `Tandem.toAccessibleName` to prevent creating more accesible names that are not translatable.

**Comment by samreid** [comment]
Reverted RectangularRadioButton usage in https://github.com/phetsims/sun/commit/1e2dd5869880fd41672adeeba92aa300f40b410e

Let's check with @zepumph before deleting `Tandem.toAccessibleName`

**Comment by pixelzoom** [comment]
> Let's check with @zepumph before deleting Tandem.toAccessibleName

My 2 cents is that this is no different than suggesting that the default label for a checkbox should be derived from it tandem name.  It's never an appropriate default for a localized application.

**Comment by pixelzoom** [comment]
@samreid said:
> Reverted RectangularRadioButton usage in https://github.com/phetsims/sun/commit/1e2dd5869880fd41672adeeba92aa300f40b410e

And did you investigate whether sims were relying on this behavior?  For example, are you now missing accessible names in the Density suite?

**Comment by zepumph** [comment]
Sounds good. @pixelzoom please note your concerns in https://github.com/phetsims/scenery/issues/1526 and feel free to close that issue. We thought it could be a nice way to provide a first pass, but especially with PhET's push towards translating these, it doesn't seem too valuable since we can't bring the values to production.

**Comment by pixelzoom** [comment]
Noted in https://github.com/phetsims/scenery/issues/1526.

No response to my question about whether sims may be relying on the code that @samreid removed from RectangularRadioButton.  So back to you again to (maybe) investigate and close.

**Comment by pixelzoom** [comment]
That can be done via RectangularRadioButtonItems.options.  There is no need for  labelContent/innerContent/accessibleName.   Sims should be using accessibleName. Sims should not be using labelContent/innerContent and other APIs identified as "low-level" in ParallelDOM.ts.  Where accessibleName is not supported, developers should identify those case and create GitHub issues to add support, rather than resorting to workaround. 

See https://github.com/phetsims/sun/issues/901 for the path forward on acessibleName, helpText, etc.

See https://github.com/phetsims/sun/issues/899 for the problems with the description API for radio button groups specifically.

**Comment by pixelzoom** [comment]
Definitely broken for density-and-buoyancy-common BlocksModeRadioButtonGroup.

In 1.2.2 A11y View:
<img width="217" alt="screenshot_3538" src="https://github.com/user-attachments/assets/9d8d9ab7-6f22-41f4-94d9-24a77c6e2e32">

In main:
<img width="202" alt="screenshot_3537" src="https://github.com/user-attachments/assets/d75e4853-ba97-438a-857d-e00da66bbc6c">

**Comment by pixelzoom** [comment]
Also broken in density-and-buoyancy-common BuoyancyApplicationsScreenView:

<img width="149" alt="screenshot_3540" src="https://github.com/user-attachments/assets/aebf673d-fc30-40ed-88d4-e8b6d90d8bc0">

In Buoyancy 1.2.1 A11y View:
<img width="155" alt="screenshot_3541" src="https://github.com/user-attachments/assets/8f09650d-bb2a-46df-9e44-9c9580fd6ed0">

In Buoyancy main A11y View:

<img width="239" alt="screenshot_3542" src="https://github.com/user-attachments/assets/6f853622-8ac9-43f5-a241-41d743f0e276">

**Comment by pixelzoom** [comment]
Broken in Mean Share in Balance, FairShareNotepadNode.  @marlitas how do you feel about this change breaking your work?

<img width="185" alt="screenshot_3545" src="https://github.com/user-attachments/assets/47d74fc7-d930-4a26-b776-8c705c1b4f4e">

In MSaB 1.1 A11y View:
<img width="219" alt="screenshot_3544" src="https://github.com/user-attachments/assets/044351b3-3b98-42e8-b6d9-bcc41e76a918">

In MSaB main A11y View:
<img width="283" alt="screenshot_3543" src="https://github.com/user-attachments/assets/32f2c8a9-fefc-4145-9686-ff560324fb8c">

**Comment by pixelzoom** [comment]
Broken in multiple radio button groups in Color Vision. @marlitas FYI.

1.3.0:
<img width="327" alt="screenshot_3547" src="https://github.com/user-attachments/assets/bf7bca07-a164-4c9c-bf27-0f67499f20c7">

main:
<img width="289" alt="screenshot_3548" src="https://github.com/user-attachments/assets/31e9432f-328d-4566-8098-6eb5fd8ba9b1">

**Comment by samreid** [comment]
I added one for https://github.com/phetsims/density-buoyancy-common/issues/423

**Comment by samreid** [comment]
I'm very confused about this issue. The claim in the title and top comment is that the default from the tandem could not be overridden. However, following the instructions in https://github.com/phetsims/sun/issues/904#issuecomment-2429456215 I saw that we can have the default from the tandem and override it like so:

<details>

```diff

Subject: [PATCH] Pass repo to check, see https://github.com/phetsims/perennial/issues/364
---
Index: sun/js/buttons/RectangularRadioButton.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/sun/js/buttons/RectangularRadioButton.ts b/sun/js/buttons/RectangularRadioButton.ts
--- a/sun/js/buttons/RectangularRadioButton.ts	(revision 1e2dd5869880fd41672adeeba92aa300f40b410e)
+++ b/sun/js/buttons/RectangularRadioButton.ts	(date 1729691650307)
@@ -94,6 +94,7 @@
       containerTagName: 'li',
       appendDescription: true,
       appendLabel: true,
+      accessibleName: Tandem.toAccessibleName( providedOptions, 'RadioButton' ),
 
       // phet-io
       tandem: Tandem.REQUIRED,
Index: density-buoyancy-common/js/common/view/BlocksModeRadioButtonGroup.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/density-buoyancy-common/js/common/view/BlocksModeRadioButtonGroup.ts b/density-buoyancy-common/js/common/view/BlocksModeRadioButtonGroup.ts
--- a/density-buoyancy-common/js/common/view/BlocksModeRadioButtonGroup.ts	(revision 18298ece882d0a8d7dbd3a4bbabf40982124b0f4)
+++ b/density-buoyancy-common/js/common/view/BlocksModeRadioButtonGroup.ts	(date 1729691451139)
@@ -43,7 +43,10 @@
     super( modeProperty, [ {
       value: TwoBlockMode.ONE_BLOCK,
       createNode: () => BlocksModeRadioButtonGroup.getSingleCuboidIcon(),
-      tandemName: 'oneBlockRadioButton'
+      tandemName: 'oneBlockRadioButton',
+      options: {
+        accessibleName: 'TESTING'
+      }
     }, {
       value: TwoBlockMode.TWO_BLOCKS,
       createNode: () => BlocksModeRadioButtonGroup.getDoubleCuboidIcon(),

```

</details>

<img width="1146" alt="image" src="https://github.com/user-attachments/assets/9d09ad4c-f99c-404e-acdb-4509c180e3cc">

I am not involved with the subteam that is working on making the a11y text i18nizable, so I don't know the timeline, strategy, etc or whether we want any support like https://github.com/phetsims/scenery/issues/1526 based on tandems or based on i18nizable labels.

Thanks to @pixelzoom for identifying cases where this tandem default was being used, and disruptions caused by the revert.

> And could we please wrap this up rather than back-and-forth assigning?

The parts I still need help on are:
1. Should I restore the reverted commit (for now)? There are likely to be other affected situations.
2. It seems https://github.com/phetsims/scenery/issues/1526 may give us a way forward to reuse translatable text.
3. I don't really follow https://github.com/phetsims/scenery/issues/1526#issuecomment-2200743380 about how some things are overridable and some are not.

I cannot easily tell from Monday which subteam is working on translatable a11y text, so I think the best thing for now is to self-unassign and check in at dev meeting tomorrow. I'll add it as an agenda item, but also happy to discuss on zoom beforehand.

**Comment by samreid** [comment]
In dev meeting today, @pixelzoom agreed to move forward with the tandem names shown as in the lower picture in https://github.com/phetsims/scenery/issues/1526#issuecomment-1944166933

**Comment by pixelzoom** [comment]
To clarify...  https://github.com/phetsims/sun/issues/904#issuecomment-2435966643 was not the final consensus.  Consensus was that default accessibleName should be base on a translatable string Property, e.g. by discovery in a Node's content.    In the meantime, we decided to remove `Tandem.toAccessibleName`, remove the 1 usage in density-buoyancy-common, and creat a GitHub issue in density-buoyancy-common

**Comment by pixelzoom** [comment]
I completed the work identified in https://github.com/phetsims/sun/issues/904#issuecomment-2436018783, so I believe this issue can be closed.
