### ISSUE TITLE
ComboBox: support for `accessibleName` and `helpText`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#906]
Related to https://github.com/phetsims/models-of-the-hydrogen-atom/issues/67 and https://github.com/phetsims/scenery-phet/issues/876 ...

Build out support for `accessibleName` and `helpText` in ComboBox and its items, so that these APIs are consistent with other usages of the high-level API when they appear in sim-specific code.

Document high-level API in ComboBox.md, with exemplars.

**Comment by jessegreenberg** [comment]
This was done in the commits referenced above.

- `a11yName` was renamed to `accessibleName` throughout ComboBox stack.
- I verified that the accessibleName and helpText behavior functions work for ComboBox.
- TrimParallelDOMOptions is used to limit the API.

And I removed the TODOs pointing to this issue in MOTHA. @pixelzoom I am going to close this one but feel free to take a look.
