### ISSUE TITLE
AccordionBox: focus highlight should adjust if `showTitleWhenExpanded: false`

### ISSUE THREAD

**Issue by marlitas** [phetsims/sun#907]
In Number pairs we noticed that the focus highlight looks incorrect when the option `showTitleWhenExpanded` is set to false.

<img width="401" alt="image" src="https://github.com/user-attachments/assets/5d316aec-1032-4060-8fda-40ed3207377e">

@pixelzoom and I felt like AccordionBox should dynamically handle the focus highlight accordingly.

This could especially be a problem if any of the content was interactive.

**Comment by marlitas** [comment]
I am also happy to take care of this if that would be helpful @jessegreenberg

**Comment by jessegreenberg** [comment]
Thanks @marlitas, that is an oversight. Can you please review this commit?

**Comment by marlitas** [comment]
Sorry for the delayed review on this. The changes look good and it is behaving as expected. Thanks!
