### ISSUE TITLE
Create "expand/collapse button with label".

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#919]
In https://github.com/phetsims/fourier-making-waves/issues/254, we identified a need for a "expand/collapse button with label" in order to properly support alt input features.   For example:

<img width="230" alt="screenshot_3626" src="https://github.com/user-attachments/assets/8f71d3c5-7725-4fbc-9068-3132b350b960">

Clicking on either the button or label should toggle the Property associated with the ExpandCollapseButton.

Focus highlight should surround both the button and label, and tab traversal should not visit the ExpandCollapseButton invidually.

Interactive highlight should similarly surround both the button and label.

This is not blocking for https://github.com/phetsims/fourier-making-waves/issues/254.

Note that fourier-making-waves currently includes LabeledExpandCollapseButton, which might be used as a starting point -- but the label should be generalized to any type of Node. Creating such a subclass seems preferrable to adding yet-another option to ExpandCollapseButton.

**Comment by samreid** [comment]
During today's dev meeting, it was proposed that Fourier: Making Waves and other cases can use an Accordion Box to achieve the functionality described.

**Comment by pixelzoom** [comment]
Uses of ExpandCollapseButton that should be using AccordionBox have been identified, and GitHub issues are linked above.

I spoke with @arouinfar and summarized today's developer meeting discussion.  She is OK with closing this issue as "won't fix".
